### PR TITLE
alienpy 1.5.7:: hotfix for xrootd uploads

### PR DESCRIPTION
**Pull request by adriansev**
* Hot fix the async mechanics for pipelining. this affected the multicommit mechanics for xrootd copy

### CODE REVIEW

**Review by costing — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , @ktf , 
Could you take a look at the errors? The one in macos is not related to this PR, which would be good to have ASAP.
Chiara

**Comment by adriansev** [comment]
Hi @TimoWilken! 2 tests fail with:
```
matBudGeom94418_geometry.root does not exist. Will create it on the fly
[INFO] Loading geometry from matBudGeom94418_geometry-aligned.root
Error in <TFile::TFile>: file /System/Volumes/Data/build/alice-ci-workdir/alidist-o2/sw/BUILD/6df45ce2167b60e19b2706ead6945771feaf176d/O2/Detectors/Base/matBudGeom94418_geometry-aligned.root does not exist
[FATAL] Failed to open file matBudGeom94418_geometry-aligned.root
```

and one have:
```
socket.timeout: The read operation timed out
```

**Comment by pzhristov** [comment]
The problems with the Geant3 simulation are caused by Xcode 15.1 and an apparent mismatch with dfortran 13.2. I am trying to recompile GCC-Toolbox locally, but the recipe needs changes for arm64. So, the macosx issues are not releated to the PR.  However, on ubuntu 22.04 we have
Downloading pyOpenSSL-23.3.0-py3-none-any.whl (58 kB)
Collecting rich
  Downloading rich-13.7.0-py3-none-any.whl (240 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/sw/ubuntu2204_x86-64/Python-modules/1.0-13/share/python-modules/lib/python/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
Does this have to do with the PR?

**Comment by adriansev** [comment]
> However, on ubuntu 22.04 we have Downloading pyOpenSSL-23.3.0-py3-none-any.whl (58 kB) Collecting rich Downloading rich-13.7.0-py3-none-any.whl (240 kB) ERROR: Exception: Traceback (most recent call last): File "/sw/ubuntu2204_x86-64/Python-modules/1.0-13/share/python-modules/lib/python/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher yield Does this have to do with the PR?

it does not.. these are the dependencies to alienpy and you can see in log that there is actually a `socket.timeout: The read operation timed out` in the installing process for rich.. 
so it would seem a network problem

**Comment by pzhristov** [comment]
Ok, then I will merge the PR.

**Pull request merged**
