### PR TITLE
Disable builtin_davix in ROOT

### PR DESCRIPTION
**Pull request by dberzano**
Enabled by default in ROOT master but problematic and unneeded

### CODE REVIEW

**Comment by dberzano** [comment]
@pzhristov can you have a look please?

**Comment by dberzano** [comment]
@ktf as a matter of fact Davix is currently troublesome only when using the master version of ROOT, and not a tagged one. In principle, the problem of different UUID versions will be gone completely with JAliEn, that's the plan.

Say, we can live without this PR merged at the moment IMHO. Up to @pzhristov to decide...

**Comment by ktf** [comment]
Mine was a comment, not a request for changes. I have no objections to this, let's just keep it on the table.

**Comment by dberzano** [comment]
Superseded by #1213.

**Pull request closed without merging**
