### PR TITLE
arrow: bump to 0.17.0 (O2-1340)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@aphecetche you will also need this if you want to try the new arrow.

**Comment by ktf** [comment]
The error is actually in arrow upstream, however to move to 0.17.0 (which fixes the problem) we need to understand how to override the LLVM version.

**Comment by ktf** [comment]
@Barthelemy are you building QualityControl with C++17?

**Comment by Barthelemy** [comment]
@ktf Sorry for the delay, I was not around on Friday. We do not set any C++ version in QC. Should I add the following ? 
```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
```

**Comment by ktf** [comment]
I think it actually comes from root. I tried that. It's also weird it does not happen on my mac.

**Comment by Barthelemy** [comment]
The error on Mac is also different from the one on CC7. On Mac it says : 
```
[m[0;32mBM_ASoAHelpersCombGenCollisionsPairsCategories/4096     [m[0;33m   2602894 ns    2602892 ns [m[0;36m       269[m Combinations=762.058k[m   1116.84MB/s[m
[mError in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libRIO, output: $ROOT_DYN_PATH/libRIO
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libCling, output: $ROOT_DYN_PATH/libCling

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/a3401451a0334b8cd622e071e7fb187da1d0eca2/O2/stage/tests/o2-test-framework-benchmark_ASoAHelpers] BM_ASoAHelpersCombGenCollisionsPairsCategories(benchmark::State&) /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/O2/2196/0/Framework/Core/test/benchmark_ASoAHelpers.cxx:0
```
and on CC7:
```

In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/arrow/v0.17.0-3/include/arrow/record_batch.h:25:
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/arrow/v0.17.0-3/include/arrow/result.h:34:12: error: no member named 'launder' in namespace 'std'
using std::launder;
      ~~~~~^
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/arrow/v0.17.0-3/include/arrow/result.h:400:23: error: no member named 'launder' in namespace 'arrow::internal'
    return *internal::launder(reinterpret_cast<const T*>(&data_));
```

**Comment by ktf** [comment]
I think it's simply root not supporting fully C++17... :-/ I think I managed to hide arrow from the cling in O2. Let's see the new build...

**Comment by ktf** [comment]
Finally.

**Comment by ktf** [comment]
@aalkin

**Pull request merged**
