### PR TITLE
xjalienfs:: tag 1.2.3

### PR DESCRIPTION
**Pull request by adriansev**
update tag to 1.2.3

### CODE REVIEW

**Comment by adriansev** [comment]
ping @costing  :D you are the only requested reviewer that i know :)

**Comment by costing** [comment]
Looks like the macOS failure is blocking the PR. I don't see the Approve button yet.

**Review by costing — APPROVED** [review]

**Comment by adriansev** [comment]
@ktf any idea about the macOS failure? the Details show nothing

**Comment by ktf** [comment]
@MichaelLettrich the macOS builders have troubles again.

**Pull request merged**
