### PR TITLE
move to v6-26-10-alice7

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by ktf** [comment]
Bumped to v6-26-10-alice7, as discussed.

**Comment by ktf** [comment]
@pzhristov FYI, will not merge until @Barthelemy gives green light with his tests.

**Comment by Barthelemy** [comment]
it helps with regards to opening files downloaded from the CCDB but it won't help with the post processing problem we saw at P2. It will be fixed by the PR I prepared in QC. I would therefore wait for the PR in QC to be merged, before merging this one.

**Comment by ktf** [comment]
Any news on this?

**Comment by Barthelemy** [comment]
@ktf yes, QC is patched here: https://github.com/alisw/alidist/pull/4733

**Comment by Barthelemy** [comment]
@ktf we are good to go

**Comment by ktf** [comment]
I assume you tested also with this PR included?

**Comment by Barthelemy** [comment]
yes, I had tested with it

**Comment by ktf** [comment]
I assume this is not needed anymore? We are about to bump to v6-28-00 in any case.

**Pull request closed without merging**
