### PR TITLE
Move to GCC v6.2, C++14 and stable builds

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf @sawenzel @mkrzewic @awegrzyn not yet to be merged, but almost - I am doing the final moves to finally enable C++14 and stabilizing the FairRoot builds we use.

**Comment by awegrzyn** [comment]
Hi @dberzano,
This PR still prevents from using gcc 6 from devtoolset-6 - see [gcc-toolchain.sh:15](https://github.com/dberzano/alidist/blob/wp3/gcc-toolchain.sh)

**Comment by dberzano** [comment]
Hi @awegrzyn, nope - look at the `defaults-o2.sh` (maybe you need the `o2-daq` ones?)

**Comment by awegrzyn** [comment]
Hi,
Indeed if I run it with `--defaults o2` it picks gcc correctly!
Thanks

**Comment by awegrzyn** [comment]
@dberzano Could you apply following change in `libpng.sh:7`:
`
< source: git://git.code.sf.net/p/libpng/code
---
> source: https://git.code.sf.net/p/libpng/code
`
In O2 Lab we can only access outside via HTTP.

**Comment by dberzano** [comment]
Please pull. I have also changed the recipe for `libxml2` which featured a `git://` URL as well.

**Comment by dberzano** [comment]
Hi all and in particular @mkrzewic, I have added full C++14 support for VGM and GEANT4_VMC. Note that in order to avoid problems with software versions requiring validations, those two components are exactly the same as before plus the additional patches required for C++14, so their functionalities are unchanged.

**Comment by dberzano** [comment]
I am closing it in favor of #679 (which is wrt/`master`).

**Pull request closed without merging**
