### PR TITLE
Bump QCG to v1.6.9 and QC to v0.20.1

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by Barthelemy** [comment]
Could you bump QC to v0.20.0 ?

**Comment by ktf** [comment]
The issue with DebugGUI is a screw up of mine. I accidentally merged in alidist something which should have not been. I reverted the change, if you bump your PR it should be fine.

**Comment by awegrzyn** [comment]
@ktf @MichaelLettrich Could you explain why `alidist_macOS` failed?

**Comment by Barthelemy** [comment]
The following tests FAILED:
	 53 - DataFormats/MemoryResources/test/testMemoryResources.cxx (Failed)
	 71 - Utilities/O2Device/test/test_O2Device.cxx (Failed)

I don't think that it can be related to our changes as it is upstream.

**Comment by Barthelemy** [comment]
Could someone force merge ?

**Comment by awegrzyn** [comment]
I'd really prefer not to force merge as test stopped on O2 and we'd like to test `QualityControl` and `qcg` as well

**Comment by ktf** [comment]
Mmm... No, and AFAICT that code has not changed since a while. I wonder if this is the side effect of some other PR. @mkrzewic @matthiasrichter do you have any idea?

**Comment by Barthelemy** [comment]
@awegrzyn I understand and I agree, let's not force merge.

**Comment by awegrzyn** [comment]
@ktf Now this fails with on macOS with:
```
[ 49%] Linking CXX shared library libFairMQPlugin_test_dummy.dylib
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Could not initialize shared memory transport: boost::interprocess_exception::library_error
CMake Error at /build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/CMake/v3.13.1-1/share/cmake-3.13/Modules/GoogleTestAddTests.cmake:39 (message):
  Error running test executable.

    Path: '/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/BUILD/0eb075fcb5ac0939ab823220b406bcf79ded77b4/FairMQ/test/testsuite_MemoryResources'
    Result: Child aborted
    Output:
      [ERROR] Could not initialize shared memory transport: boost::interprocess_exception::library_error
```

**Comment by ktf** [comment]
We restarted the builders. It actually looks like a cleanup issue in fairmq itself.

@rbx @dennisklein any suggestion on how to wipe clean shared memory in case some stale resource is left behind?

**Comment by rbx** [comment]
With this command you can see if any files are open:
`fairmq-shmmonitor -v -i -s <sessionid>`
And this one to cleanup anything that was not closed properly:
`fairmq-shmmonitor --cleanup -s <sessionid>`

**Comment by Barthelemy** [comment]
still the same error

**Comment by Barthelemy** [comment]
The test `test_Framework_test_SimpleStatefulProcessing01` fails. The warning in QC is fixed in v0.20.1. It did not appear on my Mac nor on the CC7 Ci.

**Comment by Barthelemy** [comment]
Why is `build/O2/alidist ` marked as failed although the logs don't show anything wrong ?

**Comment by Barthelemy** [comment]
the mac  build has been going since this morning. Is it blocked ? @ktf @MichaelLettrich

**Comment by Barthelemy** [comment]
@awegrzyn `build/O2/alidist` is red but for no obvious reason, `build/O2Suite/alidist_macOS` is red due to ServiceDiscovery not being reachable. Consul is there. It is not an error we usually get. 

What do you think ? force merge ?

**Comment by awegrzyn** [comment]
Yes, I guess there's no point on blocking the release for another week

**Comment by Barthelemy** [comment]
alidist went green. 
Mac build is failing with 
```

The following tests FAILED:
	 20 - testCheckWorkflow (Timeout)`
```

@alisw/infrastructure-admins could someone force merge this PR ? thanks

**Comment by Barthelemy** [comment]
and now we have 3 red builds... without touching anything 😕

**Comment by ktf** [comment]
Build machines are being killed by zombies:

```
root     30314  0.1  0.0      0     0 ?        Z    Jan08   0:47 [o2-sim-device-r] <defunct>
```

@sawenzel I suspect your change of the other time actually made things worse. :-/

**Comment by ktf** [comment]
@sawenzel can we disable the test until the problem is fixed?

**Comment by ktf** [comment]
I mean using the `o2-sim-parallel` for the test.

**Comment by Barthelemy** [comment]
@ktf could we force merge this specific PR ? it has been blocked since before Christmas for various, independent and unrelated reasons. It is blocking our FLP release.

**Pull request merged**
