### PR TITLE
Provide recipes for O2 code checks

### PR DESCRIPTION
**Pull request by sawenzel**
Providing initial recipes to build and execute a basic O2 code checking tool.
Updating existing clang recipe (bump version + modulefile support).

### CODE REVIEW

**Comment by sawenzel** [comment]
Jenkins fails because the recipes are related to O2 and need o2 defaults.

**Comment by ktf** [comment]
Nothing really depends on this. Merging.

**Comment by ktf** [comment]
Actually, how about you do this in prod? Why next?

**Comment by sawenzel** [comment]
Just thought that it is normal procedure to introduce things in next which are released into prod.

**Pull request merged**
