### PR TITLE
Cannot assume boost is installed with brew

### PR DESCRIPTION
**Pull request by aphecetche**

### CODE REVIEW

**Comment by ktf** [comment]
@PascalBoeschoten @awegrzyn @Barthelemy can you please fix the recipes as I suggested in my review comment? Thanks.

**Comment by ktf** [comment]
This:

https://github.com/alisw/alidist/search?utf8=✓&q=BOOST_ROOT&type=

is how we do it elsewhere.

**Comment by ktf** [comment]
Actually, all the DAQ owned packages should probably be fixed

https://github.com/alisw/alidist/search?p=2&q=%22osx+BOOST_ROOT%22&type=&utf8=✓

@Barthelemy

**Comment by aphecetche** [comment]
Hi,

Indeed : 

BOOST_ROOT=${BOOST_ROOT:-$(brew --prefix boost)}

is probably better than total removal like in my original PR ;-) 

Still, brew --prefix boost always return a path, whether or not boost is actually installed or not.

Also, the fact that every and all recipe dealing with boost has to do this trick (correctly or incorrectly) smells a bit, don't you think ? 
Could there be a better way to deal, at alibuild level maybe, with this very well known package in the case the system one is preferred  ?

**Comment by Barthelemy** [comment]
Please see https://github.com/alisw/alidist/pull/956

**Comment by ktf** [comment]
@Barthelemy PR is indeed doing the right thing, as done elsewhere, therefore I am closing this.

**Pull request closed without merging**
