### PR TITLE
 PWGPP-485 - adding new dependencies for  interactive visualization 

### PR DESCRIPTION
**Pull request by miranov25**
Hallo @ktf , @pzhristov,  @dberzano

As we discussed last week we would like to include python interactive visualization and ML into alidist recipes (https://github.com/miranov25/RootInteractive).  As first step I made a modification of the python-modules.sh

### New dependencies:
* pandas 
* jupyter
  * jupyter,jupyterlab
* ML
  * sklearn,skgarden
  * tensorflow keras
* interactive graphics:
  * qgrid,ipympl,request,runtime,plotly,bqplot,bokeh
  * I started to investigate vaex - not yet in dependencies

### My consideration:
* For new dependencies I did not specify (yet) version numbers. 
  * Our github library () is working with these recipe for 3 months
* Current alidist recipe does not work properly in  case of virtual environment
  * user has to copy paste pip install command from the log file
````
pip install matplotlib numpy certifi ipython ipywidgets ipykernel notebook metakernel pyyaml jupyter jupyterlab sklearn scikit-garden  pandas qgrid ipympl request runtime plotly bqplot bokeh tensorflow keras
````
### Enabling jupyter-lab
To enable interactive graphics in jupyter-lab additional steps are needed.  I did not enter them yet into recipe:
* install nodejs
* install extensions for interactive visualization
````
jupyter labextension install @jupyter-widgets/jupyterlab-manager  #OK
jupyter labextension install bqplot   #OK
jupyter labextension install qgrid@1.0.1-beta.0
jupyter labextension install jupyterlab_bokeh      #OK
jupyter labextension install jupyter-matplotlib
````

**When could we meet to review changes for python-modules?**

In meantime we are preparing pull request for the https://github.com/miranov25/RootInteractive repository.  Currently we are refactoring directory structure.

Regards
Marian.

### CODE REVIEW

**Comment by miranov25** [comment]
Hallo @ktf , @pzhristov, @dberzano
I'm not sure if you received the notification. See description above.
Marian

**Comment by ktf** [comment]
This looks ok to me, but I'd like it to be discussed in WP3 at large. @dberzano

**Comment by miranov25** [comment]
In which meeting we  should report/request? Usually we are discussing development during the QA tools meeting on Wednesday. 
I do not see in indico  any dedicated  WP3 meetings

**Comment by dberzano** [comment]
@miranov25 from what I know it is largely useless to install such packages on Python 2.7. What we need to do first is moving to Python 3. All ongoing ML efforts in ALICE are, notably, using Python 3.6 (@ginnocen can confirm), with Python 3.7 on the radar as soon as Tensorflow supports it.

The other issue I see here is that packages are not pinpointed. You need to specify the exact version (that's for reproducibility) of the packages you install. `pip freeze` can help you identifying the version numbers.

What about we move to Python 3 first and have this on hold? @svallero is already working on it.

**Comment by miranov25** [comment]
Could you estimate time needed to move to Python 3? 
For our current application  we are using   using Python 2.7 without problem.
Should we ask for time slot for following  QC meeting, or do you prefer another meeting?

**Comment by dberzano** [comment]
Meeting's not needed to discuss this. Python 3 will be ready when it will be ready. In the meanwhile you can start by pinpointing the version numbers as requested, can you do that? Thanks.

**Comment by ktf** [comment]
Closing this. Please reopen a new one rebased on the new python3 developments.

**Comment by miranov25** [comment]
Hello @ktf 

If I understand correctly all alibuild recipes are for Python3. Could you confirm.
As we discussed during the OFFLINE week, I started  to  prepare RootInteractive as a pip package.
If you confirm I will do support only for Python3, preparation should be easier.

I will keep this request close and prepare new pull request soon. Eventually i will need a help with pip package preparation, so I plan to come to CERN.

Marian

**Comment by ktf** [comment]
Yes we are fully python 3 now.

**Pull request closed without merging**
