### PR TITLE
fix the version of setuptools

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by sy-c — DISMISSED** [review]

**Comment by Barthelemy** [comment]
what about `setuptools==59.6.0` in `defaults-o2-dataflow` and we change it asap we move to python 3.9 ?

**Comment by awegrzyn** [comment]
Yes, we also have distinction between pythons, so we could have `setuptools==59.6.0` for 3.6 and `setuptools==65.5.1` for 3.9.

**Comment by Barthelemy** [comment]
see my commit

**Comment by awegrzyn** [comment]
@ktf Is that okay with you?

**Comment by Barthelemy** [comment]
Could someone approve and merge ?

**Pull request merged**
