### PR TITLE
bump readout v0.23

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
@alisw/dataflow-experts can some please review?

**Comment by sy-c** [comment]
@dberzano @ktf the build/O2Suite/alidist_macOS test fails but the "details" link ends up in "404 not found". Can you please have a look ?

**Comment by ktf** [comment]
@sy-c you actually need AliceO2Group/Readout#45 (and 2.3.1, I guess).

**Comment by sy-c** [comment]
Thanks ! (please note that the logs link "build/O2/alidist details" is still broken, 404 not found)

**Comment by ktf** [comment]
Yes, I know, but for that I need a bit more time.

**Pull request merged**
