### PR TITLE
CEFPv4

### PR DESCRIPTION
**Pull request by mpuccio**
Hi @TimoWilken,

Again, would it be possible to create a new O2Physics tag starting here?
Hopefully, we should not do it too often anymore...
Thanks a lot!!!
Cheers,
Max

### CODE REVIEW

**Comment by TimoWilken** [comment]
Hi @mpuccio, thanks, will do on Monday if that's alright!

**Comment by mpuccio** [comment]
Hi @TimoWilken,
sure, let me know when it is started!
Thanks a lot!
Max

**Comment by TimoWilken** [comment]
@mpuccio It's building now!

**Comment by mpuccio** [comment]
@TimoWilken thanks a lot!

**Pull request merged**
