### PR TITLE
Drop secret from tpcfecutils.sh

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Having non managed secrets in recipes will break other builds. Dropping it.

**Comment by vascobarroso** [comment]
Pinging @sk3x to review. 
I have the feeling we are going in circles, wasn't this the original problem ?

**Comment by ktf** [comment]
I think the password protected repository is just the submodule that was removed. I just tried on a machine where I do not have credentials and it seems to work.

**Comment by ktf** [comment]
@TimoWilken I just saw this PR going from "all green" to "all yellow", just by reloading the page. Are you sure there is no race condition it the checkers that marks all the checks as "pending" even if only one failed?

**Comment by ktf** [comment]
Now everything is green again. Maybe a github glitch..

**Comment by ktf** [comment]
macOS unrelated and unneeded. Indeed dropping the secret had no issues, so I assume it's fine.

**Comment by ktf** [comment]
ok. apparently not the case. Any objections to forking the repository to AlicePrivateExternals gitlab group? For that one everyone in ALICE, including our CI, has access (but not the rest of the world).

**Comment by ktf** [comment]
@vascobarroso @sk3x

**Comment by sk3x** [comment]
No objections.
Can you set it up to automatically stay in sync?

**Comment by ktf** [comment]
I have to check how to do that. I guess we could setup a gitlab action.

**Comment by ktf** [comment]
can you add my gitlab account to your repository? There is apparently a way to automatically mirror things in gitlab but I need rights.

**Comment by sk3x** [comment]
I just added @eulisse, was that correct?

**Comment by ktf** [comment]
yes.

**Comment by ktf** [comment]
mirroring every 3h should be in place now. Please let me know if you have troubles.

**Comment by sk3x** [comment]
Sounds good, thanks a lot.

**Pull request merged**
