### PR TITLE
Use default gRPC build for ODC

### PR DESCRIPTION
**Pull request by AndreyLebedev**

### CODE REVIEW

**Comment by teo** [comment]
Now that the special gRPC version is cut out, @AndreyLebedev @ktf do we even need a separate defaults for ODC? Building with `o2-dataflow` should be equivalent in this case.

**Comment by ktf** [comment]
@teo for me, the less defaults the better.

**Comment by teo** [comment]
Then I'd propose to eliminate `defaults-odc.sh` altogether, and update the ODC aliBuild instructions to use `--defaults o2-dataflow`. @AndreyLebedev would this be ok for you?

**Comment by AndreyLebedev** [comment]
> Then I'd propose to eliminate `defaults-odc.sh` altogether, and update the ODC aliBuild instructions to use `--defaults o2-dataflow`. @AndreyLebedev would this be ok for you?

Yes, I'll do it.

**Pull request merged**
