### PR TITLE
Check new FairMQ version

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@dennisklein @rbx apparently  this->ChangeState(state); is not marked nodiscard. What should we do with the result?

**Comment by dennisklein** [comment]
> @dennisklein @rbx apparently this->ChangeState(state); is now marked nodiscard. What should we do with the result?

You complained a while ago that this interface is broken the way it is and that it needs improvement, therefore we created issue FairRootGroup/FairMQ#441 and resolved it via https://github.com/FairRootGroup/FairMQ/commit/435d07eaf95ed3c412dd89e0b5aa9f81c57b4fa1 as discussed together on Mattermost. See also https://github.com/FairRootGroup/FairMQ/releases/tag/v1.5.0.

**Comment by rbx** [comment]
`true` is success (state change queued or done), `false` is change state has failed (reason is logged). Handle it accordingly, or use the throwing variant instead (`ChangeStateOrThrow()`).

**Comment by ktf** [comment]
Yes, now I remember.

**Comment by ktf** [comment]
@cuveland could you please have a look at the remaining issues in DataDistribution and provide a fixed tag?

**Comment by ktf** [comment]
@cuveland any update on this?

**Comment by davidrohr** [comment]
DD should build now with new FMQ. I have built an experimental version to test at P2. Let's see. FST is passed, but we have to test some runs with ECS and FLPs. (@ktf @cuveland )

**Comment by rbx** [comment]
FYI: there is now FairMQ v1.6.0: https://github.com/FairRootGroup/FairMQ/releases/tag/v1.6.0
It contains a new feature needed by @knopers8 (not sure, how urgent it is).

**Comment by davidrohr** [comment]
CI failure unrelated, tested on staging at P2, merging.
For FairMQ 1.6.0: Please open a separate PR, but since this works, I'll go ahead with this one.

**Pull request merged**
