### PR TITLE
Add unzip system recipe as it is required by DIM

### PR DESCRIPTION
**Pull request by awegrzyn**
DIM recipe uses `unzip`...

### CODE REVIEW

**Review by kostorr — APPROVED** [review]

**Comment by ktf** [comment]
Is this really needed? Do we have a case in which unzip is not in the base system?

**Review by ktf — COMMENTED** [review]
Do we really need this?

**Comment by awegrzyn** [comment]
Yes, default CC7 OpenStack image.

**Comment by ktf** [comment]
Ok, I would suggest we use type, though.

**Review by kostorr — APPROVED** [review]

**Pull request merged**
