### PR TITLE
Bump AliECS to v0.17.80

### PR DESCRIPTION
**Pull request by teo**

### CODE REVIEW

**Review by sy-c — APPROVED** [review]

**Comment by ktf** [comment]
I would recommend to move to use alibuild-recipe-tools to generate the modulefiles, both for modules 4 compatibility, correctness, and performance (no recursion in dependencies...).

**Comment by teo** [comment]
> I would recommend to move to use alibuild-recipe-tools to generate the modulefiles, both for modules 4 compatibility, correctness, and performance (no recursion in dependencies...).

Thanks @ktf I'd be happy to, but I struggle to find any documentation on this. Can you point me where to RTFM please?

**Comment by ktf** [comment]
RTFM is at http://alisw.github.io/alibuild/reference.html#runtime-environment, you can probably just copy what is done in boost.sh or python.sh.

**Comment by teo** [comment]
@ktf alright, thanks! I've put something together, currently testing locally. I'll submit it in a separate PR.

**Pull request merged**
