### PR TITLE
Make sure the o2-dataflow uses a setuptools which does not break xrootd

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by adriansev** [comment]
@ktf could you check if this workaround works? https://github.com/pypa/setuptools/issues/3693#issuecomment-1321651396
i can do it only later in the evening

**Comment by awegrzyn** [comment]
Why this is needed? `xrootd` is explicitly disabled in `o2-dataflow` defaults?

**Comment by Barthelemy** [comment]
@awegrzyn it is an attempt at fixing this issue: https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/QualityControl/1524/b1d1215233f3fabbf18f5522cd176aadee7217db/build_QualityControl_o2-dataflow_macOS/fullLog.txt

**Comment by awegrzyn** [comment]
ah okay, I got misleaded by PR title

**Comment by ktf** [comment]
@davidrohr @shahor02 since a day or so I see things failing due to:

```
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2/4681/0/Detectors/CTF/test/test_ctf_io_tpc.cxx:134: [1;31;49merror: in "CTFTest": check memcmp(vecIn.data(), bVec.data(), bVec.size()) == 0 has failed[0;39;49m
```

is this a known issue?

**Pull request merged**
