### PR TITLE
Make Readout not behave differently in CI from the rest

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by sy-c — APPROVED** [review]

**Comment by awegrzyn** [comment]
I think you would need to get rid of `-Werror` from here as well: https://github.com/AliceO2Group/Readout/blob/master/CMakeLists.txt#L30

**Comment by ktf** [comment]
Why? I think the issue is the different behaviour, not the behaviour itself, no?

**Comment by sy-c** [comment]
> Why? I think the issue is the different behaviour, not the behaviour itself, no?

exactly... I put the explicit -Werror to detect them on my dev system, and avoid bad surprises when doing the osx checks

**Comment by awegrzyn** [comment]
Because the error comes from fact that `o2` defaults are using GCC 10 that reports that warning and GCC 7 does not.

**Comment by awegrzyn** [comment]
Okay, I'm a bit confused, how did it pass?

**Comment by ktf** [comment]
Old readout. The issue is in the new version.

**Comment by sy-c** [comment]
> Because the error comes from fact that `o2` defaults are using GCC 10 that reports that warning and `dataflow` defaults still use GCC 7 that does not.

great, if that's so simple, no problem, I will use o2 defaults instead of dataflow on my dev node.

**Comment by ktf** [comment]
Shall I just close this, then?

**Comment by sy-c** [comment]
I think it's still worth to remove the unnecessary custom part... let me just fix the source code first.

**Comment by ktf** [comment]
@sy-c did you fix the code in the end? Can we merge this?

**Comment by sy-c** [comment]
@awegrzyn yes, we have been using gcc10 everywhere for some time now.

**Pull request merged**
