### PR TITLE
PATH information for MCStepLogger in modulefile

### PR DESCRIPTION
**Pull request by sawenzel**

### CODE REVIEW

**Comment by sawenzel** [comment]
error is unrelated

**Comment by sawenzel** [comment]
@dberzano : I believe there might be a (configuration) problem with the @alisw/simulation-experts team. Although this is listed as CODEOWNERS for this package, I cannot ask for approval from this team.

**Comment by sawenzel** [comment]
Can this be merged please?

**Comment by ktf** [comment]
The problem is that you cannot approve your own PRs, I think. Are you the only "simulation-experts"?

**Pull request merged**
