### PR TITLE
bump infologger 1.3.7

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
@alisw/infrastructure-admins there's "build/ali-bot/test " failing but I don't think it's related to this PR. Can you please check?

**Comment by ktf** [comment]
`build/ali-bot/test` was a (failed) attempt to have more robust reporting of failed builds. I disabled it for now.

**Comment by vascobarroso** [comment]
Still waiting for macos build. Maybe it is blocked again ?

**Comment by ktf** [comment]
No, just slow. One machine had to rebuild ROOT, the other one seems to be using a single core to build something with node-gyp.

@awegrzyn do you know if the we can increase the number of jobs for `node-gyp`?

**Comment by awegrzyn** [comment]
@ktf I will take a look at it, in addition there's new `node-gyp` that supports Python 3.

**Pull request merged**
