### PR TITLE
Bump arrow to 10.0.0

### PR DESCRIPTION
**Pull request by aalkin**

### CODE REVIEW

**Comment by pzhristov** [comment]
@aalkin Should we start tagging the arrow branch instead of using hashes?

**Comment by ktf** [comment]
Definitely. Although it  apparently does not build as it seems to be lacking the option for C++17.

**Comment by aalkin** [comment]
@ktf that option supposed to come from `defaults`, is it not?

**Comment by ktf** [comment]
I think in the default we simply have the env variable, then we need to expose it to cmake.

**Pull request closed without merging**
