### PR TITLE
Bump qualitycontrol to v1.21.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@ktf @TimoWilken There is an "aliDoctor error" on fullCI/alidist

**Comment by ktf** [comment]
@TimoWilken is on it. Credentials for tpcfecutils do not work with the new one build one container approach.

**Comment by ktf** [comment]
On the other hand the issue in Detectors/FIT/raw/include/FITRaw/DigitBlockFIT.h seems to be real.

@shahor02 @davidrohr does it ring any bell?

**Comment by ktf** [comment]
Merging since build/O2/alidist-dataflow and build/O2/alidist work.

**Comment by Barthelemy** [comment]
@ktf I created a ticket for the FIT problem: https://alice.its.cern.ch/jira/browse/O2-2436

**Comment by ktf** [comment]
Claimed to be fixed by https://github.com/AliceO2Group/AliceO2/pull/6566.

**Pull request merged**
