### PR TITLE
Bump to v2.2.10 and use offical repo

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Concerning the copy of the .git directory to the build location: The make process generates a file "Git_Info.C" per directory which it uses later, based on the information in the .git directory. In case the file is missing the build ends in error. This problem didn't exist with our own fork, because we imported the code from the tarball, where the files Git_Info.C are provided by the SHERPA authors. So when moving to the official repository copying the .git directory is mandatory.

**Comment by mfasDa** [comment]
Still SHERPA 2.2.10 does not build under C++17 :(

Though I understand currently generator has its own defaults on should start seriously thinking about combining again defaults (o2, next-root6, generators, and drop release) into one, in order to make packages compatible for grid usage, in particular as aligenmc now is supported by the MCgen train.

**Review by preghenella — APPROVED** [review]
thanks @mfasDa 
the changes look ok with me.

**Comment by preghenella** [comment]
@mfasDa 
the issue of combining the various defaults into a single one is not so trivial.
This because some packages need to override the version of a requirement, some other packages do not.

I think the goal is a good one, but the way forward might not be so trivial.

**Comment by preghenella** [comment]
hi @mfasDa 
do you agree to proceed with this PR, merge it and bring the discussion about C++17 and the defaults in another place?
@MichaelLettrich @ktf 
I find the checks above are failing, but there is no real insight on the reason why?

**Comment by mfasDa** [comment]
> hi @mfasDa
> do you agree to proceed with this PR, merge it and bring the discussion about C++17 and the defaults in another place?
> @MichaelLettrich @ktf
> I find the checks above are failing, but there is no real insight on the reason why?

Hi @preghenella , 

Yes let's separate the issues. I think this PR should be ready to merge.

Cheers

Markus

**Comment by MichaelLettrich** [comment]
@preghenella I have found the source of the problem and fixed it. Sorry it took so long. The tests should run and report properly again. allow for a bit of time for the system to catch up with the pending builds.

**Comment by mfasDa** [comment]
@MichaelLettrich Thanks for you help!

Do I have to trigger a new CI test (by adding a blank line or whitespace) or will it launch automatically?

**Comment by MichaelLettrich** [comment]
@mfasDa  it will get picked up automatically, however to accelerate retesting, you can reset the status of individual unit tests using the  `Clean PR Checks` action which you can find in "actions".

**Comment by mfasDa** [comment]
@MichaelLettrich Thanks for the hint! I am not yet familiar with github actions, what do I need to do in order to reset the build CI tests of this PR? I don't see anything in `Clean PR Checks` I can launch.

**Comment by preghenella** [comment]
@mfasDa 
I think I managed to clean the PR via actions, ticks are back to yellow state

**Comment by mfasDa** [comment]
Thhe macOS build error is still unrelated. The log for generators is still empty.

**Comment by preghenella** [comment]
@MichaelLettrich 
any idea why the checks still fail after `Clean PR checks`?

**Comment by preghenella** [comment]
`macOS` check fails with
```
 rm -f Release/nothing.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/nothing.a Release/obj.target/nothing/../../node-addon-api/src/nothing.o
Usage: /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/autotools/v1.6.3-1/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
```
@mfasDa is this something related to this PR?

**Comment by preghenella** [comment]
sorry @mfasDa ,
you already commented it was unrelated...
waiting from @MichaelLettrich or @ktf to proceed

**Comment by mfasDa** [comment]
@preghenella The important line is here:
```
sw/BUILD/qcg-latest/log
sw/BUILD/O2-latest/log
```
The mac build test is failing in 2 packages which are completely unrelated to the generators but part of O2 (qcg and O2 itself). The only test which is really of relevance, the aligenerators test, has no logs
```
Finished building on alibuild01.cern.ch at 2021-01-07-14:00:42
Built commit 0c869d00e32f37aba254b0e0685b4b37742924bb from https://github.com/alisw/alidist/pull/2723
To log into the build machine, use:
    aurora task ssh -l root build/mesosci/prod/ci_alisw_slc7-builder_latest/3
No logs found. Please check the aurora log.
See http://alisw.github.io/infrastructure-pr-testing for more instructions.
```

**Comment by MichaelLettrich** [comment]
@preghenella, @mfasDa, indeed the macOS issue is general and is being addressed , see #2738.  no idea about the generators test, @ktf  ?

**Comment by preghenella** [comment]
Done

**Comment by mfasDa** [comment]
Any chance to get this recovered?

@preghenella Could you maybe trigger the CI?

**Comment by mfasDa** [comment]
@preghenella @maireiphc  Build seems now fixed. Time for merge?

**Comment by preghenella** [comment]
let's merge.
I cannot do it.
@sawenzel or @ktf  can you please merge?

**Review by preghenella — APPROVED** [review]

**Pull request merged**
