### PR TITLE
Disable libfabric backends pulling in infiniband verbs or RDMA

### PR DESCRIPTION
**Pull request by davidrohr**
@ktf @chiarazampolli : This removes the libibverbs and librdmacm dependencies for me.

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf : We have again unused variables in O2Physics that break the alidist CI:
```
/System/Volumes/Data/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4830/0/DPG/Tasks/TOF/tofOfflineCalib.cxx:112:20: error: unused variable 'responseEl' [-Werror,-Wunused-variable]
    constexpr auto responseEl = ResponseImplementation<PID::Electron>();
```
Perhaps we should add such an unused variable check to the O2Physics CI?

**Comment by chiarazampolli** [comment]
Hello @davidrohr , 
Thanks! Will you commit a fix to O2Physics? Otherwise @njacazio, can you take care?
Chiara

**Comment by ktf** [comment]
https://github.com/AliceO2Group/O2Physics/pull/2012 to fix the issue in O2Physics. I will enable the check for O2Physics PRs. I think I actually pointed out the issue already, but somehow we did not converge.

**Comment by ktf** [comment]
@davidrohr @chiarazampolli this is now merged and as discussed it should fix the issues with running on the Grid while we figure out if we need libfabric at all.

**Pull request merged**
