### PR TITLE
Drop authentication from TpcFecUtils

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@alisw/dataflow-experts please make sure your repository can be accessed by the alibuild user. I also would prefer that the the submodule is treated as a separate package.

**Comment by vascobarroso** [comment]
@sk3x can you comment on the request from @ktf ?

**Comment by ktf** [comment]
Merging this as it's breaking the CI.

**Comment by sk3x** [comment]
The repository now can be accessed by the alibuild user.

What exactly is the issue with the deploy tokens?
Will removing them non break things for some other non-alibuild users?

**Comment by ktf** [comment]
If they build from scratch, yes. They would need to download it prebuilt from the server.

What is the point for making it private if you then ship the tokens in the recipe?

**Comment by sk3x** [comment]
Ok, I think #2638 and this are one discussion, so maybe let's have it here.

What we are interested in is being able to build RPMs for CentOS on FLPs. The FEC utils depend on some other packages managed here (essentially ReadoutCard and LLA). I wasn't aware there is an alibuild user, deploy tokens were our compromise to get that running successfully.

Can this simply be exempted from the CI?

**Pull request merged**
