### PR TITLE
Bump ODC to 0.70

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by ktf** [comment]
Will this fix the issue with:

```
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: In file included from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Logger.h:12,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/DDSSubmit.h:21,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Controller.h:12,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Controller.cpp:9:
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/InfoLogger.h:42:38: error: 'synchronous_sink' in namespace 'boost::log::v2_mt_posix::sinks' does not name a template type
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:    42 |     using CSink = boost::log::sinks::synchronous_sink<CBackend>;
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:       |                                      ^~~~~~~~~~~~~~~~
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/InfoLogger.h: In member function 'void odc::core::CInfoLogger::registerSink(odc::core::ESeverity, bool) const':
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/InfoLogger.h:56:27: error: 'make_shared' is not a member of 'boost'; did you mean 'std::make_shared'?
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:    56 |         auto sink{ boost::make_shared<CSink>() };
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:       |                           ^~~~~~~~~~~
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: In file included from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/memory:84,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/system/detail/to_std_category.hpp:19,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/system/detail/error_category_impl.hpp:99,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/system/error_category.hpp:11,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/system/error_code.hpp:14,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/filesystem/path_traits.hpp:22,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/filesystem/path.hpp:26,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/boost/v1.75.0-73/include/boost/filesystem.hpp:16,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/DDSSubmit.h:16,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Controller.h:12,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Controller.cpp:9:
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-9/include/c++/10.2.0/bits/shared_ptr.h:872:5: note: 'std::make_shared' declared here
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:   872 |     make_shared(_Args&&... __args)
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:       |     ^~~~~~~~~~~
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: In file included from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Logger.h:12,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/DDSSubmit.h:21,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Controller.h:12,
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:                  from /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/Controller.cpp:9:
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/InfoLogger.h:56:39: error: 'CSink' was not declared in this scope
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:    56 |         auto sink{ boost::make_shared<CSink>() };
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:       |                                       ^~~~~
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/InfoLogger.h:56:46: error: expected primary-expression before ')' token
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:    56 |         auto sink{ boost::make_shared<CSink>() };
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:       |                                              ^
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.xDf2AVkTX2/SOURCES/ODC/0.69/0.69/odc/InfoLogger.h:58:27: error: incomplete type 'boost::log::v2_mt_posix::core' used in nested name specifier
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:    58 |         boost::log::core::get()->add_sink(sink);
2022-05-07@00:31:11:DEBUG:O2PDPSuite:ODC:0:       |                           ^~~
2022-05-07@00:31:12:DEBUG:O2PDPSuite:ODC:0: [ 43%] Linking CXX executable odc-ex-processor
```
?

**Comment by ktf** [comment]
currently ODC breaks the buils...

**Comment by davidrohr** [comment]
I think so. But what I don't understand: when I reenabled ODC in alidist, the CI was green. So apparently the CI and the builds behave differently. How can that be?

**Comment by davidrohr** [comment]
I started a build with the new ODCs for the EPNs to check if it is fixed:
https://alijenkins.cern.ch/job/DailyBuilds/job/WeeklyO2Release/30/console

**Comment by davidrohr** [comment]
ok, apparently also with 0.70 it breaks the builds.
I have no idea why the RPM builds fail while the CI passes.
@ktf @TimoWilken : Any idea? What can be the difference?
In any case, I'll disable ODC again for o2-defaults, and try the next version manually with an RPM build before reenabling it.
But would still be good to understand why the CI doesn't catch it.

**Pull request merged**
