### PR TITLE
Bump to v6-30-01-alice3

### PR DESCRIPTION
**Pull request by ktf**
Fixes https://github.com/root-project/root/pull/14853

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 could you have a look?

**Comment by shahor02** [comment]
Yes, will rebuild in the evening.

**Review by shahor02 — APPROVED** [review]
@ktf Thanks, works as expected.

**Comment by ktf** [comment]
Starting the caching in:

https://alijenkins.cern.ch/job/CacheO2Package/

**Pull request merged**
