### PR TITLE
libwebsockets: fix for new XCode

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by MichaelLettrich — APPROVED** [review]

**Comment by Atlantic777** [comment]
I think we can't use this libwebsockets version, please don't merge it yet.

**Review by MichaelLettrich — CHANGES_REQUESTED** [review]
@Atlantic777 mentioned that we cannot bump.

**Comment by MichaelLettrich** [comment]
@Atlantic777 any way to fix this?

```bash
2020-11-13@17:13:08:DEBUG:libwebsockets:libwebsockets:v3.0.1: In file included from /Users/alibuild/alice/sw/SOURCES/libwebsockets/v3.0.1/v3.0.1/lib/core/context.c:22:
2020-11-13@17:13:08:DEBUG:libwebsockets:libwebsockets:v3.0.1: /Users/alibuild/alice/sw/SOURCES/libwebsockets/v3.0.1/v3.0.1/lib/core/private.h:301:9: error: 'MSG_NOSIGNAL' macro redefined [-Werror,-Wmacro-redefined]
2020-11-13@17:13:08:DEBUG:libwebsockets:libwebsockets:v3.0.1: #define MSG_NOSIGNAL SO_NOSIGPIPE
2020-11-13@17:13:08:DEBUG:libwebsockets:libwebsockets:v3.0.1:         ^
2020-11-13@17:13:08:DEBUG:libwebsockets:libwebsockets:v3.0.1: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/sys/socket.h:584:9: note: previous definition is here
2020-11-13@17:13:08:DEBUG:libwebsockets:libwebsockets:v3.0.1: #define MSG_NOSIGNAL    0x80000         /* do not generate SIGPIPE on EOF */
```

**Comment by Atlantic777** [comment]
Yes have seen that one. A sed script that comments out that line should fix it. I'm trying to reproduce it again on my setup just to confirm.

**Comment by Atlantic777** [comment]
I can't reproduce now the issue on my machine but I remember the exact problem when I updated XCode to some v12 beta. Can we survive with something like this?

https://github.com/Atlantic777/alidist/commit/b15baa9d2fb778670fd582491ee4edf11f416b99

**Comment by ktf** [comment]
The patch is fine, but can't we simply fork and apply it to our own repo?

**Comment by Atlantic777** [comment]
Sure, a fork with the patch works as well. I don't have any preferences. In any case, we should be able to update libwebsockets in a couple of weeks and switch back to upstream soon.

**Comment by pzhristov** [comment]
Unfortunately JAliEn-ROOT does not compile with this version of libwebsockets since they have removed ws_ping_pong_interval from the structure lws_context_creation_info. Version 4.0.0 is ok from this point of view, but needs a small patch from upstream, namely
`
commit 7b2ef3b19e61752ebde7c47ddb38a6d381befa13
Author: 小明 <caobug@user.github.invalid>
Date:   Sun Sep 20 19:14:48 2020 +0100

    ios: adapt to MSG_NOSIGNAL available in iOS SDK 12+

diff --git a/lib/plat/unix/private-lib-plat-unix.h b/lib/plat/unix/private-lib-plat-unix.h
index feb22273..c894aff2 100644
--- a/lib/plat/unix/private-lib-plat-unix.h
+++ b/lib/plat/unix/private-lib-plat-unix.h
@@ -183,6 +183,8 @@ delete_from_fd(const struct lws_context *context, int fd);
  * but happily have something equivalent in the SO_NOSIGPIPE flag.
  */
 #ifdef __APPLE__
+/* iOS SDK 12+ seems to define it, undef it for compatibility both ways */
+#undef MSG_NOSIGNAL
 #define MSG_NOSIGNAL SO_NOSIGPIPE
 #endif
`

**Comment by Atlantic777** [comment]
> Unfortunately JAliEn-ROOT does not compile with this version of libwebsockets since they have removed ws_ping_pong_interval from the structure lws_context_creation_info. Version 4.0.0 is ok from this point of view, but needs a small patch from upstream, namely
> [https://github.com/warmcat/libwebsockets/commit/c8fc7a6f37ed516cc19da69d4fb9c4450823bc79](url)

@pzhristov yes, with that change it should compile and work fine. As @ktf suggested we can fork libwebsockets, or apply [inline patch](https://github.com/Atlantic777/alidist/commit/b15baa9d2fb778670fd582491ee4edf11f416b99) as suggested above.

The future JAliEn-ROOT versions from 0.7.x branch (libjalien) will be compatible with new libwebscokets versions.

**Comment by pzhristov** [comment]
@Atlantic777 I think we can go for the inline patch for the moment. Do you want to update to 4.0.0 or any other tag from 4.0.xx series?

**Comment by Atlantic777** [comment]
@pzhristov we need to stay on libwebsockets 3.0.x for the moment. If I remember correctly, even 3.1.x had problems (it compiled, but didn't work as expected at runtime).

**Comment by pzhristov** [comment]
> @pzhristov we need to stay on libwebsockets 3.0.x for the moment. If I remember correctly, even 3.1.x had problems (it compiled, but didn't work as expected at runtime).

@Atlantic777 I propose to close this PR and then you can open a new one with the inline patch.

**Pull request closed without merging**
