### PR TITLE
Bump qualitycontrol to v1.7.3

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@ktf there seems to be something wrong with the builders

**Comment by ktf** [comment]
I will check.

**Comment by ktf** [comment]
macOS issue under investigation by @MichaelLettrich, but likely unrelated. Merging.

**Comment by MichaelLettrich** [comment]
@ktf @Barthelemy builder has simply died. Restarted and back in service.

**Pull request merged**
