### PR TITLE
O2: fix typo in jalien deps

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy I think the CCDB test in QC fails again.

**Comment by Barthelemy** [comment]
@ktf I don't see a CCDB test failing. There is the QC warning which is fixed in QC and I will prepare a patch version.

**Comment by ktf** [comment]
On centos8 I have:

```
sw/BUILD/QualityControl-latest/log
41/41 Test #25: testCheckWorkflow ................***Failed    9.57 sec
98% tests passed, 1 tests failed out of 41
```

in the pretty report...

**Comment by Barthelemy** [comment]
that is not ccdb, it is a test of the DPL workflow containing checkRunners. 

Let's see how it goes for https://github.com/alisw/alidist/pull/2709

**Pull request merged**
