### PR TITLE
Bump cpprestsdk and Bookkeeping binding

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@TimoWilken @ktf Looks like something's wrong with the builds :(

**Comment by ktf** [comment]
I think it's gitlab failing again. I will restart the build.

**Comment by ktf** [comment]
I can confirm that it's gitlab:

git ls-remote --heads --tags https://gitlab.cern.ch/VecGeom/VecGeom.git

or similar, simply hang.

**Comment by ktf** [comment]
https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3059658 has been created to follow up the issue. We should probably consider mirroring everything to Github...

**Comment by awegrzyn** [comment]
Okay, thanks for checking promptly!

**Review by sy-c — APPROVED** [review]

**Comment by ktf** [comment]
Error unrelated (gitlab still flaky).

**Pull request merged**
