### PR TITLE
Bump qualitycontrol to v1.61.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by davidrohr** [comment]
@Barthelemy : This bump seems to fail on MacOS:
```
--
[250/466] Building CXX object Modules/TOF/CMakeFiles/O2QcTOF.dir/src/CheckNoise.cxx.o
FAILED: Modules/TOF/CMakeFiles/O2QcTOF.dir/src/CheckNoise.cxx.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -DFMT_SHARED -DO2QcTOF_EXPORTS -I/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.61.0/v1.61.0/Modules/TOF/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.61.0/v1.61.0/Modules/TOF/src -I/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.61.0/v1.61.0/Modules/TOF -I/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.61.0/v1.61.0/Framework/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/boost/v1.75.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/FairLogger/v1.11.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/fmt/8.1.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/FairMQ/v1.4.51-local1/include/fairmq -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/FairMQ/v1.4.51-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/ROOT/v6-24-06-patches-alice1-local3/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/Common-O2/v1.6.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/libInfoLogger/v2.4.4-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/Monitoring/v3.12.0-local3/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/Configuration/v2.6.3-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/Control-OCCPlugin/v0.43.0-local2/include/Occ -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/grpc/v1.45.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/protobuf/v3.15.8-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/c-ares/1.18.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/re2/2019-09-01-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/abseil/20211102.0-local1/include -isystem /opt/homebrew/opt/openssl@1.1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/O2/4257-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/curl/7.70.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/O2/4257-local1/include/GPU -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/FairRoot/v18.4.7-local7/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/VMC/v2-0-local5/include/vmc -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/arrow/v5.0.0-alice3-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/Vc/1.4.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/ms_gsl/4.0.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/libjalienO2/0.1.3-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/RapidJSON/v1.1.0-alice2-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/libuv/v1.40.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_arm64/TBB/v2021.5.0-local1/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -Wno-error=unused-function -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.15 -fPIC -std=gnu++17 -MD -MT Modules/TOF/CMakeFiles/O2QcTOF.dir/src/CheckNoise.cxx.o -MF Modules/TOF/CMakeFiles/O2QcTOF.dir/src/CheckNoise.cxx.o.d -o Modules/TOF/CMakeFiles/O2QcTOF.dir/src/CheckNoise.cxx.o -c /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.61.0/v1.61.0/Modules/TOF/src/CheckNoise.cxx
/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.61.0/v1.61.0/Modules/TOF/src/CheckNoise.cxx:57:42: error: more '%' conversions than data arguments [-Werror,-Wformat-insufficient-args]
      mo->addMetadata(Form("noisyChannel%i"), channelFormat);
                                        ~^
```
Could you have a look?
I'd like to bump QC to 1.61 today asap, since it fixes the current CI issues with the FullCI

**Comment by Barthelemy** [comment]
I'll have a look. 
The real problem is that the macos build has been broken for quite some time and we are merging blindly on mac.

**Comment by Barthelemy** [comment]
Nicolò fixed it: https://github.com/AliceO2Group/QualityControl/pull/1230
I am going to merge it right away and add the ITS fix on top (https://github.com/AliceO2Group/QualityControl/pull/1229)

**Comment by Barthelemy** [comment]
https://github.com/alisw/alidist/pull/4258

**Pull request closed without merging**
