### PR TITLE
bump readout v0.24

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins, it seems there is something stuck in the checks... build/O2/alidist is still not completed after 17 hours. Can you please advise ?

**Comment by dberzano** [comment]
@sy-c job has been restarted.

**Comment by dberzano** [comment]
(For the record: the OpenStack node where this builder was running was completely frozen and I had to force-reboot it...)

**Comment by sy-c** [comment]
@dberzano thanks!

**Pull request merged**
