### PR TITLE
ThePEG and dependencies

### PR DESCRIPTION
**Pull request by dberzano**
Supersedes #112. Requesting to merge:

* ThePEG v2015-08-11
* CRMC v1.5.4
* JEWEL v2.0.2

Embedded PDF sets:

* LHAPDF5: cteq6l cteq6ll EPS09LOR_208
* LHAPDF6: cteq6l1

@qgp: if this is correct we can - finally - proceed.

### CODE REVIEW

**Comment by dberzano** [comment]
@mfloris

**Comment by dberzano** [comment]
Here are the dependency trees (note that ThePEG indirectly depends on LHAPDF 6, whereas JEWEL depends on LHAPDF 5):

iterm2 ij5yg1 dist

iterm2 qxn4mq dist

iterm2 97lfa6 dist

All of them build and work correctly. Do we need to publish all of them? Waiting for @mfloris, @qgp.

**Comment by mfloris** [comment]
Not sure about JEWEL, but we would need thepeg and CRMC asap!

Thanks!
Michele.

**Comment by qgp** [comment]
Hi @dberzano,

the PDFsets look ok to me.

JEWEL would also be needed for the LEGOtrains. So, could you also deploy it?

Cheers,
  Jochen

**Pull request merged**
