### PR TITLE
Fix XRootD 5.4.2 bindings on macOS / Ubuntu

### PR DESCRIPTION
**Pull request by ktf**
$ORIGIN simply does not exists on mac

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Tested on Ubuntu20 , working. 

@adriansev , FYI.

**Comment by ktf** [comment]
Ok, I simply tagged the wrong repo. I also move everything to use alibuild-generate-recipe to avoid multiple loading of the dependencies.

**Comment by adriansev** [comment]
@ktf i just tried to build xjalienfs (with xrootd set in development mode but set on the v5.4.2-alice1 tag) o alibuildmac03 and when trying to enable the build i got:
```
alienv enter xjalienfs/latest-xjalienfs-o2
Loading XRootD/xjalienfs-local1
  Module ERROR: can't read "XROOTD_ROOT": no such variable
        while executing
    "prepend-path PYTHONPATH ${XROOTD_ROOT}/lib/python/site-packages"
        invoked from within
    "if { True } {
      prepend-path PYTHONPATH ${XROOTD_ROOT}/lib/python/site-packages
      # This is probably redundant, but should not harm.
      module load    ..."
        (file "/Users/asevcenc/alisw/sw/MODULES/osx_x86-64/XRootD/xjalienfs-local1" line 19)
    Please contact <root@localhost>

Loading xjalienfs/latest-xjalienfs-o2
  ERROR: Load of requirement XRootD/xjalienfs-local1 failed
```
any idea about this?

**Comment by ktf** [comment]
yes, my bad, it needs to be \$PKGROOT. i will fix it in a bit.

**Comment by adriansev** [comment]
@ktf sorry that i cannot help more than error messages:
```
alienv enter xjalienfs/latest-xjalienfs-o2
Loading XRootD/xjalienfs-local2
  Module ERROR: can't read "PKGROOT": no such variable
        while executing
    "prepend-path PYTHONPATH $PKGROOT/lib/python/site-packages"
        invoked from within
    "if { True } {
      prepend-path PYTHONPATH $PKGROOT/lib/python/site-packages
      # This is probably redundant, but should not harm.
      module load          ..."
        (file "/Users/asevcenc/alisw/sw/MODULES/osx_x86-64/XRootD/xjalienfs-local2" line 19)
    Please contact <root@localhost>

Loading xjalienfs/latest-xjalienfs-o2
  ERROR: Load of requirement XRootD/xjalienfs-local2 failed
```

**Comment by ktf** [comment]
`\$PKG_ROOT`... my bad... try now.

**Comment by adriansev** [comment]
@ktf yup. it works!

**Comment by ktf** [comment]
@TimoWilken could you warm up the cache with this?

**Comment by TimoWilken** [comment]
Caching succeeded, merging.

**Pull request merged**
