### PR TITLE
Some modifications related to ROOT6

### PR DESCRIPTION
**Pull request by aiola**
Note: this PR contains a rebase from master.

The two new commits are:

1) Update ROOT6 recipe to make it work with 6.09/2
2) Update RooUnfold recipe to make it work with ROOT6

Unfortunately these changes are not backward compatible as they are. They should be implemented with some conditional check on the version of ROOT. Maybe someone can do that or instruct me on how to do it?

### CODE REVIEW

**Comment by dberzano** [comment]
Hi, can you please rebase/check whether this works with the current master of alidist? We have made some consistent changes.

**Comment by aaniin** [comment]
Hello @aiola , 

I encountered the same problem with builtin_vdt. See https://github.com/alisw/alidist/pull/775 where I simply **added** `-Dbuiltin_vdt`, however you **replace** `-Dvdt=on` with `-Dbuiltin_vdt`. Does root5 compile with only the `-Dbuiltin_vdt`?
My root5 compiled with `-Dvdt=on` and `-Dbuiltin_vdt=on` does not give the feature builtin_vdt which you check for. I'd expect this to fail at configure stage.

Cheers,
Hans

root 5
```bash
root-config --features
alien asimage astiff builtin_afterimage builtin_ftgl builtin_glew builtin_pcre builtin_lzma cxx11 cintex exceptions explicitlink fftw3 fortran genvector http mathmore memstat minuit2 monalisa opengl pythia6 pythia6_nolink python reflex roofit shared soversion ssl thread tmva vdt xft xml x11 xrootd
```

root 6
```bash
root-config --features
alien asimage astiff builtin_afterimage builtin_ftgl builtin_gl2ps builtin_glew builtin_llvm builtin_lzma builtin_pcre builtin_tbb builtin_unuran builtin_vdt cling cxx11 exceptions explicitlink fftw3 fortran genvector http imt mathmore memstat minuit2 monalisa opengl pch pythia6 pythia6_nolink python roofit shared soversion ssl thread tmva vdt x11 xft xml xrootd
```

**Comment by aiola** [comment]
Hello @aaniin,
my changes were not meant to work with ROOT5. In fact, I suggested to merge them in a separate branch and not to master. I think that your proposed solution is better since it is compatible with both versions of ROOT.
Best,
Salvatore

**Comment by ktf** [comment]
Can you rebase on top of dev, please?

**Comment by aiola** [comment]
Hello @ktf,
as far as I can tell it is already rebased to dev (but it includes also some other commits from master). Do you want me to reset to dev and cherry-pick only the last two commits?
In any case, I think that we should actually drop this PR and use @aaniin's solution (PR #775).
Best,
Salvatore

**Comment by ktf** [comment]
Ok, perfect. If @aaniin solution is what we need, then I close this.

**Pull request closed without merging**
