### PR TITLE
Bump FairMQ to 1.4.18

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by ktf** [comment]
Did someone move a tag? :-/

**Comment by davidrohr** [comment]
No idea what happened, perhaps? I build it locally for me this morning and it worked.

**Comment by ktf** [comment]
i am investigating...

**Comment by ktf** [comment]
seems to break something...

**Comment by ktf** [comment]
@rbx @dennisklein this seems to put FairMQ in some race condition on SIGTERM. The actual backtrace is:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff70446882 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff70507425 libsystem_pthread.dylib`_pthread_cond_wait + 698
    frame #2: 0x00007fff6d5d6623 libc++.1.dylib`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
    frame #3: 0x00000001053f8e75 libFairMQStateMachine.1.4.16.dylib`fair::mq::StateMachine::WaitForPendingStateFor(int) const [inlined] std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000000000l> >(this=<unavailable>, __lk=0x00007ffeec0083b0, __d=<unavailable>) at __mutex_base:0 [opt]
    frame #4: 0x00000001053f8e60 libFairMQStateMachine.1.4.16.dylib`fair::mq::StateMachine::WaitForPendingStateFor(int) const [inlined] std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(this=<unavailable>, __lk=0x00007ffeec0083b0, __t=<unavailable>) at __mutex_base:383 [opt]
    frame #5: 0x00000001053f8e60 libFairMQStateMachine.1.4.16.dylib`fair::mq::StateMachine::WaitForPendingStateFor(int) const [inlined] bool std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >, fair::mq::StateMachine::WaitForPendingStateFor(int) const::$_1>(this=0x00007fc83021a4b0, __lk=0x00007ffeec0083b0, __t=<unavailable>, __pred=<unavailable>) const::$_1) at __mutex_base:395 [opt]
    frame #6: 0x00000001053f8e60 libFairMQStateMachine.1.4.16.dylib`fair::mq::StateMachine::WaitForPendingStateFor(int) const [inlined] bool std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000l>, fair::mq::StateMachine::WaitForPendingStateFor(int) const::$_1>(this=0x00007fc83021a4b0, __lk=0x00007ffeec0083b0, __d=<unavailable>, __pred=<unavailable>) const::$_1) at __mutex_base:429 [opt]
    frame #7: 0x00000001053f8e42 libFairMQStateMachine.1.4.16.dylib`fair::mq::StateMachine::WaitForPendingStateFor(this=<unavailable>, durationInMs=<unavailable>) const at StateMachine.cxx:366 [opt]
  * frame #8: 0x0000000103d5fc33 libO2Framework.dylib`o2::framework::DataProcessingDevice::ConditionalRun() [inlined] bool FairMQDevice::WaitFor<long long, std::__1::ratio<1l, 1000000l> >(this=<unavailable>, duration=<unavailable>) at FairMQDevice.h:411:31 [opt]
    frame #9: 0x0000000103d5fc11 libO2Framework.dylib`o2::framework::DataProcessingDevice::ConditionalRun(this=<unavailable>) at DataProcessingDevice.cxx:398 [opt]
```

any idea of what might be going wrong?

**Comment by ktf** [comment]
Ok, the issue is that FairMQ simply does not handle one SIGTERM. I think I have a fix.

**Comment by ktf** [comment]
https://github.com/FairRootGroup/FairMQ/pull/267 should fix it.

**Comment by davidrohr** [comment]
Thx, would have taken me a while to find this :|

**Comment by davidrohr** [comment]
I tried that fix locally and it works for me

**Comment by Barthelemy** [comment]
QC cannot work with the current O2 and FairMQ due to the greedy configuration parameters. We really need either this PR to go in or some kind of fix in O2.

**Comment by ktf** [comment]
I am on it.

**Comment by ktf** [comment]
After the workaround in FairMQ we can merge this.

**Pull request merged**
