### PR TITLE
Bump qualitycontrol to v1.4.2

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@davidrohr @MichaelLettrich 
Here is the fix that did not go to a release.

**Review by sy-c — APPROVED** [review]

**Comment by Barthelemy** [comment]
@MichaelLettrich the macOS build died (?)

**Comment by MichaelLettrich** [comment]
... again one of those repo errors with LLVM :( I reset the build.

**Comment by davidrohr** [comment]
@MichaelLettrich @TimoWilken : The CI run on mac failed again without log, could you check?

**Comment by MichaelLettrich** [comment]
@ktf we seem to have a problem with the LLVM repos again. 

```bash
DEBUG: Updating reference repository: cd /build/mirror/clang && git fetch -f --tags https://github.com/llvm/llvm-project 2>&1 && git fetch -f https://github.com/llvm/llvm-project '+refs/heads/*:refs/heads/*' 2>&1
DEBUG: From https://github.com/llvm/llvm-project
DEBUG:  * branch                      HEAD       -> FETCH_HEAD
DEBUG: Auto packing the repository in background for optimum performance.
DEBUG: See "git help gc" for manual housekeeping.
DEBUG: warning: The last gc run reported the following. Please correct the root cause
DEBUG: and remove gc.log.
DEBUG: Automatic cleanup will not be performed until the file is removed.
DEBUG: 
DEBUG: fatal: Failed to write bitmap index. Packfile doesn't have full closure (object efd84a5f5db2dfd8b4dcf3ac8b56a00edd61a693 is missing)
DEBUG: fatal: failed to run repack
DEBUG: 
DEBUG: error: cannot lock ref 'refs/heads/master': is at 3c050a597c599cea035537b8875774dcc48922c3 but expected 1d3cd7172b2fb62a41fb962bc506913e2a6e8a8e
DEBUG: From https://github.com/llvm/llvm-project
DEBUG:  ! 1d3cd7172b2f..3c050a597c59  master     -> master  (unable to update local ref)
DEBUG: Auto packing the repository in background for optimum performance.
DEBUG: See "git help gc" for manual housekeeping.
DEBUG: warning: The last gc run reported the following. Please correct the root cause
DEBUG: and remove gc.log.
DEBUG: Automatic cleanup will not be performed until the file is removed.
DEBUG: 
DEBUG: fatal: Failed to write bitmap index. Packfile doesn't have full closure (object efd84a5f5db2dfd8b4dcf3ac8b56a00edd61a693 is missing)
DEBUG: fatal: failed to run repack
DEBUG: 
ERROR: Error while updating reference repos https://github.com/llvm/llvm-project.
```

**Pull request merged**
