### PR TITLE
Improve check for system's GCC-Toolchain

### LINKED ISSUE #208: Avoid requiring autotools on modern platforms
We should evaluate whether or not we should require autotools on modern platforms where we can rely on the system ones.

### PR DESCRIPTION
**Pull request by dberzano**
Fixes alisw/alibuild#208.

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf: what do you think of the last commit? I want to make sure that `cc` and `c++` come from the same location.

**Comment by ktf** [comment]
+1

**Comment by ktf** [comment]
I just realized this will fail if c++ is a symbolic link?

**Comment by dberzano** [comment]
No, I have tested it - `test -f` should work in this case. Did it fail for you?

**Comment by rqwa** [comment]
I talked to the admins of our cluster and they suggested to set the compiler explicitly in the configuration. I.e.: `CC=gcc CXX=g++ cmake` 
Is this also a possible solution?

**Comment by rqwa** [comment]
After the link to cc  have been added, the output of `ls -l $(which cc) $(which c++)` is the following:
```
-rwxr-xr-x 4 root root 3116106 Jan 31  2015 /cm/shared/apps/gcc/4.8.4/bin/c++
lrwxrwxrwx 1 root root       3 Jan 28  2015 /usr/bin/cc -> gcc
```
Also compiling works now and a dry-run gives the following output:
```
[...]
We will build packages in the following order: defaults-release AliEn-CAs autotools CMake OpenSSL ApMon-CPP UUID GSL GEANT4 gSOAP MonALISA-gSOAP-client XRootD xalienfs AliEn-Runtime ROOT vgm GEANT3 GEANT4_VMC AliRoot AliPhysics
--dry-run / -n specified. Not building.
```
But after switching to IB/v5-08/next with:
```
cd ali-master/alidist
git checkout IB/v5-08/next
git pull
```
The output of the dry-run includes the the GCC-Toolchain again:
```
[...]
We will build packages in the following order: defaults-release AliEn-CAs autotools GCC-Toolchain ApMon-CPP CMake UUID GSL OpenSSL GEANT4 gSOAP MonALISA-gSOAP-client XRootD xalienfs AliEn-Runtime ROOT vgm GEANT3 GEANT4_VMC AliRoot AliPhysics
--dry-run / -n specified. Not building.
```

**Comment by ktf** [comment]
`CC=gcc CXX=g++ cmake` is not a solution as it would require changes everywhere and have a special setup for clang. Given that the official `cmake` expects `cc` and `c++` I would prefer this is fixed on your side (or that you use the compiler we provide, as it now happens in next).

**Comment by rqwa** [comment]
I haven't changed anything in the cmake config.
As I already wrote a link was set from cc to the right gcc, and the compilation works with the already installed gcc version. But in next the link is not detected and alibuild wants to build the GCC-toolchain even it is not necessary.

**Comment by ktf** [comment]
Ah, I see now. Your link setup is wrong. You should have:

```
/cm/shared/apps/gcc/4.8.4/bin/c++
/cm/shared/apps/gcc/4.8.4/bin/cc -> gcc
```

aliBuild will check that c++ and cc come from the same directory.

**Comment by rqwa** [comment]
Thanks, that solved the problem.

**Comment by ktf** [comment]
Great.

**Pull request merged**
