### PR TITLE
ROOT: move to 6.18.02

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by Barthelemy** [comment]
works like a charm on CC7 . @sawenzel I have just tested storage and retrieval with storeAsTFile and it worked like a charm, very small file size. Beyond my expectations.

**Comment by ktf** [comment]
Ok, let's wait for the checks and then we merged.

**Comment by Barthelemy** [comment]
The errors in the Mac build are weird. I don't think that it is related to the new ROOT.

**Comment by ktf** [comment]
Yeah, they are unrelated, but I was still hoping to be able to see a fully green build before merging. #1806 should help...

**Comment by sawenzel** [comment]
Is anything blocking to merge this? I believe the problems on MacOS are not related.

**Comment by ktf** [comment]
@barthelemy asked a bit of time to test it.

**Comment by Barthelemy** [comment]
It is all good, I have already tested it and approved. Thanks !

**Pull request merged**
