### PR TITLE
Change realpath to readlink (without -f this time)

### PR DESCRIPTION
**Pull request by marcovanleeuwen**
Trying again with readlink. This works for other recipes, so would also expect it to work here..

### CODE REVIEW

**Comment by pzhristov** [comment]
@marcovanleeuwen What is the issue you try to solve? I tested on my mac and in fact realpath works better than readlink:
[...hristov/alisw/alidist] readlink `which python3`
../Cellar/python@3.9/3.9.1_4/bin/python3
[...hristov/alisw/alidist] realpath `which python3`
/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/bin/python3.9

**Comment by pzhristov** [comment]
In addition, SLC6 is not supported anymore, so we have dropped the SLC6 builds since December.

**Comment by marcovanleeuwen** [comment]
Hi Peter,

This change is indeed for SLC6; we have a local farm which still runs SLC6, so I thought it would be useful to keep this working.

Marco.

**Comment by davidrohr** [comment]
For reference, Full CI fails due to https://alice.its.cern.ch/jira/browse/O2-2034

**Review by pzhristov — COMMENTED** [review]
I propose to move the use of readlink in the case statement only for SLC6, this will not affect MacOS where we have only realpath. It is time to process this PR.

**Comment by marcovanleeuwen** [comment]
This pull request is no longer needed

**Pull request closed without merging**
