### PR TITLE
The DelphesO2 receipt

### PR DESCRIPTION
**Pull request by preghenella**
The receipt to build the fast-simulation interface between `Delphes` and the `o2`.

### CODE REVIEW

**Comment by preghenella** [comment]
the failure of the `build/O2/alidist-dataflow` check seems to be unrelated to this PR

**Comment by ktf** [comment]
As discussed, improvements for next round:
* Use `-DCMAKE_INSTALL_LIBDIR=lib` to get rid of lib64
* Use `alibuild-recipe-tools` to remove the boilerplate for the modulefile, e.g.:

```bash
...
build_requires:
  - alibuild-recipe-tools
...
---
...
mkdir -p $INSTALLROOT/etc/modulefiles
alibuild-generate-module > $INSTALLROOT/etc/modulefiles/$PKGNAME
```

**Comment by ktf** [comment]
For now `alibuild-generate-module` generates only the basic "module" dependencies. All the rest is still up to you. So I would suggest something like:

```bash
cat << EOF >> $INSTALLROOT/etc/modulefiles/$PKGNAME
set DELPHESO2_ROOT \$::env(BASEDIR)/$PKGNAME/\$version
prepend-path PATH \$DELPHESO2_ROOT/bin
prepend-path LD_LIBRARY_PATH \$DELPHESO2_ROOT/lib
EOF
```

**Comment by preghenella** [comment]
Thanks @ktf ,
it works. 
For the `O2DPG` case in #2462 you have commented that

> Given it is our own recipe, I do not care about O2DPG_ROOT.

This is also our own recipe, so I would keep the `DELPHESO2_ROOT` env variable even if we discussed to remove it.
Unless you disagree, in which case I have no objections and I will remove it.

**Comment by ktf** [comment]
As long as you will not want to pick it up from the system, it's fine.

**Pull request merged**
