### PR TITLE
o2suite: add DataDistribution

### PR DESCRIPTION
**Pull request by ironMann**
jira #O2-936

### CODE REVIEW

**Comment by ironMann** [comment]
Expected problems with MacOS ... 

@ktf is macos builder in Jenkis operational?

**Comment by ktf** [comment]
You mean for the PR checker? It's not in jenkins. I think @MichaelLettrich was having more issues...

**Comment by ironMann** [comment]
I was attempting to run https://alijenkins.cern.ch/job/build-any-ib/ on a osx_x86-64-large instance: 8355

**Comment by ktf** [comment]
Mmm... I think the label is wrong. Did you make it up or did you select it from a combobox? I think the machine kind is called "FLP OSX" or something like that. @awegrzyn or @Barthelemy might know.

You can however exclude packages from a given architecture using the:

```
 - Package:<arch-matching-regex>
```

format as described [here](http://alisw.github.io/alibuild/reference.html#the-header).

In this particular case:

```
- DataDistribution:"(?!osx)"
```

just like we do for GCC a few lines above.

**Pull request merged**
