### PR TITLE
rivet + rivet-hi: Do not fail on deprecated declarations

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@maireiphc @marcovanleeuwen do we really need the pluginCMS of fastjet?
```
                            ^~~~~~~~
pluginCMS/CMS_2013_I1223519.cc:156:54: error: reference to 'Et' is ambiguous
       vector<double> jetets; transform(jets, jetets, Et);
```

The error is actually genuine.

**Comment by marcovanleeuwen** [comment]
Hi Guilio,

The pluginCMS seems to be part of the rivet analysis/ses code:

`/mnt/mesos/sandbox/sandbox/sw/BUILD/3af4d45464fb17313999d5efcb5afae6264e9eea/Rivet/analyses`

I am not sure whether we can remove a single analysis from rivet. Maybe @maireiphc knows? Or maybe there is an update/fix in rivet for this?

Marco.

**Comment by maireiphc** [comment]
Hi @ktf, @marcovanleeuwen,

    to answer your question, in the Rivet language, the plugin is a cxx code meant to be the Rivet MC analysis corresponding to an actual article from a given collaboration.
The "pluginCMS" is in fact the full set of CMS analyses that already made into the Rivet source.

https://github.com/alisw/rivet/tree/master/analyses/pluginCMS
Here there is only one culprit out of the 335 analyses available :
https://github.com/alisw/rivet/blob/master/analyses/pluginCMS/CMS_2013_I1223519.cc
corresponding to http://inspirehep.net/record/1223519 (a SUSY search)

What we can do as a temporary fix : 
1 - simply delete that specific code from our own alisw repo of Rivet (I guess ALICE can leave without that specific code for a while without really missing it)
2 - port the fixes introduced later by the official Rivet authors ("Et" -> "Kin::Et") + ("biset" -> "std::bitset")
    - https://gitlab.com/hepcedar/rivet/commit/0d5f91a4c8e66f5c6cbd7d231c73a46be9c7109a
    - https://gitlab.com/hepcedar/rivet/commit/ced494d4016dde5dcd24567a276942fa0f64c446

A more long term fix is to move our Rivet 2.7.2 to the newer Rivet release 3.1.0 where the fixes are in the official sources (this will call for upgrade of other packages, YODA for sure, fastjet probablly as well).

What is a puzzling to me is the fact that the original pull request which triggered such an issue (lzma.sh update, https://github.com/alisw/alidist/pull/2055/commits/72f3f4e9f28e9dde5c57fc8efea9bd4b6c64153b) has been merged into the mains alisw/alidist recipe 2 days ago.
The build checks failed back then but the daily build of yesterday for AliGenerator (so including Rivet) did not complain about anything and went through it successfully
https://alijenkins.cern.ch/job/DailyBuilds/job/DailyAliGenerators/186/consoleFull

Any idea why it can be so ?

**Comment by marcovanleeuwen** [comment]
Hi Antonin, all,

Would it then make sense to try and move to the newer Rivet as well? We already have a recent version of fastjet (v3.3.3_1.042). Could you put the new Rivet version in our local repo (as a pull request; making sure to to also remove files if needed; there is a command for that in the fastjet update ticket... ) Do you have a machine at which you can test-compile to see what else needs an update?

Marco.

**Comment by maireiphc** [comment]
Hi @marcovanleeuwen, @ktf ,

1.  I have ported by hand the mods the culprit plugin. Wating @ktf eye to be merged (check there that my target directory makes sense, I am unsure about the our fix policy between branches, master, etc)
https://github.com/alisw/rivet/pull/4

2. @marcovanleeuwen : In the middle term (i.e. rather soonish still), I agree that we will need to switch to rivet 3.1.0.
Here I just want to make the compilation of AliGenerators to work again, since there are many fronts opened in parallel (Herwig, Sherpa, ... fastjet, libgmp)

**Comment by ktf** [comment]
I just merged the PR. Are you able to create a tag? If not I can give you the rights.

**Comment by maireiphc** [comment]
It looks that I cannot tag alisw/rivet (if I am not mistaken) by looking at the web interface.
Should I have the rights to do so, I should see sthg under : https://github.com/alisw/rivet/releases
 right ?

**Comment by ktf** [comment]
I made https://github.com/orgs/alisw/teams/pagmc as a maintainer. Can you try again?

**Comment by maireiphc** [comment]
Ok, now Rivet now tagged (2.7.2 branch tagged with 2.7.2-alice4).
Thanks for the right accreditation.
I have just created a PR to modify alidst/rivet.sh accordingly : https://github.com/alisw/alidist/pull/2080
Let's see if the compilation checks succeed.

**Comment by ktf** [comment]
Looks like we do not actually need this anymore?

**Comment by maireiphc** [comment]
Yes indeed. It looks like the Rivet compilation is not sensitive finally to this deprecated use of boost in fastjet.Envoyé depuis un smartphone.
-------- Message d'origine --------De : Giulio Eulisse <notifications@github.com> Date : 14/02/2020  08:03  (GMT+01:00) À : alisw/alidist <alidist@noreply.github.com> Cc : Antonin MAIRE <antonin.maire@cern.ch>, Mention <mention@noreply.github.com> Objet : Re: [alisw/alidist] rivet + rivet-hi: Do not fail on deprecated declarations (#2058) Looks like we do not actually need this anymore?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alisw/alidist/pull/2058?email_source=notifications\u0026email_token=AGMHSC4FGRRO2U4YZH76PSTRCY6ZBA5CNFSM4KRTCKTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELXZHDA#issuecomment-586126220",
"url": "https://github.com/alisw/alidist/pull/2058?email_source=notifications\u0026email_token=AGMHSC4FGRRO2U4YZH76PSTRCY6ZBA5CNFSM4KRTCKTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELXZHDA#issuecomment-586126220",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
