### PR TITLE
Do not require Python modules on osx_arm64. 

### PR DESCRIPTION
**Pull request by pzhristov**
Check for specific setuptools==60.8.2 that work for XRootD on Mac M1.

### CODE REVIEW

**Comment by pzhristov** [comment]
This PR should be checked on Mac M1 where we do not use miniconda3 for the python packages. Miniconda is useful since it enables the Metal GPUs to tensorflow, etc., but some people may rely on the standard pip3.

**Comment by pzhristov** [comment]
@ktf  The check correctly found unsupported version and failed. I updated the setuptools==60.8.2 on our M1 server, so now the problem is fixed. If you agree, I propose to merge.

**Comment by ktf** [comment]
This is fine with me, did you update all the servers, though? I would have expected the test to be redone and become green.

**Comment by ktf** [comment]
I have restarted the test just to make sure.

**Comment by pzhristov** [comment]
The compilation is OK, but something is wrong with the tests.

**Comment by ktf** [comment]
That test usually fails when there is some CCDB hiccup, so it should be safe.

**Pull request merged**
