### PR TITLE
Bump AliECS to v0.37.0 + bump Go to 1.18

### PR DESCRIPTION
**Pull request by teo**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by vascobarroso** [comment]
@alisw/infrastructure-admins is this change ok for you ? If so, can this be merged ?

**Comment by awegrzyn** [comment]
I'm not sure if this matters but there's 1 warning that might be treated as error:
```
## sw/BUILD/Control-OCCPlugin-latest/log
--
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
/sw/SOURCES/Control-OCCPlugin/v0.37.0/v0.37.0/occ/occlib/OccServer.cxx: In member function 'virtual grpc::Status OccServer::Transition(grpc::ServerContext*, const occ_pb::TransitionRequest*, occ_pb::TransitionReply*)':
/sw/SOURCES/Control-OCCPlugin/v0.37.0/v0.37.0/occ/occlib/OccServer.cxx:197:18: warning: structured bindings only available with '-std=c++17' or '-std=gnu++17'
  197 |             auto [newKey, newValue] = propMapEntryToPtree(item.key(), item.value());
      |                  ^
In file included from /sw/slc8_x86-64/boost/v1.75.0-33/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
--
```

**Comment by vascobarroso** [comment]
@awegrzyn I see. But then shouldn't it fail for all tests (including our reference `alidist-dataflow-cs8`) ?
Still, @teo could you have a look ?

**Comment by awegrzyn** [comment]
It depends on defaults, but as I said before, I'm not certain this is actual cause of failure.

**Comment by teo** [comment]
The line of the warning hasn't been changed for a long time. Everything looks fine to me, IMO this can be merged as long as RPMs build fine.

**Comment by vascobarroso** [comment]
RPMs are fine, tested in STAGING. @ktf could you merge this ? Thanks!

**Pull request merged**
