### PR TITLE
Bump Monitoring v1.9.2

### PR DESCRIPTION
**Pull request by awegrzyn**
Export AliceO2::Monitoring target

### CODE REVIEW

**Comment by Barthelemy** [comment]
Let me know if you want me to force the merge (there is a test that fails but I can't see the reason)

**Comment by awegrzyn** [comment]
@dberzano @ktf Could you take a look at failing build?

**Comment by awegrzyn** [comment]
Could you restart `build/O2/alidist` build?

**Comment by dberzano** [comment]
OK for the record the error was, probably, some intermittently failing test. The reason why the log wasn't uploaded, I don't know but I am trying to figure it out in other similar pull requests (we're having the problem with AliPhysics too).

**Pull request merged**
