### PR TITLE
Reenable the multinode test

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@knopers8

**Review by knopers8 — APPROVED** [review]

**Comment by Barthelemy** [comment]
@ktf There is an analysis test failure. Could you have a look ?

**Comment by ktf** [comment]
@TimoWilken this one seems to have issues on Centos 8

**Comment by knopers8** [comment]
This test uses DPL proxies and checks them in the context of QC. Since the proxies are likely to be modified quite soon, it would be good if this test was enabled before that.

**Comment by ktf** [comment]
Given dataflow seems to work. I am merging this.

**Comment by knopers8** [comment]
Thanks!

**Pull request merged**
