### PR TITLE
Bump Monitoring to v3.0.2

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by ktf** [comment]
Please make sure you remove [WIP] if you want this to be tested.

**Comment by ktf** [comment]
What does [DNM] stand for?

**Comment by ktf** [comment]
Ah, Do Not Merge...

**Comment by awegrzyn** [comment]
I'm want to merge it AFTER new FLP Suite is released. Thx!

**Comment by awegrzyn** [comment]
@ktf it is good to go now

**Comment by knopers8** [comment]
I am seeing millions of metric logs in any DPL executable after this one has been merged. Is it just me?
```[134687:D]: [METRIC] matcher_variables/219,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/220,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/221,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/222,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/223,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/224,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/225,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/226,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/227,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/228,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/229,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/230,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/231,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
[134687:D]: [METRIC] matcher_variables/232,0 null 1587980047624 hostname=aido2qc10.cern.ch,name=o2-testworkflows-diamond-workflow,dataprocessor_id=D
```
They disappear after reverting the commit.

**Comment by ktf** [comment]
@awegrzyn did you change the format of the metrics?

**Comment by awegrzyn** [comment]
Nope, I did not intend to change the metric format but maybe it's side effect of some other change :|

@knopers8 what shall I run to see this?

**Comment by ktf** [comment]
I see a bunch of "null". Maybe that's the problem? Did anything change there?

**Comment by knopers8** [comment]
@awegrzyn 
For example this:
```
alienv enter O2/latest
o2-testworkflows-diamond-workflow -b
```
Any DPL workflow prints these now.

**Comment by awegrzyn** [comment]
Hmm, there are not metrics on my macOS, lemme see CC7.

**Comment by awegrzyn** [comment]
I get `[12:21:41][ERROR] getDevice(): no valid device provided. Exiting.`, I guess this is why I'm not getting any metrics? What am I doing wrong?

**Comment by awegrzyn** [comment]
When I  try other workflow `o2-testworkflows-parallel-workflow` I get `[12:33:35][ERROR] Unhandled exception reached the top of main: unordered_map::at: key not found, device shutting down.`

**Pull request merged**
