### PR TITLE
Add TpcFecUtils to FLP Suite v0.14.0 branch

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
Manually tested

**Comment by ktf** [comment]
This will break the builds. Did you test building FLUKA afterwards in the same environment?

**Comment by awegrzyn** [comment]
@ktf we did the same for the FLP Suite v0.13.0 and there was no issue, it's actually you who told us to keep it in separate branch

**Comment by awegrzyn** [comment]
See https://github.com/alisw/alidist/pull/2685

**Comment by ktf** [comment]
Sorry I missed this was a separate branch.

**Pull request merged**
