### PR TITLE
Update SHERPA + AliGen fixes

### PR DESCRIPTION
**Pull request by jackal1-66**
This update brings also additional compatibility with newer compilers.

### CODE REVIEW

**Comment by jackal1-66** [comment]
This PR includes multiple fixes:
- Sherpa update to allow compilation with newer default compilers
- Rivet removal of old fastjet-config fix => this was causing errors during compilation
- JETSCAPE update to newer version (see alisw/JETSCAPE#3)
- Yoda fix for cython => added link in cython binary folder to python3 executable

**Comment by jackal1-66** [comment]
@pzhristov @ktf @maireiphc this PR should have fixed multiple issues of the past days seen on AliGenerators building, 
could you please merge it? All tests seem to have passed succesfully

**Comment by jackal1-66** [comment]
@ktf Could you have a look at this? AliGenenerators has been out since few weeks now

**Comment by ktf** [comment]
Thanks!

**Pull request merged**
