### PR TITLE
Add temporary repository for ML model storage

### PR DESCRIPTION
**Pull request by fcatalan92**
@ktf As discussed by mail, I have created a temporary repository to store the ML models for the inference on Hyperloop. It will be deleted when CCDB storage will be available.

I made the module an O2 requirement since there are developments that could need this feature.

### CODE REVIEW

**Comment by ktf** [comment]
Thanks. 
@awegrzyn I guess we need to disable this for o2-dataflow, as we do for ONNX?

**Comment by awegrzyn** [comment]
Yes, thanks !

**Comment by ktf** [comment]
@fcatalan92 do you actually need this in O2 proper? I.e. will it be used for the sync / async reco / simulation? If this is just O2Physics related we should probably move the dependency there.

**Comment by fcatalan92** [comment]
@ktf Hi, my understanding is that this will be used also for calibration / QC / simulation. So it is needed in O2.

**Comment by ktf** [comment]
ok, so i leave it as it is for now. @awegrzyn please make sure you pick it up in your flp suite branch, so that for next version we can drop the workaround I currently have to do the EPN builds.

**Comment by awegrzyn** [comment]
As it's a bit late for v0.56.0 it will come with following release.

**Pull request merged**
