### PR TITLE
Bump qualitycontrol to v1.40.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by davidrohr** [comment]
@ktf @jgrosseo @TimoWilken : O2Physics is currently breaking PRs:
```
## sw/BUILD/O2Physics-latest/log
--
[8/446] Building CXX object Common/Tools/CMakeFiles/O2Physicsexe-pidparam-tpc-bethe-bloch.dir/handleParamTPCBetheBloch.cxx.o
FAILED: Common/Tools/CMakeFiles/O2Physicsexe-pidparam-tpc-bethe-bloch.dir/handleParamTPCBetheBloch.cxx.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -I/Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/O2Physics/daily-20211124-1650/daily-20211124-1650 -I/Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/O2Physics/daily-20211124-1650/daily-20211124-1650/Common/Core -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/O2/3601-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/Common-O2/v1.6.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/boost/v1.75.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/Configuration/v2.6.3-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/libInfoLogger/v2.4.1-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/Monitoring/v3.10.1-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/curl/7.70.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/FairMQ/v1.4.43-local3/include/fairmq -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/FairMQ/v1.4.43-local3/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/FairLogger/v1.10.2-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/fmt/8.0.1-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/ROOT/v6-24-06-local6/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/O2/3601-local1/include/GPU -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/FairRoot/v18.4.2-local11/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v5.0.0-alice3-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/Vc/1.4.1-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/ms_gsl/3.1.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/libjalienO2/0.1.3-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/RapidJSON/v1.1.0-alice2-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/libuv/v1.40.0-local1/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=11.6 -std=gnu++17 -MD -MT Common/Tools/CMakeFiles/O2Physicsexe-pidparam-tpc-bethe-bloch.dir/handleParamTPCBetheBloch.cxx.o -MF Common/Tools/CMakeFiles/O2Physicsexe-pidparam-tpc-bethe-bloch.dir/handleParamTPCBetheBloch.cxx.o.d -o Common/Tools/CMakeFiles/O2Physicsexe-pidparam-tpc-bethe-bloch.dir/handleParamTPCBetheBloch.cxx.o -c /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/O2Physics/daily-20211124-1650/daily-20211124-1650/Common/Tools/handleParamTPCBetheBloch.cxx
/Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/O2Physics/daily-20211124-1650/daily-20211124-1650/Common/Tools/handleParamTPCBetheBloch.cxx:146:96: error: variable 'headers' is uninitialized when used here [-Werror,-Wuninitialized]
    BetheBloch* bb = api.retrieveFromTFileAny<BetheBloch>(path + "/" + exp_name, metadata, -1, headers);
                                                                                               ^~~~~~~
/Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/O2Physics/daily-20211124-1650/daily-20211124-1650/Common/Tools/handleParamTPCBetheBloch.cxx:81:46: note: initialize the variable 'headers' to silence this warning
--
[11/446] Building CXX object Tutorials/CMakeFiles/O2Physicsexe-analysistutorial-track-iteration.dir/src/trackIteration.cxx.o
[12/446] Building CXX object Common/Tasks/CMakeFiles/O2Physicsexe-analysis-validation.dir/validation.cxx.o
[13/446] Building CXX object Tutorials/CMakeFiles/O2Physicsexe-analysistutorial-extended-tables.dir/src/extendedTables.cxx.o
```

**Comment by TimoWilken** [comment]
@davidrohr https://github.com/alisw/ali-bot/pull/1126 should fix this.

**Comment by davidrohr** [comment]
@Barthelemy : could you force push to trigger a restart?

**Comment by ktf** [comment]
The warnings in macOS should be fixed by [AliceO2Group/O2Physics#](https://github.com/AliceO2Group/O2Physics/pull/352) and are otherwise unrelated. Merging this.

**Pull request merged**
