### PR TITLE
bump readout

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
the cc8 and alidist failures do not seem related to this PR... can you please check ?

**Comment by ktf** [comment]
No, indeed, I am already looking into the issue.

**Comment by sy-c** [comment]
@alisw/dataflow-experts someone to review, please ?

**Review by vascobarroso — APPROVED** [review]

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins, is it possible to please fix the failing CI tests?

**Comment by sy-c** [comment]
@alisw/infrastructure-admins @ktf can you please merge this PR or fix the CI ?

**Pull request merged**
