### PR TITLE
Bump bookkeeping to v0.16.9

### PR DESCRIPTION
**Pull request by vascobarroso**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@vascobarroso CI will not report any error on this as this `Bookkeeping` it not used in any package
@DimitrySteenkamer It looks like `v0.16.9` fails with 
```
/cpp-api-client/src/CreateRunParameters.h:4:10: fatal error: boost/date_time/posix_time/ptime.hpp: No such file or directory
 #include <boost/date_time/posix_time/ptime.hpp>
```
If I take a look at your CMake (https://github.com/AliceO2Group/Bookkeeping/blob/decc0eed681edcdb667ca892d78f06996583c873/cpp-api-client/CMakeLists.txt#L16) you don't mention `date_time` in `COMPONENTS`.

**Comment by awegrzyn** [comment]
Actually the error comes from `CreateRunParameters.h` header? Do you even use it? As far as I can see it's included in `BookkeepingInterface.h` but never used?

**Review by awegrzyn — CHANGES_REQUESTED** [review]
see my comments

**Comment by DimitrySteenkamer** [comment]
I do not know why the error says this. Because bookkeepingApi.cpp uses this header as well.
https://github.com/AliceO2Group/Bookkeeping/blob/decc0eed681edcdb667ca892d78f06996583c873/cpp-api-client/src/BookkeepingApi.cpp#L3

**Review by DimitrySteenkamer — APPROVED** [review]

**Comment by awegrzyn** [comment]
@DimitrySteenkamer The error says that because use `Boost::date_time` in public header and in CMake you link against it under `PRIVATE`...

**Pull request merged**
