### PR TITLE
Bump LLVM and CodeChecker to 17.0.6

### PR DESCRIPTION
**Pull request by davidrohr**
include #5439 and #5569

### CODE REVIEW

**Comment by ktf** [comment]
This works on hyperloop. I am restarting the fullCI and macos tests.

**Comment by davidrohr** [comment]
FullCI was green already, when the test reran it failed for some random reason.
MacOS ran multiple times, and always failed with different reasons 🤷‍♂️.

**Comment by ktf** [comment]
Ok, merging this. Let's see...

**Comment by vascobarroso** [comment]
@davidrohr @ktf FYI this change is breaking our RPM generation. I have created a ticket for Barth who will be back on Wednesday (https://its.cern.ch/jira/browse/OCONF-819) but we might need to revert this in the FLP Suite release branches if we need to release new RPMs in the meantime.

**Pull request merged**
