### PR TITLE
Bump DDS to 3.7.21

### PR DESCRIPTION
**Pull request by lkrcal**

### CODE REVIEW

**Comment by davidrohr** [comment]
@TimoWilken : could you check why this is repeatedly failing without a log in the fullCI?

**Comment by ktf** [comment]
@davidrohr do you understand the issue:

```
Detected critical problem in logfile reco_NOGPU.log
reco_NOGPU.log-o2-dpl-run --session default --severity info --shm-segment-id 0 --shm-segment-size 8000000000  --early-forward-policy noraw --monitoring-backend no-op:// --fairmq-rate-logging 0 --timeframes-rate-limit 24 --timeframes-rate-limit-ipcid 0 -b --run 
reco_NOGPU.log-
reco_NOGPU.log:terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
reco_NOGPU.log-  what():  option '--configKeyValues' cannot be specified more than once
reco_NOGPU.log:terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::multiple_occurrences>'
reco_NOGPU.log-  what():  option '--configKeyValues' cannot be specified more than once
reco_NOGPU.log:[ERROR] error while setting up workflow in o2-tpc-idc-factorize: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
reco_NOGPU.log:[ERROR] Dynamic exception type: boost::wrapexcept<boost::program_options::multiple_occurrences>
reco_NOGPU.log:[ERROR] std::exception::what: option '--configKeyValues' cannot be specified more than once
reco_NOGPU.log-[ERROR] 
killing child 5585
Running: TIME="#walltime %e" /sw/slc8_x86-64/O2/4425-slc8_x86-64-local1/share/scripts/monitor-mem.sh /usr/bin/time --output=reco_NOGPU.log_time './reco_NOGPU.log_tmp.sh'
/usr/bin/time --output=reco_NOGPU.log_time ./reco_NOGPU.log_tmp.sh
```

did you change the scripts?

**Comment by ktf** [comment]
(@TimoWilken is on holidays, BTW).

**Comment by davidrohr** [comment]
Ahh, this is a new error... The first 2 builds in the FullCI failed without a log file. I'll have a look.

**Pull request merged**
