### PR TITLE
Update RapidJSON to fix GCC-8 compilation error

### PR DESCRIPTION
**Pull request by awegrzyn**
Obsoletes https://github.com/alisw/rapidjson/pull/2

### CODE REVIEW

**Comment by ktf** [comment]
@michael.lettrich @dberzano looks like the logs are not available for macOS...

**Comment by dberzano** [comment]
Having a look.

**Comment by dberzano** [comment]
They should come back at some point, it's been fixed.

**Comment by ktf** [comment]
@dberzano they are still not available.

**Pull request merged**
