### PR TITLE
Add the recipes for the Configuration module

### PR DESCRIPTION
**Pull request by Barthelemy**
Recipes to compile the Configuration module. It needs a review.

### CODE REVIEW

**Comment by Barthelemy** [comment]
By the way, am I right to ask for a PR to IB/v5-08/next ?

**Comment by ktf** [comment]
Since you only introduce new packages, how about we use prod directly?

**Comment by Barthelemy** [comment]
Fine with me !

**Comment by Barthelemy** [comment]
It seems that changing the base branch to prod I now brought along a number of commits from next. Is there a way to get it right ? or should I simply create a new branch from prod and copy my files there and create a new PR ?

**Comment by Barthelemy** [comment]
New PR here : https://github.com/alisw/alidist/pull/577

**Pull request closed without merging**
