### PR TITLE
Drop ApMon-CPP on macOS

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@costing @awegrzyn It does not relocate correctly when built in one place and used as a binary from a different one. Rather than patching it, I guess it's easier to simply drop it, as in any case we do not want to report to monalisa from people laptops.

**Comment by ktf** [comment]
@MichaelLettrich @TimoWilken this has been building for over 8 hours on aido2os. Could you check why?

**Comment by costing** [comment]
No problem skipping it for Mac builds.

**Review by awegrzyn — APPROVED** [review]

**Comment by TimoWilken** [comment]
@ktf disk space ran out again. I'll restart the builder.

**Comment by ktf** [comment]
Merging this. Tested locally and in any case broken in the CI tests right now.

**Pull request merged**
