### PR TITLE
Removed Pythia8 override in defaults

### PR DESCRIPTION
**Pull request by jackal1-66**

### CODE REVIEW

**Comment by jackal1-66** [comment]
PR opened following #5398. No need to have Pythia overrides anymore.

**Comment by ktf** [comment]
The issue seems legit. Could you check?

**Comment by jackal1-66** [comment]
@ktf will check asap

**Comment by jackal1-66** [comment]
Ciao @ktf I just opened a PR on EVTGEN to make it compatible with the latest versions of Pythia (alisw/EVTGEN#2)

**Comment by ktf** [comment]
With your fixed EVTGEN this now merged fine. Merging.

**Pull request merged**
