### PR TITLE
Bump onnxruntime to v1.12.1

### PR DESCRIPTION
**Pull request by fcatalan92**
@ktf For the moment I have created a new branch on my fork, could you port it to the alisw one?

@saganatt @ChSonnabend I have already tested the new version and didn't see any problem, but please have a look at your workflows.

### CODE REVIEW

**Comment by ktf** [comment]
Done. Let me know when you are happy to merge.

**Comment by ktf** [comment]
Are we ok to merge this?

**Comment by ChSonnabend** [comment]
Unfortunately I can't build O2 at the moment (our server at GSI has no space left on disk) but it should work without problems, so for me it's fine if we merge it.

**Comment by ktf** [comment]
@saganatt

**Comment by saganatt** [comment]
Hi, sorry for the delay, it works well for me.

**Pull request merged**
