### PR TITLE
WIP Switch off Fortran: h2root and hbook are not needed and their compila…

### PR DESCRIPTION
**Pull request by pzhristov**
…tion causes problems on MacOS

### CODE REVIEW

**Comment by pzhristov** [comment]
The error we see in the linking of AliRoot/MICROCERN library on SLC7 is similar to what we had in Root, and has to be fixed separately.

**Comment by dberzano** [comment]
There's also GEANT3. GEANT3 takes the Fortran config from ROOT. We should apply `-DCMAKE_Fortran_compiler=gfortran` to the `geant3.sh` recipe.

**Comment by pzhristov** [comment]
In theory if we add Fortran to project(Geant3) (together with CXX and C), this should be enough, CMake should be able to find it automatically.

**Comment by dberzano** [comment]
In principle yes, but we must really specify `-DCMAKE_Fortran_COMPILER` to avoid ambiguities (it's a small change).

**Pull request merged**
