### PR TITLE
daily tags: auto-update dist definitions

### PR DESCRIPTION
**Pull request by alibuild**
The daily-tags.sh script has created a tag release with these changes.

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf @TimoWilken The change from `nightly-*` to `daily-*` broke our upgrade deployment as `n` is always higher than `d`, do you plan to use `daily` or it was just 1 time? If so, would it be possible to make it compatible with  YUM versioning?

**Comment by ktf** [comment]
We use daily when we tag between nightlies some hot patch, as we did
yesterday. In general they are not needed. Can't you simply filter out
daily- from the RPM building? Will you actually allow for intraday
deployments?

Ciao,
Giulio

**Comment by awegrzyn** [comment]
Understood, yes we can remove `daily-` and `nightly-` prefixes from RPM version, but I'd need your confirmation that there will be no daily and nightly releases with the exact same date (`daily-X` and `nightly-X`)? Suffixing is of course fine (`daily-X-1` and `nightly-X`)

**Comment by ktf** [comment]
daily-X always has time associated with it right now, so that we can release more than once during the day. Would that suffice?

**Comment by awegrzyn** [comment]
Yep that's enough, thx

**Pull request merged**
