### PR TITLE
Simplify pickup of system protobuf

### PR DESCRIPTION
**Pull request by dberzano**
Should supersede #879.

### CODE REVIEW

**Comment by dberzano** [comment]
@davidrohr @ktf this is what I have in mind, I am currently testing it with O2. For FairRoot, I have already tested it and it correctly picks:

* protobuf from the system, in case no protobuf from ours is available;
* protobuf from ours in case it is available.

This works with a patched FairRoot only. Bump to patch version will be added to this PR later. Stay tuned!

**Comment by dberzano** [comment]
See FairRootGroup/FairRoot#652, proposed for upstream dev.

**Comment by dberzano** [comment]
So if you pick up this alidist version (and you don't have FairRoot in devel mode, so that you are forced to use our version) it should work.

Waiting for confirmation from @davidrohr :-)

**Comment by davidrohr** [comment]
@dberzano : Hi Dario, I rebuilt from scratch and protobuf is picked up correctly from the system.
Thanks
David

**Comment by dberzano** [comment]
@davidrohr thanks for checking, I had to merge it before your check as @shahor02 needed it sooner :-)

**Comment by davidrohr** [comment]
@dberzano : I saw that, but wanted to let you know that it works with system protobuf as well, so I think we can close this topic now.

**Comment by ktf** [comment]
@dberzano this (or something related to this) seems to have broken the PR builds on system which have both system and our protobuf, e.g. the build machines. See for example:

https://github.com/AliceO2Group/AliceO2/pull/626

**Comment by ktf** [comment]
@dberzano @dennisklein for the record the actual problem seems to be:

```
...
-DProtoBuf_DIR=/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/protobuf/v3.0.2
...
-- Looking for Protobuf... - found: libraries: optimized;/lib64/libprotobuf.so;debug;/lib64/libprotobuf.so;-lpthread, includes: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/protobuf/v3.0.2-1/include, protoc: /bin/protoc
``` 

which if I understand correctly is simply wrong.

**Comment by dennisklein** [comment]
Yes, looks wrong. It seems to mix up system installation with custom installation somehow. I had a holiday today, will have a look at it tomorrow.

**Comment by dberzano** [comment]
I have a fix. I'm making a PR.

**Comment by dberzano** [comment]
See FairRootGroup/FairRoot#656.

**Pull request merged**
