### PR TITLE
Aliecs bump + Mac build fix

### PR DESCRIPTION
**Pull request by teo**

### CODE REVIEW

**Comment by teo** [comment]
Note: the alidist_macOS CI build fails because of the gRPC issue addressed in https://github.com/alisw/alidist/pull/1704

**Comment by ktf** [comment]
Can you cherry pick #1704 so that we test all at once?

**Comment by Barthelemy** [comment]
The failing CI is due to downstream error (Readout).

**Comment by Barthelemy** [comment]
and actually your PR works on my Mac with defaults o2-dataflow

**Comment by ktf** [comment]
Merged. Let's take care of Readout in a separate PR.

**Pull request merged**
