### PR TITLE
Bump qcg.sh version 1.9.4

### PR DESCRIPTION
**Pull request by graduta**

### CODE REVIEW

**Review by kostorr — APPROVED** [review]

**Comment by graduta** [comment]
@davidrohr  Is there any way we could get the builds of this PR retriggered?
Thank you

**Comment by davidrohr** [comment]
You can force-push another commit hash, and you can use `git commit --amend` to change the hash of an existing commit

**Comment by graduta** [comment]
@davidrohr , ok. 
I was hoping there would be a button for this. I use GitHub Actions to automatically raise PRs in alidist after a new NPM release of QCG and I do not have this repository set up locally. 

Maybe we can look at having a rebuild button in the future. 

Thank you for your help

**Comment by davidrohr** [comment]
@graduta : Hm, don't think there is a button to trigger this in the github user interface. We can do it by forcing it manually in aurora, but for users I think the best way is to just force push. Anyway, I am also not really an expert for the CI :)

**Comment by graduta** [comment]
@awegrzyn , @ktf it seems like there is a problem with the macOS machine. Could one of you have a look, please?

```
fatal error: error in backend: IO failure on output stream: No space left on device
```

**Comment by ktf** [comment]
we actually have a way to retrigger tests via github actions. i will document it once i am back home.

**Comment by MichaelLettrich** [comment]
> @MichaelLettrich  it seems like there is a problem with the macOS machine. Could you have a look, please?
> 
> ```
> fatal error: error in backend: IO failure on output stream: No space left on device
> ```

I will take care of macos

**Pull request merged**
