### PR TITLE
add o2 defaults catered towards system libs

### PR DESCRIPTION
**Pull request by adriansev**
prepared defaults for testing building with system curl and openssl dependencies

### CODE REVIEW

**Comment by adriansev** [comment]
@ktf this might not build given the target and if the prerequisites listed at https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-centos8.html are not used on testing machines.
I did this defaults for easy building with system libraries for testing and investigations.

**Comment by ktf** [comment]
Didn't we decide that we actually deploy the full installation on the EPNs? Why is this needed now?

**Comment by adriansev** [comment]
@ktf no, it is not needed, this is just an investigative tool on possibility and compatibility with system provided software ... if you tell me that the presence of this setting would have a negative impact i will try to keep it only in my branch

**Comment by davidrohr** [comment]
In my opinion the pure presense of the defaults obviously doesn't break anything, but it could lead people into using it and expecting support. So in case it is only for your private tests, I would actually indeed prefer if it could be kept in a private fork.
Particularly, when it is used only by you there cannot be merge conflicts.

**Comment by adriansev** [comment]
got it!

**Pull request closed without merging**
