### PR TITLE
xrootd update to 5.4.0

### PR DESCRIPTION
**Pull request by adriansev**
* https://github.com/xrootd/xrootd/releases/tag/v5.4.0
* https://github.com/xrootd/xrootd/blob/v5.4.0/docs/ReleaseNotes.txt

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken could you warm up the  cache so that we do not wait the rebuilds?
@MichaelLettrich could you check what is going on with the ARM mac?
@sawenzel do I understand correctly VecCore is downloaded out of band by VecGeom? Is it possible to have it as a proper package?

**Comment by MichaelLettrich** [comment]
@ktf @pzhristov 
This looks like a specific Apple ARM64 issue.

```bash
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + pushd /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8 /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/BUILD/3435c3c865fbfed11e8581dfd7265cbed6532ce8/xjalienfs
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + WORK_DIR=/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + bash -ex /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4/relocate-me.sh
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + [[ /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8 == '' ]]
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + OP=osx_arm64/xjalienfs/1.3.7-local4
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + PP=osx_arm64/xjalienfs/1.3.7-local4
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + PH=3435c3c865fbfed11e8581dfd7265cbed6532ce8
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + sed -e 's|/[^ ;:]*INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4|/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4|g;s|[@][@]PKGREVISION[@]3435c3c865fbfed11e8581dfd7265cbed6532ce8[@][@]|local4|g' osx_arm64/xjalienfs/1.3.7-local4/etc/modulefiles/xjalienfs.unrelocated
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: ++ otool -D osx_arm64/xjalienfs/1.3.7-local4/lib/python3.9/site-packages/gnureadline.cpython-39-darwin.so
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: ++ tail -n1
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: ++ sed -e 's|/[^ ]*INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4|/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4|g'
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + install_name_tool -id osx_arm64/xjalienfs/1.3.7-local4/lib/python3.9/site-packages/gnureadline.cpython-39-darwin.so: osx_arm64/xjalienfs/1.3.7-local4/lib/python3.9/site-packages/gnureadline.cpython-39-darwin.so
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: ++ otool -D osx_arm64/xjalienfs/1.3.7-local4/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: ++ tail -n1
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: ++ sed -e 's|/[^ ]*INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4|/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/INSTALLROOT/3435c3c865fbfed11e8581dfd7265cbed6532ce8/osx_arm64/xjalienfs/1.3.7-local4|g'
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: + install_name_tool -id osx_arm64/xjalienfs/1.3.7-local4/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so '(architecture' 'arm64):' osx_arm64/xjalienfs/1.3.7-local4/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: more than one input file specified (arm64): and (architecture)
2022-01-07@10:49:46:DEBUG:O2Suite:xjalienfs:3696: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
2022-01-07@10:49:46:ERROR:O2Suite:xjalienfs:3696: Error while executing /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SPECS/osx_arm64/xjalienfs/1.3.7-local4/build.sh on `alibuildmac04.cern.ch'.
2022-01-07@10:49:46:ERROR:O2Suite:xjalienfs:3696: Log can be found in /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/BUILD/xjalienfs-latest/log
2022-01-07@10:49:46:ERROR:O2Suite:xjalienfs:3696: Please upload it to CERNBox/Dropbox if you intend to request support.
2022-01-07@10:49:46:ERROR:O2Suite:xjalienfs:3696: Build directory is /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/BUILD/xjalienfs-latest/xjalienfs.
++ report_pr_errors --no-comments
++ extra_args=()
++ local repo checkout_name extra_args
++ '[' alisw/alidist '!=' alisw/alidist ']'
++ short_timeout report-pr-errors --default master --pr alisw/alidist#3696@c942e2df322a7704b1264f02da9012675f098fa4 -s build/alidist/O2Suite/o2/macOS-arm --logs-dest s3://alice-build-logs.s3.cern.ch --log-url https://ali-ci.cern.ch/alice-build-logs/ --no-comments
++ timeout -s9 600 report-pr-errors --default master --pr alisw/alidist#3696@c942e2df322a7704b1264f02da9012675f098fa4 -s build/alidist/O2Suite/o2/macOS-arm --logs-dest s3://alice-build-logs.s3.cern.ch --log-url https://ali-ci.cern.ch/alice-build-logs/ --no-comments
```

**Comment by ktf** [comment]
Mmm looks like xrootd builds "fat" (arm and x86) modules and aliBuild has  troubles with it. I will investigate.

**Comment by adriansev** [comment]
while i understand that this is not o priority, this is just a gentle ping @ktf about this status :) thanks a lot!
while i do not have proof of problems, there are quite a few items in the release nodes regarding client-side functionality..

**Comment by ktf** [comment]
@TimoWilken actually fixed the issue in aliBuild, so we can now go forward with this. Restarting the tests.

**Comment by ktf** [comment]
@TimoWilken we can merge this, but we should probably pre-cache this and the TBB PR. Can you do that?

**Comment by TimoWilken** [comment]
> @TimoWilken we can merge this, but we should probably pre-cache this and the TBB PR. Can you do that?

I've started a caching job for this PR and #3787 together (CacheO2Package#23).

**Pull request merged**
