### PR TITLE
Bump qualitycontrol to v1.13.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by kostorr — DISMISSED** [review]

**Comment by Barthelemy** [comment]
@awegrzyn @ktf Something with qcg went wrong with the `alidist` build

**Comment by knopers8** [comment]
I think it is because we added the `O2` prefix to library names

**Comment by awegrzyn** [comment]
Yes:
```
ld: cannot find -lQualityControl
collect2: error: ld returned 1 exit status
```

**Comment by Barthelemy** [comment]
what is the best course of action ? update qcg ?
Very sorry about that. I think that we should test qcg in QC PRs.

**Comment by Barthelemy** [comment]
@ktf as discussed I update O2 to v21.10

**Comment by Barthelemy** [comment]
@ktf O2 build on Mac fails it seems ?

**Comment by Barthelemy** [comment]
I don't understand any of the failures in `alidist` and `macOS`. @ktf @TimoWilken

**Comment by TimoWilken** [comment]
@Barthelemy aliBuild couldn't find a new tag from qcg when building. I've fetched the tag manually, restarted the checks and sent a PR to alibuild that should fix this in future.

**Comment by Barthelemy** [comment]
@TimoWilken Thank you !

**Review by vascobarroso — APPROVED** [review]

**Comment by davidrohr** [comment]
@TimoWilken : Why isn't there the full CI among the checks for this PR?

**Pull request merged**
