### PR TITLE
Update geant4 recipe

### PR DESCRIPTION
**Pull request by ihrivnac**
Restore back the Modulefile variables removed in previous commit
and keep modifications for data sets

### CODE REVIEW

**Comment by ihrivnac** [comment]
@ktf,   there are added back all variables which I removed from module file in the last update. Let's try this first, and if it does not help, we can then revert the file to the previous version completely.

**Comment by ihrivnac** [comment]
@ktf, the geant4 recipe is now as before, and the builds end with Geant4 installation, which passes ok (what was also the case before reverting the recipe), and the check is marked as failed.

**Comment by ihrivnac** [comment]
@kft,
I investigated the guntest failure on CC7, which caused the AliRoot PR failures after merging this PR, and the problems seems to be in aliBuild interpretation of the sed command used to defined the G4 data sets variables.
While in the recipe, there is:

`G4ABLADATA : "`${G4INSTALL}/bin/geant4-config --datasets | grep G4ABLADATA | sed 's/[^ ]* [^ ]* //'`"
`
The aliBuild adds` '' `around spaces:
```
DEBUG:AliRoot-guntest:AliRoot-guntest:0: +++++ /root/alice/sw/slc7_x86-64/GEANT4/v10.5.1-3/bin/geant4-config --datasets
DEBUG:AliRoot-guntest:AliRoot-guntest:0: +++++ grep G4ABLADATA
DEBUG:AliRoot-guntest:AliRoot-guntest:0: +++++ sed 's/[^' ']*' '[^' ']*' //
DEBUG:AliRoot-guntest:AliRoot-guntest:0: sed: -e expression #1, char 4: unterminated `s' command

```
The error can be reproduced in a terminal:
```
[root@o2tests02 alice]# /root/alice/sw/slc7_x86-64/GEANT4/v10.5.1-3/bin/geant4-config --datasets | grep G4ENSDFSTATEDATA | sed 's/[^]*[^]*' '//'
sed: -e expression #1, char 10: unterminated `s' command

```
while the original expression works fine:

```
[root@o2tests02 alice]# /root/alice/sw/slc7_x86-64/GEANT4/v10.5.1-3/bin/geant4-config --datasets | grep G4ABLADATA | sed 's/[^ ]* [^ ]* //'
/root/alice/sw/slc7_x86-64/GEANT4/v10.5.1-3/share/Geant4-10.5.1/data/G4ABLA3.1

```
Is there a way to tell aliBuild not to add the '' ?
Thank you.

**Comment by ktf** [comment]
I think the correct way of escaping strings in YAML is:

```YAML
G4ABLADATA: | ${G4INSTALL}/bin/geant4-config --datasets | grep G4ABLADATA | sed 's/[^ ]* [^ ]* //'
```

**Comment by ihrivnac** [comment]
@ktf, thank you, but this gives me the following errors:

```
ERROR: Unable to parse alidist/geant4.sh
ERROR: while scanning a block scalar
ERROR:   in "<string>", line 17, column 15:
ERROR:       G4ABLADATA: | ${G4INSTALL}/bin/geant4-config ... 
ERROR:                   ^
ERROR: expected a comment or a line break, but found '$'
ERROR:   in "<string>", line 17, column 17:
ERROR:       G4ABLADATA: | ${G4INSTALL}/bin/geant4-config - ... 
ERROR:                     ^

```

**Pull request merged**
