### PR TITLE
Bump qualitycontrol to v1.6.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@awegrzyn That should fix the warning in QC we see in macos and thus fix the build.

**Review by awegrzyn — APPROVED** [review]

**Comment by Barthelemy** [comment]
@awegrzyn npm error it seems, related to python

**Comment by awegrzyn** [comment]
Yes, I cannot reproduce it on my setup so I created a this PR https://github.com/alisw/alidist/pull/2626 that might fix the issue.
The problem is that this PR is "red" for past 20 days and as I'm not able to test it locally I'd like to have all checks green.

**Comment by ktf** [comment]
#2626 has been red for a while due to the issue fixed by this PR, AFAICT. Merging it.

**Comment by ktf** [comment]
(any other issue with #2626 was solved 2 weeks ago, BTW...)

**Comment by Barthelemy** [comment]
I have actually made a full version instead of the patch here: https://github.com/alisw/alidist/pull/2677

**Pull request closed without merging**
