### PR TITLE
Remove ownership of rapidjson from dataflow group

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
https://github.com/alisw/alidist/pull/1878

**Comment by Barthelemy** [comment]
@awegrzyn @ktf

**Comment by ktf** [comment]
Can you rebase? I think this was already done in https://github.com/alisw/alidist/commit/36e431de270f8022dac70cfecca6da97c44e917f

**Comment by Barthelemy** [comment]
Correct ! sorry for the noise.

**Pull request closed without merging**
