### PR TITLE
fastjet: update to v3.3.3_1.042-alice1

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by pzhristov** [comment]
@ktf FASTJET 3.4.0 was released on 25/06, may be we should skip version 3.3.3.

**Comment by ktf** [comment]
That's fine with me. This is just the minimal change to fix the compilation issue some people were experiencing.

**Comment by ktf** [comment]
@amorsch for information, since we discussed yesterday about which version to propose to the PB.

**Comment by pzhristov** [comment]
@ktf There is also fastjet version 3.4.0, probably we can try it

**Comment by mverwe** [comment]
Hello,

From PWG-JE side we were preparing to switch to fastjet 3.3.4 with contrib 1.045. See this presentation: https://indico.cern.ch/event/1032236/contributions/4334720/attachments/2231982/3782148/210421_fastjetupdate.pdf

I would think it is better to directly jump to these versions than a step in between.
@mfasDa @bhohlweger

**Comment by mfasDa** [comment]
3.4.0 together with contrib 1.045 are already used in the JALIEN defaults, and the corresponding fastjet and contrib versions have been ported to the ALICE fork, so adaption would be trivial. I would then rather suggest to combine all defaults (at least all ROOT6-based like o2, next-root6, jalien and generators) to the same fastjet version, this makes it easier to combine packages.

**Comment by raymondEhlers** [comment]
The constituent subtraction validation slipped through, I think. If Bernhard emails me, I can help him setup the train to do the validation

**Comment by bhohlweger** [comment]
Hi in the course of writing you ;)

**Comment by bhohlweger** [comment]
Hi 

I opened a PR to bump the fastjet version to 3.4.0 and fjcontribution to 1.045: https://github.com/alisw/fastjet/pull/10 (we would need a tag v3.4.0_1.045-alice1)

and I opened another PR to alidist in order to create a "temporary" tag following the same strategy as before: https://github.com/alisw/alidist/pull/3155

Cheers 

Bernie

**Comment by ktf** [comment]
Tag is now available at https://github.com/alisw/fastjet/releases/tag/v3.4.0_1.045-alice1

**Comment by ktf** [comment]
Superseded by #3155

**Pull request closed without merging**
