### PR TITLE
Add npm installation prefix to qcg recipe

### PR DESCRIPTION
**Pull request by Barthelemy**
make sure we install in the right place

### CODE REVIEW

**Comment by Barthelemy** [comment]
@ktf Because node.js needs to know where it is (@awegrzyn can correct me). Would having a different name be ok ?

**Comment by ktf** [comment]
Does it need to know about it at runtime? Why not simply relying on LD_LIBRARY_PATH?

**Comment by Barthelemy** [comment]
As far as I can see, in the binding definition for node.js (to access QC from JS), it needs the include directories : 
```
      'include_dirs': ["<!@(node -p \"require('node-addon-api').include\")", "<@(qc_root)/include", "<@(root_include)", "$(CONFIGURATION_ROOT)/include", "$(COMMON_O2_ROOT)/include", "$(BOOST_ROOT)/include" ],
```
Thus when building qcg it requires to know these variables.

**Comment by ktf** [comment]
A different name is not ok, because it will still prevent people who installed boost from the system to pick it up correctly, since `BOOST_ROOT` is not set by anyone else. How are the bindings generated?

**Comment by awegrzyn** [comment]
@Barthelemy `BOOST_ROOT` is only required during compilation, not execution.

**Comment by ktf** [comment]
`BOOST_ROOT` is guaranteed to be present at build time the package is built via aliBuild and boost from the system is not compatible with the one we expect in O2.
 
What do you mean by manual installation?

**Comment by Barthelemy** [comment]
@ktf We discussed with adam and I am dropping the line I added to boost.sh. I keep the other fix that I need. Adam will think how to make it work in a proper way.

**Comment by awegrzyn** [comment]
@ktf Could you merge?

**Comment by ktf** [comment]
Related to this, can you tell me what `otool -h someBindingLibrary.so` returns on mac? I suspect you have been hit by a bug in aliBuild which was not correctly relocating the RPATH for bundles (as opposed to dylibs).

**Pull request merged**
