### PR TITLE
Bump qualitycontrol to v1.9.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@mfasDa

**Comment by Barthelemy** [comment]
@ktf @TimoWilken generators failed without logs

**Comment by TimoWilken** [comment]
@Barthelemy known problem, sorry, working on it. Build is pending so it runs again soon.

**Comment by Barthelemy** [comment]
@ktf @awegrzyn could this be forced merged ?

**Pull request merged**
