### PR TITLE
Update FastJet and FJContrib to v3.2.1_1.024

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
This **must not be merged** until proper validation is performed. Pending approval from the Jet group.

**Comment by adriansev** [comment]
Hi! I had used 3.2.1 since it appeared in august and I seen no problems in my analysis. Anyway,
the changelogs http://fastjet.fr/all-releases.html (for fastjet) and http://fastjet.hepforge.org/svn/contrib/tags/1.024/NEWS (for contrib) makes a compelling argument for upgrade. Still, the conveners of PWGJE should be asked about this (and provided with a link to this PR) in order to be discusses on the group list.
Thank you!

**Comment by dberzano** [comment]
Hello @adriansev, this PR is the result of an internal discussion. When the appropriate PWG will give us green lights, we will merge it. Also note that the PR is to the `next` branch, not the `prod` one. Note that the discussion on this topic is, as said, internal and does not pertain to this PR :-)

**Comment by adriansev** [comment]
oh, ok, i see. thank you anyway :)

**Pull request merged**
