### PR TITLE
Update acts.sh: compile with GEANT4 flags=ON

### PR DESCRIPTION
**Pull request by altsybee**

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by altsybee** [comment]
Hi, I removed the "trailing spaces after \" in L26, hopefully now it should pass the checks..

**Comment by ktf** [comment]
I would be good to actually pass the GEANT4 path explicitly to CMake, to avoid picking up an eventual system installation.

**Comment by altsybee** [comment]
> I would be good to actually pass the GEANT4 path explicitly to CMake, to avoid picking up an eventual system installation.
Could you implement this change, please?.. I'm not an expert in this business at all

**Review by sawenzel — APPROVED** [review]

**Comment by sawenzel** [comment]
I updated this PR with @ktf suggestion and made Geant4 a runtime requirement. For me it builds. I guess we can safely merge given that this is used just for R&D and not production.

**Comment by altsybee** [comment]
Thanks a lot, sure!

**Comment by altsybee** [comment]
So, now it fails at something unrelated to the acts.sh change, I guess..

**Pull request merged**
