### PR TITLE
bump readout+infologger

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
@alisw/infrastructure-admins can you please fix the CI issues blocking this PR ?

**Comment by davidrohr** [comment]
From what I see, both the macOS and the O2 CI are failing in QC ctests  @Barthelemy .

@TimoWilken : It seems the log files in the full log for the macOS are not sorted after the data as they should be, can you check?

**Comment by Barthelemy** [comment]
Hi 
Calling @knopers8 for the multi_node setup. I know that Piotr is working on a fix: https://github.com/AliceO2Group/QualityControl/pull/697

**Comment by sy-c** [comment]
@Barthelemy @knopers8 @alisw/infrastructure-admins : I'm not sure who's in charge here, but please help having this PR merged.

**Review by teo — APPROVED** [review]

**Pull request merged**
