### PR TITLE
Only build ReadoutCard on CentOS

### PR DESCRIPTION
**Pull request by kostorr**

### CODE REVIEW

**Review by Barthelemy — APPROVED** [review]

**Comment by kostorr** [comment]
@Barthelemy it looks like some QC tests failed on macOS

**Comment by Barthelemy** [comment]
it seems spurrious.

**Comment by Barthelemy** [comment]
@ktf @knopers8 Do you have any ideas why these 3 tests are suddenly timing out ?

**Comment by ktf** [comment]
Is it running on top of yesterday daily? There was problem with a signed short used in place of pid_t which randomly broke things (and of course did not break them during the checks of the associated PR). This should be fixed in today daily. @TimoWilken could you retrigger the tests?

**Comment by TimoWilken** [comment]
I've retriggered the macOS test, all the others are green at the moment.

**Comment by knopers8** [comment]
> @ktf @knopers8 Do you have any ideas why these 3 tests are suddenly timing out ?

I have no clue, to be honest. There were no changes in QC which could have caused that.

**Comment by ktf** [comment]
@Barthelemy what would be the expected runtime for those tests?

**Pull request merged**
