### PR TITLE
Use libtirpc for compiling ApMon-CPP

### PR DESCRIPTION
**Pull request by Atlantic777**
This should fix the problems with compiling ApMon-CPP on platforms with new glibc.

### CODE REVIEW

**Comment by ktf** [comment]
Libtoolize does not exist on mac. I think you need to make it use glibtoolize.

**Comment by Atlantic777** [comment]
Yup, switch to glibtoolize helped, but this just exposed more issues with libtirpc on MacOS. It looks like we are not the only ones: https://github.com/openwrt/packages/issues/8756 .

```
config.status: executing depfiles commands
config.status: executing libtool commands
++ make -j 4 install
Making install in src
  CC       libtirpc_la-auth_none.lo
  CC       libtirpc_la-auth_unix.lo
  CC       libtirpc_la-authunix_prot.lo
  CC       libtirpc_la-binddynport.lo
auth_none.c:81:9: error: unknown type name 'mutex_t'
        extern mutex_t authnone_lock;
               ^
auth_none.c:83:2: warning: implicit declaration of function 'mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_lock(&authnone_lock);
        ^
auth_none.c:87:4: warning: implicit declaration of function 'mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
                        mutex_unlock(&authnone_lock);
                        ^
auth_none.c:103:2: warning: implicit declaration of function 'mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_unlock(&authnone_lock);
        ^
auth_none.c:113:9: error: unknown type name 'mutex_t'
        extern mutex_t authnone_lock;
               ^
auth_none.c:117:2: warning: implicit declaration of function 'mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_lock(&authnone_lock);
        ^
auth_none.c:123:2: warning: implicit declaration of function 'mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_unlock(&authnone_lock);
        ^
auth_none.c:166:9: error: unknown type name 'mutex_t'
        extern mutex_t ops_lock;
               ^
auth_none.c:170:2: warning: implicit declaration of function 'mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_lock(&ops_lock);
        ^
auth_none.c:180:2: warning: implicit declaration of function 'mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_unlock(&ops_lock);
        ^
7 warnings and 3 errors generated.
In file included from binddynport.c:41:
In file included from ../tirpc/rpc/rpc.h:73:
../tirpc/rpc/rpcent.h:53:8: error: redefinition of 'rpcent'
struct rpcent {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:159:8: note: previous definition is here
struct rpcent {
       ^
binddynport.c:94:2: warning: implicit declaration of function 'mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_lock(&port_lock);
        ^
binddynport.c:137:2: warning: implicit declaration of function 'mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_unlock(&port_lock);
        ^
2 warnings and 1 error generated.
auth_unix.c:408:9: error: unknown type name 'mutex_t'
        extern mutex_t ops_lock;
               ^
auth_unix.c:412:2: warning: implicit declaration of function 'mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_lock(&ops_lock);
        ^
auth_unix.c:422:2: warning: implicit declaration of function 'mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        mutex_unlock(&ops_lock);
        ^
2 warnings and 1 error generated.
make[1]: *** [libtirpc_la-auth_none.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [libtirpc_la-binddynport.lo] Error 1
make[1]: *** [libtirpc_la-auth_unix.lo] Error 1
make: *** [install-recursive] Error 1
```

**Comment by Atlantic777** [comment]
Well, it looks like "rpc/rpc.h" still works fine on MacOS. Maybe we can use libtirpc for Linux builds only.

**Comment by ktf** [comment]
Yes please.

**Pull request merged**
