### PR TITLE
Bump ms_gsl

### PR DESCRIPTION
**Pull request by davidrohr**
@ktf @aphecetche

### CODE REVIEW

**Comment by aphecetche** [comment]
well, the bump might require some changes to AliceO2 first ... 

In file included from /Users/laurent/alice/pr/sw/SOURCES/O2/v1.2.0/0/Utilities/O2Device/include/O2Device/O2Device.h:33:
/Users/laurent/alice/pr/sw/SOURCES/O2/v1.2.0/0/Utilities/O2Device/include/O2Device/Utilities.h:92:22: error: use of undeclared identifier 'headerBufferSize'; did you mean 'headerBuffer'?
    span::index_type headerBufferSize{0};
                     ^~~~~~~~~~~~~~~~
                     headerBuffer

**Comment by davidrohr** [comment]
FYI: I had tried 2.1 locally before on Linux, never on Mac, but while bumping I saw they recently released 3.0. Let's wait how the linux CI concludes.
And I do not understand this error message actually. This is a variable declaration, so why `undeclared identifier`.

**Comment by davidrohr** [comment]
Apparently span::index_type was removed between ms_gsl 2.1 and 3.0. With 2.1 it is still working for me.
Shall I change the bump to 2.1 only, or do we want to fix it in O2?

**Comment by ktf** [comment]
I would start with 2.1, since in the end only O2 depends on it.

**Comment by davidrohr** [comment]
@sawenzel : Apparently, before the old ms_gsl was pulling in the headers needed for uint data type on macos, which is no longer the case. Could you update the MCTruthContainer to include all required data types by itself?

**Comment by sawenzel** [comment]
ok

**Comment by sawenzel** [comment]
https://github.com/AliceO2Group/AliceO2/pull/3428

**Pull request merged**
