### PR TITLE
[WIP] Use CMake config in *InfoLogger

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
As discussed with @sy-c, this goes along with:

* AliceO2Group/Common#15
* AliceO2Group/InfoLogger#5

Not to be merged.

**Comment by dberzano** [comment]
(Note that we should tag & bump InfoLogger as well.)

**Comment by ktf** [comment]
I assume this is actually obsolete?

**Comment by sy-c** [comment]
Yes, I'm closing it, the infologger cmake was redone from scratch since then.

**Pull request closed without merging**
