### PR TITLE
Bump Geant3 to v3-7

### PR DESCRIPTION
**Pull request by ihrivnac**

### CODE REVIEW

**Comment by ihrivnac** [comment]
@ktf, @TimoWilken ,
The two failing tests have no logs.

**Comment by TimoWilken** [comment]
@ihrivnac, I've restarted the tests.

**Comment by ktf** [comment]
@TimoWilken looks like the ubuntu CI has troubles.

**Comment by TimoWilken** [comment]
Seems like it messed up its local alidist clone so it couldn't fetch the master branch. I've restarted it, hopefully that'll fix it.

**Comment by ktf** [comment]
@TimoWilken Looks like ubuntu is still broken. Could you have a look?

**Comment by TimoWilken** [comment]
@ktf fix is in https://github.com/alisw/alibuild/pull/654.

**Review by pzhristov — APPROVED** [review]

**Pull request merged**
