### PR TITLE
Bump qualitycontrol to v1.118.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by vkucera** [comment]
@Barthelemy @sawenzel I'm afraid that the CI checks for https://github.com/AliceO2Group/AliceO2/pull/11851 will not be happy until this release is picked up by alidist.

**Comment by Barthelemy** [comment]
I am fine with merging it but it must not be picked up for anything at P2.

**Comment by vkucera** [comment]
> I am fine with merging it but it must not be picked up for anything at P2.

Is there anything pending at P2 to make sure the right version is picked up?

**Comment by davidrohr** [comment]
EPN builds use QC from the FLPSuite, or manually defined one. Should not be picked up automatically if not merged in the FLPSuite

**Comment by vkucera** [comment]
> EPN builds use QC from the FLPSuite, or manually defined one. Should not be picked up automatically if not merged in the FLPSuite

Thanks @davidrohr

**Pull request merged**
