### PR TITLE
Bump QCG to 1.6.7

### PR DESCRIPTION
**Pull request by graduta**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@MichaelLettrich maybe you could help out?

**Comment by MichaelLettrich** [comment]
on it

**Comment by MichaelLettrich** [comment]
hi it is the same problem as in #1913 . FairMQ failed to build because of git issues. Hopefully the problem should be fixed by now but the builder is rebuilding a lot of things now, so allow for a bit of delay.

**Comment by awegrzyn** [comment]
All right, thanks !

**Comment by ktf** [comment]
See last commit for linter issue.

**Pull request merged**
