### PR TITLE
Align ROOT 6 and CMake overrides in O2 and ROOT 6

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf now the two defaults use the same ROOT version and the same CMake version. Any comment?

**Comment by ktf** [comment]
Fine with me, but let's wait for the tests.

**Comment by dberzano** [comment]
@matthiasrichter if you use the `IB/v5-08/prod` branch with `--defaults o2` this should solve AliceO2Group/AliceO2#186. Can you help updating O2 in order to match the new DDS API?

**Comment by matthiasrichter** [comment]
@dberzano thanks, I will use this for the installation and then update the code to match the new DDS API

**Comment by matthiasrichter** [comment]
I did a test now, freshly cloned alidist (`IB/v5-08/prod`) and alibuild in a virgin folder, 
command: `alibuild/aliBuild --defaults o2 build o2`

Still O2 is built without DDS

**Comment by dberzano** [comment]
What about FairRoot? What does the sole output of the `cmake` part of O2 say? O2 is supposed to crash while building DDS, but at this point it should recognize it at least.

**Comment by dberzano** [comment]
@matthiasrichter forget what I have said. The change I have mentioned is not in this pr.

**Comment by matthiasrichter** [comment]
ah, ok, let me know when it is in

**Pull request closed without merging**
