### PR TITLE
bump readout v1.0.1 & readoutcard v0.10.2

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
 build/O2/alidist  test is failing with   5/318 Test   #2: /Common/Field/macro/createMapsFromText.C_compiled ...............................***Failed    9.25 sec

This does not look related to this PR. Can you please advise ?

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins
the test failing yesterday is now ok.
there is still something wrong, but in the macOS SSL build. This is not related to this PR.
Can you please merge this PR?

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins
any news about this, please?

**Comment by Barthelemy** [comment]
@pzhristov do you happen to have write access to this repo ?

**Comment by sy-c** [comment]
Thank you!

**Pull request merged**
