### PR TITLE
Bump ReadoutCard to v0.15.3

### PR DESCRIPTION
**Pull request by kostorr**

### CODE REVIEW

**Comment by Barthelemy** [comment]
Could someone merge ?

**Comment by awegrzyn** [comment]
Why we can't merge?!

**Comment by awegrzyn** [comment]
@ktf GitHub says "You’re not authorized to merge this pull request." and then "The base branch restricts merging to authorized users." Could you please, please, please fix it?

**Comment by ktf** [comment]
Apparently "squashing commits" and "forbidding everyone including admins to push" only leaves owners the ability merged. :-/ Reverted.

**Comment by ktf** [comment]
For the record, it was an attempt to avoid me to force push (which worked), but apparently  it prevents others from merging...

**Pull request merged**
