### PR TITLE
[WIP] try common_recipe option on two recipes

### PR DESCRIPTION
**Pull request by aphecetche**

### CODE REVIEW

**Comment by aphecetche** [comment]
Not a real PR, but more a supporting piece for https://alice.its.cern.ch/jira/browse/O2-414

**Comment by Barthelemy** [comment]
seems more readable, good job.

**Comment by ktf** [comment]
I like the idea. I had something similar in mind at some point, but without using functions. Yours is definitely better. Do you understand the build failure, though?

**Comment by aphecetche** [comment]
concerning the build failure : yes, it's expected as it's not only a change in the recipes. There is an alibuild counterpart : https://github.com/alisw/alibuild/pull/551

**Comment by dberzano** [comment]
This is very nice and simple and reduces so much boilerplate, thanks.

**Comment by ktf** [comment]
closing this for now, as it requires the whole collaboration to move to a new version of aliBuild.

**Pull request closed without merging**
