### PR TITLE
Bump FairRoot

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This will hopefully work out of the box, fixing macOS builds, without having to bump the rest of the externals (and without breaking O2).

**Comment by ktf** [comment]
I see now:

```
[ 15%] Linking CXX shared library libProcessorZlibCompress.dylib
In file included from /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/Readout/v1.0.5/v1.0.5/src/testMonitor.cxx:16:
In file included from /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/osx_x86-64/Monitoring/v2.6.3-1/include/Monitoring/MonitoringFactory.h:19:
In file included from /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/osx_x86-64/Monitoring/v2.6.3-1/include/Monitoring/Monitoring.h:26:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/unordered_map:384:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__hash_table:19:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
```

@MichaelLettrich are you sure you installed Xcode command line tools correctly?

**Comment by ktf** [comment]
From StackOverflow, it looks like we might need:

```bash
$ brew update
$ brew upgrade
```

**Comment by sawenzel** [comment]
Isn't this overlapping with #1776?

**Comment by ktf** [comment]
Is #1776 converging? I understood there were still issues.

**Comment by sawenzel** [comment]
In my understanding all the problems have been addressed.

**Comment by ktf** [comment]
Ah, ok. I was fooled by the fact that the builds where still red, but that's an issue related to `OCC_plugin`. Ok, let's fix that then and merge #1776.

**Comment by ktf** [comment]
Build on mac seem to be back, but there is now what seems to be a genuine issue in the CcdbAPI. @Barthelemy @sawenzel could you take a look?

```
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/usr/lib/libcurl.4.dylib] AddFormData (no debug info)
[/usr/lib/libcurl.4.dylib] Curl_getformdata (no debug info)
[/usr/lib/libcurl.4.dylib] Curl_http (no debug info)
[/usr/lib/libcurl.4.dylib] multi_runsingle (no debug info)
[/usr/lib/libcurl.4.dylib] curl_multi_perform (no debug info)
[/usr/lib/libcurl.4.dylib] curl_easy_perform (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/BUILD/f15abf7baaeeb41def075db5f00c67ef7591a0cf/O2/stage/lib/libO2CCDB.dylib] o2::ccdb::CcdbApi::store(TObject*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, long, long, bool) const /build/ci_checks/alidist_checker_macos_o2_ci_1/sw/SOURCES/O2/1806/0/CCDB/src/CcdbApi.cxx:135
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/BUILD/f15abf7baaeeb41def075db5f00c67ef7591a0cf/O2/stage/tests/o2-test-ccdb-CcdbApi] store_test::test_method() /Library/Developer/CommandLineTools/usr/include/c++/v1/string:1406
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/BUILD/f15abf7baaeeb41def075db5f00c67ef7591a0cf/O2/stage/tests/o2-test-ccdb-CcdbApi] store_test_invoker() /build/ci_checks/alidist_checker_macos_o2_ci_1/sw/SOURCES/O2/1806/0/CCDB/test/testCcdbApi.cxx:250
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::execution_monitor::catch_signals(boost::function<int ()> const&) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::execution_monitor::execute(boost::function<int ()> const&) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::execution_monitor::vexecute(boost::function<void ()> const&) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::unit_test::framework::state::execute_test_tree(unsigned long, unsigned int, boost::unit_test::framework::state::random_generator_helper const*) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::unit_test::framework::run(unsigned long, bool) (no debug info)
[/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/boost/v1.68.0-1/lib/libboost_unit_test_framework.dylib] boost::unit_test::unit_test_main(bool (*)(), int, char**) (no debug info)
[/usr/lib/system/libdyld.dylib] start (no debug info)
```

**Comment by Barthelemy** [comment]
I am not able to reproduce it. @sawenzel what about you ? What do you think, could we just comment out this test as we are deprecating "store" and "retrieve" ?

**Comment by sawenzel** [comment]
The test is now again disabled on Mac

**Comment by ktf** [comment]
This will make the AliceO2 PRs work again while we wait for the alidist ones to catch up.

**Comment by davidrohr** [comment]
OK, I guess that means I rebase #1776 :|

**Comment by ktf** [comment]
Nah, I just fixed the commit on github, no need to do anything #1776 will hopefully be green at some point tonight.

**Pull request merged**
