### PR TITLE
Bump DIM to v20r30

### PR DESCRIPTION
**Pull request by vascobarroso**

### CODE REVIEW

**Review by kostorr — APPROVED** [review]

**Comment by ktf** [comment]
Did you mispell the tag?

**Comment by awegrzyn** [comment]
Okay, it looks like we're using 2 sources of DIM at the same time:
- ZIP file from official page
- Our GitHub "fork" (uploaded ZIP content)

@kostorr @vascobarroso Which one you prefer to use? Using GitHub "fork" is more aliBuild oriented but that means syncing the repo before each bump.

**Comment by kostorr** [comment]
I'd stay with the zip as this is how DIM is shipped.

**Comment by awegrzyn** [comment]
@ktf I'm pretty sure `source: ` filed was added because of some valid reason, any idea why? Do you think removing it and keeping just ZIP file is okay?

**Comment by awegrzyn** [comment]
I think this is reason of using Git repo: https://github.com/alisw/alidist/pull/2435
@kostorr I think now it's up to you to make changes.

**Comment by kostorr** [comment]
@awegrzyn can you give me access to this please? 
https://github.com/alisw/dim

**Comment by awegrzyn** [comment]
I was not able to grant to write access but I uploaded `v20r30`.

**Comment by kostorr** [comment]
@awegrzyn thanks, @ktf maybe you can grant me access?

**Comment by ktf** [comment]
I made @kostorr writer and @awegrzyn admin for alisw/dim.

**Review by awegrzyn — APPROVED** [review]

**Pull request merged**
