### PR TITLE
Switch to v5.9.1-alice4 incorporating fixes for gfortran-8

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Incorporating fixes needed for gfortran-8 in https://github.com/alisw/LHAPDF/pull/7 using a new tag v5.9.1-alice4

**Comment by mfasDa** [comment]
@qgp @maireiphc Please review!

**Comment by maireiphc** [comment]
Hi Markus,

  any further clue why the checks failed ?
The install dir : /mnt/mesos/sandbox/sandbox/sw/INSTALLROOT/533db2058a6eebdc26c1b2812600cf5b52f17b76/slc7_x86-64/lhapdf5/v5.9.1-alice4-1/share/LHAPDF.
...

++ pushd /mnt/mesos/sandbox/sandbox/sw/INSTALLROOT/533db2058a6eebdc26c1b2812600cf5b52f17b76/slc7_x86-64/lhapdf5/v5.9.1-alice4-1/share/lhapdf
/mnt/mesos/sandbox/sandbox/sw/SPECS/slc7_x86-64/lhapdf5/v5.9.1-alice4-1/lhapdf5.sh: line 11: pushd: /mnt/mesos/sandbox/sandbox/sw/INSTALLROOT/533db2058a6eebdc26c1b2812600cf5b52f17b76/slc7_x86-64/lhapdf5/v5.9.1-alice4-1/share/lhapdf: No such file or directory

Cheers, Antonin

**Comment by mfasDa** [comment]
@maireiphc I think there is not yet a tag created from the patches branch. The last test is ...-alice3. Not sure what happens when there is no tag, probably it stays with the previous branch which would be master which is at LHAPDF6.

Cheers

Markus

**Pull request closed without merging**
