### PR TITLE
Bump ROOT to v6.30.01-alice2

### PR DESCRIPTION
**Pull request by ktf**
Bump ROOT to v6.30.01-alice2

### CODE REVIEW

**Comment by ktf** [comment]
Last commit updated to include full mathmore from ROOT.

**Comment by ihrivnac** [comment]
@ktf , as agreed inhttps://github.com/alisw/alidist/pull/5204, we can drop `vdt` in the `ROOT` build  and then remove `DVDT_*` options from all VMC packages.

**Comment by ktf** [comment]
@ihrivnac I think today @pzhristov was mentioning that he tried and something was not working.

**Comment by davidrohr** [comment]
Is someone looking into the crash of tpc its matching qc with the new root version?

**Comment by ktf** [comment]
The QC issue is a genuine issue in `MatchITSTPCQC::finalize` [#12458](https://github.com/AliceO2Group/AliceO2/pull/12458).

**Comment by ktf** [comment]
The:

```
 18/517 Test #473: o2sim_G3 .............................................................................***Failed  Required regular expression not found. Regex=[SIMULATION RETURNED SUCCESFULLY
517/517 Test #116: Detectors/Base/test/testMatBudLUT.cxx ................................................***Failed    1.83 sec
```

errors I see elsewhere. @sawenzel @costing are they CCDB related?

**Comment by costing** [comment]
I didn't see ccdb-related messages, but is it expected that the tests access the production instance?

**Comment by ktf** [comment]
macOS issues unrelated. Tested also on hyperloop.

Caching done.

**Comment by sawenzel** [comment]
This breaks all PyROOT related processing (which we do in anchored MC): https://alice.its.cern.ch/jira/browse/O2-4525

**Comment by ktf** [comment]
I think https://github.com/alisw/alidist/pull/5298 should fix it.

**Pull request merged**
