### PR TITLE
Upgrade Rivet to 3.1.1

### PR DESCRIPTION
**Pull request by preghenella**
This PR upgrades Rivet to v3.1.1.
It comes also with an upgraded YODA.

### CODE REVIEW

**Comment by preghenella** [comment]
the `build/AliGenerators/prod-latest` check fails.
From the log it seems to be that it is not taking the defaults for `generators`.
Could this be the case?

**Comment by maireiphc** [comment]
Hi Roberto,

   if the build checks are in line with the official build, it should read alidist/default-generator.sh.
See for instance the build parameters used today : https://alijenkins.cern.ch/job/DailyBuilds/job/DailyAliGenerators/320/parameters/ (DEFAULTS field).

Could it be that the compiler used (gcc 7.3), despite normally compatible for c++14, is not "activated" or "set up properly" in our case with desired option(s) to deal with host c++14 features ?

My 2 cents

**Comment by preghenella** [comment]
Hi @maireiphc ,
on alidock this works and only building with the updated `defaults-generators.sh`.
The complaint about `c++14` looks like the `--defaults generators` are not set in this check.

It is not clear to me that these checks are done with the same configuration as the one used for the Jenkins daily builds.

@ktf , can you please help us figure out what is the actual setting of the `build/AliGenerators/prod-latest` check? Thanks.

**Comment by preghenella** [comment]
thanks to @ktf that pointed out to me that failed check was running with `--defaults prod-latest`.
They were in fact not including the `c++14` flag which should allow to build the upgraded Rivet.

@ktf modified the check to run with `--defaults generators`.
The check chain is supposed to start automatically.

**Comment by preghenella** [comment]
well, I guess I have to trigger this somehow... 
the new checks are not starting

**Comment by ktf** [comment]
They just take long because it's doing a full rebuild of all the PRs. Now done. Merging.

**Pull request merged**
