### PR TITLE
Bump FairMQ to v1.4.38

### PR DESCRIPTION
**Pull request by rbx**
A regression in shmem was introduced in the previous tag. Fixed in this tag.

### CODE REVIEW

**Comment by ironMann** [comment]
Thanks @rbx for the fast response!

@vascobarroso This should fix instability in the FLP chain that we see on large setups. How soon can we deploy this in the current O2 suite? Thanks

**Comment by awegrzyn** [comment]
Are these changes touch public headers? I'm wondering if we need to recompile everything above or we could get away with replacing library.

**Comment by ironMann** [comment]
From stack traces it looks like the problem is contained within the library.
```
/opt/o2/lib/libFairMQ.so.1.4(_ZN4fair2mq5shmem7Message10DeallocateEv+0x492)[0x7fba764daf42]
/opt/o2/lib/libFairMQ.so.1.4(_ZN4fair2mq5shmem7MessageD1Ev+0x24)[0x7fba764db854]
/opt/o2/lib/libFairMQ.so.1.4(_ZN4fair2mq5shmem7MessageD0Ev+0x9)[0x7fba764dbad9]
StfSender[0x4a16a2]
StfSender[0x49f736]
StfSender[0x456e9f]
```

**Comment by awegrzyn** [comment]
ok, @rbx could you confirm?

**Comment by rbx** [comment]
The latest bug-fixing commit touches only private headers. But this tag contains also commits with publicly visible changes (examples and two new methods in `fair::mq::shmem::Monitor`).

**Review by ktf — APPROVED** [review]

**Pull request merged**
