### PR TITLE
Bump bookkeeping to v0.59.0

### PR DESCRIPTION
**Pull request by martinboulais**

### CODE REVIEW

**Review by TimoWilken — APPROVED** [review]

**Comment by vascobarroso** [comment]
@TimoWilken any idea why this PR went to you for approval instead of @alisw/dataflow-experts ?

**Comment by TimoWilken** [comment]
@vascobarroso `bookkeeping-api.sh` isn't listed in [the CODEOWNERS file](https://github.com/alisw/alidist/blob/master/CODEOWNERS), so it fell back to the default entry. I'll add it! Are there any other unlisted recipes that should be owned by @alisw/dataflow-experts as well?

**Comment by vascobarroso** [comment]
@TimoWilken thanks! Looking at the list, I cannot see any other that should be owned by @alisw/dataflow-experts.

**Comment by TimoWilken** [comment]
Great, thanks for checking @vascobarroso!

**Pull request merged**
