### PR TITLE
Bump 

### PR DESCRIPTION
**Pull request by ironMann**
Bump DataDist to v1.3.7
@vascobarroso The memory usage default is decreased to 128MB

Requires ppconsul bump to v0.2.3

### CODE REVIEW

**Comment by vascobarroso** [comment]
@ironMann great thanks a lot! Let's see if it makes the CI happy :crossed_fingers:

**Comment by ktf** [comment]
@vascobarroso This is working in the PDP CI, shall I merge and you cherry pick it in your branch or shall I hold as well?

**Review by vascobarroso — APPROVED** [review]

**Comment by vascobarroso** [comment]
@ktf you can merge, that will actually simplify testing in our nightly CI. If still broken, I will report here. 
For completeness, this is not for next Monday, it is for the week after (as agreed yesterday with the RC).

**Comment by ktf** [comment]
The issue I see is that that will end up in the PDP suite releases, so I would like either @davidrohr or @shahor02 to greenlight it.

**Comment by vascobarroso** [comment]
@ironMann I confirm that the new DD passes our FLP Suite CI. Thanks for the fix!

**Pull request merged**
