### PR TITLE
Bump qualitycontrol to v1.60.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by Barthelemy** [comment]
@ktf @davidrohr could you help us interpret the error in the fullCI test ?

**Comment by davidrohr** [comment]
Something is wrong with the ITS task
```
[2401:qc-task-ITS-ITSTrackTask]: [10:17:14][STATE] Exiting FairMQ state machine
[2401:qc-task-ITS-ITSTrackTask]: [10:17:14][FATAL] error while setting up workflow in o2-qc: stol
[2401:qc-task-ITS-ITSTrackTask]: For later analysis we write a core dump to core_dump_2401
```

**Comment by davidrohr** [comment]
Ah, perhaps it needs this PR: https://github.com/AliceO2Group/O2DPG/pull/424 ?
If so I can merge that in O2DPG.

**Comment by knopers8** [comment]
@iravasen Do we need the PR mentioned by David to fix this problem?

**Comment by iravasen** [comment]
@knopers8 @davidrohr yes it is needed if you are using the latest QC.

**Comment by davidrohr** [comment]
Also the QC processing on the EPN fails. I have merged the PR and will retry with it.

**Comment by davidrohr** [comment]
For reference, https://github.com/AliceO2Group/O2DPG/pull/424 is not enough. I just tried locally. I'll try to fix it and push a fix to O2DPG and then merge this.

**Comment by Barthelemy** [comment]
thank you

**Pull request merged**
