### PR TITLE
Disable HepMC3 due to O2 failed tests

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf @preghenella @sawenzel I am testing it to see if it fixes the failing O2 tests.

**Comment by sawenzel** [comment]
Thanks.

**Comment by dberzano** [comment]
By the way @sawenzel is right, we should enable alidist tests to prevent this. Maybe the new PR checker by @brinick addresses this problem too?

**Comment by dberzano** [comment]
Fun fact: this PR does not solve the problem, but I think I have found the culprit. Opening a new one soon.

**Pull request closed without merging**
