### PR TITLE
Revert "[O2-1976] Fix unloading Python module"

### PR DESCRIPTION
**Pull request by ktf**
Reverts alisw/alidist#2771

### CODE REVIEW

**Comment by ktf** [comment]
@awegrzyn apparently this breaks lxplus installations. I suspect it got introduced in a too new version of modulefiles.

**Comment by awegrzyn** [comment]
Nope, `module-info mode [modetype]` does work with `3.2.10`

**Comment by ktf** [comment]
Ciao,

apparently not:

```
→ /cvmfs/alice.cern.ch/bin/alienv enter VO_ALICE@O2::nightly-20210121-1
Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}

Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}

Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}

Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}

Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}

Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}

Python/v3.6.10-102(53):ERROR:102: Tcl command execution failed: if { [module-info mode load] } {
  setenv SSL_CERT_FILE  [exec /bin/python3 -c "import certifi; print(certifi.where())"]
}
```

**Comment by ktf** [comment]
Ah, you are missing a `\`. It's `\$PKG_ROOT`...

**Comment by awegrzyn** [comment]
Indeed, that's correct, no idea how did it happen :(

**Comment by ktf** [comment]
Ok, I've reverted my revert and added the fix on top.

**Pull request merged**
