### PR TITLE
Bump to NodeJS v13.12.0 to get newest node-gyp

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf @MichaelLettrich This fixes issue with `node-gyp` on macOS.
I'm not able to merge as `alidist-dataflow` is failing, any idea why?

**Comment by MichaelLettrich** [comment]
@awegrzyn : thanks for the quick solution :) 
the dataflow test is new as far as I know and does not seem to work properly yet, travis is broken since this morning and I don't have rights to restart it @ktf

**Comment by ktf** [comment]
The dataflow test should work fine. Why do you say it does not?

Travis is fine. The issue seems to be doxygen running for hours. @ihrivnac did anything change recently there?

**Comment by ktf** [comment]
Merging this since it solves the issue on mac. Issue with alidist-dataflow being investigated.

**Comment by MichaelLettrich** [comment]
@ktf : sorry - I didn't see `build/O2/alidist-dataflow ` completing sucessfully on any of the open PRs since this builder was put in place so I was wondering what was going on? Sorry if I made it sound more like a statement rather than a question.

**Pull request merged**
