### PR TITLE
Bump CMake to 3.18

### PR DESCRIPTION
**Pull request by davidrohr**
Has some new CUDA related features I'd like to use

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf : Could you check what breaks the GLFW build with CMake 3.18
@kostorr : I see that this and several other alidist PRs fail in CentOS 8 in building ALF/src/AlfServer.cxx: Could you check what is the problem?

**Comment by awegrzyn** [comment]
Until issue with ALF @ C8 is not fixed: https://github.com/alisw/alidist/pull/2410

**Comment by davidrohr** [comment]
@ktf : Could you check what is the issue with GLFW?

**Comment by ktf** [comment]
Cannot reproduce on lxplus. I suspect the issue is a missing X11 package in the docker container which is now required by the FindX11 macro in CMake...

**Comment by davidrohr** [comment]
@ktf : One issue that I have seen is anyway that the glfw / opengl / debuggui recipes are not consistently checking for all required dependencies. I had it several times that on some servers it would find all depencencies it checks for, but then it would still fail the build since other dependencies (which were not checked) were missing. I think this should be cleaned up, probably gradually.

**Comment by davidrohr** [comment]
@ktf : hm, I don't understand this. build/O2/alidist uses the slc7-builder container, right?
I just tried this locally with slc7-builder and it worked...

**Comment by ktf** [comment]
Me neither. I did try and was unable to reproduce. However when I reset the tests here, it still fails...

**Comment by ktf** [comment]
> build/O2/alidist uses the slc7-builder

yes.

**Comment by davidrohr** [comment]
@ktf : I tried to debug what is the problem in glfw so I added --debug-output to cmake in glfw.sh. For whatever reason, with --debug-output it compiles correctly. I tried 2 times with and without, and the behavior is consistent. Are you OK if we merge this as is, shouldn't be a problem except for some glfw cmake debug output written to the logs, or do you have an idea how we can debug it?
I need CMake 3.18 for some new CUDA features.

**Comment by ktf** [comment]
Yes, it's fine with me. I suspect an actual CMake bug... I added a comment and merged.

**Pull request merged**
