### PR TITLE
Build own version of OFI if not found on the system

### PR DESCRIPTION
**Pull request by ktf**
Build OFI on mac as well, for consistency.

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 could you try this?

**Comment by ktf** [comment]
@dennisklein is that really true you need 1.6.0+? That prevents using system packages for a bunch of platforms.

**Comment by dennisklein** [comment]
I do not know, never tried older versions. There is some piece of initialization which requests a minimal ofi api version currently, this would need to be relaxed to allow older versions.

That said, I would say `-DBUILD_OFI_TRANSPORT=ON` is a linux only feature, even though it is not enforced on FairMQ side. AFAIK, there is libfabric for macos (which I have never tried), but not libibverbs. (?)

May I ask, what is the problem?

**Comment by dennisklein** [comment]
Here I request ofi api version `1.5` during initialization, see https://github.com/FairRootGroup/asiofi/blob/ce3a5125fba61ac10cff53aa5229186719b2693c/include/asiofi/info.hpp#L129. Not sure to which range of package versions this corresponds and if I use any api that is only available since `1.5`. One would need to try.

**Comment by chiarazampolli** [comment]
Ciao,

In case you are interested, and it is useful, for me this PR worked for me with this issue. 

Chiara

**Comment by ktf** [comment]
Multiple people have issues because a recent enough ofi was not available for their setup (ubuntu, IIUC). `FI_VERSION` seems to be exactly the OFI version, no?

**Comment by shahor02** [comment]
@ktf  Thanks, worked also on Ubuntu 18.04!
@dennisklein : [here](https://alice-talk.web.cern.ch/t/alibuild-o2-fails-on-ubuntu-18-04-after-python3-ofi-updated-in-alidist/253) is the description of the problem.

**Comment by dennisklein** [comment]
> Multiple people have issues because a recent enough ofi was not available for their setup (ubuntu, IIUC). `FI_VERSION` seems to be exactly the OFI version, no?

Until `1.6` there was [this comment](https://github.com/ofiwg/libfabric/blob/v1.6.x/include/rdma/fabric.h#L78-L80) stating that it is not the case. In `master` this comment is gone, so maybe they match the package version now?

**Comment by dennisklein** [comment]
@shahor02 Thx and sry I missed your question on alice talk. I wrote a reply there now.

**Comment by dennisklein** [comment]
@ktf On many hosts I have installed ofi myself so far where an OFED installation was present, I had problems building without the `--enable-mlx=no` configure option. Just FYI.

**Comment by ktf** [comment]
I've added your suggestion..

**Pull request merged**
