### PR TITLE
Bump to CMake 3.16

### PR DESCRIPTION
**Pull request by davidrohr**
First test, should hopefully work now that FairRoot / boost / everything is bumped.

### CODE REVIEW

**Comment by ktf** [comment]
I think we will need at least 6d8c35996c5ab2dc27bfda24c02b0624a10fa248 for FairRoot.

**Comment by davidrohr** [comment]
Not sure, I built it locally with our current tag and it worked.
But fine, we can also boost FairRoot further by these 4 commits.

**Comment by MichaelLettrich** [comment]
The problem with macOS is a known issue in the macOS build environment. We will fix it asap.

**Comment by davidrohr** [comment]
@ktf @MichaelLettrich : Is there any progress with the MacOS issue with CMake 3.15?

**Comment by ktf** [comment]
In principle the issues should be solved now. I triggered a rebuild by bumping the minor version.

**Comment by davidrohr** [comment]
No, still same issue as before

**Comment by davidrohr** [comment]
@ktf @MichaelLettrich : What is the plan for getting the new CMake run on MacOS? Now that CHEP is over, we might retry this.

**Comment by davidrohr** [comment]
@MichaelLettrich : The new cmake is still failing on MacOS with the float header problems. Can this eventually be fixed?

**Comment by MichaelLettrich** [comment]
There seems to be some bug either in a CMake File or in CMake itself because the Readout package fails to build with `-Werror`. We have the same Errors with the system CMake in macOS Catalina. See [O2-1074](https://alice.its.cern.ch/jira/browse/O2-1074)

**Comment by MichaelLettrich** [comment]
#2031 should bring a fix and we should finally be able to merge this.

**Comment by MichaelLettrich** [comment]
#2031 was merged. @davidrohr  can you bump this for retesting?

**Comment by davidrohr** [comment]
@MichaelLettrich : It failed again with the same problem.
This error is in O2, so the workaround for readout cannot help.
We could implement the same workaround for O2.
But actually, I would prefer to try to find a proper fix for CMake instead of disabling CI features.
Is there already a bug report to CMake and are people working on this?

**Comment by davidrohr** [comment]
I just updated this and added the workaround also to o2, just for the time being.
Still, I'd prefer a proper solution.

**Comment by MichaelLettrich** [comment]
Can you please revert the workaround? There are 7 receipes which need that treatment. I will address them in its own PR. 

Also I have been able to find a [CMake bugreport](https://gitlab.kitware.com/cmake/cmake/issues/19845#note_689595) and use it to create a small reproducer that fails outside of our environment. So this is definitely a bug in CMake which we need to work around for now.

**Comment by davidrohr** [comment]
ok, I'll wait for your fix and then rebase. I'll keep the CI running here, just to see whether it passes O2 now.

**Comment by MichaelLettrich** [comment]
Hopefully after PR #2037 has been merged, we will finally be able to merge this.

**Comment by davidrohr** [comment]
@ktf : The CI has finally passed. Can we merge this? Then we can close #2037 and revert #2031 (which will be no longer needed), and then I can also open a PR to revert the ROOT CMake workaround we have in place.
@MichaelLettrich : ping

**Comment by ktf** [comment]
We should move to the alisw organisation, but apart from that this is fine for me.

**Comment by davidrohr** [comment]
You'll have to do this ... :)
Anyhow, trying to get this merged into CMake upstream. It's vlearly a bug on their end. Don't want to keep many custom patches.

Kind Regards
David Rohr

**Comment by davidrohr** [comment]
FYI @ktf @MichaelLettrich : The fix should make it into the CMake 3.17 release.

**Pull request merged**
