### PR TITLE
Add @alisw/mrrtf to CODEOWNERS

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@alisw/mrrtf can someone check (notably @aphecetche)? Members were found here: https://mrrtf.github.io/

**Comment by aphecetche** [comment]
Hi Dario,

The source for the member list is the right one ;-)

Just to clarify : all users of the alisw/mrrtf (will) have the right to merge PRs related to alo ?

**Comment by dberzano** [comment]
TL;DR: yes

Longer story:

* all @alisw/mrrtf have Write access to the repo
* however, merging PRs in master is subject to an approved review and green tests

If a person from @alisw/mrrtf opens a PR, then it's _another_ person from the same group who should review it.

**Comment by dberzano** [comment]
For the record, we still see the "Required statuses must pass before merging" even if all required statuses are green. I have contacted GitHub support about that, it seems we're not alone with this problem.

**Pull request merged**
