### PR TITLE
Bump libfmt to 9.1.0

### PR DESCRIPTION
**Pull request by davidrohr**
Needs AliceO2Group/DataDistribution#170 AliceO2Group/AliceO2#10147 AliceO2Group/QualityControl#1531

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf @pzhristov  : Unfortunately I have no Mac so I cannot easily reproduce and fix this. The PR is producing plenty of errors on the MacOS CI (not the MacOS ARM though, and also Linux seems fine) like:
```
[18/309] Building CXX object PWGEM/Dilepton/Tasks/CMakeFiles/O2Physicsexe-analysis-em-lmee-lf-cocktail.dir/lmeeLFCocktail.cxx.o
FAILED: PWGEM/Dilepton/Tasks/CMakeFiles/O2Physicsexe-analysis-em-lmee-lf-cocktail.dir/lmeeLFCocktail.cxx.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DDPL_ENABLE_BACKTRACE -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_SHARED -I/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/Common/Core -I/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0 -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/O2/4628-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/Configuration/v2.6.3-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/boost/v1.75.0-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/Monitoring/v3.14.1-local3/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/curl/7.70.0-local2/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/FairMQ/v1.4.55-local2/include/fairmq -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/FairMQ/v1.4.55-local2/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/FairLogger/v1.11.1-local2/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/fmt/9.1.0-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/ROOT/v6-26-04-patches-alice2-local2/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/O2/4628-local1/include/GPU -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/RapidJSON/v1.1.0-alice2-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/arrow/v9.0.0-alice1-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/ms_gsl/4.0.0-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/libuv/v1.40.0-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/Vc/1.4.1-local1/include -isystem /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/osx_x86-64/libjalienO2/0.1.4-local1/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=10.15 -std=gnu++17 -MD -MT PWGEM/Dilepton/Tasks/CMakeFiles/O2Physicsexe-analysis-em-lmee-lf-cocktail.dir/lmeeLFCocktail.cxx.o -MF PWGEM/Dilepton/Tasks/CMakeFiles/O2Physicsexe-analysis-em-lmee-lf-cocktail.dir/lmeeLFCocktail.cxx.o.d -o PWGEM/Dilepton/Tasks/CMakeFiles/O2Physicsexe-analysis-em-lmee-lf-cocktail.dir/lmeeLFCocktail.cxx.o -c /Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx:739:14: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
      printf(Form("Error: Could not open Efficiency file %s\n", fFileNameLocal.Data()));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx:739:14: note: treat the string as an argument to avoid this
--
      printf(Form("Error: Could not open Efficiency file %s\n", fFileNameLocal.Data()));
             ^
             "%s", 
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx:746:14: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
      printf(Form("Error: Could not open histogram %s from file %s\n", histname.Data(), fFileNameLocal.Data()));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx:746:14: note: treat the string as an argument to avoid this
--
      printf(Form("Error: Could not open histogram %s from file %s\n", histname.Data(), fFileNameLocal.Data()));
             ^
             "%s", 
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx:765:14: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
      printf(Form("Error: Could not open Resolution file %s\n", fFileNameLocal.Data()));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/build/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4628/0/PWGEM/Dilepton/Tasks/lmeeLFCocktail.cxx:765:14: note: treat the string as an argument to avoid this
--
      printf(Form("Error: Could not open Resolution file %s\n", fFileNameLocal.Data()));
```

I don't see how this can come from the change of fmt? This must have been there before? Or it could be different headers included by fmt now?
But anyhow, isn't the construct `printf(Form(...` bogus?

**Comment by ktf** [comment]
i think it might be the new xcode. i will try to have a look later this evening.

**Comment by davidrohr** [comment]
ok, thx. Everything else has passed now. If it is only XCode on MacOS, then I'd merge it.

**Comment by ktf** [comment]
Ok, nevermind, indeed O2Physics on macOS was simply broken by some PR merged with red tests. Should be fixed by https://github.com/AliceO2Group/O2Physics/pull/1435/files. Merging this.

**Pull request merged**
