### PR TITLE
Enable GCC 10 in dataflow defaults

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Review by ktf — APPROVED** [review]

**Review by davidrohr — APPROVED** [review]
thx :)

**Comment by awegrzyn** [comment]
For FLP Suite v0.18.x release we do have a dedicated so this applies from v0.19.0

**Comment by awegrzyn** [comment]
@ktf Could you remove `devtoolset` section from https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-centos7.html ?

**Comment by ktf** [comment]
@awegrzyn  done in https://github.com/alice-doc/alice-analysis-tutorial/pull/130.  We should probably revisit those instructions completely.

**Comment by davidrohr** [comment]
@Barthelemy @awegrzyn : o2/alidist-dataflow is green, can I merge it?

**Comment by awegrzyn** [comment]
On my setup I get `No package 'capstone' found` and then `parallel_backend_tbb.h:28:6: error: #error Intel(R) Threading Building Blocks 2018 is required`, any ideas?

**Comment by awegrzyn** [comment]
Sorry, forgot to mention that this happens when compiling `DebugGUI`

**Comment by ktf** [comment]
Yes, I am trying to update Tracy to see if that fixes the problem/

**Pull request merged**
