### PR TITLE
Bump monitoring to v2.4.0

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by sawenzel** [comment]
I confirm that this solved the compile problem on SLC6. Thanks a lot.

**Comment by sawenzel** [comment]
@dberzano : Seems like G4 is crashing on the mac due to a window server problem:
```
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2019-02-20 17:41:36.758 O2SimDeviceRunner[58119:34210892] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3f707ff5 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6b863efb objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3f72e9e8 __CFArrayCopyDescription + 0
	3   libGCocoa.6.14.04.so                0x000000012382c854 _ZN4ROOT6MacOSX3X1123GetRootWindowAttributesEP18WindowAttributes_t + 52
	4   libGui.6.14.so                      0x00000001150c1f2a _ZN7TGFrameC2EP8TGClientmPK8TGWindow + 586
	5   libGui.6.14.so                      0x000000011508747d _ZN8TGClientC2EPKc + 685
	6   libGui.6.14.so                      0x0000000115175402 _ZN16TRootApplicationC2EPKcPiPPc + 146
	7   libGui.6.14.so                      0x0000000115194c62 _ZN15TRootGuiFactory20CreateApplicationImpEPKcPiPPc + 50
	8   libCore.6.14.so                     0x00000001092316e4 _ZN12TApplication18InitializeGraphicsEv + 292
	9   libCore.6.14.so                     0x00000001092313a8 _ZN12TApplicationC2EPKcPiPPcPvi + 984
	10  libRint.6.14.so                     0x00000001107aa01a _ZN5TRintC2EPKcPiPPcPvib + 42
	11  libgeant4vmc.dylib                  0x000000010c9387d7 _ZN13TG4RunManager12CreateRootUIEv + 295
	12  libgeant4vmc.dylib                  0x000000010c937e4a _ZN13TG4RunManagerC2EP19TG4RunConfigurationiPPc + 698
	13  libgeant4vmc.dylib                  0x000000010c93acb5 _ZN7TGeant4C2EPKcS1_P19TG4RunConfigurationiPPc + 1397
	14  libSimSetup.dylib                   0x000000010a8322bc _ZN2o28g4config6ConfigEv + 188
	15  libSimSetup.dylib                   0x000000010a832d5b _ZN2o28g4config8G4ConfigEv + 299
	16  O2SimDeviceRunner                   0x000000010916b5f8 _ZNSt3__110__function6__funcIZ10o2sim_initbE3$_0NS_9allocatorIS2_EEFvvEEclEv + 40
	17  libSteer.dylib                      0x0000000112973164 _ZN2o25steer8O2RunSim4InitEv + 1908
	18  O2SimDeviceRunner                   0x000000010915fe14 _Z10o2sim_initb + 2612
	19  O2SimDeviceRunner                   0x000000010916212d _ZN2o27devices11O2SimDevice7initSimER13FairMQChannelRNSt3__110unique_ptrI10FairRunSimNS4_14default_deleteIS6_EEEE + 301
	20  O2SimDeviceRunner                   0x0000000109161ee3 _Z13initializeSimNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEES5_RNS_10unique_ptrI10FairRunSimNS_14default_deleteIS7_EEEE + 339
	21  O2SimDeviceRunner                   0x0000000109165667 main + 3607
	22  libdyld.dylib                       0x00007fff6c92aed9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I remember that we had seen this some point in the past already. Funnily this is not happening when we run the tests in O2.

**Comment by sawenzel** [comment]
For reference, I found the original bug report here: https://alice.its.cern.ch/jira/browse/O2-289.
It seems that it can be fixed by with access rights to the GUI subsystem.

**Comment by dberzano** [comment]
Please leave this one open, I am using it to test the fix proposed by @sawenzel on the macOS nodes.

**Comment by dberzano** [comment]
For the record the fix seems to work, so it can be now merged _when the tests are green_.

**Pull request merged**
