### PR TITLE
bump readout v0.19.1

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
The osx issue in the failing test has been fixed. How to trigger again a test ?

**Comment by ktf** [comment]
I retriggered it by changing some cosmetics..

**Comment by sy-c** [comment]
I don't have the impression the check was relaunched, is there a way to see the corresponding timestamp?
After the fix, it was tested to build ok on macosx without libnuma.

**Comment by ktf** [comment]
The tests were relaunched for sure, as I saw them yellow. Maybe it's yet another thing which does not get picked up by incremental builds (because the configuration already happened). I will try locally on my Mac and then merge.

**Comment by awegrzyn** [comment]
I re-triggered the build and the output is the same.

**Pull request merged**
