### PR TITLE
bump arrow

### PR DESCRIPTION
**Pull request by aalkin**

### CODE REVIEW

**Comment by ktf** [comment]
did you miss xsimd?

**Comment by aalkin** [comment]
xsim was added in #4411

**Comment by aalkin** [comment]
@ktf @pzhristov 
The error `undefined reference to `typeinfo for llvm::ObjectCache'` seems to point to disabled LLVM's RTTI. I assume we need to enable it in for clang we build on linux. We can also try to use `-fno-rtti` for arrow, but I would expect it is actually used by gandiva.

**Comment by aalkin** [comment]
Update: on ubuntu 22.04 I cannot reproduce the error, everything builds normally.

**Comment by pzhristov** [comment]
I reproduced the problem on Ubuntu 18.04, but it is not clear to me how in the past the RTTI was OK, and now it is not.

**Comment by TimoWilken** [comment]
Hi @aalkin @pzhristov, I've just pushed a commit that enables building RTTI in LLVM. Let's see if that fixes it.

**Comment by aalkin** [comment]
Looks like enabling RTTI solved the issue, the remaining error is unrelated.

**Comment by pzhristov** [comment]
Yes, I am merging this PR.

**Pull request merged**
