### PR TITLE
Bump Abseil, Protobuf, gRPC, AliECS

### PR DESCRIPTION
**Pull request by teo**

### CODE REVIEW

**Review by sy-c — APPROVED** [review]

**Review by vascobarroso — APPROVED** [review]

**Comment by vascobarroso** [comment]
@alisw/alidist-maitainers could you check if this is good to go ?

**Comment by ktf** [comment]
@TimoWilken the macOS issue seems to be due to homebrew automatically updating llvm to an unsupported version. Could you check how come that happened?

@vascobarroso this has not actually checked anything on macOS, given you are bumping also bits which we do build there (like protobuf), I would prefer to check everything is fine there as well.

**Comment by vascobarroso** [comment]
@ktf ok fair enough. This is already at P2, so whenever you are happy please merge. Thanks!

**Comment by pzhristov** [comment]
> @TimoWilken the macOS issue seems to be due to homebrew automatically updating llvm to an unsupported version. Could you check how come that happened?

I think that when we call `brew install alisw/system-deps/o2-full-deps`, we install llvm and not llvm@14, then brew picks the latest version that is llvm 15.

**Comment by ktf** [comment]
Actually we force `llvm@13`, see https://github.com/alisw/homebrew-system-deps/blob/master/Formula/o2-full-deps.rb#L42. Something must be overriding that?

**Comment by TimoWilken** [comment]
Hm, we have both the `llvm` and the `llvm@13` brew packages installed. If I run `clang --version` I get `Apple clang version 13.0.0`, but maybe the newer version is interfering somehow.

**Comment by vascobarroso** [comment]
@ktf @TimoWilken any luck in sorting this out ?

**Comment by ktf** [comment]
The errors seem genuinely coming from this PR. Did you check on macOS locally?

**Comment by teo** [comment]
> The errors seem genuinely coming from this PR. Did you check on macOS locally?

I did not. TBH I'm not sure I have the Mac expertise to debug this time-efficiently. Are we building with LLVM on Mac?

**Review by vascobarroso — APPROVED** [review]

**Comment by Barthelemy** [comment]
I have tried this branch on my mac and arrow could build.

**Comment by Barthelemy** [comment]
I confirmed that on my Mac under Monterey, using `o2-dataflow`, this branch works

**Comment by ktf** [comment]
I think we build the whole defaults o2 in the CI for both macOS and macOS-arm. Maybe that's the issue?

I also confirm that this is the only PR which fails with this error for the mac and it was just retested.

**Comment by Barthelemy** [comment]
I have just tried with defaults `o2` and I had no problem on my machine with this branch.

**Comment by teo** [comment]
@ktf I've just done `aliBuild build O2 --defaults o2` on a Mac for the `aliecs-bump` branch, and it built correctly with no issue. I've tried the same with Arrow explicitly, and it also builds. This is the OS of the machine in question:

```
% uname -v
Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
```

It builds fine on @Barthelemy's Mac as well. Do you know in what ways might the CI machines be different?

**Comment by ktf** [comment]
Ciao,

it looks like somehow we have llvm 15 now installed by homebrew in the same
folder of llvm14:

(base) ***@***.*** ~ % cat
***@***.***/lib/cmake/llvm/LLVMConfig.cmake
| grep 15.0.3
set(LLVM_PACKAGE_VERSION 15.0.3)

not sure how that could have happened. I am reinstalling the system
dependencies on the mac and I will try again.


Ciao,
Giulio

**Comment by vascobarroso** [comment]
@ktf @TimoWilken what can we do to help unblock this ?

**Comment by awegrzyn** [comment]
Hi,
On my mac I've been facing this problem since months already... I tried using different LLVM but then the compilation was failing somewhere else. This makes me think if the compilation issue is related to this PR.
If anyone has an idea how to fix it I'd be happy to try it out.

```
uname -v
Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
```

**Comment by vascobarroso** [comment]
@ktf @TimoWilken pinging to keep this as top priority. We have a release tomorrow and we need a working CI. Thanks!

**Comment by ktf** [comment]
I tried a couple of things but that did not help. I am now rebuilding by hand, to see if it at least reproduces on the same machine.

**Comment by ktf** [comment]
Ok, I found a way to reproduce and to fix the issue on the build machine. @awegrzyn could you try with `brew install llvm@14` on your broken setup and see if that fixes it?

**Comment by ktf** [comment]
@TimoWilken could you install llvm@14 everywhere and make sure llvm (i.e. 15) is not present?

**Comment by awegrzyn** [comment]
> Ok, I found a way to reproduce and to fix the issue on the build machine. @awegrzyn could you try with `brew install llvm@14` on your broken setup and see if that fixes it?

@ktf I tried but it fails on `googlebenchmark`:
```
env: python: No such file or directory
make[2]: *** [test/CMakeFiles/copy_donotoptimize_assembly_test] Error 127
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ktf** [comment]
Cool, but in which package did you put it?

**Comment by ktf** [comment]
@awegrzyn Please check #4665.

**Pull request merged**
