### PR TITLE
Adjust lib dir

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
it seems the new version installs to `lib64` by default

**Review by sawenzel — APPROVED** [review]

**Comment by benedikt-voelkel** [comment]
failing fullCI seems to be unrelated / failed in general

**Comment by benedikt-voelkel** [comment]
@pzhristov is that something we can merge?
As mentioned the exported lib dir is currently not aligned with the actual lib dir (`lib` vs ` lib64`)

**Review by ktf — APPROVED** [review]

**Comment by ktf** [comment]
evtgen was not in the list of CODEOWNERS, so it needed some extra approval. I changed this in #4521.

**Pull request merged**
