### PR TITLE
Bump to llvm/clang 7.0

### PR DESCRIPTION
**Pull request by sawenzel**
Necessary to resolve https://alice.its.cern.ch/jira/browse/O2-412;
Needs to be merge **after** https://github.com/alisw/clang/pull/2 and a new tag has been created.

### CODE REVIEW

**Comment by sawenzel** [comment]
Anything holding back this PR? Without it the o2codechecker will stay blind.

**Comment by ktf** [comment]
There is a check that is still red, can you check what is going on there? I am away today.

**Comment by sawenzel** [comment]
I checked and fixed. But the ticket requires intervention from admins also in other places (tag creation for clang) since I don't have the right to do it.

**Comment by ktf** [comment]
I think I've everything in place. Let's check the tests are green and then I will merge. Do we actually build the package though?

**Comment by sawenzel** [comment]
I guess the package is not build in alidist PRs.

**Comment by ktf** [comment]
I do not remember actually. We might actually have some logic in place which checks every package whose recipe has been modified.

**Comment by dberzano** [comment]
Nope, it's not tested (it's just linted). It can be merged without waiting.

**Comment by sawenzel** [comment]
Thanks. I also updated the codechecker: https://github.com/AliceO2Group/O2CodeChecker/pull/27
The system is hopefully consistent now.

**Pull request merged**
