### PR TITLE
WIP Bump GCC to 11.2 [DO NOT MERGE YET]

### PR DESCRIPTION
**Pull request by MichaelLettrich**
Bump GCC to 11.2 for O2 defaults

### CODE REVIEW

**Comment by ktf** [comment]
https://github.com/alisw/alidist#guidelines-for-contributing-recipes

**Comment by MichaelLettrich** [comment]
Thanks for letting me know. The pr is preliminary only since we need to change it to a tag instead of a branch once we have tagged, working version of GCC-Toolchain in alice/v11.

**Comment by ktf** [comment]
please mark this as WIP, unless you are ready to merge it, otherwise it will rebuild the full stack until fixed.

**Comment by MichaelLettrich** [comment]
We can't do this too easily for O2 currently, closing. See [O2-2829](https://alice.its.cern.ch/jira/browse/O2-2829).

**Pull request closed without merging**
