### PR TITLE
bump qc to v0.18

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by sawenzel** [comment]
This should be merged despite failing AliGenerators test.

**Comment by ktf** [comment]
@Barthelemy  it looks like there is a genuine error in QC:

```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/QualityControl/v0.18.0/v0.18.0/Framework/test/testInfrastructureGenerator.cxx(70): [4;31;49mfatal error: in "qc_factory_remote_test": critical check workflow.size() == 4 has failed [6 != 4][0;39;49m
``

**Comment by Barthelemy** [comment]
@ktf I am having a look

**Comment by Barthelemy** [comment]
Waiting for the mac build but it is already confirmed that the previous problem is fixed. AliGenerators should be ignored.

**Pull request merged**
