### PR TITLE
FairMQ: bump to 1.4.9

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This should address a regression when using shmem transport. See also AliceO2Group/AliceO2#2547.

**Comment by ktf** [comment]
@dennisklein @rbx any ETA for 1.4.9? IIRC we need that for the shared memory issue.

**Comment by dennisklein** [comment]
> @dennisklein @rbx any ETA for 1.4.9? IIRC we need that for the shared memory issue.

We were [waiting for your feedback](https://github.com/AliceO2Group/AliceO2/pull/2547#issuecomment-547591245). We are ready to move forward. Will do the release right now

**Comment by dennisklein** [comment]
https://github.com/FairRootGroup/FairMQ/tree/v1.4.9

**Comment by ktf** [comment]
@rbx @dennisklein what happened to Uuid()?

**Comment by rbx** [comment]
Nothing, `std::string Uuid();` is still in `Tools.h` and/or `tools/Unique.h`, why?

**Comment by rbx** [comment]
Ah, there is a new target `FairMQ::Tools` that you need to depend on.

**Comment by rbx** [comment]
Although it should have been picked up from FairMQ target, since it is a public dependency of it...

**Comment by ktf** [comment]
@rbx Can you check why that is not the case?

**Comment by rbx** [comment]
The file that has problem with it is https://github.com/AliceO2Group/Readout/blob/v1.2.0/src/ConsumerFMQchannel.cxx. Looking at it more closely I see that there is no tools included anywhere in the entire Readout repository (neither `<fairmq/Tools.h>` nor `<fairmq/tools/Unique.h>`).
In the 1.4.9 we did a bit of cleanup of the include statements. Looks like ConsumerFMQchannel depended on one of the FairMQ headers that it does include having a tools include that is now gone.

Anyway, the correct solution would be for ConsumerFMQchannel.cxx to include the tools that it uses, either `<fairmq/Tools.h>` or `<fairmq/tools/Unique.h>`.

**Comment by ktf** [comment]
Ah, ok, understood.

**Comment by ktf** [comment]
See AliceO2Group/Readout#84

**Comment by ktf** [comment]
@MichaelLettrich are the mac builds just slow?

**Pull request merged**
