### PR TITLE
xjalienfs :: tag 1.2.9

### PR DESCRIPTION
**Pull request by adriansev**
Brief user-centric changelog:  
- XrootdCp:: add -strictspec and -http options
- XrootdCp::makelist_xrdjobs:: enforce unix authentication 
- MyCopyProgressHandler::end ::  fix deletion of meta file
- XrootD::cp rework the checks and messages to be clear and informative
- XRootD::cp fix the return/message for the single file copies with destionation already present
- add SEqos command and the internal get_qos
- add certkey-match and tokenkey-match commands
- add {cert,token}-verify commands
- XRootD:: uploads will default to 4 replicas ONLY if absolutly no specs given
- XRootD:: uploads will default to 4 replicas for any .sh, .C, .jdl, .xml smaller than 1MiB

### CODE REVIEW

**Comment by adriansev** [comment]
i see  
```
[ERROR] Requested resource does not exist: http://ccdb-test.cern.ch:8080/Test/pid22237/CCDBPathUnitTest/999/Hello=World/
```

i think this is not related to the PR.. any thoughts? @alien-experts

**Comment by ktf** [comment]
No, indeed , I think it's unrelated. @Barthelemy

**Comment by Barthelemy** [comment]
probably a transient problem

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
so, is there a way to restart tests? do i need some empty commit to be added to the branch?

**Pull request merged**
