### PR TITLE
Drop QCG from alidist

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by awegrzyn** [comment]
@TimoWilken `build/O2/alidist` has not completed since yesterday, could you have a look?

**Comment by TimoWilken** [comment]
@awegrzyn the builder was stuck. I've unstuck it and I've fixed the issue that got it stuck.

**Comment by awegrzyn** [comment]
Shall I clean the PR check once again? or this is taken care of?

**Comment by TimoWilken** [comment]
No need, this PR is in the queue! It's just building a different PR at the moment, this one should be next.

**Pull request merged**
