### PR TITLE
We should build ms_gsl with the GCC we also use for O2, not the system one

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Review by sawenzel — APPROVED** [review]

**Comment by ktf** [comment]
AFAICT, ms_gsl is header only. Why would this be needed?

**Comment by ktf** [comment]
Also, depending on CMake brings GCC-Toolchain in the environment indirectly. What is currently broken without this?

**Comment by ktf** [comment]
I would also check the prefer_system check for GCC does not select the system one because it's recent enough, yet it might not have the specific architecture support turned on...If you have a log feel free to point it to me.

**Review by ktf — CHANGES_REQUESTED** [review]
I think this is not actually the issue.

**Pull request closed without merging**
