### PR TITLE
Add Sacrifice

### PR DESCRIPTION
**Pull request by qgp**
This adds an interface to run Pythia8 standalone and produce HepMC output.

### CODE REVIEW

**Comment by qgp** [comment]
@dberzano: rebased as discussed

**Comment by dberzano** [comment]
Hello @qgp, compilation failed with the following error:

```
DEBUG:Sacrifice:v1.0.0: /build/workarea/pr/2015/1/BUILD/ff03169f7571c3459826c6d03b088f98610375cf/Sacrifice/config/missing: line 81: aclocal-1.14: command not found
DEBUG:Sacrifice:v1.0.0: WARNING: 'aclocal-1.14' is missing on your system.
DEBUG:Sacrifice:v1.0.0:          You should only need it if you modified 'acinclude.m4' or
DEBUG:Sacrifice:v1.0.0:          'configure.ac' or m4 files included by 'configure.ac'.
DEBUG:Sacrifice:v1.0.0:          The 'aclocal' program is part of the GNU Automake package:
DEBUG:Sacrifice:v1.0.0:          <http://www.gnu.org/software/automake>
DEBUG:Sacrifice:v1.0.0:          It also requires GNU Autoconf, GNU m4 and Perl in order to run:
DEBUG:Sacrifice:v1.0.0:          <http://www.gnu.org/software/autoconf>
DEBUG:Sacrifice:v1.0.0:          <http://www.gnu.org/software/m4/>
DEBUG:Sacrifice:v1.0.0:          <http://www.perl.org/>
DEBUG:Sacrifice:v1.0.0: make: *** [aclocal.m4] Error 127
```

You should add `autoreconf -ivf` before `./configure` and add as a build dependency (not a runtime one) `autotools`.

**Comment by qgp** [comment]
Hi @dberzano, thanks for the checks, updated accordingly.

**Comment by dberzano** [comment]
Thanks! Test started.

**Pull request merged**
