### PR TITLE
Changes to allow fotran packages to build with gcc 10

### PR DESCRIPTION
**Pull request by aalkin**
* Adds `-std=legacy` to gfortran flags
* Adds relevant `allow` flags

### CODE REVIEW

**Comment by pzhristov** [comment]
@aalkin The new options do not work with some of the old compilers. What is the platform that moved to gcc 10?

**Comment by aalkin** [comment]
> @aalkin The new options do not work with some of the old compilers. What is the platform that moved to gcc 10?

I apologize, this was supposed to stay in draft state. Fedora 32 has gcc10 and I was adapting everything to it.

**Comment by ktf** [comment]
What do we want to do with this? Is it ready to be reviewed?

**Comment by aalkin** [comment]
I did not have time to update it, but it needs a version check so that new options are only used with gfortran in gcc10. It is not complicated, but I did not put a priority on it.

**Comment by ktf** [comment]
Ok, closing this for now.

**Pull request closed without merging**
