### PR TITLE
Make linter check for Modulefile creation

### PR DESCRIPTION
**Pull request by dberzano**
Does not check defaults

### CODE REVIEW

**Comment by dberzano** [comment]
#851 was merged without a proper Modulefile and it's causing publisher problems. We should make sure that all recipes have a Modulefile creation. (Given that the "proper" solution would be to make aliBuild create a default one in case it's absent.)

**Comment by sawenzel** [comment]
The modulefile in #851 was there initially but we took it out since this is a header only library.

**Comment by ktf** [comment]
@sawenzel We should have made `ms_gsl` a build_requires as well. I forgot to mention.

**Comment by dberzano** [comment]
Hi @ktf, there was a request for aliBuild/alienv to also load the environment you would use for building: in principle in that case Modulefiles should be there, but also in my opinion the clean solution would be to automatically create them with aliBuild. Closing it.

@sawenzel @ktf Could please someone fix #851 then?

**Comment by dberzano** [comment]
I see it's done in #853.

**Comment by ktf** [comment]
I agree on creating them in alibuild, but then again, if build_require is specified, I see no reason for checking if a modulefile is there. What should also probably happen is that the linter uses the same parser as alibuild and is able to lint the whole chain of dependencies, not single packages.

**Comment by dberzano** [comment]
@ktf Yes this is why I have closed the PR ;-)

**Pull request closed without merging**
