### PR TITLE
Added ONNXRuntime as requirement to O2

### PR DESCRIPTION
**Pull request by SwirtaB**
ONNXRuntime is required for the fastsim module to work

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by sawenzel** [comment]
Needed for https://github.com/AliceO2Group/AliceO2/pull/8162

**Comment by awegrzyn** [comment]
Can we disable it in dataflow defaults?

**Comment by ktf** [comment]
and in the EPN ones, I guess.

**Comment by sawenzel** [comment]
@SwirtaB : Can you please disable ONNX in the defaults-o2-dataflow + epn files?

**Comment by SwirtaB** [comment]
@sawenzel Should I do it by adding 
```
disable:
  - ONNXRuntime
```
to those .sh files?

**Comment by sawenzel** [comment]
> @sawenzel Should I do it by adding
> 
> ```
> disable:
>   - ONNXRuntime
> ```
> 
> to those (dataflow and epn) .sh files?

Yes please! Like this, we will have ONXX in the normal O2 builds but not in more specialized configurations.

**Review by sawenzel — APPROVED** [review]

**Comment by sawenzel** [comment]
@TimoWilken : Can we merge this please? Full-CI fails with usual unrelated CCDB-token problem.

**Pull request merged**
