### PR TITLE
v0.7.1 QC and qcg in flpproto

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
related to O2-273 : setup a machine for qcg.

**Comment by Barthelemy** [comment]
@awegrzyn I have added a commit to add lib64 to the LD_LIBRARY_PATH for QualityControl.

**Comment by ktf** [comment]
Out of curiosity, why using `lib64`?

**Comment by Barthelemy** [comment]
@ktf That is a very good question actually :) It is linked to this other PR : https://github.com/AliceO2Group/QualityControl/pull/61

I started using ${CMAKE_INSTALL_LIBDIR} but realized that on my system it points to lib64. Thus libraries were not found. 

As noted by Adam in the other PR, we should review this to make sure we are all on the same line. I have absolutely no opinion on it, I just followed what was done in Monitoring.

**Comment by awegrzyn** [comment]
I've tested how CMake sets `CMAKE_INSTALL_LIBDIR` on different platforms:
- macOS - `lib`
- CC7 - `lib64`
- SLC6 - not set at all (empty)

I'd be strongly in favour of hardcoding this var to a fixed path (most probably `lib`).

**Comment by ktf** [comment]
Yeah, an alternative would be being able to extract it via cmake, but I am not sure if it's actually possible...

**Comment by Barthelemy** [comment]
ok, I can do that. I would prefer than relying on something that changes from platform to platform.

**Pull request merged**
