### PR TITLE
Bump Pythia version to 8.235

### PR DESCRIPTION
**Pull request by qgp**

### CODE REVIEW

**Comment by qgp** [comment]
@dberzano: from my side yes, but I don't understand what these errors here are? Unrelated?

**Comment by sawenzel** [comment]
Fine for me

**Comment by dberzano** [comment]
@qgp definitely unrelated. I am updating the branch, waiting for the tests again, and merging! Thanks!

**Comment by qgp** [comment]
@dberzano: Thanks for merging, we would then also need a new deployment of AliGenerators. Could this be done with the current versions in alidist (only change Pythia 8)?

**Comment by dberzano** [comment]
Do you need a build against the current alidist master? Did we use `root6` as defaults for the last build?

**Pull request merged**
