### PR TITLE
Bump JAliEn to 1.2.1

### PR DESCRIPTION
**Pull request by zensanp**
Update JAliEn (Java components only). Doesn't affect AliPhysics / O2 in any way.

### CODE REVIEW

**Review by costing — APPROVED** [review]

**Comment by ktf** [comment]
@shahor02 I think we merged something which did not compile in O2.

```
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-1/include/c++/7.3.0/cassert:44:0,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_O2_alidist-dataflow/0/Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx:26:
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_O2_alidist-dataflow/0/Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx: In member function 'void o2::its::Tracker::findTracks(const o2::its::ROframe&)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_O2_alidist-dataflow/0/Detectors/ITSMFT/ITS/tracking/src/Tracker.cxx:249:12: error: 'nClusters' was not declared in this scope
     assert(nClusters >= mTrkParams[0].MinTrackLength);
            ^
```

**Comment by shahor02** [comment]
@ktf This is an old code, problem shows up now when asserts are activated. I've already fixed one in the same file this morning: https://github.com/AliceO2Group/AliceO2/pull/4232.
Will post a fix when tested.

**Comment by ktf** [comment]
@MichaelLettrich can you restart the macOS builder?

**Comment by MichaelLettrich** [comment]
@ktf the builder is running again. Might need some time to catch up with the prs.

**Pull request merged**
