### PR TITLE
[O2-3591] Downgrade ROOT

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by ktf** [comment]
See also https://alice.its.cern.ch/jira/browse/O2-3591

**Review by knopers8 — APPROVED** [review]

**Comment by TimoWilken** [comment]
I've started a caching job for this PR: https://alijenkins.cern.ch/job/CacheO2Package/68/

**Comment by TimoWilken** [comment]
Caching is done; this can be merged.

**Comment by Barthelemy** [comment]
@TimoWilken I cannot merge myself

**Pull request merged**
