### PR TITLE
bump Common v1.5.0

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Review by graduta — DISMISSED** [review]

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
Can someone please have a look at this? The remaining builds are stuck since yesterday, with no progress, and I see some regular time updates in centos8 "Building since...".

**Comment by ktf** [comment]
@TimoWilken can you check what is going on here?

**Comment by ktf** [comment]
@sy-c would you mind to move to alibuild-recipes-tools to generate the modulefile?

**Comment by sy-c** [comment]
Hello @ktf, I have unfortunately no idea what you are talking about !

**Comment by ktf** [comment]
@TimoWilken looks like we now have unrelated tests pending for this PR.

**Comment by TimoWilken** [comment]
@ktf, alisw/ali-bot#837 should fix that

**Pull request merged**
