### PR TITLE
Bump FastJet to v3.4.1_1.052-alice1

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by hahassan7** [comment]
Hi @ktf ,

Thanks for updating fastjet. But shouldn't we also bump it in the fastjet.sh script ??

**Comment by ktf** [comment]
That's for aliphysics.

**Comment by hahassan7** [comment]
I see. Then it's good. Thanks !

**Comment by hahassan7** [comment]
Hi @ktf , Can we merge this pull request ? since all the tests have passed. Thanks.

**Comment by ktf** [comment]
I think the agreement in the WP4 / S&C meeting was to ask for official blessing by your PWG. @ddobrigk did you manage to follow that up? @hahassan7 could you alternatively have the convenors say a word on this thread?

**Comment by ktf** [comment]
@lhavener thanks. I have now added a team @alisw/pwgje and invited you there. Next time an update to fastjet is needed you will be automatically notified. Please let me know if anyone else should be added there.

**Pull request merged**
