### PR TITLE
fix the moderncppkafka recipe

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]

**Comment by vascobarroso** [comment]
@ktf any input on this ?

**Comment by ktf** [comment]
Only what I commented. It's not clear  to me why you would need to expose the _ROOT variable to the build. Usually that means that something else is broken in the CMakeLists.

**Comment by Barthelemy** [comment]
I am not 100% sure either, but at this stage I need it to be able to carry on. Many dev setups are broken.

**Comment by Barthelemy** [comment]
could we merge it please ?

**Comment by ktf** [comment]
Adding this variable is definitely the wrong thing to do, just like using alienv for the development setup (you should use the init.sh). You should fix your CMakeLists and / or switch to use init.sh for the dev environments.

**Pull request merged**
