### PR TITLE
root: use builtin afterimage

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo this might explain the issue on ubuntu. Kudos for @wiechula for spotting it.

**Comment by pzhristov** [comment]
@ktf Which issue on Ubuntu?

**Comment by ktf** [comment]
@pzhristov Running our O2 slc7 builds on the train machine which are ubuntu. @jgrosseo might have more details.

**Comment by jgrosseo** [comment]
Thanks. Let me know once this is used for a build, and I'll try!

**Pull request merged**
