### PR TITLE
Readout: require mysql only on production platform

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@sy-c would you be ok with this? So that we do not have to require mqsql installations for users e.g. on mac or ubuntu.

**Comment by ktf** [comment]
Actually maybe we could drop it completely for defaults-o2 and keep it only for defaults-dataflow? You use that for the FLP deployment, no?

**Comment by sy-c** [comment]
Hello @ktf, both solutions are fine, I have no preference.

**Review by sy-c — DISMISSED** [review]

**Comment by ktf** [comment]
I will actually do both...

**Pull request merged**
