### PR TITLE
Update ROOT to v6-28-04-alice2

### PR DESCRIPTION
**Pull request by ktf**
Includes the patch to reduce memory overhead

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken I am afraid I pushed a new tag with the same name, could you clean up the worker nodes?

**Comment by TimoWilken** [comment]
Did  you already delete them @ktf? I can't find any v6-28-04-alice2 versions of ROOT on the CI builders!

**Comment by ktf** [comment]
Restarting the missing tests.

**Comment by ktf** [comment]
Now also ROOT timed out. Very weird. Yet another IPv6 screwup?

**Comment by ktf** [comment]
The memory reduction patch was merged in LLVM upstream. Merging this to continue profiling. @chiarazampolli would it be possible to pick it up for the asycn reco tags?

**Pull request merged**
