### PR TITLE
Bump CMake to 3.23.1

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf : If this gets green, I'd merge this one and #3533 over Eastern? Will hopefully not cause that much disturbance then.

**Comment by awegrzyn** [comment]
Could you tag me when you do so? I'll run some clean up on FLP build server.

**Comment by davidrohr** [comment]
I'll do it Saturday evening, will tag you then.

**Comment by davidrohr** [comment]
@awegrzyn : ping

**Comment by ktf** [comment]
Did you merge also the OpenSSL fixes? This now breaks the builds with:

```
2022-04-17@06:14:34:DEBUG:O2PDPSuite:O2:0: /mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.FhrfvqYkHf/slc7_x86-64/CMake/v3.23.1-2/bin/cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

?

**Comment by ktf** [comment]
Notice how:

/mnt/mesos/sandbox/sandbox/jenkins/workspace/DailyBuilds/DailyO2Physics/daily-tags.FhrfvqYkHf/slc7_x86-64/OpenSSL/v1.0.2o-60/lib

seems to be correctly there. I am now checking if the libraries are present.

**Comment by davidrohr** [comment]
Yes, I merged both. Both were green. Can it be that they don't work well together? Or is it some incremental build problem?

Kind Regards
David Rohr

**Comment by davidrohr** [comment]
But actually what is broken? My PR https://github.com/AliceO2Group/AliceO2/pull/8596 which I updated later yesterday went through correctly.

**Pull request merged**
