### PR TITLE
WIP: Add Action to trigger RPM generation when recipe changes

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by ktf** [comment]
Very nice, actually.

**Comment by ktf** [comment]
I've subscribed alisw to "Actions".

**Comment by ktf** [comment]
I've added KERBEROS_PASSWORD and KERBEROS_USER, with a fake password, I suggest we merge this and we make sure secrets are not leaked, and then we use the actual password.

**Comment by awegrzyn** [comment]
I've already tested it in my fork but sure: https://github.com/awegrzyn/alidist/commit/cec2854e43321abf9304848ba03e856f805a4e95/checks?check_suite_id=247719822

**Comment by ktf** [comment]
Ok, I've updated it with real secrets. I guess we can merge and try it out.

**Pull request merged**
