### PR TITLE
Bump librdkafka to v1.8.2

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by ktf** [comment]
Why do you need the setenv?

**Comment by awegrzyn** [comment]
Just for development purposes, but indeed I can keep it in my fork

**Comment by ktf** [comment]
Ok. Keep in mind that the environment provided by the modulefiles is not meant, by design, to include the development variables you need to build. In general my reccomandation is to make sure the cmakecache / compile_commands.json is self contained and does not need extra development information. If you want to have the environment as used by alibuild you should source etc/profile.d/init.sh.

**Comment by ktf** [comment]
Errors unrelated. Relevant part compiled. Merging.

**Pull request merged**
