### PR TITLE
Use $IGNORE_ERRORS to compile with -k

### PR DESCRIPTION
**Pull request by ktf**
Now that defaults allow us to do so, let's use an environment variable to
control wether or not the build should fail on error.

### CODE REVIEW

**Comment by ktf** [comment]
@dberzano can you merge this for the next release?

**Comment by dberzano** [comment]
Makes perfect sense to me. This also solves a problem for some users. The variable `IGNORE_ERRORS` is supposed to be set manually by the user, right?

**Comment by sawenzel** [comment]
@dberzano: Yes, from my understanding we should catch errors by default and ignore them only upon request.

**Comment by dberzano** [comment]
Ported in `IB/v5-08/next` (this PR is to prod). Closing, will soon merge to prod.

**Pull request closed without merging**
