### PR TITLE
xrootd:: make sure to use the same dependencies as ROOT; disable all …

### PR DESCRIPTION
**Pull request by adriansev**
…unused features

Hi @TimoWilken ! with this PR i try to bring xrootd dependencies in sync with ROOT ones
Moreover, to reduce the risk of various dependencies to be automatically picked up, i turned off all unused features.
Could you please take a look?
Thanks a lot!

### CODE REVIEW

**Comment by adriansev** [comment]
@TimoWilken seems that the way that ROOT use openssl and libxml2 is not working on macos..
Any idea what could be the problem and how can we have a consistent openssl and libxml2 for both ROOT and XRootD?
Thanks a lot!!

**Comment by TimoWilken** [comment]
Hi @adriansev, just blindly copying the `if [[ $ALIEN_RUNTIME_VERSION ]]; then ...; fi` block from the ROOT recipe won't work. On MacOS, we don't install OpenSSL nor libxml2 in AliEn-Runtime, as far as I can tell.

Also, for instance, the `SYS_OPENSSL_ROOT` variable is internal to the ROOT recipe; ROOT sets it to the right thing on MacOS to avoid taking OpenSSL from AliEn-Runtime.

**Comment by adriansev** [comment]
> Hi @adriansev, just blindly copying the `if [[ $ALIEN_RUNTIME_VERSION ]]; then ...; fi` block from the ROOT recipe won't work. On MacOS, we don't install OpenSSL nor libxml2 in AliEn-Runtime, as far as I can tell.
> 
> Also, for instance, the `SYS_OPENSSL_ROOT` variable is internal to the ROOT recipe; ROOT sets it to the right thing on MacOS to avoid taking OpenSSL from AliEn-Runtime.

Hi @TimoWilken 
Ok, now i seen that actually the setting for OPENSSL_ROOT was already done for macos
so, what do you think would be the proper solution to make sure that both xrootd and root use the same openssl and libxml2? (which root will also use xrootd for TNetXNGFile)
Thanks a lot!

**Comment by TimoWilken** [comment]
What's the problem with depending on `OpenSSL:(?!osx)`? On Linux, the OpenSSL from our OpenSSL package should be identical with the one from AliEn-Runtime as the latter just copies it from the former. And on MacOS, we use the system one for both.

**Comment by adriansev** [comment]
> What's the problem with depending on `OpenSSL:(?!osx)`? On Linux, the OpenSSL from our OpenSSL package should be identical with the one from AliEn-Runtime as the latter just copies it from the former. And on MacOS, we use the system one for both.

there is no problem at all :) .. what i'm trying to do is to have in both recipe (xrootd and root) the same definition (and usage) of the requirements

**Comment by TimoWilken** [comment]
If there's no problem, then I would not make it more complicated than it needs to be.

Using `OpenSSL:(?!osx)` should get you the same OpenSSL that ROOT uses, modulo any explicit fallback to brew on MacOS (but that's already handled by the xrootd recipe).

**Comment by adriansev** [comment]
> If there's no problem, then I would not make it more complicated than it needs to be.
> 
> Using `OpenSSL:(?!osx)` should get you the same OpenSSL that ROOT uses, modulo any explicit fallback to brew on MacOS (but that's already handled by the xrootd recipe).

got it.. i used the same options as in root.sh 
now, about libxml2, i also kept the same options as in root.sh
does the final diff look good to you?
Thanks a lot!

**Review by TimoWilken — APPROVED** [review]
Sure, looks fine to me now!

**Comment by TimoWilken** [comment]
Hm, I'm not sure why the FST can't find an alien token. The build definitely got one as usual in the `JALIEN_TOKEN_KEY` and `JALIEN_TOKEN_CERT` environment variables.

**Comment by adriansev** [comment]
@TimoWilken temporary glitch i would say given that initial form of PR was ok on O2/fullCI and was failing on macos .. and relative to xrootd, it seems that it was successful but i see a weird thing just after the xrootd compilation (seems to be an openssl related problem):
```
Successfully installed xrootd-5.5.3
Cleaning up...
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 827, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
pip._vendor.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/utils/outdated.py", line 141, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/download.py", line 387, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 640, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

```

**Comment by adriansev** [comment]
@ktf @TimoWilken guys, any idea what is going on? Maybe a restart can help?
Does it make sense for all other tests to work except this?
Thanks a lot!

**Comment by adriansev** [comment]
@ktf @TimoWilken it seems that the problems is recurrent (and i see no relation to my PR):
```
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 589, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 827, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
pip._vendor.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/pip/_vendor/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/utils/outdated.py", line 141, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/download.py", line 387, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 640, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
++ popd
```

i see an explanation here: 
https://blog.richard.do/2022/05/17/python-pip-cant-connect-to-https-url-because-the-ssl-module-is-not-available/

and i can see in the full log the following:
```
ag "Found.*OpenSSL" fullLog.txt 
135:-- Found OpenSSL: /sw/slc8_x86-64/OpenSSL/v1.1.1m-2/lib/libcrypto.so (found suitable version "1.1.1m", minimum required is "1.0.2")  
888:>>>>>>   Found XRootD python bindings: ++ LD_LIBRARY_PATH=/sw/INSTALLROOT/35d2fd60cb3dca3b5eb092b1804067eda650c900/slc8_x86-64/XRootD/v5.5.3-local1/lib:/sw/slc8_x86-64/CMake/v3.23.1-10/lib:/sw/slc8_x86-64/AliEn-Runtime/v2-19-le-16/lib:/sw/slc8_x86-64/UUID/v2.27.1-9/lib:/sw/slc8_x86-64/ApMon-CPP/v2.2.8-alice5-7/lib:/sw/slc8_x86-64/libtirpc/libtirpc-1-1-4-7/lib:/sw/slc8_x86-64/AliEn-CAs/v1-7/lib:/sw/slc8_x86-64/OpenSSL/v1.1.1m-2/lib:/sw/slc8_x86-64/alibuild-recipe-tools/0.2.3-4/lib:/sw/slc8_x86-64/libxml2/v2.9.3-17/lib:/sw/slc8_x86-64/zlib/v1.2.8-17/lib:/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/lib:/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/lib64:/sw/slc8_x86-64/defaults-release/v1-5/lib
15510:-- Found OpenSSL: /sw/slc8_x86-64/OpenSSL/v1.1.1m-2/lib/libcrypto.so (found suitable version "1.1.1m", minimum required is "1.0.2")  
15512:-- Found OpenSSL Crypto Library: /sw/slc8_x86-64/OpenSSL/v1.1.1m-2/lib/libcrypto.so
16650:-- Found OpenSSL: /sw/slc8_x86-64/AliEn-Runtime/v2-19-le-16/lib/libcrypto.so (found version "1.1.1m")  
36881:-- Found OpenSSL: /sw/slc8_x86-64/OpenSSL/v1.1.1m-2/lib/libcrypto.so (found version "1.1.1m")  
41280:-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1k")  
54879:-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1k")  
70017:-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1k")
```

so, i count 3 locations for openssl that are used in the same test:
```
1. /sw/slc8_x86-64/OpenSSL/v1.1.1m-2
2. /sw/slc8_x86-64/AliEn-Runtime/v2-19-le-16
3. /usr/lib64
```

Moreover, the python infrastructure (at least in xrootd) see all 3 mixed libraries due to:
```
888:>>>>>>   Found XRootD python bindings: ++ LD_LIBRARY_PATH=/sw/INSTALLROOT/35d2fd60cb3dca3b5eb092b1804067eda650c900/slc8_x86-64/XRootD/v5.5.3-local1/lib:/sw/slc8_x86-64/CMake/v3.23.1-10/lib:/sw/slc8_x86-64/AliEn-Runtime/v2-19-le-16/lib:/sw/slc8_x86-64/UUID/v2.27.1-9/lib:/sw/slc8_x86-64/ApMon-CPP/v2.2.8-alice5-7/lib:/sw/slc8_x86-64/libtirpc/libtirpc-1-1-4-7/lib:/sw/slc8_x86-64/AliEn-CAs/v1-7/lib:/sw/slc8_x86-64/OpenSSL/v1.1.1m-2/lib:/sw/slc8_x86-64/alibuild-recipe-tools/0.2.3-4/lib:/sw/slc8_x86-64/libxml2/v2.9.3-17/lib:/sw/slc8_x86-64/zlib/v1.2.8-17/lib:/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/lib:/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-2/lib64:/sw/slc8_x86-64/defaults-release/v1-5/lib
```

were both OpenSSL from /sw/slc8_x86-64/OpenSSL/v1.1.1m-2 and from /sw/slc8_x86-64/AliEn-Runtime/v2-19-le-16 met

So, the problem is not due to my PR, and the problem will not go away no matter what I do.
Could you please weight on this issues in order to move forward? i would also like to move to fix libxml2 that takes the system lzma instead of alidist one (while already root and boost use LZMA_ROOT)

**Comment by adriansev** [comment]
@TimoWilken I apologize, i did not seen your message. So, given the problem with ssl usage, i absolutely certain that alien-token-init comes from the fact that ssl module of python cannot be used (as such anything ssl related will break). Any output of alien-token-init is hidden because is used like this: `21:  alien-token-info >& /dev/null` (in prodtests/full_system_test.sh)
So, is there any way to move forward with this?
Also, let me re-iterate that IMHO is highly unlikely that this PR have anything to do with python infrastructure, OpenSSL or xjalienfs/alien.py package as this only change XRootD compilation arguments (and xjalienfs load xrootd ONLY when used)

**Pull request closed without merging**
