### PR TITLE
DebugGUI: bump to v0.3.1

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken this tested the "rivet" configuration, which I removed. Was it simply running with the old configuration?

**Comment by TimoWilken** [comment]
@ktf, yes, the `rivet.env` is now gone from that container. That test must have run before the builder got the updates to ali-bot.

**Comment by ktf** [comment]
@TimoWilken build/O2/alidist-centos8 is pending since hours.

**Comment by ktf** [comment]
@MichaelLettrich do you understand what is going wrong with the mac builds?

**Comment by MichaelLettrich** [comment]
@ktf investigating

**Comment by MichaelLettrich** [comment]
@ktf seems that git cannot find the tag:

```bash
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + export GIT_REFERENCE=/build/mirror/debuggui
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + GIT_REFERENCE=/build/mirror/debuggui
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + export GIT_PARTIAL_CLONE_FILTER=--filter=blob:none
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + GIT_PARTIAL_CLONE_FILTER=--filter=blob:none
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + [[ ! https://github.com/AliceO2Group/DebugGUI == '' ]]
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + [[ h != \/ ]]
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: + git checkout v0.3.0
2020-10-23@11:14:50:DEBUG:O2Suite:DebugGUI:2558: error: pathspec 'v0.3.0' did not match any file(s) known to git
2020-10-23@11:14:50:ERROR:O2Suite:DebugGUI:2558: Error while executing /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SPECS/osx_x86-64/DebugGUI/v0.3.0-1/build.sh on `aido2osx3.cern.ch'.
2020-10-23@11:14:50:ERROR:O2Suite:DebugGUI:2558: Log can be found in /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/DebugGUI-latest/log
2020-10-23@11:14:50:ERROR:O2Suite:DebugGUI:2558: Please upload it to CERNBox/Dropbox if you intend to request support.
2020-10-23@11:14:50:ERROR:O2Suite:DebugGUI:2558: Build directory is /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/DebugGUI-latest/DebugGUI.
```

**Pull request merged**
