### PR TITLE
daily tags: auto-update dist definitions

### PR DESCRIPTION
**Pull request by alibuild**
The daily-tags.sh script has created a tag release with these changes.

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken also in this case, there seems to be too many change for the automatic update. Could you check?

**Comment by TimoWilken** [comment]
As far as I know, every daily build pushes to `rc/master`, even if it doesn't push a tag. Should this be turned off if `DO_NOT_CREATE_NEW_TAG` is set?

**Comment by Barthelemy** [comment]
we would need this tag for the new FLP Suite. @vascobarroso

**Comment by Barthelemy** [comment]
@ktf @TimoWilken so.... why is it all red ?

**Comment by ktf** [comment]
@Barthelemy fullCI was red due to the Copyright migration (sigh).

@TimoWilken could you check what is wrong with the generators / macos test?

**Comment by TimoWilken** [comment]
AliGenerators said: `RuntimeError: Error on fetching ''EPOS''. Aborting.` I'll look into the MacOS one.

**Comment by ktf** [comment]
Maybe @preghenella or @maireiphc can help on the EPOS one?

**Comment by TimoWilken** [comment]
I'm guessing it was a random failure of the GitLab... I'll see if it happens again.

**Comment by maireiphc** [comment]
> Maybe @preghenella or @maireiphc can help on the EPOS one?

This is something that I have seen in the past for the daily build when they fail. It was recent (~month) but the log are not accessible anymore. As far as I remember, it was with EPOS (one of the private version that we have in ALICE, i.e. hosted not under github/alisw but gitlab; DPMJET is the other MC generators with that kind of access restrictions.)
https://alijenkins.cern.ch/job/DailyBuilds/job/DailyAliGenerators/
The next days, the build suceeded again without intervention being triggered (at least from me)

**Comment by ktf** [comment]
In https://github.com/alisw/alidist/pull/3120 @awegrzyn reenable a package which in the past was causing us troubles.

**Pull request merged**
