### PR TITLE
Reopen bumping grpc to v1.45.1

### PR DESCRIPTION
**Pull request by awegrzyn**
Reopens https://github.com/alisw/alidist/pull/4040
Related to https://github.com/alisw/alidist/pull/4086

### CODE REVIEW

**Review by ironMann — APPROVED** [review]
LGTM. 
I originally forgot, but we could try bumping protobufs with this bunch. Though, I don't have any reason for that, atm.

**Comment by davidrohr** [comment]
@vascobarroso @awegrzyn : Could you comment when we can merge this and DD 1.4?

**Comment by awegrzyn** [comment]
I'd say as soon as checks pass.

**Comment by davidrohr** [comment]
ok, but checks had passed before and then @vascobarroso asked me to revert, since there were problems in the FLPSuite tests (not the github CI). Perhas you can directly check this before?

**Comment by awegrzyn** [comment]
@davidrohr Actually, I'd propose to merge this one and AliECS bump (https://github.com/alisw/alidist/pull/4090) first, after that I'm gonna double check everything is fine, and in the end I'd go with new DD (https://github.com/alisw/alidist/pull/4086)

**Comment by awegrzyn** [comment]
> ok, but checks had passed before and then @vascobarroso asked me to revert, since there were problems in the FLPSuite tests (not the github CI). Perhas you can directly check this before?

Yes, there was linking issue when generating `mesos` FLP RPM, but this should be fixed already.

**Comment by davidrohr** [comment]
> @davidrohr Actually, I'd propose to merge this one and AliECS bump (#4090) first, after that I'm gonna double check everything is fine, and in the end I'd go with new DD (#4086)

ok great, let's do it that way. If github CI is green and I miss to see and merge it, you can ping me on mattermost.

**Comment by davidrohr** [comment]
does not affect AliRoot, O2/alidist is kind of overloaded at the moment, and this has passed all the other CIs, merging

**Comment by awegrzyn** [comment]
@ironMann Do you have a preference in `protobuf` version to have?

**Pull request merged**
