### PR TITLE
Bump ROOT to v6-28-08-alice1

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by sawenzel** [comment]
This doesn't do it. We need v6-28-08 according to ROOT team. Testing right now.

**Comment by sawenzel** [comment]
I confirm that with v6-28-08 the issue with the StreamerInfos is fixed.

**Comment by ktf** [comment]
PR updated.

**Comment by sawenzel** [comment]
It appears that all builds fail now. Something was changed in the CMake (related to VDT?? https://github.com/root-project/root/issues/11797)

**Comment by ktf** [comment]
It's probably the same issue as in https://github.com/alisw/alidist/pull/5214/files. Let me use that one, instead.

**Comment by ktf** [comment]
Closing in favour of https://github.com/alisw/alidist/pull/5278.

**Pull request closed without merging**
