### PR TITLE
Bump to ROOT v6-32-06-alice1

### PR DESCRIPTION
**Pull request by ktf**
- Make sure ROOT works on macOS 15 Sequoia (requires enabling ROOT7)
- Disable VecGeom on macOS (apparently not used)
- Include improvements to geometry handling by @sawenzel 
- Include reverts necessary to have pythia6 and proof working

### CODE REVIEW

**Comment by ktf** [comment]
@aalkin @pzhristov with this I get to O2.

@aalkin, do you have a PR for the std::enable_if issue?

**Comment by ktf** [comment]
@sawenzel @pzhristov this should work already for O2.

@pzhristov can you remind me what you need to add to the root.sh recipe, as discussed offline?

**Comment by sawenzel** [comment]
Thanks @ktf.

@ktf @pzhristov : I am still a little worried that we bring back TPythia6 into ROOT, since there will **for sure** be duplicated symbols in AEGIS and ROOT. This may not materialize as a problem during compilation, but only during runtime. So I would like to propose to check if event generation still works ok during runtime. A suitable test would be to run `o2-sim-dpl-eventgen --nEvents 1 --generator external --configFile ${O2DPG_ROOT}/MC/config/PWGEM/ini/GeneratorLFCocktailpp.ini` in the O2sim environment (doesn't really need O2Physics).

**Comment by pzhristov** [comment]
@sawenzel We can avoid the problems with the duplicated symbols, if we return AEGIS to version v1.5.3.

**Comment by ktf** [comment]
Merging this since it's green. I will now revert aegis as well.

**Pull request merged**
