### PR TITLE
Bump ReadoutCard to v0.15.4

### PR DESCRIPTION
**Pull request by kostorr**

### CODE REVIEW

**Comment by awegrzyn** [comment]
Dear builders, please don't fail this time !

**Comment by Barthelemy** [comment]
Builders heard you but we are not allowed to merge ...

**Comment by Barthelemy** [comment]
@ktf ?

**Comment by sawenzel** [comment]
@pzhristov : Could you merge this?

**Comment by ktf** [comment]
For some reason our settings now require "Maintainer" role to merge. I've added the usual suspects to the `alisw/alidist-maintainer` role. Let me know if you still have troubles.

**Pull request merged**
