### PR TITLE
Move everything to C++20

### PR DESCRIPTION
**Pull request by ktf**
Move everything to C++20

### CODE REVIEW

**Comment by ktf** [comment]
@awegrzyn do you have any idea of what the issue with monitoring could be:

```C++
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-local1/include/c++/12.2.0/bits/basic_string.h:1647:19,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-local1/include/c++/12.2.0/bits/basic_string.h:815:28,
    inlined from 'void o2::monitoring::ProcessDetails::generateProcessName()' at /sw/SOURCES/Monitoring/v3.17.5/v3.17.5/src/ProcessDetails.cxx:62:20:
/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-local1/include/c++/12.2.0/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
--
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
```

maybe the `inline` in a `.cxx` confuses it?

**Comment by awegrzyn** [comment]
> @awegrzyn do you have any idea of what the issue with monitoring could be:

Not really, but I managed to reproduce it locally so I will have a look

**Comment by awegrzyn** [comment]
@ktf You can bump monitoring to `v3.18.0` to get rid of the warning (it requires new boost).

**Comment by ktf** [comment]
Ok, perfect, thanks.

**Comment by ktf** [comment]
@awegrzyn I think TpcFecUtils/v0.3.1/v0.3.1/src/fec.hpp has the same issue as monitoring. Could you please take a look?

**Review by jackal1-66 — APPROVED** [review]
Minor changes, should not cause problems.

**Comment by awegrzyn** [comment]
@ktf You can bump `TpcFecUtils` to `v0.3.2`

**Comment by davidrohr** [comment]
@ktf : it tries to compile the GPU code with C++20, which fails.
But anyway, we want to switch from faking CMake CXX compiler to HIP language: https://github.com/AliceO2Group/AliceO2/pull/12255
I am currently testing that PR. Once that PR is merged, we should check again.
Probably we still need to hack CMake to fix this, but the way to hack it will likely change.

**Comment by davidrohr** [comment]
ok, still broken with HIP as CMake language. Will have a look tonight...

**Comment by davidrohr** [comment]
@ktf : FullCI is green now :)

**Comment by TimoWilken** [comment]
Caching here @ktf: https://alijenkins.cern.ch/job/CacheO2Package/96/

**Comment by ktf** [comment]
Caching done. Merging!!!!!!

**Comment by Barthelemy** [comment]
I am getting the following on our mac jenkins: 
```
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Detectors/MUON/MCH/Workflow/src/entropy-encoder-workflow.cxx:20:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Detectors/MUON/MCH/CTF/include/MCHCTF/CTFCoder.h:23:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/DataFormats/Detectors/MUON/MCH/include/DataFormatsMCH/CTF.h:21:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/EncodedBlocks.h:32:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/internal/Packer.h:20:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Utilities/rANS/include/rANS/pack.h:24:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Utilities/rANS/include/rANS/internal/metrics/Metrics.h:29:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Utilities/rANS/include/rANS/internal/metrics/SizeEstimate.h:25:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: In file included from /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Utilities/rANS/include/rANS/internal/common/typetraits.h:22:
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0: /Users/aldaqci/alice-jenkins-master/sw/SOURCES/O2/dev/0/Utilities/rANS/include/rANS/internal/encode/Encoder.h:112:18: error: ISO C++20 considers use of overloaded operator '==' (with operand types 'o2::mch::CTFHelper::Iter_bcIncROF' and 'o2::mch::CTFHelper::Iter_bcIncROF') to be ambiguous despite there being a unique best viable function [-Werror,-Wambiguous-reversed-operator]
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0:   if (inputBegin == inputEnd) {
2024-02-02@08:09:45:DEBUG:O2Suite:O2:0:       ~~~~~~~~~~ ^  ~~~~~~~~
```
Do you think that it is related ?

**Comment by ktf** [comment]
How old is that code? I fixed a bunch of those in the past.

**Comment by ktf** [comment]
Ah, it might actually be a bug in the old XCode. What do you use?

**Comment by Barthelemy** [comment]
I am starting a meeting now. 
The OS is
```
aldaqci@aido2osx2 alice-jenkins-master % sw_vers
ProductName:		macOS
ProductVersion:		13.6
BuildVersion:		22G120
```

O2 is from today.

**Comment by Barthelemy** [comment]
```
aldaqci@aido2osx2 ~ % pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
version: 14.3.1.0.1.1683849156
```

**Comment by ktf** [comment]
I cannot reproduce it on my box and it runs with:

```
→ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
version: 15.1.0.0.1.1700200546
```

i.e. the next version. I would be tempted to say "update and we see"...

**Comment by mfasDa** [comment]
There is a problem now with the pythia in AliRoot, which is different from the pythia in AliGenerators. Seems that needs to be updated as well:

```
2024-02-02@15:47:05:DEBUG:AliPhysics:AliRoot:aliceo2: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/vector:549:52: error: arithmetic on a pointer to an incomplete type 'Pythia8::fjcore::ClosestPair2D::Point'
2024-02-02@15:47:05:DEBUG:AliPhysics:AliRoot:aliceo2:         {return static_cast<size_type>(__end_cap() - this->__begin_);}
2024-02-02@15:47:05:DEBUG:AliPhysics:AliRoot:aliceo2:                                        ~~~~~~~~~~~ ^
```

**Comment by ktf** [comment]
Did you update aliroot? This is just a missing header for which the compiler now complains.

**Comment by mfasDa** [comment]
@ktf Yes, this is AliRoot master, just updated a few minutes before.

Note that AliRoot ships an internal Pythia 8, which is Pythia 8.2.43. It does not use the Pythia 8.3 from AliGenerators which you bumped as can be seen in the thread above

**Comment by mfasDa** [comment]
It seems connected to a forward declaration in the cxx file, where the object is defined. file is PYTHIA8/pythia8/src/FJcore.cc (line 760). I am not even sure this is used, might be only needed if one does jet analysis from within the Pythia. It exists also in Pythia 8.3.04, however I am not sure it is compiled there. After commenting the file in the CMakeLists.txt AliRoot compiles. with c++20.

**Comment by ktf** [comment]
Ok, thanks. Strange that the CI does not catch it. Could you submit a PR to AliRoot when it's clear what's going on?

**Comment by mfasDa** [comment]
It is unfortunately not so simple, and therefore offline experts will need to look at it. First of all, we cannot get rid of the file as it is used in other libraries as dependency. Second, the problem is in this code block which introduces a circular dependency which is tricky to solve (Shuffle depends on Point, Point on Shuffle, and this the authors try to solve with a forward declaration which creates now the compiler error above.):
``` c++
  class Point; // will be defined below
  template<class T> class triplet {
  public:
    inline const T & operator[](unsigned int i) const {return _contents[i];};
    inline       T & operator[](unsigned int i)       {return _contents[i];};
  private:
    T _contents[_nshift];
  };
  class Shuffle {
  public:
    unsigned int x, y;
    Point * point;
    bool operator<(const Shuffle &) const;
    void operator+=(unsigned int shift) {x += shift; y+= shift;};
  };
  typedef SearchTree<Shuffle>     Tree;
  typedef Tree::circulator        circulator;
  typedef Tree::const_circulator  const_circulator;
  triplet<SharedPtr<Tree> >  _trees;
  SharedPtr<MinHeap>     _heap;
  std::vector<Point>     _points;
  std::stack<Point *>    _available_points;
  std::vector<Point *>   _points_under_review;
  static const unsigned int _remove_heap_entry = 1;
  static const unsigned int _review_heap_entry = 2;
  static const unsigned int _review_neighbour  = 4;
  void _add_label(Point * point, unsigned int review_flag);
  void _set_label(Point * point, unsigned int review_flag);
  void _deal_with_points_to_review();
  void _remove_from_search_tree(Point * point_to_remove);
  void _insert_into_search_tree(Point * new_point);
  void _point2shuffle(Point & , Shuffle & , unsigned int shift);
  Coord2D _left_corner;
  double _range;
  int _ID(const Point *) const;
  triplet<unsigned int> _shifts;     // absolute shifts
  triplet<unsigned int> _rel_shifts; // shifts relative to previous shift
  unsigned int _cp_search_range;
};
class ClosestPair2D::Point {
public:
  Coord2D coord;
  Point * neighbour;
  double  neighbour_dist2;
  triplet<circulator> circ;
  unsigned int review_flag;
  double distance2(const Point & other) const {
    return coord.distance2(other.coord);
  };
```

**Comment by Barthelemy** [comment]
> I cannot reproduce it on my box and it runs with:
> 
> ```
> → pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
> version: 15.1.0.0.1.1700200546
> ```
> 
> i.e. the next version. I would be tempted to say "update and we see"...

I have updated and now it works. Thank you

**Comment by mfasDa** [comment]
@ktf Concerning that the issue is not caught by the CI: From what I see the CI of alidist test only O2. My understanding is that AliRoot has not yet been tested with the CI for mac. 

Looking at AliPhysics PRs there are more c++-20 incompatibilities in old code  :(

**Comment by mfasDa** [comment]
Also the compiler errors in the AliPhysics CI seem to be related - as the one in PYTHIA mentioned above - to forward declarations of objects which are used in std::vectors, for which then a static_assert fails.

**Comment by mfasDa** [comment]
For the record: Article explaining the issue with forward declarations in vectors with c++20: https://www.lukas-barth.net/blog/cpp20-vector-incomplete/

**Pull request merged**
