### PR TITLE
Bump Configuration to v2.5.0

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Review by kostorr — APPROVED** [review]

**Comment by awegrzyn** [comment]
@ktf Do you really need this test? Apparently file content clashes with what I define in Configuration test.

**Comment by ktf** [comment]
I think the error is real. It means that the changes do not override the defaults in macOS.

**Comment by ktf** [comment]
The error was indeed real and an actual difference in boost behaviour between linux and macOS. I fixed it in AliceO2. Triggering rebuild.

**Comment by awegrzyn** [comment]
@costing `ccdb-test` server is down, could you please disable `CCDB/test/testCcdbApi.cxx` test?

**Comment by awegrzyn** [comment]
Waiting for https://github.com/AliceO2Group/AliceO2/pull/4699

**Comment by ktf** [comment]
@TimoWilken this is still pending...

**Comment by TimoWilken** [comment]
@ktf It's still doing #2570 (building O2 right now), this one is next. The PR showing queue position went through after the worker restarted I think, so it doesn't have that feature yet

**Comment by ktf** [comment]
ah, yes, you are right. My bad, actually.

**Comment by awegrzyn** [comment]
@ktf @TimoWilken Any idea how can I fix macOS worker? The PR in AliceO2 was merged hours ago, I restarted the worker using GH action few times but it still picks up old version.

**Comment by ktf** [comment]
have you rebased?

**Comment by awegrzyn** [comment]
is a rebase needed? dont' we pick up dev of AliceO2?

**Comment by ktf** [comment]
That's what I would have expected.

**Comment by ktf** [comment]
Actually I think something is wrong serverside:

```bash
→ curl https://ccdb-test.cern.ch:8080/qc/TST_KEEP/task/to_be_kept/1761624421889/qc_version\=0.24.0/
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
→ which curl
/usr/bin/curl
```

@costing did you update the server yesterday? It seems to be incompatible with the SSL library shipped on macs...

**Comment by ktf** [comment]
Tested locally. Merging this.

**Pull request merged**
