### PR TITLE
Bump FairMQ to v1.4.24

### PR DESCRIPTION
**Pull request by pzhristov**

### CODE REVIEW

**Comment by ktf** [comment]
Looks like a genuine error:

```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.4.24/v1.4.24/fairmq/ofi/Socket.cxx: In member function 'virtual int64_t fair::mq::ofi::Socket::Send(std::vector<std::unique_ptr<FairMQMessage> >&, int)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.4.24/v1.4.24/fairmq/ofi/Socket.cxx:287:28: error: cannot convert 'fair::mq::TransferResult' to 'int64_t {aka long int}' in return
     return TransferResult::error;
                            ^~~~~
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.4.24/v1.4.24/fairmq/ofi/Socket.cxx: In member function 'virtual int fair::mq::ofi::Socket::Receive(fair::mq::MessagePtr&, int)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.4.24/v1.4.24/fairmq/ofi/Socket.cxx:434:28: error: cannot convert 'fair::mq::TransferResult' to 'int' in return
     return TransferResult::error;
                            ^~~~~
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.4.24/v1.4.24/fairmq/ofi/Socket.cxx: In member function 'virtual int64_t fair::mq::ofi::Socket::Receive(std::vector<std::unique_ptr<FairMQMessage> >&, int)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.4.24/v1.4.24/fairmq/ofi/Socket.cxx:459:28: error: cannot convert 'fair::mq::TransferResult' to 'int64_t {aka long int}' in return
     return TransferResult::error;
                            ^~~~~
```

**Comment by ktf** [comment]
@rbx @dennisklein

**Comment by rbx** [comment]
Fixed in v1.4.25.

**Comment by pzhristov** [comment]
I will push one more commit bumping to v1.4.25.

**Pull request merged**
