### PR TITLE
Bump qualitycontrol to v1.7.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by graduta — APPROVED** [review]

**Comment by ktf** [comment]
@Barthelemy looks like the `struct {` issue is still there.

**Comment by Barthelemy** [comment]
@ktf but why do I not see these errors in the QC PRs ?

**Comment by Barthelemy** [comment]
@ktf forget it, of course I cannot see them because the mac builders are broken....

**Comment by ktf** [comment]
As far as I case see, they are also in the PR checker:

https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/QualityControl/577/4901cbf25e89ed382ea87069dee1fb518b41f9b3/build_QualityControl_o2-dataflow_macOS/pretty.html

**Comment by Barthelemy** [comment]
a new patch version will be needed.

**Pull request closed without merging**
