### PR TITLE
Fix debian 8

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@miranov25 can you try with this? It should fix the autotools issue.

**Comment by miranov25** [comment]
### Starting tests with fix (/tmp/miranov/alicesw5Test2) and using local auotuools (tmp/miranov/alicesw5) as a reference build

* patched version 
```
==> The following packages will be built by aliBuild because they couldn't be picked up from the system:
    - SWIG
    - autotools
 ```   
Expected results in 30 minutes

**Comment by miranov25** [comment]
Build  failed after ROOT compilation in JAliEn-ROOT-latest
/tmp/miranov/alicesw5Test2/sw/BUILD/JAliEn-ROOT-latest/JAliEn-ROOT
```
DEBUG:AliPhysics:JAliEn-ROOT:0: [  4%] Generating G__JAliEnROOT.cxx, G__JAliEnROOT.h
DEBUG:AliPhysics:JAliEn-ROOT:0: #error "You need a ISO C conforming compiler to use the glibc headers"
DEBUG:AliPhysics:JAliEn-ROOT:0: Error: Missing one of '
DEBUG:AliPhysics:JAliEn-ROOT:0: ^M\/' expected at or after line 97.
DEBUG:AliPhysics:JAliEn-ROOT:0: Error: Unexpected end of file (G__fgetstream():2) /usr/include/sys/cdefs.h:419:
DEBUG:AliPhysics:JAliEn-ROOT:0: Error: Symbol extern"C"{#define __need_size_t#define __need_NULL#include<stddef is not defined in current scope  /usr/include/stdio.h:44:
DEBUG:AliPhysics:JAliEn-ROOT:0: Error: Failed to evaluate extern"C"{#define __need_size_t#define __need_NULL#include<stddef.h>#include<bits/types
DEBUG:AliPhysics:JAliEn-ROOT:0: Error: Failed to evaluate extern"C"{#define __need_size_t#define __need_NULL#include<stddef.h>#include<bits/types.h>#define __need_FILE#define __need___FILE#end
if#if!defined __FILE_defined&&defined __need_FILE struct _IO_FILE
DEBUG:AliPhysics:JAliEn-ROOT:0: Error: Symbol __BEGIN_NAMESPACE_STD typedef struct _IO_FILE FILE is not defined in current scope  /usr/include/stdio.h:48:
```


There are 22 commits between my working version (which I use now)   and current version
 git log 0c81b8d615a862af08aa859c51bd8307a6bc5d88..origin/master

I will return back to that commit

**Comment by ktf** [comment]
Mmm... This is unrelated to autotools. Did that work?

**Comment by ktf** [comment]
@Atlantic777 does it ring any bell?

**Comment by miranov25** [comment]
@ktf 
autotools were compiled without problems - looks like your fix was sucessfull
I will revert changes to last commits which  i have in my working AliRoot https://github.com/alisw/alidist/commit/0c81b8d615a862af08aa859c51bd8307a6bc5d88

**Comment by Atlantic777** [comment]
> @Atlantic777 does it ring any bell?

Not really... How to reproduce it? Debian 8, ROOT6, JAliEn-ROOT, --defaults next-root6?

**Comment by ktf** [comment]
macOS broken again in CCDB. @Barthelemy could you have a look next monday? Merging since the rest seems to work fine.

**Comment by miranov25** [comment]
> > @Atlantic777 does it ring any bell?
> 
> @ktf @miranov25 Not really... How to reproduce it? Debian 8, ROOT6, JAliEn-ROOT, --defaults next-root6?

* build command:
```
aliBuild build AliPhysics -a ubuntu1604_x86-64 --debug  --disable DPMJET
```
* System:
```
 lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

uname -a 
Linux lxbk0200 3.16.0-10-amd64 #1 SMP Debian 3.16.81-1 (2020-01-17) x86_64 GNU/Linux

```

**Comment by miranov25** [comment]
@Atlantic777  and @ktf 
I rebuild AliPhsycs from scratch using current origin/master.
```
git describe       
fatal: No annotated tags can describe 'a805dc2fa47c719816df6dcf7e105fc9e616d12b'.
``` 
For AliRoot+ROOT5 compilation  finished successfully. Problem which I reported yesterday (https://github.com/alisw/alidist/pull/2226#issuecomment-621968739) could be related to the fact that I used @ktf branch not master

```
aliBuild build AliPhysics -a ubuntu1604_x86-64 --debug  --disable DPMJET
```

**Comment by preghenella** [comment]
Hello @ktf ,
something is apparently broken while building on CC7.
I traced it to this commit since it seems to me the only one relevant for the issue I observe.

Until bcaea8e314c0eb762ebd436d9a8bbbcdd50158f7 all was fine.
I cat try to dig more into which is the actual commit that is causing the problem.
The problem is observed after installation of `Clang`, that fails in the final test with the following symptoms

```
++ rm /home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/lib/cmake/clang/ClangTargets-release.cmake.bak
++ cat
++ /home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/bin-safe/clang++ -v -c test.cc
clang version 9.0.0 (/home/flp/o2/sw/SOURCES/Clang/v9.0.0/llvmorg-9.0.0/clang 0399d5a9682b3cef71c653373e38890c63c4c365)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/bin-safe
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 "/home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/bin-safe/clang-9" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cc -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /home/flp/o2/sw/BUILD/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/Clang/test.gcno -resource-dir /home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/lib/clang/9.0.0 -isysroot /usr -internal-isystem /usr/usr/local/include -internal-isystem /home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/lib/clang/9.0.0/include -internal-externc-isystem /usr/include -internal-externc-isystem /usr/usr/include -fdeprecated-macro -fdebug-compilation-dir /home/flp/o2/sw/BUILD/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/Clang -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -faddrsig -o test.o -x c++ test.cc
clang -cc1 version 9.0.0 based upon LLVM 9.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/usr/usr/local/include"
ignoring nonexistent directory "/usr/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/flp/o2/sw/INSTALLROOT/50d7838577a2ec12e9a177ff1f5d0cbbe1b9fdca/slc7_x86-64/Clang/v9.0.0-1/lib/clang/9.0.0/include
 /usr/include
End of search list.
test.cc:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
```

I can provide a full log if needed.
Roberto

**Comment by Barthelemy** [comment]
@ktf Random failure it seems. I am preparing a new release to disable this specific test to avoid problems in the near future.

**Pull request merged**
