### PR TITLE
Make sure Python-modules are installed in the proper place

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy @awegrzyn I am not sure if this was always broken or if some recent changes in pip broke the behaviour, but this should hopefully fix your python woes.

**Comment by Barthelemy** [comment]
thank you

**Comment by Barthelemy** [comment]
Could we merge this ?

**Comment by ktf** [comment]
Yes. I was waiting for the tests.

**Pull request merged**
