### PR TITLE
Bump Monitoring to v3.0.6

### PR DESCRIPTION
**Pull request by awegrzyn**
This fixes compatibility issue with StdOut backend.

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy testDbFactory failed. Is this expected?

**Comment by Barthelemy** [comment]
@ktf no, but what are those things ? 
```
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libRIO, output: $ROOT_DYN_PATH/libRIO
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libCling, output: $ROOT_DYN_PATH/libCling
```

**Comment by Barthelemy** [comment]
@awegrzyn isn't it the problem you saw with qcg ?

**Comment by Barthelemy** [comment]
@ktf I have the feeling that there is something wrong with the CCDB. There was an update this morning I think. @costing could you confirm ? 
The CCDB clean up script stopped working at about 7:15 this morning as well. 
I am trying to understand what is going on.

**Comment by Barthelemy** [comment]
https://github.com/AliceO2Group/QualityControl/pull/377

**Comment by awegrzyn** [comment]
Ok in meanwhile I added a change required for ROC tools

**Comment by awegrzyn** [comment]
@ktf @MichaelLettrich macOS build failed on O2 tests, there are no more `dataflow` nor `C8` builds?

**Comment by ktf** [comment]
@awegrzyn For centos8, I was modifying something last night. Most likely it did not work as expected.

**Comment by awegrzyn** [comment]
Okay, I need this to progress with some tasks for QC, what can I do to have it merge ASAP?

**Pull request merged**
