### PR TITLE
Adding dask modules to python-module-list

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Needed as build requirement for ROOT's distributed RDataFrame (successor of PROOF-on-demand)

**Comment by mfasDa** [comment]
CI error unrelated

**Comment by TimoWilken** [comment]
I've restarted the last red CI check, since that was fixed in O2 in the meantime.

Is it necessary to specify the three `dask[*]` packages on separate lines, or can you combine them like `dask[array,dataframe,distributed]`? Do you expect to have different versions of each item in future?

Apart from that, looks good to me; I'd be fine with merging once CI is green.

**Comment by mfasDa** [comment]
@TimoWilken @ktf Any chance this can get merged?

**Comment by mfasDa** [comment]
> I've restarted the last red CI check, since that was fixed in O2 in the meantime.
> 
> Is it necessary to specify the three `dask[*]` packages on separate lines, or can you combine them like `dask[array,dataframe,distributed]`? Do you expect to have different versions of each item in future?
> 
> Apart from that, looks good to me; I'd be fine with merging once CI is green.

@TimoWilken Thanks for the suggestion. In the most likely case different version for the different parts of dask will create incompatibilities internally, so obviously we need one version for all. I have changed the PR as you suggested. This can however not include dask-jobqueue, because it is a separate package.

Once the CI is green, can you please then merge the PR?

**Comment by TimoWilken** [comment]
Thanks @mfasDa! I've integrated this into #5343 as commit https://github.com/TimoWilken/alidist/commit/d5e82aca4ef8159a2bffea2a71240af7f1278fd0, since I'm about to merge that one and it restructured the module list such that an auto-merge wouldn't work.

**Pull request closed without merging**
