### PR TITLE
Bump qualitycontrol to v0.26

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by ktf** [comment]
@MichaelLettrich could you investigate the macOS issue? On linux I see a bunch of repositories being half cloned in the sandbox. Removing them did the trick. Not sure what caused it. Investigating but not immediately.

**Comment by MichaelLettrich** [comment]
@ktf should be back in business again. I will keep an eye on it.

**Comment by ktf** [comment]
Ok, thanks. I am taking care of the other ones.

@maireiphc does the generators one ring any bell??

**Comment by maireiphc** [comment]
Hello @ktf,

  on the generator side, I do not see something special as far as I can judge. When the qualitycontrol should be invoked ? build time (successful build today) ? execution time (not tested locally / usage of CVFMS, AliGenerators not deployed) ?

**Comment by Barthelemy** [comment]
@maireiphc The QC should not be invoked in the generator as far as I know. It seems to be something else : 
```
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.h:1065:0,
                 from ../include/Herwig/Utilities/Interpolator.tcc:16,
                 from ../include/Herwig/Utilities/Interpolator.h:215,
                 from ../include/Herwig/PDT/GenericWidthGenerator.h:20,
                 from ../include/Herwig/Decay/DecayPhaseSpaceMode.h:17,
                 from VectorMeson/a1ThreePionCLEODecayer.h:15,
                 from ./a1ThreePionCLEODecayer.cc:14:
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.tcc: In instantiation of 'void ThePEG::ParVectorTBase<Type>::setImpl(ThePEG::InterfacedBase&, std::__cxx11::string, int, ThePEG::StandardT) const [with Type = bool; std::__cxx11::string = std::__cxx11::basic_string<char>; ThePEG::StandardT = ThePEG::Int2Type<1>]':
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.tcc:83:10:   required from 'void ThePEG::ParVectorTBase<Type>::set(ThePEG::InterfacedBase&, std::__cxx11::string, int) const [with Type = bool; std::__cxx11::string = std::__cxx11::basic_string<char>]'
./OniumToOniumPiPiDecayer.cc:461:1:   required from here
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.tcc:61:19: warning: '*' in boolean context, suggest '&&' instead [-Wint-in-bool-context]
     tset(i, Type(t*unit()), place);
                  ~^~~~~~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.tcc: In instantiation of 'void ThePEG::ParVectorTBase<Type>::insertImpl(ThePEG::InterfacedBase&, std::__cxx11::string, int, ThePEG::StandardT) const [with Type = bool; std::__cxx11::string = std::__cxx11::basic_string<char>; ThePEG::StandardT = ThePEG::Int2Type<1>]':
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.tcc:116:13:   required from 'void ThePEG::ParVectorTBase<Type>::insert(ThePEG::InterfacedBase&, std::__cxx11::string, int) const [with Type = bool; std::__cxx11::string = std::__cxx11::basic_string<char>]'
./OniumToOniumPiPiDecayer.cc:461:1:   required from here
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ThePEG/v2.1.2-1/include/ThePEG/Interface/ParVector.tcc:94:22: warning: '*' in boolean context, suggest '&&' instead [-Wint-in-bool-context]
     tinsert(i, Type(t*unit()), place);
                     ~^~~~~~~
  CXX      Perturbative/HwPerturbativeDecay_la-Perturbative__all.lo
  CXX      Perturbative/HwPerturbativeHiggsDecay_la-PerturbativeHiggs__all.lo
  CXXLD    HwWeakCurrents.la
  CXX      ScalarMeson/HwSMDecay_la-SMDecayer__all.lo
```

**Pull request merged**
