### PR TITLE
Monitoring: Enforce no warnings and run tests in CI

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@sy-c Could you take a look what's happening in the Readout? macOS build fails with `ld: library not found for -lnuma`

**Comment by sy-c** [comment]
I'm pretty sure this is fixed with the latest readout version. Is there a way to check the readout git commit hash used for this build? I suspect it's not using the good one.

**Comment by dberzano** [comment]
From the fifth line of the log, the version is Readout v0.19.1. The hash is what corresponds to that git tag, meaning [this](https://github.com/AliceO2Group/Readout/tree/v0.19.1).

**Comment by sy-c** [comment]
There was a hickup in the procedure to release this readout version, it was at some point re-tagged. That's why I want to check the hash used for the build and not the tag version.

**Comment by dberzano** [comment]
That's what I suspected. Unfortunately we don't support retag (the issue popped up already a couple of times in the past), the only course of action is to produce a new tag instead and update the recipe properly.

**Comment by sy-c** [comment]
ok, I have pushed a fresh v0.19.2 tag for readout https://github.com/alisw/alidist/pull/1555
(code is unchanged)

**Pull request merged**
