### PR TITLE
Compile ROOT with FFTW3

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@martenole

**Comment by davidrohr** [comment]
If this is the problem, why did it work on Ole's laptop?

**Comment by ktf** [comment]
I guess ROOT picks up fftw3 from the system and uses that.

**Comment by martenole** [comment]
because I have fftw3 installed and by default root picks up the system one

**Comment by martenole** [comment]
Here is a small reproducer which works on my laptop, but throws an error message on the EPNs:
```
auto fConv = std::make_unique<TF1Convolution>("[3] * TMath::Landau(x, [0], [1]) * exp(-[2]*x)", "TMath::Gaus(x, 0, [0])", 0., 320, true);
fConv->SetNofPointsFFT(2000);
auto fFit = std::make_unique<TF1>("fitConvLandau", *fConv, 0., 320, fConv->GetNpar());
auto hist = std::make_unique<TH1F>("h", "", 320, 0, 320)
auto fitStatus = hist->Fit("fitConvLandau", "LQB", "", 1, 320-4)

```

**Review by martenole — APPROVED** [review]
Working on the EPNs, thanks a lot!

**Pull request merged**
