### PR TITLE
[WIP] Add explicit Common dependency to O2

### PR DESCRIPTION
**Pull request by sy-c**
libInfoLogger depends on Common-O2
need to define variable for cmake find path

### CODE REVIEW

**Comment by dberzano** [comment]
Thanks for referencing the O2 PR! It clarifies.

**Comment by sy-c** [comment]
some discussion is going on about dependencies... I wait for a conclusion before merging this PR

**Comment by dberzano** [comment]
Hi @sy-c, can you pull-rebase from the master and force-push please?

```
git pull --rebase origin master
git push -f
```

Thanks!

**Comment by sy-c** [comment]
sorry, I really screwed up ...
my alidist fork was in bad shape and I just deleted it to start clean, but I forgot I had this PR still open...

I propose to just drop / close this PR for the time being - I'm not the owner any more.
It's a simple change and I have the diff, I'll start a fresh PR later.

I'm pretty sure it's an interesting dummy use case  you probably never got in the PR workflow so far :)

**Comment by sy-c** [comment]
fork repo does not exist any more

**Comment by Barthelemy** [comment]
" alisw:master from unknown repository" 😆  well played, Sylvain, well played...

**Pull request closed without merging**
