### PR TITLE
Implement the proposal for the "stream" based releases

### PR DESCRIPTION
**Pull request by ktf**
Proposal description at:

https://github.com/alisw/alidist/pull/2757

### CODE REVIEW

**Comment by ktf** [comment]
A better way of implementing this would be to use the soon (aliBuild 1.7.2) to be introduce `%(branch_stream)s` expansion. Closing this for now.

**Comment by davidrohr** [comment]
@ktf : Just for my understanding: how will branch_stream work? Will you have to set version to `%(branch_stream)s`? Or will the presence of a branch_stream tag != "" in the default already fix all versions to the same stream? I'd prefer something along the latter, since if we have to set all the versions, there is a chance we miss one package, e.g. when we add new packages.

**Comment by ktf** [comment]
http://alisw.github.io/alibuild/reference.html describes the behavior. It gets activated only when building from the `-patches` branch in alidist and otherwise falls back to what specified in `tag:`.

**Comment by davidrohr** [comment]
ok, thx, I see. But then still, if someone would add a package with some explicit version / change a version, RPMs would be created with the incorrect version? Wouldn't it be simpler if we could just hard-override all version fields for all packages in the defaults? Then we'd need to change one line in the default, and all versions would be aligned, without room for mistakes?

**Comment by ktf** [comment]
We could simply have "%(branch_stream)s" always the default for `version`, and drop `version` everywhere. That way people will have to actively add it if they do not want this behavior, which might be useful for things like built time only packages.

**Comment by davidrohr** [comment]
But then I don't understand what is the advantage? Doesn't that mean the version field becomes kind of obsolete, but if someone uses it accidentally, it will yield incorrect RPM versions. I mean, it is up to you, but in my opinion just overriding the version is still simpler and safer :)

**Comment by ktf** [comment]
The advantage would be that one does not need the extra commit. Anyways we can still discuss this, what is not clear to me is wether there is interest in the proposal or not.

**Pull request closed without merging**
