### PR TITLE
Move to Apache Arrow 4.0.1

### PR DESCRIPTION
**Pull request by aalkin**

### CODE REVIEW

**Review by pzhristov — DISMISSED** [review]

**Comment by pzhristov** [comment]
THe protobuf issue we see in the builds is not related to this PR. I propose to merge.

**Comment by pzhristov** [comment]
We need this also on Mac mini M1.

**Comment by aalkin** [comment]
> THe protobuf issue we see in the builds is not related to this PR. I propose to merge.

There is also some other issue with duplicated arrow targets

**Comment by pzhristov** [comment]
Ok, let me check with a local clone of arrow.

**Comment by aalkin** [comment]
I cannot reproduce this issue locally neither on mac or linux. @ktf do you have any suggestions?

**Comment by aalkin** [comment]
Apparently there is now `find_dependency(Arrow)` in arrow's `GandivaConfig.cmake`, but when it is called, `arrow_shared` target already exists because of our own `FindO2arrow.cmake`. With my local cmake v3.20 it does not cause any issue, however.

**Comment by pzhristov** [comment]
As far as I can see, the issue is on the Mac builders with

CMake Error at /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/FindArrow.cmake:174 (add_library):
  add_library cannot create imported target "arrow_shared" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/FindArrow.cmake:317 (arrow_find_package_home)
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/FindArrow.cmake:357 (arrow_find_package)
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/CMake/v3.19.2-1/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/GandivaConfig.cmake:54 (find_dependency)
  dependencies/FindO2arrow.cmake:18 (find_package)
  dependencies/O2Dependencies.cmake:39 (find_package)
  dependencies/CMakeLists.txt:12 (include)
--
CMake Error at /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/FindArrow.cmake:200 (add_library):
  add_library cannot create imported target "arrow_static" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/FindArrow.cmake:317 (arrow_find_package_home)
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/FindArrow.cmake:357 (arrow_find_package)
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/CMake/v3.19.2-1/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/arrow/v3.0.0-1/lib/cmake/arrow/GandivaConfig.cmake:54 (find_dependency)
  dependencies/FindO2arrow.cmake:18 (find_package)
  dependencies/O2Dependencies.cmake:39 (find_package)
  dependencies/CMakeLists.txt:12 (include)
--
CMake Error at /Volumes/build/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/CMake/v3.19.2-1/share/cmake-3.19/Modules/FeatureSummary.cmake:457 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  dependencies/O2Dependencies.cmake:164 (feature_summary)
  dependencies/CMakeLists.txt:12 (include)
  CMakeLists.txt:57 (include)

**Comment by pzhristov** [comment]
The reason why arrow causes problems is its dependency on liblz4-dev and libprotoc-dev, which is required in ArrowConfig.cmake. If we use CMake 3.19, somehow this is not treated correctly. I installed both packages with apt and the compilation worked. We may have issues later with the alidist version of protobuf, so the next step is to introduce dependency of arrow on alidist protobuf and make sure protoc is compiled.

**Comment by aalkin** [comment]
Our arrow recipe already has dependencies on lz4 and protobuf, I think. Does alidist protobuf provide `libprotobuf-lite` target?

**Comment by pzhristov** [comment]
Our arrow indeed depends on protobuf and lz4, but for some reason this is not enough. I tried to force the compilation of protoc in protobuf (this was not enough), and also I do not see how to have the equivalent of liblz4-dev in our lz4.

**Comment by pzhristov** [comment]
As expected, we have issues in gandiva, probably because of the mismatch in protoc. The test fails with

/home/phristov/alisw/sw/SOURCES/O2/dev/0/Framework/Core/test/test_Expressions.cxx(202): fatal error: in "TestGandivaTreeCreation": critical check s.ok() has failed

*** 1 failure is detected in the test module "Test Framework Expressions"

**Comment by pzhristov** [comment]
I disabled protobuf in favor of the (older) version from the system, but the test is still failing on Ubuntu 18.04.

**Comment by pzhristov** [comment]
@aalkin Unfortunately the problem  with test_Framework_test_Expressions is present also on Mac, so more investigations are needed.

**Comment by aalkin** [comment]
@ktf should I trigger re-testing of this PR, since protobuf bump was merged?

**Comment by pzhristov** [comment]
The problem with the new version of Arrow is that its CMake modules redefine the CMAKE_MODULE_PATH and then the configuration of O2 breaks. This certainly happens on Mac Big Sur and Ubuntu 20.04 with CMake 3.20.3. I am testing a patch for o2.sh and O2/dependencies/FindO2arrow.cmake, but the real fix probably has to be done in Arrow.

**Comment by pzhristov** [comment]
This PR should be tested again as soon as https://github.com/alisw/alidist/pull/3088 and https://github.com/AliceO2Group/AliceO2/pull/6391 are merged.

**Comment by pzhristov** [comment]
The simple "solution" is to remove the protobuf dependency in  O2. It is not needed. The corresponding PR https://github.com/AliceO2Group/AliceO2/pull/6437 is merged.

**Comment by pzhristov** [comment]
Now the Control-OCCPlugin build suffers from the same protobuf problem in the O2/alidist-dataflow check. Since protobuf is used extensively in the package, we have to fix the source of the issue.

**Comment by ktf** [comment]
@aalkin @pzhristov I updated the arrow repository with alice/apache-arrow-4.0.1, cherry picking our changes is not so easy, though...

**Comment by aalkin** [comment]
@ktf I've ported our changes. They've (finally!) added trigonometric functions, so I will have to do some cleanups and rearrange the code, but I've got it merged and compiled locally. Meanwhile we can try bumping this PR up to 4.0.1 and see if that clears CMake issue.

**Comment by pzhristov** [comment]
@aalkin Should I wait for your changes before I start the CMake tests?

**Comment by aalkin** [comment]
@pzhristov my changes should only matter in runtime for analysis tasks, so I think we can start testing CMake as is. And we will simply update alice-4.0.1 branch later.

**Comment by ktf** [comment]
@TimoWilken there is a aliDoctor error on the mac builds. Could you take a look?

**Comment by TimoWilken** [comment]
The following change seems to solve the protobuf conflict, but now arrow wants openssl >= 1.1, while we only have 1.0. Should I add an alidist recipe for that as well, or would it be enough to install `openssl11-devel` (or equivalent) everywhere?

```patch
diff --git a/arrow.sh b/arrow.sh
index bce7aa2..7782636 100644
--- a/arrow.sh
+++ b/arrow.sh
@@ -88,6 +88,7 @@ cmake ./src_tmp/cpp
       ${PROTOBUF_ROOT:+-DProtobuf_PROTOC_LIBRARY=$PROTOBUF_ROOT/lib/libprotoc.$SONAME}              \
       ${PROTOBUF_ROOT:+-DProtobuf_INCLUDE_DIR=$PROTOBUF_ROOT/include}                               \
       ${PROTOBUF_ROOT:+-DProtobuf_PROTOC_EXECUTABLE=$PROTOBUF_ROOT/bin/protoc}                      \
+      ${PROTOBUF_ROOT:+-DARROW_PROTOBUF_USE_SHARED=ON}                                              \
       ${BOOST_ROOT:+-DBoost_ROOT=$BOOST_ROOT}                                                       \
       ${LZ4_ROOT:+-DLZ4_ROOT=${LZ4_ROOT}}                                                           \
       -DARROW_WITH_UTF8PROC=OFF                                                                     \
```

**Comment by pzhristov** [comment]
@TimoWilken We probably can bump the openssl version to 1.1 and check if the jalien/xrootd packages still compile

**Comment by davidrohr** [comment]
> @TimoWilken We probably can bump the openssl version to 1.1.1k and check if the jalien/xrootd packages still compile/work

I am absolutely in favor of bumping OpenSSL, but my last attempt here failed in many places: #2760

**Comment by pzhristov** [comment]
> > @TimoWilken We probably can bump the openssl version to 1.1.1k and check if the jalien/xrootd packages still compile/work
> 
> I am absolutely in favor of bumping OpenSSL, but my last attempt here failed in many places: #2760

Yes, I saw the first issue in xjalienfs, so apparently the bump needs additional changes in the packages.

**Comment by pzhristov** [comment]
@TimoWilken Unfortunately the proposed additional line breaks the compilation of Root, when the arrow-dependent part is processed (MacOS BigSur). I think we should find another solution.

**Comment by pzhristov** [comment]
Replaced by https://github.com/alisw/alidist/pull/3230

**Pull request closed without merging**
