### PR TITLE
Drop asiofi / asio from FairMQ

### PR DESCRIPTION
**Pull request by ktf**
They are now deprecated and will be removed in 1.5.0.

### CODE REVIEW

**Comment by TimoWilken** [comment]
Is it worth removing the asiofi and asio recipes from alidist entirely, since they won't be tested by CI after this change and will presumably just become stale? They don't seem to be used by anything other than FairMQ.

**Comment by davidrohr** [comment]
I think so, and also libfabric should be removed.
I asked 2 weeks ago (on 16th), and said we'd remove it in 2 weeks since noone complains. So I think we cann remove the 3 now.

**Comment by dennisklein** [comment]
> Is it worth removing the asiofi and asio recipes from alidist entirely, since they won't be tested by CI after this change and will presumably just become stale? They don't seem to be used by anything other than FairMQ.

From my point of view, they can go away, perhaps also `ofi.sh`. Originally, they were all introduced by me, but I have not tracked if anybody else started to depend on them.

**Comment by ktf** [comment]
No objections to dropping the recipes completely, but let's do that in a separate PR, since this one is already undergoing testing....

**Pull request merged**
