### PR TITLE
bump readout

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
This PR was opened 6 hours ago and there is still no progress for many tests. Is this normal ?

**Comment by sy-c** [comment]
Update: the maxS test has just completed with error, but it seems unrelated to the PR.
build/AliRoot/alidist build/O2/alidist build/O2/alidist-dataflow build/O2/fullCI/alidist

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
can you please merge this PR ?
the mac OS fail does not seem related.

**Comment by sy-c** [comment]
@davidrohr thank you !

**Pull request merged**
