### PR TITLE
Bump boost to v1.82.0

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Needed to work with the updated XCode.

**Comment by TimoWilken** [comment]
Hi @ktf, from the log, it looks like it's running out of space in `/dev/shm`, i.e. running out of memory!

The machine seems to have enough disk space available (the 1TB disk is half empty).

**Comment by ktf** [comment]
You are right. @dennisklein @rbx is there any known issue in using boost 1.83.0 with FairMQ?

**Comment by rbx** [comment]
Nothing known. But we also don't have a test environment with 1.83 afaik.

**Comment by davidrohr** [comment]
I have been using boost 1.82 for few weeks now on my laptop without problems.
Haven't tried 1.83 yet.

**Comment by ktf** [comment]
Let's try to use 1.82, then...

**Comment by ktf** [comment]
Still broken. I need to check in details.

**Comment by davidrohr** [comment]
OK, meanwhile I tried 1.83 locally, and that also works for me.
But I am also not running multiple workflows in parallel.

**Pull request closed without merging**
