### PR TITLE
fairlogger: bump to 1.6.2

### PR DESCRIPTION
**Pull request by ktf**
Now depends on fmt

### CODE REVIEW

**Comment by ktf** [comment]
@teo this fails on mac because of:

```
-- Configuring done
CMake Error at CMakeLists.txt:404 (add_library):
  Target "FairMQPlugin_OCC" links to target "fmt::fmt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

this now comes from FairLogger. Any idea on how to fix it?

**Comment by teo** [comment]
No idea except adding the relevant `find_package` to OCC I'm guessing.

**Comment by ktf** [comment]
@rbx @dennisklein could it be that you are not correctly exporting the `fmt::fmt` target?

**Comment by dennisklein** [comment]
> No idea except adding the relevant `find_package` to OCC I'm guessing.

> @rbx @dennisklein could it be that you are not correctly exporting the fmt::fmt target?

See https://github.com/FairRootGroup/FairLogger#usage. Basically, we do intentionally not call `find_package(fmt)` in our CMake package because the user might have a direct dependency on fmt himself and might want to add stronger/different criteria to the `find_package` call.

**Comment by teo** [comment]
I've added the `find_package` in `Control-OCCPlugin`, should be sorted out with https://github.com/alisw/alidist/pull/2247

**Comment by ktf** [comment]
@sy-c it looks like you have the same issue in readout. Can you do the same fix?

**Pull request closed without merging**
