### PR TITLE
Bump AliTPCCommon to alitpccommon-v1.4.5

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by dberzano** [comment]
OK let's announce it properly before merging 🙂

**Comment by dberzano** [comment]
See [ALIROOT-8007](https://alice.its.cern.ch/jira/browse/ALIROOT-8007).

**Comment by davidrohr** [comment]
No need to approve this right now, I'll need to create a new tag for c++17 (see alisw/alidist#1293)

**Comment by davidrohr** [comment]
@dberzano : Updated PR to contain required fixes for C++17. Can be merged as soon as the tests have passed. This is unrelated to changes in AliRoot, so no need to synchronize the merging with an AliRoot release.

**Comment by davidrohr** [comment]
Hi @dberzano : Can we merge this PR soon? I have an O2 PR which requires this.

**Comment by dberzano** [comment]
Yes, definitely! Give me a sec.

**Pull request merged**
