### PR TITLE
Introduce LLA

### PR DESCRIPTION
**Pull request by kostorr**

### CODE REVIEW

**Comment by kostorr** [comment]
@ktf is the generators error legit?

**Review by Barthelemy — APPROVED** [review]

**Comment by ktf** [comment]
No, it's not. @preghenella is this the usual problem with caching the wrong build path for dependencies?

@Barthelemy can you please review the bits in alidist which belong to FLP and update the CODEOWNERS file?

Thanks.

**Comment by Barthelemy** [comment]
@ktf I have reviewed the changes and I did not spot any obvious mistakes. I will update the CODEOWNERS file.

**Comment by ktf** [comment]
I meant that the issue it's unrelated and up to @preghenella & myself to sort it out.

**Pull request merged**
