### PR TITLE
alien-cas: preparations in order to get away from AliEN-Runtime

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Atlantic777 @costing We keep getting conflicts between packages used standalone by FLP and those embedded in AliEN runtime. Time to fix everything once for all and drop AliEN-runtime as a catchall solution for some common libraries.

**Comment by adriansev** [comment]
@ktf i noticed that the CAs from the cas repo are really old .. those should be updated, i will post an issue there as well

**Comment by ktf** [comment]
@adriansev fine with me. Please open a PR.

**Comment by adriansev** [comment]
> @adriansev fine with me. Please open a PR.

@ktf Please take a look at https://github.com/alisw/alien-cas/pull/7

**Comment by ktf** [comment]
Thanks. Remember to open a PR in alidist as well...

**Pull request merged**
