### PR TITLE
Update ofi to prevent issues with the new version on old platforms (O2-2752)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ironMann @davidrohr  @vascobarroso any objections to this? it looks like suddenly ofi does not compile anymore on different platforms (probably due to an update of libatomic on the system).

**Comment by Barthelemy** [comment]
O2-2752

**Review by davidrohr — APPROVED** [review]
sure, don't see a problem if it passes the FullCI

**Comment by awegrzyn** [comment]
On FLP production setups we use `libfabric` from CS8 (`1.14.0-1`) so this won't change anything for us.

**Comment by ktf** [comment]
Ok, then even better.

**Comment by ironMann** [comment]
cc @dennisklein

**Comment by ktf** [comment]
Do we actually use the libfabric we ship in alidist anywhere? Maybe we should just drop it, if no one is actually using it.

**Pull request merged**
