### PR TITLE
bump readout v0.25

### PR DESCRIPTION
**Pull request by sy-c**
see release notes: https://github.com/sy-c/Readout/blob/master/doc/releaseNotes.md

### CODE REVIEW

**Comment by sy-c** [comment]
@alisw/dataflow-experts 
anybody to push this PR ?

build/O2/alidist  fails with unrelated Error in <ACLiC>: Compilation failed!

**Comment by ktf** [comment]
On mac it actually fails linking with:

```
ld: unknown option: -soname=liblz4.so.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [liblz4.so.1.9.1] Error 1
make[2]: *** [lz4-prefix/src/lz4-stamp/lz4-build] Error 2
make[1]: *** [CMakeFiles/lz4.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Do you actually build lz4 yourself???

**Comment by sy-c** [comment]
yes, readout builds lz4
unfortunately I can't check what happens, alibuild does not work at the moment on the only mac server I have access to (it brakes in boost).

**Comment by ktf** [comment]
We do ship with a lzma package, any reason for not use that?

**Comment by sy-c** [comment]
This for real-time compression of the data. According to ITS, LZ4 is the fastest algorithm for their use case.

**Comment by ktf** [comment]
sorry, I meant lz4... My point is that we do have lz4 packaged up, IIRC....

**Comment by ktf** [comment]
https://github.com/alisw/alidist/blob/master/lz4.sh

**Comment by sy-c** [comment]
Indeed, very good point, I had not noticed lz4 was available.
recipe now make use of it with readout v0.25.1.
it should also fix the osx build.

**Comment by ktf** [comment]
Thanks! I will merge this once all tests are green.

**Comment by sy-c** [comment]
There's one failure but it does not seem related. macos build is ok.

**Pull request merged**
