### PR TITLE
Install xjalienfs correctly if running aliBuild inside venv

### PR DESCRIPTION
**Pull request by TimoWilken**
When we run aliBuild from a virtual environment, the old xjalienfs recipe installs xjalienfs inside that virtualenv, not inside its $INSTALLROOT where it should go. Fix that and force it to install inside $INSTALLROOT. We always add the $INSTALLROOT to our $PYTHONPATH anyway.

@ktf @adriansev Does this look alright to you?

I've tested this on slc7 when running aliBuild inside a virtualenv. In that case, alien.py is installed properly and I can run it without ImportErrors.

### CODE REVIEW

**Comment by TimoWilken** [comment]
Hm, that's a good point. The Python-modules recipe manually deactivates any venv it finds, but seems to do some special handling of `system-requirements.txt`. Not sure if anything actually uses that file.

For xjalienfs, I've got an issue with the CI system at the moment, where an update of xjalienfs messed up the CI's venv (outside of `sw/`), which I want to avoid.

**Comment by ktf** [comment]
This still fails no?

**Comment by TimoWilken** [comment]
Yes, because the current (alidist master) recipe affects the host venv, rather than anything inside `sw/`. So other builds running breaks the host, which makes this PR fail too. This PR doesn't *fix* the host's venv once it's broken, it just prevents it from getting broken if every build has this change.

**Comment by ktf** [comment]
As discussed, fine to merge then.

**Pull request merged**
