### PR TITLE
XRootD update to 5.5.2

### PR DESCRIPTION
**Pull request by adriansev**
[Release notes](https://github.com/xrootd/xrootd/blob/v5.5.2/docs/ReleaseNotes.txt)
Detailed commit list relative to 5.5.0 [here](https://github.com/xrootd/xrootd/compare/v5.5.0...v5.5.2)

### CODE REVIEW

**Comment by adriansev** [comment]
@ktf @TimoWilken Hi guys! Seems that the O2/macOS-arm error is unrelated (`error: unused variable 'gkEventFillMapWithCentRun2'` in O2Physics/PWGDQ/TableProducer/tableMakerMC.cxx:89)
Should/Need this be restarted?
Thanks a lot!

**Comment by davidrohr** [comment]
@shahor02 @sawenzel : There are errors from ITS digitizer:

```
digi.log-[31107:ITSDigitizer]: Error in <TFile::TFile>: file /sw/slc8_x86-64/O2/4802-slc8_x86-64-local1/share/Detectors/ITSMFT/data/AlpideResponseData/AlpideResponseData.root does not exist
digi.log-[31107:ITSDigitizer]: [09:06:55][FATAL] Cannot open response file $(O2_ROOT)/share/Detectors/ITSMFT/data/AlpideResponseData/AlpideResponseData.root
digi.log:[31107:ITSDigitizer]: [09:06:55][ERROR] Exception caught: Fatal error 
digi.log-[31107:ITSDigitizer]: Executable is /sw/slc8_x86-64/O2/4802-slc8_x86-64-local1/bin/o2-sim-digitizer-workflow
```

**Comment by sawenzel** [comment]
@mconcas: Any idea why the ALPIDE files might be missing?

**Comment by mconcas** [comment]
> 

This file should be generated during O2 compilation. 

> @mconcas: Any idea why the ALPIDE files might be missing?

@sawenzel: This file is generated during O2 compilation.
From the log, it looks like it was not, but also, it did not run from scratch so it might have skipped that part, even though the cause is not clear to me.

**Comment by TimoWilken** [comment]
Hi, the two spurious errors were caused by builders running out of disk space. I've fixed that and reset the checks (and the fullCI has already turned green).

**Comment by adriansev** [comment]
@TimoWilken 
there is still an unused variable error mac os arm (weird that is't ok on the others):
```
/System/Volumes/Data/build/alice-ci-workdir/alidist-o2/sw/SOURCES/O2Physics/4802/0/EventFiltering/PWGCF/CFFilterQA.cxx:95:18: error: unused variable 'nAllTriggers' [-Werror,-Wunused-const-variable]
static const int nAllTriggers = 6;
                 ^
1 error generated.
```
Can this be merged like this, or do we have to wait for the fix of compilation options on macos arm?
Thanks a lot!

**Comment by adriansev** [comment]
Hi @TimoWilken ! would this be ready to be merged? tests seems green now.. Thanks a lot!

**Review by TimoWilken — APPROVED** [review]

**Pull request merged**
