### PR TITLE
Bump FairMQ to v1.4.35

### PR DESCRIPTION
**Pull request by dennisklein**
and remove some obsolete options.

Continuation of #2949, but cannot push to @rbx's branch, so new PR.

### CODE REVIEW

**Comment by ktf** [comment]
@dennisklein still fails:

```
/mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/FairMQ/v1.4.35/v1.4.35/fairmq/shmem/Monitor.cxx:290: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/FairMQ/v1.4.35/v1.4.35/fairmq/shmem/Monitor.cxx:290: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
CMakeFiles/fairmq-shmmonitor.dir/shmem/Monitor.cxx.o:(.data.rel.local.DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE[DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE]+0x0): undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
collect2: error: ld returned 1 exit status
```

**Comment by dennisklein** [comment]
> @dennisklein still fails:
> 
> ```
> /mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/FairMQ/v1.4.35/v1.4.35/fairmq/shmem/Monitor.cxx:290: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
> /mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/FairMQ/v1.4.35/v1.4.35/fairmq/shmem/Monitor.cxx:290: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
> CMakeFiles/fairmq-shmmonitor.dir/shmem/Monitor.cxx.o:(.data.rel.local.DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE[DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE]+0x0): undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
> collect2: error: ld returned 1 exit status
> ```

Hmm, I need more info on your environment.

I took a docker centos7 container with epel repo enabled and `devtoolset-7` loaded (gcc 7 something), installed a bunch of system packages (`autotools`, `zip` libs and that kind of stuff), ran `aliBuild build --defaults o2 -u --always-prefer-system FairMQ` with today's master of alidist, and passes all the alibuild-built deps to FairMQ, and it configured, built and linked just fine:

```
--   DEPENDENCY FOUND     VERSION                   PREFIX
--   Boost                1.75.0 (>= 1.67)          /opt/sw/slc7_x86-64/boost/v1.75.0-1
--   DDS                  3.5.10 (>= 3.5.3)         /opt/sw/slc7_x86-64/DDS/latest
--   FairLogger           1.9.1 (>= 1.6.0)          /opt/sw/slc7_x86-64/FairLogger/latest
--   Flatbuffers          1.11.0                    /opt/sw/slc7_x86-64/flatbuffers/latest
--   ZeroMQ               4.3.3 (>= 4.1.4)          /opt/sw/slc7_x86-64/ZeroMQ/latest
--   fmt                  7.1.0 (>= 5.3.0)          /opt/sw/slc7_x86-64/fmt/latest
```

Is there any major difference to your environment?

**Comment by dennisklein** [comment]
ok, i see it is centos8 now ...

 https://github.com/CLIUtils/CLI11/issues/445 - looks like gcc 8 ships filesystem in a separate library...

**Comment by vascobarroso** [comment]
@ktf I was able to regenerate RPMs using this latest FairMQ tag (via `alidist@flp-suite-v0.17.0`), so I guess it works for `o2-dataflow` defaults. More details at https://alijenkins.cern.ch/job/BuildRPM/460/

**Comment by dennisklein** [comment]
This should fix it for centos8:

```diff
diff --git a/cmake/FairMQLib.cmake b/cmake/FairMQLib.cmake
index 2b2027d1..df4ea15a 100644
--- a/cmake/FairMQLib.cmake
+++ b/cmake/FairMQLib.cmake
@@ -205,7 +205,7 @@ macro(set_fairmq_defaults)
   endif()

   if(    CMAKE_CXX_COMPILER_ID STREQUAL "GNU"
-     AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 8)
+     AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9)
     set(FAIRMQ_HAS_STD_FILESYSTEM 0)
   else()
     set(FAIRMQ_HAS_STD_FILESYSTEM 1)
```
I will publish it on a special branch in a minute and update this PR to not stall progress here and we have to switch back to regular version numbers in a day or so.

But then the question, what about GCC 9? I have to set up proper CI builds with all major GCC version it seems ...

**Comment by ktf** [comment]
At least for now, we need to support GCC7 on cc7, c8 and ubuntu and GCC9 on cc8. At some point (hopefully soon) we will drop GCC7 and you will just have cc7, c8 on GCC9 to support. That said, I personally would simply avoid boost and use C POSIX for any filesystem related business.

**Comment by ktf** [comment]
@vascobarroso yes, cc7 works fine also here.

**Comment by dennisklein** [comment]
> @vascobarroso yes, cc7 works fine also here.

@ktf the cc8 build also looks fine now regarding FairMQ?

**Comment by ktf** [comment]
I restarted the test.

**Comment by ktf** [comment]
@TimoWilken I think there is something wrong with the AliRoot / AliPhysics tests...

**Pull request merged**
