### PR TITLE
Add missing fmt dependencies

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
fairlogger needs fmt for the formatting, and apparently they do not expose the dependency by design. I have asked what is the reasoning behind, let's see. But if they do not change it, we have to add it ourselves.

**Comment by ktf** [comment]
alibuild adds it. It's FairLogger cmake file which does not export it.

**Comment by davidrohr** [comment]
ah, it does, then I think we don't even need these changes here, except for the ones for fairlogger.sh for system fmt.

**Comment by ktf** [comment]
Since it's an explicit dependency, I would keep it.

**Pull request merged**
