### PR TITLE
Bump C++ standard to C++17

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jackal1-66 @maireiphc I need to bump the compilation standard for AliGenerators, since the new ROOT does not work anymore with C++14. Let me know if you have issues with it.

**Comment by maireiphc** [comment]
Helllo @ktf (cc @jackal1-66, @cholmcc ), I suspect some (older) generators may not comply out of the box with the std c++17.
This is to be tried though.

To that end, we may need to first try out the compilation outcome and running time of the pull request
https://github.com/alisw/alidist/pull/5171 = Update Rivet (and YODA) builds with an eye toward Rivet integration into O2 pipeline

Just to avoid to pile troubles on troubles.
Giulio, can you wait for our green light before moving further with this ?

**Comment by ktf** [comment]
Indeed, I merged it after I checked that the compilation actually works correctly.

**Comment by cholmcc** [comment]
Hi, 

Off-hand I would think most EGs work with C++17 if they work with C++14.  Most of the changes between the two (see [here](https://en.cppreference.com/w/cpp/17)) that _are_ incompatible are unlikely to be used by EG code.   In fact, most EGs, as is true of most Physics code, uses antiquated constructs and ideoms and are more likely to conform to C++98 than any more modern standard like C++14.  

Yours,
_Christian_

**Pull request merged**
