### PR TITLE
Add AGILe

### PR DESCRIPTION
**Pull request by qgp**
This provides an interface to obtain HepMC output from Pythia6. Becomes useful only after #470 has been merged.

### CODE REVIEW

**Comment by qgp** [comment]
@dberzano: rebased as discussed

**Comment by dberzano** [comment]
Hello @qgp, it looks to me that AGILe depends on autotools. Please add it as a build_requires and do rerun `autoreconf -ifv` before `./configure`. Also, Makefiles generated by autotools are known to cause problems if running `make install` in multicore, so drop the `-j` from the corresponding line. Thanks!

**Comment by qgp** [comment]
Hi @dberzano, thanks for the comments, updated accordingly.

**Comment by dberzano** [comment]
Thanks! Let's wait for the automatic test.

**Pull request merged**
