### PR TITLE
Synchronize ROOT 6 and O2 defaults

### PR DESCRIPTION
**Pull request by dberzano**
* ROOT 6 updated to the latest stable version (v6.08.00) for `root6`, `o2` and `o2-daq`

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf note that this requires an update to O2 to support the new DDS API...

**Comment by dberzano** [comment]
For the record it compiles on macOS Sierra with `--defaults o2 --disable DDS` (DDS 1.4 does not work yet for the reasons mentioned above).

**Comment by dberzano** [comment]
@matthiasrichter please try this one - note that this does not include any DDS update, so if you use a "too recent" version of FairRoot (which now should work with DDS v1.4) it should _not_ compile.

**Comment by dberzano** [comment]
I have changed the PR to get rid of what @matthiasrichter has already done in #581, and to include `o2-daq`. @ktf can we merge this?

**Comment by ktf** [comment]
I'd like to see `build/AliPhysics/root6` to succeed, first. ;-)

**Comment by dberzano** [comment]
Merged as AliPhysics builds with it. Uses ROOT 6, v6-08-02.

**Comment by dberzano** [comment]
For the record the problem's in AliPhysics and has to be fixed there.

**Comment by dberzano** [comment]
@ktf ...and I cannot reproduce it on my Ubuntu 16.04 for the record, where all libraries are loaded flawlessly.

**Comment by ktf** [comment]
Smells like some platform issue with fastjet, though.. We should try to keep it in mind.

**Pull request merged**
