### PR TITLE
Prevent LLVM double-link on linux with arrow 0.17

### PR DESCRIPTION
**Pull request by aalkin**
* Build only a single LLVM library in Clang
* Patch arrow linker version script to hide llvm symbols in gandiva.so

### CODE REVIEW

**Comment by aalkin** [comment]
@ktf this solves the issue with "LLVM ERROR: inconsistency in registered CommandLine options"
@davidrohr does this affect GPU stuff that uses Clang/LLVM?

**Comment by davidrohr** [comment]
It will not affect the GPU stuff, but it might affect the code checker @sawenzel .

**Comment by davidrohr** [comment]
The O2 codechecker CI seems broken, e.g. in AliceO2Group/AliceO2#3533. It fails with `Unable to run clang-tidy.` This could be related to this change. ping @ktf @sawenzel

**Comment by ktf** [comment]
When did the problem started to appear? Today? There is also https://github.com/alisw/alidist/pull/1842 which could be related and was merged yesterday (rather than 2 days ago).

**Comment by davidrohr** [comment]
Not sure, I saw it today for the first time, but that does of course not exclude that the problem was already there yesterday. But you are right, #1842 could be the cause as well.

**Comment by ktf** [comment]
It looks like it's indeed #1842. Reverting it brings back the tests to green. We should probably have some trivial test in o2codechecker.sh itself to make sure what is compiled actually runs.

**Pull request merged**
