### PR TITLE
alienpy 1.5.6 :: fix usage of exit command

### PR DESCRIPTION
**Pull request by adriansev**
Hi @TimoWilken ! Unfortunately a small annoyance escaped and it would be best to fix it :)
see the [commit log](https://github.com/adriansev/jalien_py/compare/1.5.5...1.5.6)

### CODE REVIEW

**Comment by adriansev** [comment]
Hi @TimoWilken @ktf all is green except the ubuntu test (unrelated to alienpy) that shows:
```
138/518 Test #108: CCDB/test/testCcdbApiDownloader.cxx ..................................................***Failed   10.19 sec
Running 6 test cases...
CURL code: 0
HTTP code: 200
/sw/SOURCES/O2/build_O2_alidist-ubuntu2204-ubuntu2204_x86-64/0/CCDB/test/testCcdbApiDownloader.cxx(304): [1;31;49merror: in "test_with_break": check httpCode == 200 has failed[0;39;49m
HTTP Code: 502

[1;31;49m*** 1 failure is detected in the test module "CCDB"
[0;39;49m
```

**Comment by TimoWilken** [comment]
Hi @costing, seems like CCDB is returning HTTP 502 errors occasionally -- see Adrian's comment above.

**Comment by costing** [comment]
Hi Timo,

The tests are performed against the ccdb-test instance, that was and is still used by MC production jobs. As such occasionally it might refuse connections until this traffic goes away. In the mean time could you retry the tests?

Cheers,

.costin

**Comment by TimoWilken** [comment]
I see, thanks @costing. Could you approve this PR as well, if it's alright? You're a code owner.

**Comment by chiarazampolli** [comment]
Hello @costing , 
Which MC productions use test CCDB? This should not happen... We can take this offline. 
Chiara

**Review by costing — APPROVED** [review]

**Pull request merged**
