### PR TITLE
Fix libxml2 git url

### PR DESCRIPTION
**Pull request by teo**

### CODE REVIEW

**Comment by teo** [comment]
@ktf doesn't seem to work here https://alijenkins.cern.ch/job/build-any-ib/6736/console

**Comment by dberzano** [comment]
@teo it's a temporary error seen in the past too many times. We don't see it frequently because we don't rebuild libxml2 too much. I'd change the URL in any case to avoid this problem in the future, but after 4/5pm today (this indeed triggers a full rebuild).

**Comment by ktf** [comment]
ahh, gitlab... ;-)

**Comment by dberzano** [comment]
@ktf it looks like the wrong URL is the reason why o2checkcode was failing everywhere... merging with some urgency!

**Pull request merged**
