### PR TITLE
Bump FairMQ version to v1.8.1

### PR DESCRIPTION
**Pull request by ktf**
Bump FairMQ version to v1.8.1

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @teo This should fix the race condition at shutdown we see on the FLP.

**Comment by davidrohr** [comment]
@Barthelemy @knopers8 : I see many QC tests timing out regularly, not only in this PR, but also in O2 PRs. Could you have a look what is the problem?

**Comment by davidrohr** [comment]
ok, tested this at P2, seems OK, global state reaches READY

**Comment by davidrohr** [comment]
ignore my last comment... commented on wrong PR...

**Comment by TimoWilken** [comment]
Done @davidrohr

**Comment by davidrohr** [comment]
errors unrelated, merging

**Pull request merged**
