### PR TITLE
libxml2:: use alidist provided lzma

### PR DESCRIPTION
**Pull request by adriansev**
since alidist already provides lzma and root use both lzma (alidist provided) and libxml2, let's make it consistent and use everywhere the alidist provided lzma.

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken could you please turn off the linter? there is too much noise in the PRs still.

**Comment by adriansev** [comment]
@ktf i tried to address most of the warnings, it's just i'm not confident to create myself the settings for automatic module file

**Comment by adriansev** [comment]
@TimoWilken @ktf i see as error the following (and for certain is not within the scope of this PR):
```
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
[16:53:13][INFO] TGeometry will not be imported to VMC

[16:53:15][WARN] Alignable volumes are not yet defined for TPC
[16:53:15][INFO] Add ITS alignable volumes
[16:53:16][INFO] Add MCH alignable volumes
[16:53:16][WARN] Alignable volumes are not yet defined for MID
[16:53:16][WARN] Alignable volumes are not yet defined for EMC
[16:53:16][INFO] Add FT0 alignable volumes
[16:53:16][INFO] FT0A <-> /cave_1/barrel_1/FT0A_1
[16:53:16][INFO] FT0C <-> /cave_1/barrel_1/FT0C_1
[16:53:16][INFO] FV0: Add alignable volumes
[16:53:16][INFO] FV0: Add alignable volume: FV0RIGHT_0: /cave_1/barrel_1/FV0_1/FV0RIGHT_0
[16:53:16][INFO] FV0: Add alignable volume: FV0LEFT_1: /cave_1/barrel_1/FV0_1/FV0LEFT_1
[16:53:16][WARN] Alignable volumes are not yet defined for FDD
[16:53:16][WARN] Alignable volumes are not yet defined for HMP
Info in <TGeoManager::Export>: Exporting ccdb_object FAIR geometry as root file. Optimizations streamed.
[16:53:17][INFO] Init CcdApi with UserAgentID: alientest06-1678726373-jTHkH1, Host: http://alice-ccdb.cern.ch/
[16:53:18][FATAL] Alien Token Check failed - Please get an alien token before running with https CCDB endpoint, or alice-ccdb.cern.ch!
For later analysis we write a core dump to core_dump_25563
```

Any idea what could be the actual problem?

**Comment by adriansev** [comment]
@ktf @TimoWilken in the macos log i see a segmentation violation in ROOT Cling:
```
 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[/System/Volumes/Data/build/alice-ci-workdir/alidist-o2/sw/osx_arm64/ROOT/v6-26-10-alice5-local6/lib/libCling.6.26.10.so] cling::IncrementalExecutor::runStaticInitializersOnce(cling::Transaction&) (no debug info)
[/System/Volumes/Data/build/alice-ci-workdir/alidist-o2/sw/osx_arm64/ROOT/v6-26-10-alice5-local6/lib/libCling.6.26.10.so] cling::Interpreter::executeTransaction(cling::Transaction&) (no debug info)
[/System/Volumes/Data/build/alice-ci-workdir/alidist-o2/sw/osx_arm64/ROOT/v6-26-10-alice5-local6/lib/libCling.6.26.10.so] cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&, bool) (no debug info)
```

**Comment by adriansev** [comment]
i will add the lzma dependency in the fixes from #4894

**Pull request closed without merging**
