### PR TITLE
FairMQ v1.4.39, asiofi v0.5.1, asio v1.19.1, FairCMakeModules v0.2.0

### PR DESCRIPTION
**Pull request by dennisklein**
@davidrohr [may have already found an issue](https://github.com/AliceO2Group/AliceO2/pull/6657#issuecomment-881544055) - do not merge yet, wait for his feedback.

### CODE REVIEW

**Comment by davidrohr** [comment]
issue was something else, new FairMQ seems to work well.
@TimoWilken : Could you check what is the aliDoctor error?

**Comment by ktf** [comment]
You should rename `faircmakemodules.rb` to `faircmakemodules.sh`.

**Comment by dennisklein** [comment]
> You should rename `faircmakemodules.rb` to `faircmakemodules.sh`.

Thank you! Done.

**Comment by ktf** [comment]
For the record:

```
→ aliBuild build FairMQ --defaults o2
ERROR: [Errno 2] No such file or directory: 'alidist/faircmakemodules.sh'
```

however:

```
→ aliBuild doctor FairMQ --defaults o2
SUCCESS: Package ZeroMQ will be picked up from the system.
SUCCESS: Package CMake will be picked up from the system.
Traceback (most recent call last):
  File "/Users/ktf/src/alibuild/aliBuild", line 132, in <module>
    doMain(args, parser)
  File "/Users/ktf/src/alibuild/aliBuild", line 65, in doMain
    doDoctor(args, parser)
  File "/Users/ktf/src/alibuild/alibuild_helpers/doctor.py", line 177, in doDoctor
    (fromSystem, own, failed, validDefaults) = getPackageList(packages                = packages,
  File "/Users/ktf/src/alibuild/alibuild_helpers/utilities.py", line 377, in getPackageList
    dieOnError(spec["package"].lower() != lowerPkg,
TypeError: 'NoneType' object is not subscriptable
(test)
```

we probably need to return a list of problematic packages as well from getPackageList

**Comment by ktf** [comment]
What do you mean by not merging a PR with 10 green tests? ;-)

**Comment by davidrohr** [comment]
I saw some issues with a large FST (that doesn't run in the CI since it takes too long) but that was unrelated.
merging.

**Pull request merged**
