### PR TITLE
Add re2 dependency in modulefile.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by teo — APPROVED** [review]

**Review by awegrzyn — APPROVED** [review]
Right, this does not use automated modulefiles... Sorry for the noise.

**Comment by ktf** [comment]
I leave next to l'Usine, I am used to noise... ;-)

**Comment by ktf** [comment]
Not really tested. Merging.

**Comment by awegrzyn** [comment]
Works on my setup.

**Pull request merged**
