### PR TITLE
Improve qcg recipe (O2-486)

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@awegrzyn fyi

**Comment by dberzano** [comment]
The error is unrelated.

**Comment by dberzano** [comment]
While we're at it, I'd copy only what's necessary here. ATM, source code is copied to the installation directory.

Here's `ls` on the root installation directory:

- [X] bin/
- [ ] binding.gyp
- [ ] build/
- [ ] config.js
- [ ] COPYING
- [ ] db.json
- [ ] docs/
- [X] etc/
- [ ] index.js
- [ ] lib/
- [X] node_modules/
- [ ] package.json
- [ ] package-lock.json
- [ ] public/
- [ ] README.md
- [ ] relocate-me.sh
- [ ] test/
- [ ] tobject2json.cc
- [X] tobject2json.node

I have checked what I know is needed for making it work, but I have no idea about the rest. Do you mind adding a check to the necessary files?

(For instance: the `.cc` is not needed, and the `build/` directory AFAIK is not needed either. Also, tests are probably not used in RPM packages.)

**Comment by awegrzyn** [comment]
Thanks for the improvements.
I ticked the files that must be present.

**Comment by dberzano** [comment]
Let me fix the recipe once more then, thanks!

**Comment by awegrzyn** [comment]
I installed `qcg/v1.4.5-2` but it still misses `tobject2json.node` file

**Comment by dberzano** [comment]
Hold on, I am checking in parallel.

**Pull request merged**
