### PR TITLE
Bump Geant4 and its dependent packages:

### PR DESCRIPTION
**Pull request by ihrivnac**
-  GEANT4: v10.7.1
-  GEANT4_VMC: v5-3
-  vgm: v4-9

### CODE REVIEW

**Comment by ihrivnac** [comment]
@ktf , @TimoWilken ,
The failure in O2 build is due to compiler error in analysis code, which has nothing to do with this PR:
```
[ 88%] Building CXX object Analysis/Tasks/CMakeFiles/O2exe-analysis-event-selection-qa.dir/eventSelectionQa.cxx.o
/mnt/mesos/sandbox/sandbox/o2-alidist/sw/SOURCES/O2/build_O2_alidist/0/Analysis/Core/src/JetFinder.cxx:68:1: internal compiler error: Segmentation fault
 }
 ^
0xb4024f crash_signal

```
On the other hand, it is surprising that this error did not happen in other PR builds, now merged.

**Comment by TimoWilken** [comment]
@ihrivnac, thanks for the report about the segfault, that's odd.

**Comment by ihrivnac** [comment]
@TimoWilken ,
The problem persists, though it can't be related to this PR, I believe.

**Review by sawenzel — APPROVED** [review]

**Comment by ihrivnac** [comment]
@TimoWilken , @ktf,
Now the problem is gone; did you make any change in the builder configuration? It looks like the same issue is now in nightly build.

**Comment by ktf** [comment]
Nothing changed, as far as I can remember. Merging this.

**Pull request merged**
