### PR TITLE
alienpy 1.6.3 :: fix incompatible dependency

### PR DESCRIPTION
**Pull request by adriansev**
* Fix behavior for missing xrootd
* Adapt async-stagger usage to the new 0.4.0 version that is backward incompatible

### CODE REVIEW

**Review by costing — DISMISSED** [review]

**Comment by adriansev** [comment]
@ktf it would seem that macos builders need an updated pip ... also note that this 1.6.3 is needed for all new installations that will break because of incompatible dependency so you decide if pip will be first fixed and then checks restarted or just merge this and then update pip ...

**Comment by adriansev** [comment]
@singiamtel my home machine is on python 3.12 (fedora 40) and i seen no problems with it .. and from what i understood macos defaults anyway to 3.12 so the pip needs to be updated anyway (i think it's on fixed version in python-modules)

**Comment by adriansev** [comment]
ping @singiamtel @ktf for macOS-arm i see a timeout in o2sim_G4, and O2/fullCI/alidist seems stuck

**Comment by adriansev** [comment]
@ktf @singiamtel it seems that a test is stuck...

**Review by zensanp — APPROVED** [review]

**Comment by adriansev** [comment]
ping @ktf @singiamtel

**Pull request merged**
