### PR TITLE
Update jalien.sh

### PR DESCRIPTION
**Pull request by costing**
Bump tag to 1.3.5

### CODE REVIEW

**Review by adriansev — APPROVED** [review]

**Comment by costing** [comment]
@ktf could you please merge this? The errors are unrelated.

On that topic, could some exceptions be applied to this project? Essentially none of the checks are relevant for it ...

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/3111 should fix the error with the builds. In general I do fast track jalien, especially if I get told only the java part changed.

**Comment by costing** [comment]
Thanks @ktf @TimoWilken ! 

For this project only the java part can change, it's nothing else but. The `jalien-root` is a different story, but for this project all these check could be masked for good.

**Comment by costing** [comment]
@iraklic could you please trigger the deployment for this tag ?

**Comment by iraklic** [comment]
@costing done.

**Pull request merged**
