### PR TITLE
Bump ROOT to v6-26

### PR DESCRIPTION
**Pull request by sawenzel**
Major bump of ROOT to v6-26.
The minor reference tag is v6-26-04 plus local ALICE patches.

### CODE REVIEW

**Comment by pzhristov** [comment]
@sawenzel It seems we have to adjust some of the checks in root.sh. I will have a look.

**Comment by sawenzel** [comment]
@pzhristov : Yes, I saw the same locally. After disabling the checks, the compilation succeeded.

**Comment by pzhristov** [comment]
@ktf @davidrohr @sawenzel Bumping FairRoot to v18.4.8 solves the ROOT::VMC issue. Do you think we can safely move to it?

**Comment by davidrohr** [comment]
If it passes the FullCI it would be ok for me. Anyway mostly used in simulation not during data taking.

**Comment by pzhristov** [comment]
Ok, the updated FairRoot v18.4.8 it compiles with the current Root v6-24-06-alice1, so I will make a PR to check the fullCI.

**Comment by pzhristov** [comment]
Ok, the updated FairRoot v18.4.8 it compiles with the current Root v6-24-06-alice1, so I will make a PR to check the fullCI.

**Comment by pzhristov** [comment]
Depends on https://github.com/alisw/alidist/pull/4296

**Comment by fcatalan92** [comment]
To enable the building of TMVA SOFIE (the new ROOT feature for ML inference) a specific flag must be set `tmva-sofie=ON` https://root.cern/doc/v626/release-notes.html#sofie-code-generation-for-fast-inference-of-deep-learning-models.

@pzhristov If it is ok for you, I can add a commit to this branch.

**Comment by pzhristov** [comment]
@fcatalan92 Yes, please add the missing settings. Thanks a lot!

**Comment by pzhristov** [comment]
@fcatalan92 I suppose it is enough to use -Dtmva-sofie=ON in root.sh.
@ktf I think we have to remove all the VMC remnants from root.sh, this is the reason for failure in build/AliGenerators/generators

**Comment by pzhristov** [comment]
I am going to edit the file now.

**Comment by fcatalan92** [comment]
@pzhristov Actually, TMVA SOFIE requires protobuf. With this commit ROOT compiles on my Ubuntu 20.04

**Comment by pzhristov** [comment]
> @pzhristov Actually, TMVA SOFIE requires protobuf. With this commit ROOT compiles on my Ubuntu 20.04

Yes, we have protobuf as requested package for O2, but it is important to put the dependency explicitly.

**Review by pzhristov — APPROVED** [review]

**Review by davidrohr — APPROVED** [review]

**Pull request merged**
