### PR TITLE
Bump to the latest EVTGEN version R02-02-00

### PR DESCRIPTION
**Pull request by pzhristov**
Using the official hepforge repository.

### CODE REVIEW

**Review by maireiphc — COMMENTED** [review]
Hello @pzhristov,  up to now PAG-MC has never been in charge of EvtGen.
I guess somebody from DPG or O² WP13 (Sandro, Roberto) may be more relevant persons to have a look.

Just a comment : I do not what is best to pick the sources : the HEPforge web page or the Gitlab dir https://gitlab.cern.ch/evtgen/evtgen/ ?

**Comment by pzhristov** [comment]
> Hello @pzhristov, up to now PAG-MC has never been in charge of EvtGen. I guess somebody from DPG or O² WP13 (Sandro, Roberto) may be more relevant persons to have a look.
> 
> Just a comment : I do not what is best to pick the sources : the HEPforge web page or the Gitlab dir https://gitlab.cern.ch/evtgen/evtgen/ ?

The CERN GitLab repository is a mirror of the EvtGen repo hosted on HepForge, so I propose to use the "official" source.

**Comment by maireiphc** [comment]
> > Just a comment : I do not what is best to pick the sources : the HEPforge web page or the Gitlab dir https://gitlab.cern.ch/evtgen/evtgen/ ?
> 
> The CERN GitLab repository is a mirror of the EvtGen repo hosted on HepForge, so I propose to use the "official" source.

Ok, I would have expected to the other way around between GitLab and HEPforge, and some transparent tools for aliBuild to recover the sources via gitlab... Nothing to add or object though.

**Comment by ffionda** [comment]
Dear @preghenella , thanks for letting me know, I confirm that we are currently using EvtGen in our Run3 DQ simulations. 
Dear @pzhristov thank you for improving the recipe for installing EvtGen. I take this opportunity to let you know that there are some issues with the compilation of EvtGen on macOS (in particular for what concern the installation of PHOTOS package), I hope your fix can also solve this issue.  Thank you,
Regards,
Fiorella

**Comment by pzhristov** [comment]
> Dear @preghenella , thanks for letting me know, I confirm that we are currently using EvtGen in our Run3 DQ simulations. Dear @pzhristov thank you for improving the recipe for installing EvtGen. I take this opportunity to let you know that there are some issues with the compilation of EvtGen on macOS (in particular for what concern the installation of PHOTOS package), I hope your fix can also solve this issue. Thank you, Regards, Fiorella

Dear @ffionda, I am preparing another fix that will solve the issues with PHOTOS on MacOS. It needs some small modifications and tests on Linux to be sure everything works.

**Pull request merged**
