### PR TITLE
Exclude failing fairmq tests

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
On my mac and CC7 , with defaults o2 and o2-dataflow, there are 3 tests failing in FairMQ and they provoke a failure of the build.

**Comment by dennisklein** [comment]
@Barthelemy Hi, if you have time, it would be aweseome, if you could additionally file an issue with FairMQ which describes your environment in more detail under which these tests fail. Thx!

**Comment by Barthelemy** [comment]
@dennisklein with pleasure, will do.

**Comment by Barthelemy** [comment]
@dennisklein The problem was that another program was using port 7777.

**Pull request merged**
