### PR TITLE
bump readout v0.27

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by ktf** [comment]
does not compile on mac... i guess you want:

```C++
#ifdef __APPLE__ & __MACH__
#define fseeko64 fseeko
#define ftello64 ftello
#endif
```

**Comment by sy-c** [comment]
@ktf I removed the 64bit calls and it's now ok on mac with v0.27.1, thanks for pointing this out.

now build/O2/alidist is red but clicking "details" leads to "404 Not Found"
this is likely unrelated, please advise

**Comment by ktf** [comment]
@dberzano

**Comment by sy-c** [comment]
The test logs 'details' are now accessible.
build/O2/alidist fails with unrelated error:
  7/331 Test   #6: /Detectors/Base/test/buildMatBudLUT.C_compiled ...............................***Failed

@alisw/infrastructure-admins can this PR please be merged?

**Comment by sy-c** [comment]
thank you!

**Pull request merged**
