### PR TITLE
Fix tracy in case freetype comes from the system

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@aalkin @davidrohr

**Comment by davidrohr** [comment]
@ktf : `TBB= ` doesn't disable tbb for me

**Comment by aalkin** [comment]
It still needs the correct include path for system freetype. Adding '-ltbb'  to EXTRA_LIBS works for me, but it may be not useful for systems without it.

**Comment by ktf** [comment]
In principle tbb is not a requirement, so I'd rather disable it. I think TBB= does not work because it's considered as not set and therefore not overriding the default.

**Comment by davidrohr** [comment]
Also `TBB=off` doesn't work for me. And I also have the same issue @aalkin just reported for the system freetype headers

**Comment by ktf** [comment]
This should fix the system freetype issue. For TBB and GLEW I guess we still need something better...

**Pull request merged**
