### PR TITLE
Bump qualitycontrol to v1.0.2

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by knopers8** [comment]
The checks are green apart from AliGenerators which shows:
```
Builing on: alibuild04.cern.ch at 2020-08-12-13:42:42
No logs found. Please check actual builders log in aurora.
See http://alisw.github.io/infrastructure-pr-testing for more instructions.
```
I would propose to merge it, as it is needed to unblock failing build checks in O2.

**Comment by ktf** [comment]
Indeed the machine is causing troubles since yesterday. I will investigate.

**Comment by ktf** [comment]
The update itself is causing issues in the AliceO2 checks. I am reverting this.

**Comment by knopers8** [comment]
Can you point me to any logs with this PR in?

**Comment by ktf** [comment]
https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/4143/ccfe12979c83b17db90654d381baeb08bd8dbaa7/build_O2_gpu/fullLog.txt

--
Ciao,
Giulio

**Comment by knopers8** [comment]
Builing on: alibuild14.cern.ch at 2020-08-13-09:04:07

This PR was merged on 9:35.

**Pull request merged**
