### PR TITLE
Bump Control to v0.5

### PR DESCRIPTION
**Pull request by teo**

### CODE REVIEW

**Comment by teo** [comment]
> -1. We do not want to have go as a mandatory dependency for InfoLogger, IMHO. Could you make that optional somehow, e.g. by moving the go bindings of infologger to a separate package?

v0.6 already depends on libInfoLogger instead of InfoLogger, but since v0.5 is already tagged I'd like to keep the InfoLogger dependency only for this version.
Perhaps we could build InfoLogger without Go+SWIG and libInfoLogger with it?

**Comment by ktf** [comment]
Nope, the opposite I would not object (InfoLogger in Go, libInfoLogger without), but asking people in O2 to forcefully depend on Go is not an option at the moment, IMHO.

**Comment by teo** [comment]
> Nope, the opposite I would not object (InfoLogger in Go, libInfoLogger without), but asking people in O2 to forcefully depend on Go is not an option at the moment, IMHO.

Fine with me, I'll revert the change to libInfoLogger and keep depending on InfoLogger.

**Comment by ktf** [comment]
@dberzano logs are missing...

**Comment by teo** [comment]
@dberzano @ktf Is someone looking into this?

**Comment by ktf** [comment]
I've approved the changes. Could you trigger a rebuild?

**Comment by ktf** [comment]
Ping @alisw/dataflow-experts

**Pull request merged**
