### PR TITLE
ALO: bump aliroot to a version that works with Xcode9

### PR DESCRIPTION
**Pull request by dstocco**

### CODE REVIEW

**Comment by dstocco** [comment]
Hello,
is there any news on this?
Please notice that this commit only affects the aliroot version used in ALO...that is currently used by a very small amount of people ;)
The modification is rather harmless....

Thanks in advance,
cheers,
Diego

**Comment by dberzano** [comment]
Hi, we have v5-09-20. Don't you want to jump on that?

**Comment by dstocco** [comment]
Ciao @dberzano ,
well, I was picking the first version that was working with Xcode9 (anyways, we did not change much in MUON). However, of course I can take the latest available version.
Do you prefer that I amend the commit or push a second one in the branch?

Thanks,
ciao,
Diego

**Comment by dstocco** [comment]
Hi @dberzano ,
while updating the PR I wanted to test it with the latest master....but I cannot compile anymore on Mac.
It now tries to compile lzma, but fails:
+ ./autogen.sh
+ autopoint -f
./autogen.sh: line 17: autopoint: command not found

Should I install xz with brew?
Cheers,
Diego

**Comment by dstocco** [comment]
Hi again,
ok, in the meanwhile I tested the PR with a master version before the inclusion of the lzma dependency and it works. Since in any case I had to force-push, I amended the previous commit.
Cheers,
Diego

**Comment by dberzano** [comment]
For the record you do need to install `xz` now, but `lzma` should compile flawlessly, and it correctly depends on `autotools`. Check with aliDoctor if you have `autotools` correctly installed.

**Comment by dstocco** [comment]
Ciao Dario,
thanks. Anyways, according to alidoctor it seems that autotools is picked from the system:
==> The following packages will be picked up from the system:
    
    - Python-modules
    - CMake
    - protobuf
    - libxml2
    - nanomsg
    - libpng
    - ZeroMQ
    - autotools
    - GSL

So, I guess it's there...
Ciao,
Diego

**Pull request merged**
