### PR TITLE
Bump monitoring to v3.8.6

### PR DESCRIPTION
**Pull request by awegrzyn**
Auto-generated PR for the following release https://github.com/AliceO2Group/Monitoring/releases/tag/v3.8.6

### CODE REVIEW

**Comment by ktf** [comment]
Not sure how this can happen, but Readout seems to have a genuine issue.

**Comment by Barthelemy** [comment]
@sy-c This is the same issue we saw in our CI. 
@ktf this is very strange because nothing has changed in Readout.

**Review by Barthelemy — APPROVED** [review]

**Comment by sy-c** [comment]
> @sy-c This is the same issue we saw in our CI.

The changes in monitoring headers caused a compilation error in readout. This is fixed, the missing header has been added.

**Comment by ktf** [comment]
Looks like there is still one issue:

```
[ 14%] Building CXX object CMakeFiles/objReadoutConsumers.dir/src/Consumer.cxx.o
/mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/Readout/v2.3.0/v2.3.0/src/testMonitor.cxx: In function 'int main()':
/mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/Readout/v2.3.0/v2.3.0/src/testMonitor.cxx:33:5: error: 'sleep' was not declared in this scope
   33 |     sleep(1);
      |     ^~~~~
```

**Comment by sy-c** [comment]
> Looks like there is still one issue:
> 
> ```
> [ 14%] Building CXX object CMakeFiles/objReadoutConsumers.dir/src/Consumer.cxx.o
> /mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/Readout/v2.3.0/v2.3.0/src/testMonitor.cxx: In function 'int main()':
> /mnt/mesos/sandbox/sandbox/o2-fullci-alidist/sw/SOURCES/Readout/v2.3.0/v2.3.0/src/testMonitor.cxx:33:5: error: 'sleep' was not declared in this scope
>    33 |     sleep(1);
>       |     ^~~~~
> ```

This was fixed with Readout v2.4.0. #3066 It seems this CI check still used 2.3.0.

**Comment by awegrzyn** [comment]
CC7 fails now with `c++: fatal error: Killed signal terminated program cc1plus` and macOS on `Detectors/TPC/workflow/CMakeFiles/O2exe-tpc-chunkeddigit-merger.dir/src/ChunkedDigitPublisher.cxx`...

**Pull request merged**
