### PR TITLE
Enforce no warning code in ReadoutCard

### PR DESCRIPTION
**Pull request by awegrzyn**
@kostorr

### CODE REVIEW

**Comment by kostorr** [comment]
Fine by me.

**Comment by ktf** [comment]
This seems to be an actual issue with this PR?

**Comment by kostorr** [comment]
I removed the warnings after the PR was created. The ReadoutCard version including them is v0.11.9. @awegrzyn Adam can you update the recipe with the new version so that it passes?

**Comment by awegrzyn** [comment]
@kostorr Feel free to edit the PR

**Comment by kostorr** [comment]
I'll check the errors on macOS and report back.

**Pull request merged**
