### PR TITLE
Bump ReadoutCard & friends, drop InfoLogger where unnecessary

### PR DESCRIPTION
**Pull request by kostorr**

### CODE REVIEW

**Review by sy-c — APPROVED** [review]

**Comment by kostorr** [comment]
@alisw/infrastructure-admins are these failures legit? Details report no logs/errors found

**Comment by awegrzyn** [comment]
I've restarted the tests

**Comment by kostorr** [comment]
@TimoWilken do you know what is going on here? Errors seem unrelated.

**Comment by TimoWilken** [comment]
@kostorr, the error is:

```
2021-01-26@08:22:22:DEBUG:O2Suite:LLA:build_O2_alidist: + cd /mnt/mesos/sandbox/sandbox/o2-alidist/sw/SOURCES/LLA/v0.1.3/v0.1.3
2021-01-26@08:22:22:DEBUG:O2Suite:LLA:build_O2_alidist: + git checkout v0.1.3
2021-01-26@08:22:22:DEBUG:O2Suite:LLA:build_O2_alidist: error: pathspec 'v0.1.3' did not match any file(s) known to git.
2021-01-26@08:22:22:ERROR:O2Suite:LLA:build_O2_alidist: Error while executing /mnt/mesos/sandbox/sandbox/o2-alidist/sw/SPECS/slc7_x86-64/LLA/v0.1.3-1/build.sh on `alientest02'.
```

I can't see v0.1.3 at https://github.com/AliceO2Group/LLA/tags, could you create it or update the recipe in this tag?

**Comment by kostorr** [comment]
Sorry about that, I made the tag, could you restart the tests?

**Comment by TimoWilken** [comment]
@kostorr done! Sorry it took me a while to reply earlier.

**Comment by kostorr** [comment]
@TimoWilken sorry for bugging you again. Two tests still fail, they seem unrelated, can you have a look?

**Comment by awegrzyn** [comment]
@TimoWilken Could you explain why `build/O2/alidist-dataflow` failed? It looks to me that all tests passed

**Comment by TimoWilken** [comment]
I suspect it fails when setting up the QC (or another) because of an aliBuild bug. It builds O2 successfully, but never gets to the actual QC build, thus the QC tests don't appear in the logs.

**Comment by TimoWilken** [comment]
Ignore the previous message, I was wrong. For some reason, aliBuild didn't fetch the v0.1.3 tag in the LLA sources. I've fetched it manually, I'll restart the build.

**Comment by kostorr** [comment]
@ktf could you merge? QC tests on macOS are unrelated.

**Pull request merged**
