### PR TITLE
Bump to GCC 10.2 everywhere except in release defaults

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
for testing, for now.

**Comment by ktf** [comment]
Closing the pull request as rebuilding it slows down the the rest of the CI.

**Comment by davidrohr** [comment]
Makes sense, the failures were with ROOT5 in the ALiRoot CI, which does not compile out of the box with GCC 10. I am not sure whether we want to do anything here @ktf @pzhristov

**Comment by pzhristov** [comment]
I really hope to get rid of Root 5 in very near future (as soon as DPG stops running productions on the old data). Out of curiosity I can try to compile Root 5 with gcc 10.2, but it will take some time to fix all the issues.

**Pull request closed without merging**
