### PR TITLE
Bump POWHEG to r3964-alice2

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Fixes floating point exception occurring when running in reweighting mode.

**Comment by mfasDa** [comment]
Hi @maireiphc ,

This PR is related to this PR in POWHEG just merged into master a couple of minutes ago: https://github.com/alisw/POWHEG/pull/7

What is the issue: In case of reweighting the POWHEG authors read the file with the events using the zlib. Since zlib is a c library the functions need to be exported as bindings of c-functions to fortran functions. In the binding they dropped the return value (gzrewind returns int) however they access the return in pwhg_io_rewind. This leads to a crash of the following type:
```

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x2b211cbdab3a in ???
#1  0x2b211cbd9d63 in ???
#2  0x2b211e0c827f in ???
#3  0x4aebf0 in pwhg_io_rewind_
	at ../pwhg_io_interface.f:30
#4  0x48a34b in opencountunit_
	at ../opencount.f:146
#5  0x40631a in MAIN__
	at ../pwhg_main.f:245
#6  0x407237 in main
	at ../pwhg_main.f:386
```
Visible on different computing systems. I checked that with the fix posted the reweighting which formerly crashed runs through.

The pull request is merged, however it is not yet tagged. I opened this PR  already to prepare, and I hope someone with merge rights creates the tag very soon. It is definitely needed at least for jets, running all pdf variations as separate productions is computing-wise not feasible.

Cheers

Markus

**Review by maireiphc — DISMISSED** [review]

**Comment by mfasDa** [comment]
Additional comment to retrigger the CI

**Review by maireiphc — APPROVED** [review]

**Comment by mfasDa** [comment]
CI errors unrelated

**Pull request merged**
