### PR TITLE
bump QC

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@knopers8

**Comment by knopers8** [comment]
Thanks for spotting it. I fixed it and released at v0.9.1

**Comment by awegrzyn** [comment]
Could you bump it? I need a new version of QC

**Comment by Barthelemy** [comment]
@awegrzyn could you approve ?

**Comment by ktf** [comment]
QC not tested with AliRoot. Merging.

**Pull request merged**
