### PR TITLE
Bump geant4_vmc to v3-6-p6:

### PR DESCRIPTION
**Pull request by ihrivnac**
This version contains the latest fixes and also the development for mixing
physics lists via biasing.

### CODE REVIEW

**Comment by ktf** [comment]
@ihrivnac the build issue on mac is genuine. Can you look into it?

**Comment by ihrivnac** [comment]
This is due to building with geant4_vmc with c++17 with Geant4 built with c++11; with adding the development for mixing Geant4 physics list ("inclxx-biasing-p2") we depend on G4 includes which we did not depend in previous version, what explains why we did not get this error before.

@sawenzel , do we need to stay with Geant4 10.4.px with O2? The most straightforward solution would be to move to Geant4 10.5 or 10.6, which both support c++17.

**Comment by ihrivnac** [comment]
I changed the PR in WIP, as we need v3-6-p6-inclxx-biasing-p2 for production; and v3-6-p6 or newer version for O2. So let's wait with merge until we agree on the version for O2.

**Comment by ktf** [comment]
Waiting for @sawenzel to greenlight.

**Comment by ihrivnac** [comment]
@ktf , as I wrote above, this is not exactly what we need; I changed the tag to  v3-6-p6 to see if  it passes testing, but we we need the development in "inclxx-biasing". 
To get a different version for production than for o2, should I put back v3-6-p6-inclxx-biasing-p2  in geant4_vms.sh and v3-6-p6 in defaults-o2.sh  ?

**Comment by ktf** [comment]
@ihrivnac yes, that's correct. However why not just using v3-6-p6-inclxx-biasing-p2 for o2 as well?

**Comment by ihrivnac** [comment]
@ktf, v3-6-p6-inclxx-biasing-p2 does not compile with c++17, that's why I changed the tag. We would have to build it with c++11.

**Pull request merged**
