### PR TITLE
bump readout + readoutcard

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
@alisw/infrastructure-admins @alisw/dataflow-experts 
The logs of failing tests are not meaningful to me, please advise.

**Comment by ktf** [comment]
@sy-c mac builds are back in business. there seems to be an actual issue with Readout.

**Comment by kostorr** [comment]
> @sy-c mac builds are back in business. there seems to be an actual issue with Readout.

That's ReadoutCard, I'm on it.

**Comment by kostorr** [comment]
@ktf can you retrigger the tests?

**Comment by ktf** [comment]
Did you retag?

**Comment by kostorr** [comment]
> Did you retag?

Same tag v0.14.4 now points to updated commit.

**Comment by kostorr** [comment]
I'm closing and I'll make a new PR with a new ReadoutCard version.

**Pull request closed without merging**
