### PR TITLE
replace pip3 calls with "python3 -m pip"

### PR DESCRIPTION
**Pull request by jezwilkinson**
Replaces pip3 calls in python-modules.sh and xjalienfs.sh with "python3 -m pip", to avoid possible errors with local pip installation ("No module named 'pip._internal'")

### CODE REVIEW

**Comment by ktf** [comment]
Actual issues seems to be bound to o2-dataflow and the fact it has a reduced set of dependencies which does not allow for importing wheel packages (and no, adding wheel does not seem to help).

@MichaelLettrich I think the Darwin builder died again...

**Comment by jezwilkinson** [comment]
Added new commit to get rid of the conflict with https://github.com/alisw/alidist/pull/2378 [removal of matplotlib lines in python-modules]

**Comment by awegrzyn** [comment]
Our job @ macOS fails on `python3 -m pip install --user -IU setuptools` with `/usr/local/opt/python/bin/python3.7: No module named pip`.

**Comment by ktf** [comment]
As far as I understand it pip comes with `brew install python3`. If you run, without alibuild:

```
python3 -m pip -V
```

I get:

```
pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
```

maybe your homebrew installation needs a `brew upgrade python3`?

**Comment by awegrzyn** [comment]
Ok, I see some issues in our setup, we're using `python3` coming from the system:
```
% python3 --version
Python 3.7.7
% which python3
/usr/local/bin/python3
```

`pip3` is there, but under different path:
```
% which pip3   
/usr/bin/pip3
```

and `python3 -m pip -V ` fails with `/usr/local/opt/python/bin/python3.7: No module named pip`

**Comment by awegrzyn** [comment]
I'll figure it out, no worries...

**Comment by ktf** [comment]
You seem to have python3 from brew (it's in `local/bin`, not in `bin`) but that copy does not have an embedded pip (which they claim is always the case https://docs.brew.sh/Homebrew-and-Python#setuptools-pip-etc). I would simply do a `brew upgrade python3`.

**Pull request merged**
