### PR TITLE
Fix Clang compilation with newer Apple SDKs

### PR DESCRIPTION
**Pull request by TimoWilken**
`xcrun --show-sdk-path` seems to give the correct result, no need for `find`.

@ktf or @davidrohr: is there a case where this doesn't work that the previous code was guarding against?

In addition, fix the build on `osx_arm64`. Tested on Mac M1.

### CODE REVIEW

**Comment by pzhristov** [comment]
@TimoWilken I switched off the compilation of Clang on MacOSX since the system compiler is doing perfectly the job.

**Comment by pzhristov** [comment]
@TimoWilken Of course, it is nice to have the possibility to compile in case we need some ALICe-specific modifications.

**Comment by TimoWilken** [comment]
Yes, good point, I forgot we were only using system packages. Oh well, maybe it'll be useful at some point. At least the `find ...` -> `xcrun --show-sdk-path` changes are needed on Intel Macs as well, especially when the next Xcode update comes along.

**Review by pzhristov — APPROVED** [review]

**Comment by ktf** [comment]
@TimoWilken looks good. As usual, could you warm up the cache?

**Comment by TimoWilken** [comment]
> looks good. As usual, could you warm up the cache?

@ktf Done!

**Pull request merged**
