### PR TITLE
Improve GCC builds

### PR DESCRIPTION
**Pull request by ktf**
- Move to GCC 13.2.0
- Move to GDB 14.2
- Do not use GCC 7.3.0 as default, since now AliRoot it's built with its own default.
- Add support for CCACHE. While disabled by default it can be enabled by passing CCACHE_DISABLE=false as environment variable.

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf Very nice, do you have any numbers/experience on speed up when using Ccache with our codebase?

**Comment by ktf** [comment]
No... In the past (15+ years ago) I frankly spent more time chasing hash conflicts than saved build time, but maybe it is worth giving another chance since a lot of time passed. Moreover they now provide distributed caches via redis as well, which might be very interesting if it works as advertised.

**Comment by ktf** [comment]
The other issue is root dictionaries generation which cannot be cached. i propose we simply try and then decide how to proceed.

**Comment by awegrzyn** [comment]
Ok thanks. Yeah, I'm keen on experiment with it as well.

**Comment by ktf** [comment]
Closed in favor of #5449 which has the minimal set required.

**Pull request closed without merging**
