### PR TITLE
Bump Pythia8 to support C++20

### PR DESCRIPTION
**Pull request by ktf**
Bump Pythia8 to support C++20

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/alisw/alidist/pull/5256).
* #5240 (2 commits)
* __->__ #5256

### CODE REVIEW

**Comment by ktf** [comment]
@maireiphc @jackal1-66 @sawenzel @pzhristov  any reason why we have a custom Pythia8 in the defaults, rather than simply updating the main recipe? Is it historical for old AliRoot releases?

**Comment by maireiphc** [comment]
Hello @ktf,

I suspect this is indeed a relics of Pythia in AliRoot Vs the rest of the ALICE software.
At the time [~2021], I believe it was Roberto Preghenella's strategy to overwrite the defaults per "software spheres" in ALICE, rather than touching the dedicated pythia.sh recipe.
At the time, AliRoot was behind in terms of version, Roberto was designing/had been designing the generator part in O² (pythia8 as default),  he was coordinator of the PAG-MC with me, thus managing Pythia8 there as well; O² and AliGenerators were **not** really moving ± in synch.

I do not foresee other reason, do I miss sthg ?

**Comment by ktf** [comment]
@sawenzel is the error with MID simulation known?
```
/sw/SOURCES/O2/daily-20231127-0100/daily-20231127-0100/Detectors/MUON/MID/Simulation/test/testSimulation.cxx(492): [1;31;49merror: in "o2_mid_simulation/MID_SimClusters/_9": check sortedPC.size() == 1 has failed [0 != 1]
Failure occurred in a following context:
    deId = 24; [0;39;49m
/sw/SOURCES/O2/daily-20231127-0100/daily-20231127-0100/Detectors/MUON/MID/Simulation/test/testSimulation.cxx(494): [1;31;49merror: in "o2_mid_simulation/MID_SimClusters/_9": &
Failure occurred in a following context:
```
?

**Comment by ktf** [comment]
@maireiphc indeed, i think it's some historical baggage. i will clean it up.

**Comment by ktf** [comment]
Merging since this compile. I will remove the defaults and bump the official tag tomorrow.

**Pull request merged**
