### PR TITLE
Unconditionally disable GPU tests in CI for incremental builds

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
GPU ctests will always fail in the CI, since there is no GPU available.
They were disabled in alidist/o2.sh, but only for full build.
This PR disables them also for incremental builds.

**Comment by MichaelLettrich** [comment]
I am wondering though If there is no way to avoid duplicate code in the receipe ? It looks like this can easily happen again in the future. (More general comment and not doubting the usefulness of the fix)

**Comment by MichaelLettrich** [comment]
Seems that there is some issues checking out the right tag on macOS @ktf , this looks very similar to #2157  

```bash
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + SHORT_TAG=v1.3.9
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: ++ dirname /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/Readout/v1.3.9/v1.3.9
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + mkdir -p /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/Readout/v1.3.9
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + [[ v1.3.9 != v1.3.9 ]]
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + rm -fr /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/b6276a2deb36d3b178b03cf7d81f03385e7337b2
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + [[ 0 == 0 ]]
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + rm -rf /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/b6276a2deb36d3b178b03cf7d81f03385e7337b2
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + mkdir -p /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/b6276a2deb36d3b178b03cf7d81f03385e7337b2/osx_x86-64/Readout/v1.3.9-1 /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/b6276a2deb36d3b178b03cf7d81f03385e7337b2 /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/b6276a2deb36d3b178b03cf7d81f03385e7337b2/Readout /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/b6276a2deb36d3b178b03cf7d81f03385e7337b2/osx_x86-64/Readout/v1.3.9-1
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + cd /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/b6276a2deb36d3b178b03cf7d81f03385e7337b2
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + ln -snf b6276a2deb36d3b178b03cf7d81f03385e7337b2 /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/Readout-latest
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + [[ -n '' ]]
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + export GIT_REFERENCE=/build/mirror/readout
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + GIT_REFERENCE=/build/mirror/readout
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + [[ ! https://github.com/AliceO2Group/Readout == '' ]]
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + [[ h != \/ ]]
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + [[ ! -d /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/Readout/v1.3.9/v1.3.9 ]]
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + cd /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/Readout/v1.3.9/v1.3.9
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: + git checkout v1.3.9
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: error: pathspec 'v1.3.9' did not match any file(s) known to git
2020-04-01@10:20:22:DEBUG:O2Suite:Readout:2168: 
2020-04-01@10:20:22:ERROR:O2Suite:Readout:2168: Error while executing /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SPECS/osx_x86-64/Readout/v1.3.9-1/build.sh on `aido2osx3.cern.ch'.
2020-04-01@10:20:22:ERROR:O2Suite:Readout:2168: Log can be found in /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/Readout-latest/log
2020-04-01@10:20:22:ERROR:O2Suite:Readout:2168: Please upload it to CERNBox/Dropbox if you intend to request support.
2020-04-01@10:20:22:ERROR:O2Suite:Readout:2168: Build directory is /System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/Readout-latest/Readout.
+ BUILD_ERROR=1
```

**Comment by ktf** [comment]
Can you cleanup the git mirrors? I suspect readout moved a tag.

**Comment by MichaelLettrich** [comment]
I deleted mirrors and sources and restarted the builder. I hope things will be back to normal again.

**Pull request merged**
