### PR TITLE
Align ROOT 6 for o2-daq

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@Barthelemy this should fix your problem.

**Comment by Barthelemy** [comment]
Thank you , perfect. Could this be merged urgently ?

**Comment by dberzano** [comment]
Let's wait for the tests, I am not sure it works. They're in progress now.

**Comment by Barthelemy** [comment]
Sure

**Comment by dberzano** [comment]
AliPhysics problem unrelated. Merging.

**Pull request merged**
