### PR TITLE
Bump clang to 13 + add llvm-spirv translator

### PR DESCRIPTION
**Pull request by davidrohr**
Same as  #3505 but spirv translator added

### CODE REVIEW

**Review by ktf — DISMISSED** [review]

**Comment by davidrohr** [comment]
I just tried this locally in the FullCI docker container, and it has build the OpenCL part correctly using the alidist clang 13. So we can get rid of the custom clang in the docker. Will do that with the next update. Still, I'll retain the possibility to add a custom clang again if needed, since we are not free to update alidist clang spontaneously.

**Comment by ktf** [comment]
Looks like it breaks the code checker.

**Comment by davidrohr** [comment]
Ah, oh course. We have to bump O2CodeChecker in addition and update some files there.
@sawenzel @pzhristov : could you have a look, and perhaps open a PR to my PR branch?
(I can also do it, but first have to catch up with some other things this week.)

**Comment by ktf** [comment]
@TimoWilken build/O2/alidist-dataflow breaks.

**Comment by TimoWilken** [comment]
The machine it ran on temporarily had network troubles. Fixed now.

**Comment by ktf** [comment]
@davidrohr @sawenzel it looks like `modernize-return-braced-init-list` started to trigger basically everywhere. It is indeed in the list of checks we explicitly enabled but somehow it silent so far. Do we really care about it?

**Comment by davidrohr** [comment]
THe list has endless repetitions, but there are still 280 unique cases.
Actually I don't care, we can either fix them, or we disable the warning, both is fine with me.
If you want I can take care of fixing it up, shouldn't take that long.

**Comment by davidrohr** [comment]
@ktf @TimoWilken @MichaelLettrich : Could you check why the MacOS CI fails here with
```
find: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/private/var/mobile: Permission denied
```

**Comment by ktf** [comment]
Looks like a genuine issue with the machine. @MichaelLettrich @TimoWilken could you have a look?

**Comment by TimoWilken** [comment]
Hm, weird. I'm not sure how it happened, but I've `chmod +r`-ed the directory and restarted the check.

**Pull request merged**
