### PR TITLE
Root: Check for AvailabilityMacros.h, i.e. command line tools, on osx

### PR DESCRIPTION
**Pull request by aaniin**
Hello @ktf , @dberzano ,

Here's a pull request for the issue of missing AvailabilityMacros.h experienced by Sedhana today. I hope this PR can be a base for discussion. No strong feelings on this PR from my side. Let me know if I should focus on other ways of contributing.

Cheers,
Hans

```sh
Hanss-MacBook:alibuild hbeck$ aliDoctor root
[...]
SUCCESS: Required package availabilitymacros will be picked up from the system.
```

Cheers,
Hans

### CODE REVIEW

**Comment by ktf** [comment]
+1 from my side.

**Comment by ktf** [comment]
Assigned to Dario for inclusion in master for the next AliRoot release.

**Comment by dberzano** [comment]
I will review it later today along with #728, both are important. I believe however that the approach is not the right one. The absence of this library is a symptom of a misconfigured development environment (outdated Xcode, absence of Xcode development tools, outdated development tools wrt/Xcode version). This header is _one_ of the things we need to check, so it's a start :-)

I'll take care of it ASAP.

**Comment by dberzano** [comment]
See #740, which is an extended version of this one.

**Pull request closed without merging**
