### PR TITLE
Improvements to support slc6 + develtools setup

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@barthelemy @vascobarroso can you try:

git pull https://github.com/alisw/alidist IB/v5-08/next

I think this should fix your issues on SLC6 + develtools-2

**Comment by ktf** [comment]
Ah, you will also need:

```
git pull https://github.com/alisw/alibuild next
```

**Comment by vascobarroso** [comment]
@ktf Still fails, here's the [log](https://github.com/alisw/alidist/files/186406/log.txt).

Also, I still had to uninstall zmq as stated in #252.

**Comment by ktf** [comment]
ah, ok, that's a separate problem in AliceO2, actually, as stated elsewhere. The problem I fixed is the issues with gettext.

**Comment by vascobarroso** [comment]
Forgot to mention: I had to install perl-Digest-SHA due to [this alibuild commit](https://github.com/alisw/alibuild/commit/611fd564e3b065845e7d6041080177d002ebfd4f).

**Comment by ktf** [comment]
alisw/alibuild#154 hopefully fixes the  sha1sum / perl-Digest-SHA dependency once for all.

**Pull request merged**
