### PR TITLE
[O2-1652] Mirror DIM package in alisw and add back ALF

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf I think build fails because:
- currently ZIP source code has been download during each build and deleted after build
- aliBuild does not pull source code from Git as it thinks that it is already there

**Review by Barthelemy — APPROVED** [review]
good

**Review by kostorr — APPROVED** [review]

**Comment by awegrzyn** [comment]
So IMO smooth transition would be:
- bring back ZIP download (keep it together with GH clone)
- remove ZIP download in a while

**Comment by ktf** [comment]
@awegrzyn agreed. I can probably restart the build container as well, but that will introduce delays as well.

**Pull request merged**
