### PR TITLE
Add dependency to common-o2

### PR DESCRIPTION
**Pull request by Barthelemy**
Configuration needs a dependency to common-o2

### CODE REVIEW

**Comment by matthiasrichter** [comment]
Hi @Barthelemy , can we maybe find a better name for the `Configuration` project? I had problems understanding the setup, as file names like `configuraton.sh` are very general and cause a wrong guidance.

**Comment by Barthelemy** [comment]
Hi @matthiasrichter , 
I understand the issue. It is not easy as the pcakge is really taking care of configuration. 

This should perhaps be discussed with @vascobarroso and @PascalBoeschoten .

**Comment by dberzano** [comment]
@matthiasrichter remember we're using a piece of software called ROOT :-) (just kidding!)

**Comment by vascobarroso** [comment]
@matthiasrichter no problem in changing if a better naming can be found. What did you have in mind ?

**Pull request merged**
