### PR TITLE
Update ninja.sh

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02, can you try with this? I think something changed in ubuntu where python2 is not there anymore.

**Review by shahor02 — APPROVED** [review]
It worked now, thanks!

**Comment by shahor02** [comment]
... but not on slc7 as CI shows.

**Comment by ktf** [comment]
Not sure this is still relevant. Reopen if the case.

**Comment by chiarazampolli** [comment]
Ciao Giulio, 

I had still issues some days ago without this patch on Ubuntu.

Chiara

**Comment by ktf** [comment]
Ok, bumping the build to see if it actually still works.

**Comment by ktf** [comment]
The rebuild worked out just fine, so I am merging this.

**Pull request merged**
