### PR TITLE
Bump the ROOT Grid plugins versions

### PR DESCRIPTION
**Pull request by Atlantic777**
Update the ROOT Grid plugins, support for MacOS Catalina and ROOT 6.18.

### CODE REVIEW

**Comment by Atlantic777** [comment]
This pull request needs to be merged together with https://github.com/alisw/AliRoot/pull/1062

**Comment by ktf** [comment]
```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliRoot/build_AliRoot_alidist/0/ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx: In static member function 'static Bool_t AliAnalysisAlien::MergeInfo(const char*, const char*)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliRoot/build_AliRoot_alidist/0/ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx:2920:28: error: 'createGridCollection' was not declared in this scope
    TGridCollection *coll = createGridCollection(collection);
                            ^~~~~~~~~~~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliRoot/build_AliRoot_alidist/0/ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx:2920:28: note: suggested alternative: 'TGridCollection'
    TGridCollection *coll = createGridCollection(collection);
                            ^~~~~~~~~~~~~~~~~~~~
                            TGridCollection
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliRoot/build_AliRoot_alidist/0/ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx: In static member function 'static Bool_t AliAnalysisAlien::MergeOutput(const char*, const char*, Int_t, Int_t)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliRoot/build_AliRoot_alidist/0/ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx:2980:31: error: 'createGridCollection' was not declared in this scope
       TGridCollection *coll = createGridCollection(basedir);
                               ^~~~~~~~~~~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliRoot/build_AliRoot_alidist/0/ANALYSIS/ANALYSISaliceBase/AliAnalysisAlien.cxx:2980:31: note: suggested alternative: 'TGridCollection'
       TGridCollection *coll = createGridCollection(basedir);
                               ^~~~~~~~~~~~~~~~~~~~
                               TGridCollection
[ 37%] Generating G__ANALYSIScalib.cxx, G__ANALYSIScalib.h
```

**Comment by Atlantic777** [comment]
Actually, this was expected to fail with the current version of AliRoot. It should work fine after the AliRoot PR is merged (https://github.com/alisw/AliRoot/pull/1062).

Anyways, I think we have a nicer workaround that doesn't require any changes in AliRoot. Is it safe to retag on our side, or it's better if we create a new tag for the Grid plugins?

**Comment by ktf** [comment]
Please retag.

**Comment by Atlantic777** [comment]
I believe this is ready to be merged now, but I am still waiting for an answer from the users that this fix works for them.

**Comment by ktf** [comment]
Any news on this?

**Comment by Atlantic777** [comment]
Well, I didn't get any news but I think it's good to be merged. It works for me. By the way, this should also unblock the ROOT 6.18 PR https://github.com/alisw/alidist/pull/1876 from @mpuccio .

**Comment by mpuccio** [comment]
It works also for me on OSX Catalina.

**Pull request merged**
