### PR TITLE
Bump FairMQ to v1.4.45

### PR DESCRIPTION
**Pull request by rbx**
Contains APIs needed for R3C-646 and improvements to significantly improve behavior described in O2-2737.

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]
thx a lot!
will wait for the CI, and then also run a manual test on the EPNs

**Comment by davidrohr** [comment]
unfortunately O2 dev is broken, I cannot run full system test with DD on the EPNs, will continue debugging this tomorrow. This PR should remain on hold in the meantime.

**Comment by ktf** [comment]
@davidrohr what is broken?

**Comment by davidrohr** [comment]
The problem with dev comes from here: https://github.com/AliceO2Group/AliceO2/pull/7927

I will now retry with FMQ 1.4.45 with the header changes reverted.

**Review by davidrohr — APPROVED** [review]
this looks good now.
FST starting from DD runs
And speedup is as expected.

**Pull request merged**
