### PR TITLE
Bump gRPC to v1.27.1

### PR DESCRIPTION
**Pull request by teo**
Related: https://alice.its.cern.ch/jira/browse/O2-1125

### CODE REVIEW

**Comment by ktf** [comment]
Notice this will not be enough. You will need the fix proposed in AliceO2Group/Configuration#51 as well.

**Comment by teo** [comment]
@ktf not sure I understand, I'm not using Travis with gRPC at all?

**Comment by ktf** [comment]
Do you build on macOS with travis? The issue is only there.

**Comment by teo** [comment]
@awegrzyn can you advise on this? Do we need to change the CMake of our packages that use gRPC?

**Pull request merged**
