### PR TITLE
Bump qualitycontrol to v1.32.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by Barthelemy** [comment]
@alisw/infrastructure-admins any idea why fullCI is failing ? could you force merge if it is not related ? thank you

**Comment by ktf** [comment]
My bad... Apologies. It was fixed this morning but apparently it did not rebuild yet. Shall I just merge it or do you want to restart the test?

**Comment by ktf** [comment]
@davidrohr looks like we have an actual issue:

```
/opt/rocm/hip/bin/hipcc -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DCUDA_ENABLED -DDPL_ENABLE_BACKTRACE -DENABLE_UPGRADES -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -DGPUCA_BUILD_EVENT_DISPLAY -DGPUCA_BUILD_QA -DGPUCA_DISPLAY_GL3W -DGPUCA_DISPLAY_OPENGL_CORE -DGPUCA_GPULIBRARY=HIP -DGPUCA_HAVE_O2HEADERS -DGPUCA_O2_LIB -DGPUCA_TPC_GEOMETRY_O2 -DHIP_ENABLED -DO2lib_GPUTrackingHIP_EXPORTS -DOPENCL1_ENABLED -DOPENCL2_ENABLED -DWITH_OPENMP -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/TRD/base/src -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Reconstruction/src -IGPU/GPUTracking/Base/hip -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Definitions -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/DataTypes -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/SliceTracker -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/TPCConvert -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/dEdx -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/ITS -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/TRDTracking -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/qa -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/display -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Global -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/HLTHeaders -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Interface -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Merger -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Refit -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Debug -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/DataCompression -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/TPCClusterFinder -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/Common -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Framework/Logger/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/Utils -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Reconstruction/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Detectors/Common/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Common/MathUtils/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Common/Constants/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Headers/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/MemoryResources/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Utilities/rANS/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Common/Utils/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/common/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Detectors/TPC/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/simulation/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Common/Field/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Framework/Core/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/CCDB/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Framework/Foundation/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Framework/Foundation/3rdparty/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Utilities/PCG/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Parameters/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Common/Types/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Common/SimConfig/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Algorithm/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Detectors/TOF/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/TPC/base/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Raw/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/TRD/base/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Detectors/TRD/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/TOF/base/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/ITSMFT/ITS/base/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/ITSMFT/common/base/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/ITSMFT/ITS/tracking/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Detectors/ITSMFT/common/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Detectors/ITSMFT/ITS/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/TPCFastTransformation -I/sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/TPCFastTransformation/devtools -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Steer/include -I/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/ITSMFT/ITS/tracking/GPU -isystem /sw/slc8_x86-64/fmt/7.1.0-7/include -isystem /sw/slc8_x86-64/FairLogger/v1.10.1-1/include -isystem /sw/slc8_x86-64/ROOT/v6-24-06-local1/include -isystem /sw/slc8_x86-64/FairRoot/v18.4.2-local1/include -isystem /sw/slc8_x86-64/arrow/v5.0.0-alice1-local1/include -isystem /sw/slc8_x86-64/Vc/1.4.1-10/include -isystem /sw/slc8_x86-64/FairMQ/v1.4.42-local1/include/fairmq -isystem /sw/slc8_x86-64/FairMQ/v1.4.42-local1/include -isystem /sw/slc8_x86-64/boost/v1.75.0-local1/include -isystem /sw/slc8_x86-64/ms_gsl/3.1.0-2/include -isystem /sw/slc8_x86-64/Common-O2/v1.6.0-local1/include -isystem /sw/slc8_x86-64/Configuration/v2.6.3-local1/include -isystem /sw/slc8_x86-64/libInfoLogger/v2.1.1-local1/include -isystem /sw/slc8_x86-64/Monitoring/v3.8.9-local1/include -isystem /sw/slc8_x86-64/libjalienO2/0.1.3-7/include -isystem /sw/slc8_x86-64/RapidJSON/v1.1.0-alice2-10/include -isystem /sw/slc8_x86-64/libuv/v1.40.0-9/include -isystem /sw/slc8_x86-64/DebugGUI/v0.6.1-3/include -isystem /sw/slc8_x86-64/GLFW/3.3.2-9/include -isystem /opt/rocm-4.3.0/hip/include -isystem /opt/rocm-4.3.0/include -isystem /opt/rocm-4.3.0/hip/../include -isystem /opt/rocm/llvm/lib/clang/13.0.0/include/.. -isystem /opt/rocm-4.3.0/hipcub/include -isystem /opt/rocm-4.3.0/rocprim/include -isystem /opt/rocm-4.3.0/rocthrust/include -fPIC -O2 -std=c++17 -fcuda-flush-denormals-to-zero -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -Wno-invalid-constexpr -Wno-ignored-optimization-argument -Wno-unused-private-field --amdgpu-target=gfx906 -fno-gpu-rdc -O2 -g -DNDEBUG -fPIC -xhip --offload-arch=gfx906 -std=c++17 -MD -MT GPU/GPUTracking/Base/hip/CMakeFiles/O2lib-GPUTrackingHIP.dir/GPUReconstructionHIP.hip.cxx.o -MF GPU/GPUTracking/Base/hip/CMakeFiles/O2lib-GPUTrackingHIP.dir/GPUReconstructionHIP.hip.cxx.o.d -o GPU/GPUTracking/Base/hip/CMakeFiles/O2lib-GPUTrackingHIP.dir/GPUReconstructionHIP.hip.cxx.o -c /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx
In file included from /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx:108:
In file included from /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstructionIncludesDevice.h:63:
/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Reconstruction/src/TrackParametrization.cxx:400:90: error: no member named 'asString' in 'o2::track::TrackParametrization<>'
               << vtx.X() << ' ' << vtx.Y() << ' ' << vtx.Z() << " | Track is: " << tmpT.asString();
                                                                                    ~~~~ ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Reconstruction/src/TrackParametrization.cxx:749:16: note: in instantiation of member function 'o2::track::TrackParametrization<>::propagateParamToDCA' requested here
--
               ^
In file included from /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx:108:
In file included from /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstructionIncludesDevice.h:64:
/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Reconstruction/src/TrackParametrizationWithError.cxx:251:107: error: no member named 'asString' in 'o2::track::TrackParametrizationWithError<float>'
    LOG(debug) << "failed to propagate to alpha=" << alp << " X=" << xv << vtx << " | Track is: " << tmpT.asString();
                                                                                                     ~~~~ ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/DataFormats/Reconstruction/src/TrackParametrizationWithError.cxx:1124:16: note: in instantiation of member function 'o2::track::TrackParametrizationWithError<float>::propagateToDCA' requested here
--
               ^
In file included from /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx:108:
In file included from /sw/SOURCES/O2/3359-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstructionIncludesDevice.h:65:
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:390:107: error: no member named 'asString' in 'o2::track::TrackParametrizationWithError<float>'
    LOG(debug) << "failed to propagate to alpha=" << alp << " X=" << xv << vtx << " | Track is: " << tmpT.asString();
                                                                                                     ~~~~ ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCA' requested here
--
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCA' requested here
template class PropagatorImpl<float>;
               ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:435:107: error: no member named 'asString' in 'o2::track::TrackParametrizationWithError<float>'
    LOG(debug) << "failed to propagate to alpha=" << alp << " X=" << xv << vtx << " | Track is: " << tmpT.asString();
                                                                                                     ~~~~ ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCABxByBz' requested here
--
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCABxByBz' requested here
template class PropagatorImpl<float>;
               ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:481:90: error: no member named 'asString' in 'o2::track::TrackParametrization<>'
               << vtx.X() << ' ' << vtx.Y() << ' ' << vtx.Z() << " | Track is: " << tmpT.asString();
                                                                                    ~~~~ ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCA' requested here
--
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCA' requested here
template class PropagatorImpl<float>;
               ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:525:90: error: no member named 'asString' in 'o2::track::TrackParametrization<>'
               << vtx.X() << ' ' << vtx.Y() << ' ' << vtx.Z() << " | Track is: " << tmpT.asString();
                                                                                    ~~~~ ^
/sw/SOURCES/O2/3359-slc8_x86-64/0/Detectors/Base/src/Propagator.cxx:630:16: note: in instantiation of member function 'o2::base::PropagatorImpl<float>::propagateToDCABxByBz' requested here
```

any idea of what might be wrong?

**Comment by Barthelemy** [comment]
As it is unrelated to QC, could you please merge ?

**Comment by vascobarroso** [comment]
@ktf @davidrohr for today's FLP Suite release, we will pick `nightly-20210924`, which seems to be the last O2 bump with a green CI.

**Comment by ktf** [comment]
As far as I can tell, nightly-20210928 (i.e. https://github.com/alisw/alidist/pull/3355) was all green as well.

**Comment by vascobarroso** [comment]
@ktf ok if you can vouch for that one we will take it. Just let me know ASAP.

**Comment by ktf** [comment]
I can confirm that all the alidist tests for that one are green:

image


 If then there is some other issue with it which is not spotted by the test, I guess it's up to @shahor02 or @davidrohr to say, however, from the CI point of view the alidist configuration at https://github.com/alisw/alidist/pull/3355/commits/f3ea8ac1b6de88f7b31957818fe6d91e420cb36a was fine.

**Comment by vascobarroso** [comment]
Ok, I will then take `nightly-20210928`. Thanks!

**Pull request merged**
