### PR TITLE
Add safety for PROTOBUF_ROOT and add protobuf for osx

### PR DESCRIPTION
**Pull request by PascalBoeschoten**

### CODE REVIEW

**Comment by PascalBoeschoten** [comment]
See issue #950

**Comment by ktf** [comment]
Can you please fix the conflict?

**Comment by PascalBoeschoten** [comment]
@ktf OK now?

**Comment by Barthelemy** [comment]
@ktf this PR should be closed right ?

**Comment by Barthelemy** [comment]
@pippohub @awegrzyn Does Configuration actually depend on protobuf ?

**Comment by awegrzyn** [comment]
Not at all, currently only `RapidJSON` and `PpConsul` are required to compile all backends.

**Comment by awegrzyn** [comment]
@Barthelemy @ktf This should be just closed (without merging).

**Pull request closed without merging**
