### PR TITLE
Revert "Drop ApMon from monitoring"

### PR DESCRIPTION
**Pull request by ktf**
Reverts alisw/alidist#4585

### CODE REVIEW

**Comment by ktf** [comment]
This apparently does not work on the grid. @awegrzyn is there a way to disable explicitly ApMon  support? As far as  I can tell it is being loaded by Monitoring and then it fails because it's not in path anymore.

**Comment by awegrzyn** [comment]
Okay, I'm not aware what's being used on the grid. On FLPs we disable it in `defaults-o2-dataflow.sh`. If you want to disable it during runtime, I don't think it's possible atm.

**Comment by ktf** [comment]
I meant I wanted to disable it at build time.  In principle, no one is using it, so I am not sure how we can end up with Monitoring linking against it. Maybe it's actually somehow found in the docker image? Do you have some cmake flag which does not even look for it on the system?

**Comment by awegrzyn** [comment]
True, you're right, it does look in `/usr/local`. Lemme disable it.

**Comment by ktf** [comment]
Indeed I think this is the issue...

**Pull request merged**
