### PR TITLE
datadist: bump to v1.0.17

### PR DESCRIPTION
**Pull request by ironMann**
@davidrohr @vascobarroso this is for the next FLP Suite. FLP and EPN packages must be bumped together.

### CODE REVIEW

**Comment by vascobarroso** [comment]
@ironMann ok thanks! 
@davidrohr, the deployment of the next FLP Suite will happen on the usual slot: Monday at 08:30. Is that ok for the EPN update ?

**Comment by davidrohr** [comment]
ok, this is annoying, probably we have to bump fmt and fairlogger in parallel.
For deploying in parallel, that should be fine. If FLP places it in the new FLPSuite, I'll make sure to have the build ready for the EPNs on monday

**Comment by davidrohr** [comment]
Checking what happens when we bump all 3 in #3566

**Comment by ironMann** [comment]
@davidrohr sorry, forgot to include logger fixes. This is now DD v1.0.16

**Comment by davidrohr** [comment]
@ironMann : There is another such issue now:
```
## sw/BUILD/DataDistribution-latest/log
--
Scanning dependencies of target monitoring
[ 59%] Building CXX object src/common/monitoring/CMakeFiles/monitoring.dir/DataDistMonitoring.cxx.o
/sw/SOURCES/DataDistribution/v1.0.16/v1.0.16/src/common/SubTimeFrameFileSink.cxx: In member function 'bool o2::DataDistribution::SubTimeFrameFileSink::makeDirectory()':
/sw/SOURCES/DataDistribution/v1.0.16/v1.0.16/src/common/SubTimeFrameFileSink.cxx:146:116: error: 'fmt::v8::appender fmt::v8::format_to(fmt::v8::basic_memory_buffer<char, SIZE, Allocator>&, fmt::v8::format_string<T ...>, T&& ...) [with T = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; long unsigned int SIZE = 500; Allocator = std::allocator<char>; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >]' is deprecated [-Werror=deprecated-declarations]
  146 |     fmt::format_to(lDir, "run{}_{}", ("0" + DataDistLogger::sRunNumberStr), FilePathUtils::getDataDirName(mRootDir));
      |                                                                                                                    ^
In file included from /sw/SOURCES/DataDistribution/v1.0.16/v1.0.16/src/common/base/DataDistLogger.h:20,
--
[ 68%] Building CXX object src/TfScheduler/CMakeFiles/TfScheduler_lib.dir/TfSchedulerStfInfo.cxx.o
[ 69%] Building CXX object src/TfScheduler/CMakeFiles/TfScheduler_lib.dir/runTfScheduler.cxx.o
cc1plus: all warnings being treated as errors
gmake[2]: *** [src/common/CMakeFiles/common.dir/SubTimeFrameFileSink.cxx.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 69%] Built target TfScheduler_lib
gmake: *** [all] Error 2
```

**Comment by ironMann** [comment]
@davidrohr v1.0.17 should contain the complete adaptation for fmt8

**Comment by davidrohr** [comment]
closing this, since DD bump was merged together with fmt and fairlogger bump

**Comment by davidrohr** [comment]
@vascobarroso : The new FLTSuite will be forked today?
Please make sure it has the latest version of FairMQ / FairLogger / DataDistribution / fmt.
Packages will be updated on the EPN on Monday in parallel.

**Comment by vascobarroso** [comment]
@davidrohr the alidist branch for FLP Suite v0.37.0 will be created tomorrow morning. We will take the new versions.

**Pull request closed without merging**
