### PR TITLE
Bump ODC to 0.50

### PR DESCRIPTION
**Pull request by AndreyLebedev**
@ironMann If possible please update ODC on the EPN to `0.50`

### CODE REVIEW

**Review by ironMann — APPROVED** [review]
@AndreyLebedev next upgrade is on Monday. I'll let you know.

**Comment by ktf** [comment]
@davidrohr @shahor02 looks like fullCI fails with:

```
## sw/BUILD/O2-full-system-test-latest/log
--
Detected critical problem in logfile reco_ASYNC.log
reco_ASYNC.log-[20460:globalfwd-track-matcher]: [20:16:02][INFO] Loaded 0 MCH Tracks  in 5 ROFs
reco_ASYNC.log-[20460:globalfwd-track-matcher]: [20:16:02][INFO] Running MCH-MFT Track Matching.
reco_ASYNC.log:[20460:globalfwd-track-matcher]: terminate called without an active exception
reco_ASYNC.log-[20447:TOFClusterer]: [20:16:02][INFO] skipping empty alignment for ITS
reco_ASYNC.log-[20447:TOFClusterer]: [20:16:02][INFO] skipping empty alignment for TPC
killing child 19755
killing child 19758
killing child 19762
killing child 19764
killing child 19766
killing child 19769
killing child 19806
killing child 20419
killing child 20420
killing child 20421
killing child 20422
killing child 20423
killing child 20424
killing child 20425
killing child 20426
```

**Comment by ktf** [comment]
@Barthelemy looks like we have:

```
## sw/BUILD/QualityControl-latest/log
--
 1/52 Test  #1: testDbFactory ...........................***Timeout  30.03 sec
--
98% tests passed, 1 tests failed out of 52
```

for QC.

**Comment by ktf** [comment]
Errors unrelated. Merging.

**Pull request merged**
