### PR TITLE
Always use werror in QC

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by mfasDa** [comment]
I had yesterday my issues with a different package (ReadoutCard) that suddenly stopped compiling under *ubuntu* - a wide spread distribution in the collaboration - because of Werror. With this change you will make the package compiler dependent. Even though this might be decided by the O2 management (I don't know what is the push for this): I don't think it is a good idea what you are doing here, even if Werror can be useful to force warnings to be corrected - it might be that your package will stop work on platforms that are wide spread in the collaboration. This is good for a debug setup but not for a production setup.

**Comment by ktf** [comment]
Please fix this in the QC Cmakelists

**Review by ktf — CHANGES_REQUESTED** [review]
Should be done in the CMakeLists.txt, IMHO.

**Comment by ktf** [comment]
@mfasDa I would say we spend more time chasing the kind of issues this trick brings us than the required support for ubuntu (for which we have even CI tests now). If very big issues arise, we can always turn of the spurious warnings.

**Comment by Barthelemy** [comment]
so let's drop this PR and continue happily with using werror in the PRs checks.

**Comment by Barthelemy** [comment]
https://alice.its.cern.ch/jira/browse/QC-512

**Pull request closed without merging**
