### PR TITLE
Allow defaults to customise python modules

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@teo @sy-c @Barthelemy @awegrzyn @ironMann, could you stress test this? it should reduce your Python-modules building pains when using the `o2-dataflow` default.

**Comment by Barthelemy** [comment]
I am testing on cc7 for o2-dataflow.

**Comment by Barthelemy** [comment]
I get an error building arrow : 
```
[  9%] Built target arrow_dependencies
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/arrow/util/basic_decimal.cc:18:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/arrow/util/basic_decimal.h:20:10: fatal error: 'array' file not found
#include <array>
         ^~~~~~~
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/decimal_wrapper.cc:18:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/decimal_ops.h:20:10: fatal error: In file included from 'cstdint' 
file not found
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/decimal_ops.cc:20:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/decimal_ops.h:20:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
#include <cstdint>
         ^~~~~~~~~
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/timestamp_arithmetic.cc:18:
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./epoch_time_point.h:22:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/../../arrow/vendored/datetime/date.h:42:10: fatal error: 'cassert'
 file not found
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/time.cc:18:
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./epoch_time_point.h:22:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/../../arrow/vendored/datetime/date.h:42:10: fatal error: #include 
<cassert>'cassert' file not found

         ^~~~~~~~~
#include <cassert>
         ^~~~~~~~~
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/arithmetic_ops.cc:20:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./types.h:21:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
make[2]: *** [src/gandiva/precompiled/decimal_wrapper.bc] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/bitmap.cc:20:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/arrow/util/bit-util.h:55:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~
1 error generated.
make[2]: *** [src/gandiva/precompiled/decimal_ops.bc] Error 1
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/hash.cc:22:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./types.h:21:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
make[2]: *** [src/gandiva/precompiled/basic_decimal.bc] Error 1
1 error generated.
make[2]: *** [src/gandiva/precompiled/bitmap.bc] Error 1
1 error generated.
1 error generated.
make[2]: *** [src/gandiva/precompiled/arithmetic_ops.bc] Error 1
make[2]: *** [src/gandiva/precompiled/hash.bc] Error 1
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/print.cc:22:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./types.h:21:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
make[2]: *** [src/gandiva/precompiled/print.bc] Error 1
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/string_ops.cc:25:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./types.h:21:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
In file included from /home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/extended_math_ops.cc:24:
/home/bvonhall/alice/sw/SOURCES/arrow/v0.14.1/apache-arrow-0.14.1/cpp/src/gandiva/precompiled/./types.h:21:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
make[2]: *** [src/gandiva/precompiled/time.bc] Error 1
1 error generated.
make[2]: *** [src/gandiva/precompiled/timestamp_arithmetic.bc] Error 1
1 error generated.
1 error generated.
make[2]: *** [src/gandiva/precompiled/string_ops.bc] Error 1
make[2]: *** [src/gandiva/precompiled/extended_math_ops.bc] Error 1
make[1]: *** [src/gandiva/precompiled/CMakeFiles/precompiled.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ktf** [comment]
Do you have the devtoolset7 installed?

**Comment by sawenzel** [comment]
Is devtoolset7 now actually an official requirement? If yes, it should be checked by the tool. I saw this error before when I tried compiling without the toolset.

**Comment by Barthelemy** [comment]
I have devtoolset 4, 6,7,8 installed but none loaded. I did not know that I had to actually load it to compile. This machine is our build machine and we did not have problem. 

I agree with sandro. If it is a requirement, it should be tested and explicitely installed. 

This being said, as we are downloading the tarballs on CC7 I don't see the point of relying on devtoolset.

**Comment by sawenzel** [comment]
Maybe the question did not mean that it is required ... though.

**Comment by Barthelemy** [comment]
yes, sorry, should not have jumped to conclusion.

This being said, I tried with devtoolset 7 and 8 and it did not help.

**Comment by Barthelemy** [comment]
trying again from scratch

**Comment by ktf** [comment]
Since ever, actually: https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-centos7.html.
That said, it's actually a bad idea, IMHO, since we should be able to build our own GCC.

**Comment by ktf** [comment]
Can you try with devtools7 and --no-system?

**Comment by ktf** [comment]
Sorry:  --always-prefer-system

**Comment by ktf** [comment]
I suspect the problem is that LLVM cannot be properly downloaded and installed from binaries.

**Comment by Barthelemy** [comment]
I had alreadz relogged to the server, loaded devtoolset-7 and relaunched a build and this time it seems to be building GCC. It will take some time but I would like to see if it works.

**Comment by sawenzel** [comment]
@ktf: Devtoolset is not actually listed in the section `Install or upgrade the required packages` of that document. I always understood that it is a convenience mechanism in order to avoid building gcc (Why would we need a gcc recipe otherwise?). I would be in favour of really mapping requirements to a build level check.

**Comment by ironMann** [comment]
I'll give this a go now. For the record, I have devtools8 enabled, but without `--always-prefer-system` GCC is always being built. Either way worked for alidist/master, but fewer dependencies is better, IMO.

**Comment by ktf** [comment]
@ironMann I suspect it rebuilds GCC because you do not have gfortran (sigh).
Can you run `aliBuild doctor GCC-Toolchain` to confirm?

**Comment by ktf** [comment]
We have the `GCC-Toolchain` for the grid, where we cannot impose devtoolset.

**Comment by ironMann** [comment]
@ktf I install all devtools8-* packages. However, this is output on top of current alidist/master:
```
cc --version
cc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
```
```
aliBuild version
aliBuild version: 1.5.5 (slc7_x86-64)
```
```
aliBuild doctor GCC-Toolchain --debug --defaults o2-dataflow

SUCCESS: Package GCC-Toolchain will be picked up from the system.
DEBUG: GCC-Toolchain: /opt/rh/devtoolset-8/root/usr/bin/gfortran
DEBUG: GCC-Toolchain: /opt/rh/devtoolset-8/root/usr/bin/cc
==> The following packages will be picked up from the system:
    - GCC-Toolchain
```
```
aliBuild doctor DataDistribution --debug --defaults o2-dataflow
==> The following packages will be built by aliBuild because usage of a system version of it is not allowed or supported, by policy:
    - Monitoring
    - googlebenchmark
    - DataDistribution
    - Ppconsul
    - MCStepLogger
    - O2
    - Common-O2
    - FairLogger
    - defaults-release
    - libInfoLogger
    - DebugGUI
    - RapidJSON
    - DDS
    - cub
    - Configuration
    - ROOT
    - ms_gsl
    - LLVM
    - protobuf
    - grpc
    - googletest
    - FairMQ
    - libffi
    - double-conversion
    - c-ares
    - FairRoot
    - Python-modules
    - Vc
    - re2
    - asiofi
    - arrow
    - fmt
==> The following packages will be picked up from the system:
    - lzma
    - FreeType
    - zlib
    - libxml2
    - ofi
    - OpenSSL
    - sqlite
    - lz4
    - GCC-Toolchain
    - GLFW
    - libpng
    - autotools
==> The following packages will be built by aliBuild because they couldn't be picked up from the system:
    - CMake
    - Python
    - flatbuffers
    - yaml-cpp
    - ZeroMQ
    - boost
    - GSL

```
However:
```
aliBuild build DataDistribution --debug --defaults o2-dataflow

DEBUG: Using aliBuild from alibuild@DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
DEBUG: 1.5.5 recipes in alidist@d21cfa3bcc55f5b23df669d893681a78adc5f91c
DEBUG: Overrides for package O2: {'version': '%(short_hash)s%(defaults_upper)s', 'tag': 'dev'}
DEBUG: Overrides for package defaults-release: {'env': OrderedDict([('CXXFLAGS', '-fPIC -O2 -std=c++17'), ('CFLAGS', '-fPIC -O2'), ('CMAKE_BUILD_TYPE', 'RELWITHDEBINFO'), ('CXXSTD', '17')])}

==> Packages will be built in the following order:
     - ms_gsl@b014508
     - autotools@v1.5.0
     - cub@v1.8.0
     - libffi@v3.2.1
     - GCC-Toolchain@v7.3.0-alice1
     - sqlite@v3.15.0
     - ofi@v1.7.1
     - FreeType@v2.6
     - lzma@v5.2.3
     - CMake@v3.13.1
     - zlib@v1.2.8
     - lz4@v1.8.3
     - ZeroMQ@v4.1.5
     - GSL@release-1-16
     - LLVM@llvmorg-7.1.0
     - FairLogger@v1.5.0
     - googlebenchmark@v1.3.0
     - re2@2019-09-01
     - fmt@5.3.0
     - Vc@1.4.1
     - googletest@release-1.8.0
     - GLFW@090b16bfae282606472f876d6b2fd23f
     - libpng@v1.6.34
     - double-conversion@v3.1.5
     - c-ares@cares-1_15_0
     - RapidJSON@091de040edb3355dcf2f4a18c425aec51b906f08
     - protobuf@v3.7.1
     - libxml2@v2.9.3
     - OpenSSL@OpenSSL_1_0_2o
     - flatbuffers@v1.11.0
     - DebugGUI@55c12c2
     - Python@v3.6.8
     - grpc@v1.19.1
     - Python-modules@1.0
     - boost@v1.70.0
     - Common-O2@v1.4.6
     - Ppconsul@e32cf6f80b598760278c018eed546f88292f1735
     - DDS@2.4
     - libInfoLogger@v1.3.7
     - asiofi@v0.3.1
     - yaml-cpp@yaml-cpp-0.6.2
     - arrow@apache-arrow-0.14.1
     - Monitoring@v2.6.3
     - Configuration@v2.2.4
     - FairMQ@v1.4.9
     - ROOT@v6-18-04
     - MCStepLogger@master
     - FairRoot@6af7e848585ce720e96a01d5565b1bd5e3884430
     - O2 (development package)
     - DataDistribution@v0.7
```

**Comment by ktf** [comment]
Ah, that's because on slc7 by default we download binaries, so the system packages are not used for anything (because we cannot guarantee that the binaries were built in a way compatible with the system package). If you want to reuse your system installation you need to add `--always-prefer-system`, but that on the other hand will not download any prebuilt package.

To summarise:

* By default on slc7 we download everything as binaries.
* If you specify `--always-prefer-system` no binaries will be downloaded.
* For other systems (mac, ubuntu) we provide no binaries, so `--always-prefer-system` is the default option.

**Comment by ironMann** [comment]
@ktf I'm not sure what you mean by download as binaries. What I see is git downloading sources and the full configure/build of each of those dependencies as listed above. Tool-chains and the rest. Is there a flag for that?

This is created by the clean aliBuild in my case, after the GCC was built from source:

```
ls -R sw/TARS/slc7_x86-64/GCC-Toolchain/ -l
... 
GCC-Toolchain-v6.2.0-alice1-4.slc7_x86-64.tar.gz -> unknown
GCC-Toolchain-v6.2.0-patches-1.slc7_x86-64.tar.gz -> unknown
GCC-Toolchain-v7.3.0-alice1-10.slc7_x86-64.tar.gz -> unknown
GCC-Toolchain-v7.3.0-alice1-11.slc7_x86-64.tar.gz -> ../../slc7_x86-64/store/fb/fb77d0f100540ac0567ee0c185346dccbfd7691c/GCC-Toolchain-v7.3.0-alice1-11.slc7_x86-64.tar.gz
GCC-Toolchain-v7.3.0-alice1-12.slc7_x86-64.tar.gz -> unknown
GCC-Toolchain-v7.3.0-alice1-1.slc7_x86-64.tar.gz -> unknown
...
```

**Comment by ktf** [comment]
git download is unfortunately there in any case. There is a patch in alibuild which might remove the need for it, but I did not have the time to review it fully.

If you build with --debug you should see that the tarballs are actually downloaded from the repo and extracted.

**Comment by ktf** [comment]
(that said, I am currently trying to fix the underlaying issue, as it's affecting me as well).

**Comment by ironMann** [comment]
OK. So here's what is printed with --debug flag. This URL returns an empty json object for me. It's the same for each packet.
```
DEBUG:DataDistribution:GCC-Toolchain:v0.7: Updating from tarballs
DEBUG:DataDistribution:GCC-Toolchain:v0.7: Updating remote store for package GCC-Toolchain@abbf9de6748650b5e299d8022a4a2efded26e37e
DEBUG:DataDistribution:GCC-Toolchain:v0.7: GET https://alicache.cern.ch//TARS/slc7_x86-64/store/ab/abbf9de6748650b5e299d8022a4a2efded26e37e/: processing (attempt 1/4)
WARNING:DataDistribution:GCC-Toolchain:v0.7: GCC-Toolchain (abbf9de6748650b5e299d8022a4a2efded26e37e) not fetched: have you tried updating the recipes?
DEBUG:DataDistribution:GCC-Toolchain:v0.7: Checking for packages already built.
DEBUG:DataDistribution:GCC-Toolchain:v0.7: Glob pattern used: /home/neskovic/o2alice/sw/TARS/slc7_x86-64/GCC-Toolchain/GCC-Toolchain-v7.3.0-alice1-*.slc7_x86-64.tar.gz
DEBUG:DataDistribution:GCC-Toolchain:v0.7: Packages already built using this version
DEBUG:DataDistribution:GCC-Toolchain:v0.7:
DEBUG:DataDistribution:GCC-Toolchain:v0.7: Looking for cached tarball in /home/neskovic/o2alice/sw/TARS/slc7_x86-64/store/ab/abbf9de6748650b5e299d8022a4a2efded26e37e
DEBUG:DataDistribution:GCC-Toolchain:v0.7: No cache tarballs found
DEBUG:DataDistribution:GCC-Toolchain:v0.7: OrderedDict([('package', 'GCC-Toolchain'), ('version', 'v7.3.0-alice1'), ('tag', 'v7.3.0-alice1'), ('source', 'https://github.com/alisw/gcc-toolchain'), ('prepend_path', OrderedDict([('LD_LIBRARY_PATH', ['$GCC_TOOLCHAIN_ROOT/lib', '$GCC_TOOLCHAIN_ROOT/lib64']), ('DYLD_LIBRARY_PATH', ['$GCC_TOOLCHAIN_ROOT/lib', '$GCC_TOOLCHAIN_ROOT/lib64']), ('PATH', ['$GCC_TOOLCHAIN_ROOT/bin'])])), ('build_requires', ['autotools', 'defaults-release']), ('prefer_system', '.*'), ('prefer_system_check', 'set -e\nwhich gfortran || { echo "gfortran missing"; exit 1; }\nwhich cc && test -f $(dirname $(which cc))/c++ && printf "#define GCCVER ((__GNUC__ << 16)+(__GNUC_MINOR__ << 8)+(__GNUC_PATCHLEVEL__))\\n#if (GCCVER < 0x070300)\\n#error \\"System\'s GCC cannot be used: we need at least GCC 7.X. We are going to compile our own version.\\"\\n#endif\\n" | cc -xc++ - -c -o /dev/null\n'), ('requires', ['autotools', 'defaults-release']), ('runtime_requires', []), ('recipe', '#!/bin/bash -e\n\nunset CXXFLAGS\nunset CFLAGS\n\necho "Building GCC because no compatible version was found on the system. To skip this step, install GCC 4.8 or 4.9, or 5.X (with the exception of 5.0 to 5.2). Make sure you have gfortran installed too."\n\nUSE_GOLD=\ncase $ARCHITECTURE in\n  osx*)\n    EXTRA_LANGS=\',objc,obj-c++\'\n    MARCH=\n  ;;\n  *x86-64)\n    MARCH=\'x86_64-unknown-linux-gnu\'\n  ;;\n  *)\n    MARCH=\n  ;;\nesac\n\nrsync -a --exclude=\'**/.git\' --delete --delete-excluded "$SOURCEDIR/" ./\n\n# Binutils\nmkdir build-binutils\npushd build-binutils\n  ../binutils/configure --prefix="$INSTALLROOT"                \\\n                        ${MARCH:+--build=$MARCH --host=$MARCH} \\\n                        ${USE_GOLD:+--enable-gold=yes}         \\\n                        --enable-ld=default                    \\\n                        --enable-lto                           \\\n                        --enable-plugins                       \\\n                        --enable-threads                       \\\n                        --disable-nls\n  make ${JOBS:+-j$JOBS} MAKEINFO=":"\n  make install MAKEINFO=":"\n  hash -r\npopd\n\n# Test program\ncat > test.c <<EOF\n#include <string.h>\n#include <stdio.h>\nint main(void) { printf("The answer is 42.\\n"); }\nEOF\n\n# GCC and deps\npushd gcc\n  for EXT in mpfr gmp mpc isl cloog; do\n    pushd $EXT\n      autoreconf -ivf\n    popd\n  done\npopd\n\nmkdir build-gcc\npushd build-gcc\n  ../gcc/configure --prefix="$INSTALLROOT"                          \\\n                   ${MARCH:+--build=$MARCH --host=$MARCH}           \\\n                   --enable-languages="c,c++,fortran${EXTRA_LANGS}" \\\n                   --disable-multilib                               \\\n                   ${USE_GOLD:+--enable-gold=yes}                   \\\n                   --enable-ld=default                              \\\n                   --enable-lto                                     \\\n                   --disable-nls\n  make ${JOBS+-j $JOBS} bootstrap-lean MAKEINFO=":"\n  make install MAKEINFO=":"\n  hash -r\n\n  # GCC creates c++, but not cc\n  ln -nfs gcc "$INSTALLROOT/bin/cc"\n  rm -rf "$INSTALLROOT/lib/pkg-config"\n\n  # Provide a custom specs file if needed\n  #SPEC="$(dirname $(gcc -print-libgcc-file-name))/specs"\n  #gcc -dumpspecs > $SPEC\n  #perl -pe \'++$x and next if /^\\*link:/; $x-- and s/^(.*)$/\\1 -rpath-link \\/lib64:\\/lib/ if $x\' $SPEC > $SPEC.0\n  #mv $SPEC.0 $SPEC\n\n  rm -f $INSTALLROOT/lib/*.la \\\n        $INSTALLROOT/lib64/*.la\npopd\n\n# From now on, use own linker and GCC\nexport PATH="$INSTALLROOT/bin:$PATH"\nexport LD_LIBRARY_PATH="$INSTALLROOT/lib64:$INSTALLROOT/lib:$LD_LIBRARY_PATH"\nexport DYLD_LIBRARY_PATH="$INSTALLROOT/lib64:$INSTALLROOT/lib:$DYLD_LIBRARY_PATH"\nhash -r\n\n# Test own linker and own GCC\nwhich ld\nwhich g++\ng++ test.c\n./a.out\nrm -f a.out\n\n# GDB\nmkdir build-gdb\npushd build-gdb\n  ../gdb/configure --prefix="$INSTALLROOT"                \\\n                   ${MARCH:+--build=$MARCH --host=$MARCH} \\\n                   --without-python                       \\\n                   --disable-multilib\n  make ${JOBS:+-j$JOBS} MAKEINFO=":"\n  make install MAKEINFO=":"\n  hash -r\n  rm -f $INSTALLROOT/lib/*.la\npopd\n\n# If fixincludes is not desired, see:\n# http://ewontfix.com/12/\n# https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/eclass/toolchain.eclass?view=markup&sortby=log#l1524\n\n# Modulefile\nMODULEDIR="$INSTALLROOT/etc/modulefiles"\nMODULEFILE="$MODULEDIR/$PKGNAME"\nmkdir -p "$MODULEDIR"\ncat > "$MODULEFILE" <<EoF\n#%Module1.0\nproc ModulesHelp { } {\n  global version\n  puts stderr "ALICE Modulefile for $PKGNAME $PKGVERSION-@@PKGREVISION@$PKGHASH@@"\n}\nset version $PKGVERSION-@@PKGREVISION@$PKGHASH@@\nmodule-whatis "ALICE Modulefile for $PKGNAME $PKGVERSION-@@PKGREVISION@$PKGHASH@@"\n# Dependencies\nmodule load BASE/1.0\n# Load Toolchain module for the current platform. Fallback on this one\nregexp -- "^(.*)/.*\\$" [module-info name] dummy mod_name\nif { "\\$mod_name" == "GCC-Toolchain" } {\n  module load Toolchain/GCC-${PKGVERSION//-*}\n  if { [is-loaded Toolchain] } { continue }\n  set base_path \\$::env(BASEDIR)\n} else {\n  # Loading Toolchain: autodetect prefix\n  set base_path [string map "/etc/toolchain/modulefiles/ /" \\$ModulesCurrentModulefile]\n  set base_path [string map "/Modules/modulefiles/ /" \\$base_path]\n  regexp -- "^(.*)/.*/.*\\$" \\$base_path dummy base_path\n  set base_path \\$base_path/Packages\n}\n# Our environment\nsetenv GCC_TOOLCHAIN_ROOT \\$base_path/GCC-Toolchain/\\$version\nprepend-path LD_LIBRARY_PATH \\$::env(GCC_TOOLCHAIN_ROOT)/lib\n$([[ ${ARCHITECTURE:0:3} == osx ]] && echo "prepend-path DYLD_LIBRARY_PATH \\$::env(GCC_TOOLCHAIN_ROOT)/lib")\nprepend-path LD_LIBRARY_PATH \\$::env(GCC_TOOLCHAIN_ROOT)/lib64\n$([[ ${ARCHITECTURE:0:3} == osx ]] && echo "prepend-path DYLD_LIBRARY_PATH \\$::env(GCC_TOOLCHAIN_ROOT)/lib64")\nprepend-path PATH \\$::env(GCC_TOOLCHAIN_ROOT)/bin\nEoF'), ('reference', '/home/neskovic/o2alice/sw/MIRROR/gcc-toolchain'), ('git_heads', ['f8c313eb82a960f2bbc7eee4b971b171e32e013f\trefs/heads/alice/v4.4.7-patches', 'e4df3a5ecc12f6bd0f1cb5f57e9ebf90d403b011\trefs/heads/alice/v4.9.3', '91424963876e0314e4a6c1bb1c5b097944b0b5ed\trefs/heads/alice/v4.9.3-next', '0a214ba04521f06f4eaeb98233f58e9d3827831c\trefs/heads/alice/v4.9.3-patches', '566140dee4986314b24bc918d4760e7460f247c8\trefs/heads/alice/v6', 'dd5f4d4ce0d639c9c0ba94bb02a272af21582531\trefs/heads/alice/v6.2.0-patches', '407b2613ca4081097f99abbc5e17da7e3543d9ab\trefs/heads/alice/v7', '61a1fb6ff726551e5176ff72f903b996cbbf5d22\trefs/heads/master', '']), ('commit_hash', 'v7.3.0-alice1'), ('hash', 'abbf9de6748650b5e299d8022a4a2efded26e37e'), ('deps_hash', 'bebc9f69deb001e958edd82b3a27dbdba609510e'), ('storePath', 'TARS/slc7_x86-64/store/ab/abbf9de6748650b5e299d8022a4a2efded26e37e'), ('linksPath', 'TARS/slc7_x86-64/GCC-Toolchain'), ('tarballHashDir', '/home/neskovic/o2alice/sw/TARS/slc7_x86-64/store/ab/abbf9de6748650b5e299d8022a4a2efded26e37e'), ('tarballLinkDir', '/home/neskovic/o2alice/sw/TARS/slc7_x86-64/GCC-Toolchain'), ('buildDir', '/home/neskovic/o2alice/sw/BUILD/abbf9de6748650b5e299d8022a4a2efded26e37e/GCC-Toolchain'), ('old_devel_hash', '0'), ('full_requires', {'autotools', 'defaults-release'}), ('full_runtime_requires', set()), ('build_family', 'o2-dataflow'), ('revision', '1'), ('cachedTarball', '')])

==> Building GCC-Toolchain@v7.3.0-alice1
...
```

**Comment by ktf** [comment]
I also checked this locally a bit and it seems to work fine on my macOS Catalina installation. I suggest we merge this, as it should solve one of the major issues preventing updatable RPMS of Python-modules, and we handle the fallout separately.

**Pull request merged**
