### PR TITLE
Bump Rivet to 2.7.1-alice1

### PR DESCRIPTION
**Pull request by qgp**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@qgp @pzhristov I will test also locally. Who will take care of the Mac?

**Comment by ktf** [comment]
@jgrosseo

**Comment by jgrosseo** [comment]
@qgp @ktf Please standby for a moment before triggering the building and deployment. @pkarczma has got a message from Andy that there may be a bug in this release

**Comment by pkarczma** [comment]
@qgp @ktf @jgrosseo there is a new 2.7.2 release available, can we bump Rivet directly to 2.7.2?

**Pull request merged**
