### PR TITLE
Bump qualitycontrol to v1.3.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@davidrohr

**Review by awegrzyn — APPROVED** [review]

**Comment by davidrohr** [comment]
@Barthelemy : It seems 1.3.1 does not contain my fix. Could you check?

**Comment by graduta** [comment]
@davidrohr  I can see that this PR was merged without waiting for the builds to be successful and now alidist builds are failing.  E.g https://github.com/alisw/alidist/pull/2528 

I am not sure if this is related but it seems that the errors are present in some QualityControl classes. Could you please have a look?

**Comment by davidrohr** [comment]
@graduta : This was actually supposed to be the fix for the problem you see, but apparently it does not contain AliceO2Group/QualityControl#510. That is why it is still failing.

**Comment by graduta** [comment]
@davidrohr In that case could you please revert the changes as this is blocking others? In my case I cannot release a new version of QCG

**Comment by davidrohr** [comment]
Reverting this will not help, the incompatible change is in O2.

The patch is already in QC, just the tag 1.3.1 does not tag the correct commit.
@Barthelemy @awegrzyn @knopers8 : Could someone create a 1.3.2 containing https://github.com/AliceO2Group/QualityControl/commit/7d510cd6413cf69e942832c917e0ff2dd0d4aca3.

**Comment by Barthelemy** [comment]
Hi, 
Ok, I am checking what happened.

**Comment by Barthelemy** [comment]
indeed, my bad, v1.3.2 incoming

**Comment by Barthelemy** [comment]
v1.3.2 seems to contain the proper commit: https://github.com/AliceO2Group/QualityControl/commits/v1.3.2

Here is the PR: https://github.com/alisw/alidist/pull/2529

**Comment by davidrohr** [comment]
Thx, just tested this locally to be absolutely sure this time :)
Force merged to return to a working state.
Thx for responding quickly

**Pull request merged**
