### PR TITLE
Modernize FairMQ recipe

### PR DESCRIPTION
**Pull request by dennisklein**
@TimoWilken https://github.com/TimoWilken/alidistlint worked like a charm for me (on Fedora 36) thx!

### CODE REVIEW

**Review by TimoWilken — APPROVED** [review]
Hi @dennisklein, thanks, that's good to hear!

This looks good to me; I'll cache this for the CI and then merge this PR when that's done.

**Comment by awegrzyn** [comment]
I can't really understand why, but with this PR I'm getting: `Unable to locate a modulefile for 'FairMQ/v1.4.56-...`

**Comment by dennisklein** [comment]
> I can't really understand why, but with this PR I'm getting: `Unable to locate a modulefile for 'FairMQ/v1.4.56-...`

During build phase or later when loading the runtime?

**Comment by awegrzyn** [comment]
When generating modulefiles: `alienv enter...`

**Comment by dennisklein** [comment]
```diff
diff --git a/fairmq.sh b/fairmq.sh
index 066e7ff0..8e57bff1 100644
--- a/fairmq.sh
+++ b/fairmq.sh
@@ -22,7 +22,7 @@ incremental_recipe: |
   cmake --install . --prefix "${INSTALLROOT}"
   MODULEDIR="etc/modulefiles"
   mkdir -p "${INSTALLROOT}/${MODULEDIR}"
-  rsync -a --delete "${MODULEDIR}" "${INSTALLROOT}/${MODULEDIR}"
+  rsync -a --delete "${MODULEDIR}/" "${INSTALLROOT}/${MODULEDIR}"
 ---
 #!/bin/bash -e

@@ -64,4 +64,4 @@ prepend-path ROOT_INCLUDE_PATH \$PKG_ROOT/include
 prepend-path ROOT_INCLUDE_PATH \$PKG_ROOT/include/fairmq
 EOF
 mkdir -p "${INSTALLROOT}/${MODULEDIR}"
-rsync -a --delete ${MODULEDIR} "${INSTALLROOT}/${MODULEDIR}"
+rsync -a --delete "${MODULEDIR}/" "${INSTALLROOT}/${MODULEDIR}"
```

This should fix it. I will make a PR.

**Pull request merged**
