### PR TITLE
Recipe for ROOT (T)Object diff utility

### PR DESCRIPTION
**Pull request by sawenzel**

### CODE REVIEW

**Comment by sawenzel** [comment]
@pzhristov : This will allow building ObjCmp as part of our toolchain.

**Comment by ktf** [comment]
Can we please host it on `https://github.com/alisw` or `https://github.com/AliceO2Group`?

**Comment by ktf** [comment]
Also we agreed in WP3 at some point we should use a tagged version for all our packages, to avoid unwanted rebuilds, so can you put an hash rather than "master"?

**Comment by sawenzel** [comment]
I can host it somewhere when its stable enough. For now it should be good enough. Will provide a tagged version.

**Comment by sawenzel** [comment]
Tagged version provided

**Comment by ktf** [comment]
Thanks.

**Pull request merged**
