### PR TITLE
Add TpcFecUtils back to O2Suite

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
https://github.com/alisw/alidist/pull/2641

**Comment by ktf** [comment]
@ihrivnac @vkucera looks like you did not update the copyright check.

**Comment by vkucera** [comment]
> @ihrivnac @vkucera looks like you did not update the copyright check.

Why am I tagged?

**Comment by ktf** [comment]
@vkucera by mistake.

**Comment by ihrivnac** [comment]
@ktf, where the  copyright check is defined?

**Comment by ktf** [comment]
In the github workflow. @TimoWilken just fixed it.

**Comment by ihrivnac** [comment]
> In the github workflow. @TimoWilken just fixed it.

Ok, thanks

**Pull request merged**
