### PR TITLE
Drop GEANT4_VMC examples

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by sawenzel** [comment]
Do you have any particular motivation for this change? I have nothing against it, in principle.

**Comment by ktf** [comment]
Not really, I just ended up recompiling it a few times due to changes in ROOT (which were quickly recompiled thank to the incremental build) and this saves 10 / 20 seconds (because it does not have an incremental build). We could also simply add an incremental recipe actually, if you prefer.

**Comment by sawenzel** [comment]
@ihrivnac

**Comment by ihrivnac** [comment]
> @ihrivnac

It's fine with me; I use the examples to test geant4_vmc updates only in stand-alone build

**Comment by ktf** [comment]
Thanks. Dropping it from the main build.

**Pull request merged**
