### PR TITLE
Fix clang compilation on CC7

### PR DESCRIPTION
**Pull request by ihrivnac**
This feix on my side the problem report https://alice.its.cern.ch/jira/browse/O2-1729

### CODE REVIEW

**Comment by ktf** [comment]
The /usr was there because it did not work otherwise in the past. We should do a bit more stress testing before we merge this.

**Comment by ihrivnac** [comment]
@ktf , Andry confirmed in JIRA that the fix works fine on her side, too. Which further stress testing do you propose to validate this?

**Comment by ktf** [comment]
did you try with the devtoolset 7?

**Comment by ihrivnac** [comment]
@ktf, I checked the version now, it should be ok:
```
[root@o2tests02 ~]# yum list installed | grep devtools
devtoolset-7.x86_64                  7.1-4.el7                  @centos-sclo-rh 
...
```

**Pull request merged**
