### PR TITLE
[O2-1736] Add missing python modules to o2-dataflow defaults

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by awegrzyn — APPROVED** [review]

**Comment by Barthelemy** [comment]
it seems to be stuck...

**Comment by ktf** [comment]
@TimoWilken can you check why this one is not being picked up?

**Comment by TimoWilken** [comment]
I'll look into it @ktf!

**Comment by TimoWilken** [comment]
It's the same problem as AliceO2Group/AliceO2#4654. Should be fixed now.

**Pull request merged**
