### PR TITLE
Move ITSresponse in O2 build_requires

### PR DESCRIPTION
**Pull request by mconcas**
@awegrzyn: FYI

### CODE REVIEW

**Comment by martenole** [comment]
@mconcas is this package already required for the O2 nightly tag of today?

**Comment by ktf** [comment]
@martenole notice I had to add it to the "override" packages in the Jenkins job description.

**Comment by martenole** [comment]
I was just wondering, because the WeeklyO2Release build uses the most recent FLP suite branch in alidist. But then it takes the o2 recipe from alidist@master. Here then the ITSresponse package is listed, but its not yet included in the alidist branch from the FLP suite. This makes the build fail with `ERROR: [Errno 2] No such file or directory: 'alidist/itsresponse.sh'`
So for building I am now not overwriting the o2 recipe anymore. Of course this would not work if O2 already required it. But it doesn't yet, this I asked Matteo and he confirmed to me on mattermost

**Comment by ktf** [comment]
@martenole You need to add ITSResponse to the ALIDIST_OVERRIDE_PKGS and you should be fine. I did it now for WeeklyO2Release too.

**Comment by awegrzyn** [comment]
@ktf Could you please merge? This breaks our RPM generation.

**Pull request merged**
