### PR TITLE
Fix module file

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Fixes problem introduced by https://github.com/alisw/alidist/pull/3657

**Comment by ktf** [comment]
this looks wrong to me . what is the error?

**Comment by ctolon** [comment]
I'm also getting problem O2 env.  Logs here:

Loading libInfoLogger/v2.4.1-3
  Module ERROR: can't read "PKG_ROOT": no such variable
    In '/home/batu/alice/sw/MODULES/ubuntu2004_x86-64/libInfoLogger/v2.4.1-3'
    Please contact <root@localhost>

**Comment by benedikt-voelkel** [comment]
Let me check again

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/3665 should be the correct fix.

**Comment by benedikt-voelkel** [comment]
Yes, sorry, I just pushed the wrong thing. Thanks!

**Comment by ktf** [comment]
So this was merely removing the broken packages, I think, which is obviously wrong. The actual fixes are in #3663 and #3662 which use the correct variable for the root of the package (PKG_ROOT is only available when using the alibuild-generate-module helper).

**Comment by Barthelemy** [comment]
sorry about that. There is also the MONITORING_ROOT to use. I can prepare a last PR.

**Comment by Barthelemy** [comment]
https://github.com/alisw/alidist/pull/3666

**Comment by awegrzyn** [comment]
@Barthelemy I don't think it is necessary

**Comment by ktf** [comment]
@Barthelemy indeed I posted the recipe for the automatically generated modulefiles, but forgot that you still had non automatically generated ones.

**Pull request closed without merging**
