### PR TITLE
[xjalienfs] Deal correctly with existing virtual env

### PR DESCRIPTION
**Pull request by aphecetche**
Proposing changes to be able to build from within an existing virtual env : can't use the `--user` option for pip, and don't need to play with paths.

### CODE REVIEW

**Comment by aphecetche** [comment]
@alisw/alien-experts as far as I can tell the CI failure is not directly directed to this PR. Can it be reviewed ? Thanks.

**Comment by aphecetche** [comment]
@alisw/alien-experts any comment on this PR ?

**Comment by costing** [comment]
Adding @adriansev to the thread

**Comment by adriansev** [comment]
i have no opinion on this.. as long as locally `alibuild ... build xjalienfs` works then it's ok... more so if the checks are successful (and the seen errors from O2 are completely unrelated) so, within the mentioned conditions, ACK from me

**Comment by aphecetche** [comment]
@adriansev ok, thanks.
Just wanted to know if there was some objections or not.  
But if ok with you I'd propose to merge this early next year only. Just to avoid any unexpected collateral damage during the Christmas break ;-)

**Comment by pzhristov** [comment]
I tested the compilation on MacOS, everything is OK. If everybody agrees, I will merge this PR.

**Pull request merged**
