### PR TITLE
Update node-gyp when building node recipe

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@MichaelLettrich could you paste the macOS log?

**Review by sy-c — APPROVED** [review]

**Comment by ktf** [comment]
@TimoWilken can you check what is going on with the missing logs?

**Comment by TimoWilken** [comment]
@ktf For build/AliRoot/alidist, it's the same error with DPMJET again:
```
ERROR: Error on 'git ls-remote --heads https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git': fatal: Authentication failed for 'https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git/'
```

**Comment by MichaelLettrich** [comment]
@awegrzyn @ktf @TimoWilken macOS fails with an error to install/update ali-bot inside the CI scripts.

**Comment by ktf** [comment]
@TimoWilken can you check what is wrong on mac here?

**Pull request merged**
