### PR TITLE
bump readout v0.17.0

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
indeed... this is defined in common-o2 which I forgot to push before this update.
PR created: https://github.com/AliceO2Group/Common/pull/21

**Comment by sy-c** [comment]
Hello @ktf @dberzano @sawenzel 
Can this PR please be merged? The failing test is not related to readout.

**Comment by ktf** [comment]
@mkrzewic @matthiasrichter I guess defining o2::vector is not a good idea, after all...

The reason for this to fail spontaneously is the merging of https://github.com/AliceO2Group/AliceO2/pull/1581/files in AliceO2.

**Comment by Barthelemy** [comment]
@ktf thank you, I did not realize. I don't have an opinion whether it is ok or not to have o2::vector. The problem is fixed and understood from my point of view.

**Comment by awegrzyn** [comment]
Can we have it merged please?

**Comment by ktf** [comment]
Errors back to "known state". Merging.

**Pull request merged**
