### PR TITLE
update POWHEG to the official repository

### PR DESCRIPTION
**Pull request by qgp**
- use alisw repository (instead of qgp)
- use tagged version (instead of master)

### CODE REVIEW

**Comment by ktf** [comment]
Thanks. Did you check it works on Mac?

**Comment by qgp** [comment]
No, check on Mac is still pending, sorry ...

**Comment by qgp** [comment]
It's not the most elegant solution, but now we use the C++ compiler for linking, adding the libgfortran explicitly for linking. This works for me both on Linux and Mac OS X.

**Comment by ktf** [comment]
Build went fine on slc5, slc6, slc7. Taking your word for mac ;-). Merging in next.

**Pull request merged**
