### PR TITLE
bump infologger

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Comment by sy-c** [comment]
Hello @alisw/alidist-maitainers  @alisw/infrastructure-admins 
It seems the CI checks are broken for reasons unrelated to this PR.
Can you please advise ?

**Comment by ktf** [comment]
@sy-c there was an out of band (i.e. not managed via alibuild / alidist) update in DataDistribution which broke the builds. @ironMann fixed the issue, but apparently some of the PR checkers still picked up the old version. @TimoWilken could you reset the failing tests?

**Comment by sy-c** [comment]
@alisw/infrastructure-admins any news ?

**Comment by ktf** [comment]
Now merged. @awegrzyn @TimoWilken @MichaelLettrich can you confirm this getting fixed on the mac correlates with aidosx03 (or whatever it was called) being removed from the builders? If yes, how is that machine installed?

**Pull request merged**
