### PR TITLE
Bump to ROOT v6.28/00 + Arrow 11

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@pzhristov this for me works for the tests in hyperloop.

**Comment by davidrohr** [comment]
@ktf : For clang 15, the SPIR-V backend is internal. I am not sure if it still works with the SPIRV-LLVM-Translator, as it is in the current recipe. But let's see, since switching to the internal backend will require changes in O2. If this PR will go through, perfect. Otherwise I'll take care of the SPIRv part.

**Comment by davidrohr** [comment]
The build has failed due to the clang SPIRV translater, what I mentioned before.
The new LLVM has an internal translator, and the external one does not exist in a version for clang15.
I have disabled the build, but this will most likely break the O2 build for GPUs. But let's get this PR pass all CIs except for the FullCI, and then I'll take care of O2 and of the CodeChecker.

**Comment by davidrohr** [comment]
@ktf @aalkin @pzhristov : With my changes, clang is building now. But it seems arrow 11 fails the compilation despite now we have llvm 15 and GCC 12:
```
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/string_ops.cc:20:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/arrow/util/value_parsing.h:31:
/sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/arrow/type.h:28:10: fatal error: 'variant' file not found
#include <variant>
         ^~~~~~~~~
[  6%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/array/builder_base.cc.o
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/decimal_wrapper.cc:18:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/decimal_ops.h:22:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/basic_decimal_scalar.h:23:
/sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/arrow/util/decimal.h:24:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/decimal_ops.cc:20:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/decimal_ops.h:22:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/basic_decimal_scalar.h:23:
/sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/arrow/util/decimal.h:24:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/extended_math_ops.cc:23:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/precompiled/decimal_ops.h:22:
In file included from /sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/gandiva/basic_decimal_scalar.h:23:
/sw/BUILD/2112441002d6d406d22ae89d8e5669770a2e90bc/arrow/src_tmp/cpp/src/arrow/util/decimal.h:24:10: fatal error: 'string_view' file not found
#include <string_view>
```
This is for the `build/AliRoot/alidist ` build. Let's see for the others...

**Comment by ktf** [comment]
Weirdly enough this seems to work fine when I build on both the EPNs and Hyperloop (ubuntu).I will trigger a rebuild, just in case something got cached...

**Comment by davidrohr** [comment]
> Weirdly enough this seems to work fine when I build on both the EPNs and Hyperloop (ubuntu).I will trigger a rebuild, just in case something got cached...

But I think this must be reproducible, since it has failed in all the build containers? I'd propose to try in one of the containers locally.

**Comment by pzhristov** [comment]
I see a problem on Ubuntu 22.04 when the O2 is compiled. For some reason several packages are not found:
-- The following REQUIRED packages have not been found:

 * Gandiva
 * FairRoot
 * RapidJSON
 * libjalienO2
   For CCDB API
 * LibUV

**Comment by TimoWilken** [comment]
Hi, I've got O2 compiling locally with these changes, but that requires https://github.com/AliceO2Group/AliceO2/pull/10834 to be applied as well.

If the O2 PR is alright, let me know and I'll restart the checks in this PR after the O2 PR is merged and/or there is a nightly including it.

**Comment by davidrohr** [comment]
If I understand correctly, this PR and the O2 PR won't work without each other. Note that this PR will in any case break the fullCI build , due to gpu and codechecker changes that need to be applied in parallel. From my side, it would be fine if you force-merge this and then merge the o2 pr once it is green. I'll then take care of codechecker and gpu build for the CI afterwards.
Or perhaps you can make the o2 pr version-dependent to be backward-compatible... But if it requires significant work, I'd just not do it. But Giulio should also comment how he sees it.

**Comment by davidrohr** [comment]
I have literally no idea how I closed this

**Comment by davidrohr** [comment]
@TimoWilken @ktf : I applied one more fix to O2 CMake, and now O2 compilation seems to pass, but it fails during O2Physics compilation, processing the O2/dependencies/O2Dependencies.cmake. Could you check?

**Comment by TimoWilken** [comment]
Ah, it seems like we need `-DLLVM_ROOT=$CLANG_ROOT` for every package that builds directly against O2 using cmake. Is that just O2Physics? Or do alo-o2, DelphesO2, DataDistribution and QualityControl also do this?

**Comment by ktf** [comment]
It looks like the codechecker needs to be updated as well now. @sawenzel any idea of how trivial that is?

**Comment by davidrohr** [comment]
Yes, codechecker needs an update whenever LLVM is updated. But let's not do this in parallel. The FullCI will be broken anyway with the new clang. I can also take care of the codechecker, have done this before.

**Comment by ktf** [comment]
Ah, ok, so it's not some automated update that we do in general? Fine with me, then.

**Comment by aalkin** [comment]
> Ah, it seems like we need `-DLLVM_ROOT=$CLANG_ROOT` for every package that builds directly against O2 using cmake. Is that just O2Physics? Or do alo-o2, DelphesO2, DataDistribution and QualityControl also do this?

I suppose it is only need by Gandiva, so anything that implements the analysis task will probably need it. AFAIK only O2Physics and QC do that, but I'm not sure.

**Comment by TimoWilken** [comment]
Thanks @aalkin, you're right. alo-o2 also seems to need it, but it fails even when given `LLVM_ROOT` because it can't find libjalieno2.

**Pull request merged**
