### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by Barthelemy** [comment]
+1

**Comment by dberzano** [comment]
@ktf I have renamed the group to "dataflow-experts" as requested, and added proper PWGMM and "dataflow" recipes to the codeowners, can you please check and possibly approve if OK? Thanks!

**Comment by dberzano** [comment]
(I still need to add a couple of things though.)

**Comment by dberzano** [comment]
OK so I wanted to test the updated CODEOWNERS with more appropriate O2 names (_i.e._ no more online/daq/offline), but given that the team name changed, this PR is not asking the proper persons to review it. Once merged, it will of course, as the new CODEOWNERS will be picked up.

**Pull request merged**
