### PR TITLE
Add fastjet dependency to O2

### PR DESCRIPTION
**Pull request by qgp**

### CODE REVIEW

**Comment by ihrivnac** [comment]
Hi @qgp ,
Could you give more details why this dependency is needed? Thank you.

**Comment by qgp** [comment]
> Hi @qgp ,
> Could you give more details why this dependency is needed? Thank you.

Hi @ihrivnac,
we are working on the inclusion of jet finding (see AliceO2Group/AliceO2#3041), which will be needed for analysis but also for skimming and eventually triggering (at reconstruction level). Let me know if you need more information.
Cheers,
   Jochen

**Comment by ihrivnac** [comment]
Thank you for the link, I don't need more info.

**Comment by qgp** [comment]
Hi @ihrivnac,
Thanks! Do you know why build/O2/alidist failed (from the log it seems because of  gcc not working). Is there anything I can do concerning that? Or are you looking into it?

**Comment by ihrivnac** [comment]
@qgp , I don't know why this is failing. It needs to be investigated on the builder itself by the administrators.

**Comment by qgp** [comment]
@ktf any suggestion how to proceed here?

**Comment by qgp** [comment]
Before requiring fastjet on macOS, we have to remove the requirement to have SIP disabled, for which in turn we need to verify that this does not break:
- O2
- AliPhysics with ROOT 6
- AliPhysics with ROOT 5
Therefore, I'd suggest to pull in fastjet only for non-macOS for now.

NB: I am working on testing fastjet with SIP but it will take a bit of time to get done all the compiles and tests.

**Comment by qgp** [comment]
By now, I have tested fastjet with SIP enabled and have not observed any problems with it. Thus, I removed the requirement to have SIP disabled from fastjet (alisw/alidist#2128. Now, I suggestto go ahead and add fastjet as dependency to O2.

**Pull request merged**
