### PR TITLE
Use python modules compatible to python 3.6

### PR DESCRIPTION
**Pull request by davidrohr**
@ktf : This is what we did to fix compilation on EPNs.

### CODE REVIEW

**Comment by ktf** [comment]
@adriansev any objections to this?

**Comment by adriansev** [comment]
> @adriansev any objections to this?

not really .. actually i do not get why is needed since we have our own python 3.9, but if this make thinks work then it's ok .. will the CI will build xrootd? (to make sure that xrootd python bindings are installed without problems)

**Comment by davidrohr** [comment]
The point is that our minimum python requirement is 3.6, which is the default python of CC8, so we use the system python on the FLPs / EPNs. The python modules versions which I downgraded require 3.7, so currently our setup is broken if you have system python 3.6. It uses that, and then fails to build the python modules.
So we have to either downgrade the modules, or bump the minimum python version to 3.7.

**Comment by adriansev** [comment]
indeed in EL7 the last available versions are the ones mentioned in this commit .. and i absolutely had no idea that in el8 there is still python3.6 when in el9 the python is 3.9

**Comment by ktf** [comment]
Ok, let's merge this, I think there is some benefit in having a configuration which is compatible with CC7 / CC8.

**Pull request merged**
