### PR TITLE
Bump and patch gRPC to v1.30.0-alice1

### PR DESCRIPTION
**Pull request by teo**
also minor Protobuf bump

### CODE REVIEW

**Comment by awegrzyn** [comment]
Is it really necessary to force-merge when 3 most important jobs fail? :(

**Comment by teo** [comment]
@awegrzyn 1 of those was a real failure which I failed to recognize. My bad.

https://github.com/alisw/alidist/pull/2331 should fix it.

**Comment by awegrzyn** [comment]
I see 3 "X" which means 3 real failures.

**Comment by awegrzyn** [comment]
@ktf Is there any way to fix `test_Framework_test_AnalysisDataModel`? It failed on both CC7 and C8.

**Comment by ktf** [comment]
It's already fixed.

**Pull request merged**
