### PR TITLE
Drop autotools macOS

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by pzhristov — APPROVED** [review]

**Comment by pzhristov** [comment]
I propose to merge this PR.

**Comment by MichaelLettrich** [comment]
@ktf @pzhristov can we merge this? maybe it allows us to solve the macOS issues in #2738

**Comment by pzhristov** [comment]
@MichaelLettrich OK, merged.

**Comment by ktf** [comment]
This will trigger a massive rebuild...

**Comment by pzhristov** [comment]
Yes, sooner it starts, sooner it will finish :)

**Comment by ktf** [comment]
ok... Once we stabilize alibuild 1.7.0 all those platform specific things will be better done with a platform default (which is like a default, but automatically added on a per platform basis). This will avoid having to touch every single recipe to do platform specific changes.

**Pull request merged**
