### PR TITLE
Fix ALIBUILD_O2_OVERRIDE_*_ARCHS

### PR DESCRIPTION
**Pull request by mconcas**
This simply was not working. @davidrohr

### CODE REVIEW

**Comment by davidrohr** [comment]
I don't understand. Your change in this PR shouldn't make any difference, and I don't understand why it was not working before. For me such syntax works:
```
qon@qon ~ $ FOO=foo
qon@qon ~ $ echo ${FOO:+--test ${FOO}}
--test foo
qon@qon ~ $ FOO=
qon@qon ~ $ echo ${FOO:+--test ${FOO}}
```

**Comment by mconcas** [comment]
> I don't understand. Your change in this PR shouldn't make any difference, and I don't understand why it was not working before. For me such syntax works:
> 
> ```
> qon@qon ~ $ FOO=foo
> qon@qon ~ $ echo ${FOO:+--test ${FOO}}
> --test foo
> qon@qon ~ $ FOO=
> qon@qon ~ $ echo ${FOO:+--test ${FOO}}
> ```

I don't understand either, I was using it on EPN and it seemed to ignore the `HIP_AMDGPUTARGET` override.
Then I copied the same format used in other lines in o2.sh and it started working.

Maybe there is no correlation.
Indeed your very same test works on EPN shell.

**Comment by davidrohr** [comment]
I think you tried an incremental build? It might not work with that.
When you changed the o2.sh recipe, that has triggered a rebuild

**Comment by mconcas** [comment]
> I think you tried an incremental build? It might not work with that. When you changed the o2.sh recipe, that has triggered a rebuild

yes, it was incremental. I did some weak tentatives to re-trigger it by changing lines in FindO2GPU.cmake and CMakeListst of ITSTrackingGPU.

**Pull request closed without merging**
