### PR TITLE
Bump QCG to 1.6.3

### PR DESCRIPTION
**Pull request by graduta**

### CODE REVIEW

**Comment by awegrzyn** [comment]
@MichaelLettrich Sorry to disturb you again, but could you paste us the log once again?
This time the tag is correct, though we still get similar behaviour.

**Comment by MichaelLettrich** [comment]
```
Using cached build for QualityControl

==> Building qcg@v1.6.3
==> qcg is being built (use --debug for full output).[ 2%] ...          :failed
ERROR: Error while executing /build/ci_checks/alidist_checker_macos_o2_ci_1/sw/SPECS/osx_x86-64/qcg/v1.6.3-1/build.sh on `alibuildmac04.cern.ch'.
ERROR: Log can be found in /build/ci_checks/alidist_checker_macos_o2_ci_1/sw/BUILD/qcg-latest/log.
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is /build/ci_checks/alidist_checker_macos_o2_ci_1/sw/BUILD/qcg-latest/qcg.
+ BUILD_ERROR=1
+ [[ 1 != '' ]]
+ badge failing
+ [[ 1855 == 1855 ]]
+ return
```

this is what I see.

**Comment by ktf** [comment]
[build/O2Suite/alidist_macOS](https://ali-ci.cern.ch/alice-build-logs/alisw/alidist/1855/db3ba7dfac5536d60d8ec6321955938fe50a2ab3/build_O2Suite_alidist_macOS/fullLog.txt) says:

```
npm verb argv "/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/node/v10.15.3-1/bin/node" "/build/ci_checks/alidist_checker_macos_o2_ci_1/sw/osx_x86-64/node/v10.15.3-1/bin/npm" "install" "@aliceo2/qc@1.6.3" "--only=production" "--loglevel=verbose" "--no-save" "--no-package-lock" "--unsafe-perm"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aliceo2/qc@1.6.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm verb exit [ 1, true ]
npm timing npm Completed in 4207ms
```

**Comment by awegrzyn** [comment]
Ok, I fixed that and macOS build already completed successfully, thank you both

**Pull request merged**
