### PR TITLE
Bump qualitycontrol to v0.23.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@shahor02 @ktf I think that https://github.com/AliceO2Group/AliceO2/pull/3128 broke the O2 build.

**Comment by shahor02** [comment]
Hi @Barthelemy what do you mean exactly? Is there some log? All the CI tests for https://github.com/AliceO2Group/AliceO2/pull/3128 where green (except the macos, which is broken everywhere).

**Comment by ktf** [comment]
The problem is that we do not test o2-dataflow for AliceO2, only for alidist.

**Comment by Barthelemy** [comment]
@shahor02 sorry, I was indeed not very precise. The log of this macos build : https://ali-ci.cern.ch/alice-build-logs/alisw/alidist/2130/dc97fbfc0d08c2b8d1d6e95444b2848daca2787d/build_O2Suite_alidist_macOS/fullLog.txt

```
[ 93%] Building CXX object Detectors/TPC/reconstruction/CMakeFiles/O2lib-TPCReconstruction.dir/src/GBTFrameContainer.cxx.o
/System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/95f93f108a989f83a1d821828ff83b71998e12a6/O2/Detectors/TOF/calibration/G__O2TOFCalibration.cxx:655:7: error: delete called on 'o2::calibration::TimeSlotCalibration<o2::dataformats::CalibInfoTOF, o2::tof::LHCClockDataHisto>' that is abstract but has non-virtual destructor [-Werror,-Wdelete-abstract-non-virtual-dtor]
      delete ((::o2::calibration::TimeSlotCalibration<o2::dataformats::CalibInfoTOF,o2::tof::LHCClockDataHisto>*)p);
      ^
/System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/95f93f108a989f83a1d821828ff83b71998e12a6/O2/Detectors/TOF/calibration/G__O2TOFCalibration.cxx:658:7: error: delete called on 'o2::calibration::TimeSlotCalibration<o2::dataformats::CalibInfoTOF, o2::tof::LHCClockDataHisto>' that is abstract but has non-virtual destructor [-Werror,-Wdelete-abstract-non-virtual-dtor]
      delete [] ((::o2::calibration::TimeSlotCalibration<o2::dataformats::CalibInfoTOF,o2::tof::LHCClockDataHisto>*)p);
      ^
/System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/95f93f108a989f83a1d821828ff83b71998e12a6/O2/Detectors/TOF/calibration/G__O2TOFCalibration.cxx:662:7: error: destructor called on 'o2::calibration::TimeSlotCalibration<o2::dataformats::CalibInfoTOF, o2::tof::LHCClockDataHisto>' that is abstract but has non-virtual destructor [-Werror,-Wdelete-abstract-non-virtual-dtor]
      ((current_t*)p)->~current_t();
      ^
/System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/95f93f108a989f83a1d821828ff83b71998e12a6/O2/Detectors/TOF/calibration/G__O2TOFCalibration.cxx:662:24: note: qualify call to silence this warning
      ((current_t*)p)->~current_t();
                       ^
                       o2::calibration::TimeSlotCalibration<o2::dataformats::CalibInfoTOF, o2::tof::LHCClockDataHisto>::
```

**Comment by shahor02** [comment]
@Barthelemy Thanks, the https://github.com/AliceO2Group/AliceO2/pull/3139 should fix this.

**Comment by Barthelemy** [comment]
@shahor02 Thank you, as always as super fast response.

**Pull request merged**
