### PR TITLE
Bump to v2.1.1-alice1

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Bumping version to v2.1.1-alice (mainly for gfortran-10 / macOS BigSur).

**Comment by preghenella** [comment]
I cannot offically review it, but I give my +1

**Comment by mfasDa** [comment]
In principle the project is hosted on gitlab (https://gitlab.com/openloops/OpenLoops.git) and there are no ALICE-specific changes like for example in SHERPA, we could as well go to the official repo directly and close the ALICE fork on github.

**Comment by preghenella** [comment]
@mfasDa 
I would personally second this suggestion.
As far as I can see, our `OpenLoops` repository is not a fork of the official one, but rather a manual copy of files.

Let's have our recipe point to the official GitHub repository and its tags.
In case we need ALICE-specific changes in the future, we can re-open out repository and make it a real fork of the official one.

**Comment by mfasDa** [comment]
Now the PR also includes moving to the official repo.

**Comment by preghenella** [comment]
@mfasDa 
is it clear what makes some of the few checks above fail?

**Comment by mfasDa** [comment]
@preghenella No clue why the PR check fails, seems to be unrelated to this commit.

**Comment by preghenella** [comment]
@ktf @MichaelLettrich 
do you have any hints why `alidist` PRs seem to fail in `dataflow` and `macOS`?
details are either missing or provide no clues.

Thanks

**Pull request merged**
