### PR TITLE
Bump CMake

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by ktf** [comment]
Issue in DataDistribution seems genuine...

**Comment by davidrohr** [comment]
while EPN is investigating, let's try the latest 3.27 release, which would be enough for my GPU needs.

**Comment by davidrohr** [comment]
@sawenzel @ktf : We have
```
152/518 Test #474: o2sim_G3 .............................................................................***Failed  Required regular expression not found. Regex=[SIMULATION RETURNED SUCCESFULLY
```
in both Mac CIs. Is that known, or can it be related to the CMake change?

**Comment by ktf** [comment]
this is the xcode bump, i guess. @TimoWilken didn't you switch the test off?

**Comment by davidrohr** [comment]
But why isn't it failing in the O2 CI, e.g. https://github.com/AliceO2Group/AliceO2/pull/1252
It runs the `o2sim_G3` test there on Mac, and it passes.

**Comment by davidrohr** [comment]
FullCI failing due to known tpc-gainmap calib error. Merging.

**Pull request merged**
