### PR TITLE
Force setuptools 49.6.0

### PR DESCRIPTION
**Pull request by ktf**
50.0.0 seems to give issues on some platforms (ubuntu and CC8).

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Just tried that and the following seems to happen:

`python3 -m pip install --user -IU setuptools` installs latest setuptools (50.0.0)
(https://github.com/alisw/alidist/blob/master/python-modules.sh#L48)

`python3 -m pip install --user -IU -r requirements.txt` afterwards however doesn't seem to overwrite the `setuptools` version even if an older version of that is specified therein.
(https://github.com/alisw/alidist/blob/master/python-modules.sh#L56)

maybe putting `wheels` and `setuptools==49.6.0` in a separate list in `python-modules-list.sh` and installing that before the actual modules of interest?

**Comment by ktf** [comment]
@MichaelLettrich "no space left on device" on macOs.

**Review by MichaelLettrich — APPROVED** [review]
Fixes my problems.

**Comment by MichaelLettrich** [comment]
@ktf  macos builds are back on track.

**Pull request merged**
