### PR TITLE
[WIP] Add KFParticle recipe

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
To be reviewed by KFParticle experts, do not merge yet.

**Comment by dberzano** [comment]
Hi @malzache, I have found a problem while compiling on Mac, which can be very easily solved. In the main CMakeLists.txt you require CMake 3.0 at least, but you should require a lower version like this:

    cmake_minimum_required(VERSION 2.8.8 FATAL_ERROR)

Can you do a commit to KFParticle changing this please, and report the new hash? We can then update the hash in this recipe and merge 👍 

Cheers

**Comment by malzache** [comment]
Dear Dario,

i asked Maksym to change it, what he did. Below his mail:

Dear Peter,
I put the changes and commit them to the KF Particle repository:

commit 07cc3c11e648d89ddfbe40ba28dba9850806369b
Author: m.zyzak <m.zyzak@gsi.de>
Date:   Wed Feb 7 12:02:07 2018 +0100

    Change minimum CMake required version to 2.8.8.

With best regards,
Maksym

**Comment by dberzano** [comment]
@malzache you can now use KFParticle with alidist's master, thanks!

**Comment by pzhristov** [comment]
Hi @dberzano and @malzache,

I compiled KFParticle, but one cannot load the library since the rootmap and the pcm files are not installed. The following change in KFParticle/CMakeFiles.txt solves the problem

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2bef8ba..2332387 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -113,3 +113,5 @@ Set(NODICT_HEADERS
 
 install(FILES ${HEADERS} ${NODICT_HEADERS} DESTINATION include)
 install(TARGETS KFParticle DESTINATION lib)
+install(FILES "${CMAKE_CURRENT_BINARY_DIR}/libKFParticle.rootmap" DESTINATION lib)
+install(FILES "${CMAKE_CURRENT_BINARY_DIR}/libKFParticle_rdict.pcm" DESTINATION lib)

Probably there is a better way, but this one at least works. I am able now to load the library, create a test object and run the test.

Cheers,
Peter

**Comment by mzyzak** [comment]
Dear all,

I added installation of pcm and rootmap files, however made them optional, since with Root5 they are not created. So, now it should work for both Root5 and Root6. I created a tag v1.0 after the modifications.

With best regards,
Maksym

**Comment by dberzano** [comment]
Hi @mzyzak, PCMs are a ROOT 6 feature, but rootmaps are available since ROOT 5. We depend on rootmaps for correctly loading classes without explicitly loading their library. Can you check if the rootmaps are created with ROOT 5, and if not, can you trigger their creation there please? Installation of rootmaps for ROOT 5 should be mandatory and not optional.

**Comment by mzyzak** [comment]
Dear Dario,

I have added generation of the rootmap with ROOT5 and updated the tag v1.0.

With best regards,
Maksym

**Comment by dberzano** [comment]
Hi, thanks, let me quickly check!

**Pull request merged**
