### PR TITLE
Move to JAliEn-ROOT 0.7.4

### PR DESCRIPTION
**Pull request by ktf**
Move to JAliEn-ROOT 0.7.4

* Fix static cast
* Improve detection of OpenSSL to use both libcrypto and libssl

### CODE REVIEW

**Comment by davidrohr** [comment]
well, the problem will be, now that we downgraded jalien-root again, to check where the performance problem in analysis comes from, this will not be compatible anymore to libwebsockets.

**Comment by ktf** [comment]
Ok, but the detection of OPENSSL needs to be corrected in any case. It currently works by accident (here and in other places, I fear).

**Review by costing — DISMISSED** [review]

**Comment by ktf** [comment]
The issue on mac is a genuine error. Probably it's now caught by new new XCode. I am preparing a fix which will require bumping to 0.7.4.

**Comment by ktf** [comment]
Tested on hyperloop as well...

**Comment by ktf** [comment]
@TimoWilken the error with git is again there. Any idea of what this might be?

```
Git command for package 'Clang' failed.
Command: git clone --bare https://github.com/llvm/llvm-project /build/nomad/alloc/3b592022-e81d-4247-9f4f-2e37864d8242/ci/local/o2-alidist/sw/MIRROR/clang
In directory: .
Exit code: -15
```

**Comment by ktf** [comment]
@davidrohr could you check on Arch linux?

**Comment by davidrohr** [comment]
I tried this and it works for me.
@costing : shall we merge and then check if it is ok in the Analysis?
Could we actually confirm that after reverting JAliEn-ROOT to 0.7.1, the Analysis issue was gone?

**Comment by ktf** [comment]
@ddobrigk @jgrosseo can you confirm that going back to 0.7.1 the issue disappeared?

**Comment by costing** [comment]
I've asked David (Chinellato) about analysis jobs, waiting for his reply. Ruben also had it on his machine and as far as I understood reverting fixed it. The same issue with 0.7.3 was observed in reco jobs too and Chiara has prepared a new async package with 0.7.1, we'll see if it helps there.

Before bumping libwebsockets by default, could we have a build with a suffix, to be tried out as a batch of jobs first? I'll be away next week and I'm reluctant to disturb the production setup during this time.

**Comment by davidrohr** [comment]
Not sure how we can create such a tag. We can merge and then use the override file option in jenkins, to take the files from alidist/master.
Or we could use a different alidist slug, which has Giulio's PR in.

**Comment by ktf** [comment]
For the record, I am building a daily tag with my branch https://alijenkins.cern.ch/job/DailyBuilds/job/AdHocO2Physics/282/. @ddobrigk can you validate it once it's done so that we can merge it?

**Comment by ktf** [comment]
daily-20231023-2201-1 uses this and it's now deployed.

**Comment by ktf** [comment]
For the record, I am now comparing a train run on the grid (kudos to @jgrosseo) with a patched version:

https://alimonitor.cern.ch/hyperloop/train-run/129599

with the vanilla one from the same day:

https://alimonitor.cern.ch/hyperloop/train-run/129692

With 90% of the jobs done and 70% of the files, the runtimes seem compatible. I will merge this once the test terminates for good.

**Comment by ktf** [comment]
Test completed, timings  are compatible. Merging.

**Pull request merged**
