### PR TITLE
Add moderncppkafka for QC

### PR DESCRIPTION
**Pull request by justonedev1**

### CODE REVIEW

**Comment by ktf** [comment]
What is this needed for? Do you really need it for the whole QC?

**Review by ktf — COMMENTED** [review]
Please, have a look at the linter messages, they look valid to me.

**Comment by justonedev1** [comment]
I will take a look at linter messages, thank you. 
It is needed for [QC-271](https://its.cern.ch/jira/browse/QC-271). Strictly speaking it is not needed but it really helps with consuming kafka from C++ justification is in the ticket.

**Comment by ktf** [comment]
Ok, so it's for the actual devices, not for some infrastructure bit. Fine then.

**Review by ktf — COMMENTED** [review]
There  is still one linter issue unresolved. Could you have a look into it?

**Pull request merged**
