### PR TITLE
bump readout

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
the CI fails with "No logs found. Please check the aurora log."
Can you please advise?

**Comment by vascobarroso** [comment]
@alisw/infrastructure-admins we need this bump + QC in #3870 for today's FLP Suite release. Will the CI recover in time ?

**Comment by ktf** [comment]
I suspect there was a problem fetching from git. I will restart the tests.

**Comment by ktf** [comment]
Well, it looks like v2.8.3 was not actually tagged:

```
git clone -b v2.8.3 https://github.com/AliceO2Group/Readout
Cloning into 'Readout'...
fatal: Remote branch v2.8.3 not found in upstream origin
```

while it works just fine for v2.8.2

**Comment by sy-c** [comment]
indeed, my fault, typo in the tag name... v2.8.3 is now available.

**Comment by sy-c** [comment]
thanks for checking

**Comment by sy-c** [comment]
@ktf the status does not seem to update... is there a way to relaunch the checks, please ?

**Comment by ktf** [comment]
I just restarted them by hand using https://github.com/alisw/alidist/actions/workflows/clean-pr-checks.yml

@TimoWilken FYI, apparently the default tests cleaned by the action did not include some of the recent tests. Could you add a recipe to the cookbook on how to add new tests, making sure you mention the fact the action yaml must be updated?

**Comment by ktf** [comment]
C8 alidist builds. Merging.

**Pull request merged**
