### PR TITLE
Enable code checks only on a set of changed files

### PR DESCRIPTION
**Pull request by sawenzel**
We are now able to run the static analysis only on  files touched by a PR!!

### CODE REVIEW

**Comment by sawenzel** [comment]
@dberzano : This is what we discussed. Now we only have to use the new feature in the PR checking.

**Comment by ktf** [comment]
Will this work for header only changes? IIRC, `compile_commands.json` only contains `.cc` references (at least it does in my case).

**Comment by sawenzel** [comment]
Will of course work. The tool deals exactly with this complication by
figuring out which source files are influenced by header files.

Am 02.06.2017 7:35 nachm. schrieb "Giulio Eulisse" <notifications@github.com

**Comment by ktf** [comment]
Ok, perfect then. +1 on my side.

**Comment by sawenzel** [comment]
I further improved this recipe in the following way. 
a) The user can give a git base commit as a reference, which is used to find out the files that have changed and on which the tests will be run:

`O2CHECKCODE_BASECOMMIT=HEAD^ alibuild build o2checkcode`

b) The user can alternatively specify a set of files directly, on the basis of which the code checks will be run

`O2_CHECKCODE_CHANGEDFILES=/TPCSimulation/Detector.h:/TPCSimulation/Point.h alibuild build o2checkcode`

c) We can connect to pull request checking  via `ALIBOT_PR_BASE` or `ALIBOT_PR_HEAD`.

**Comment by sawenzel** [comment]
@ktf, @dberzano : Please review and merge as soon as convenient.

**Comment by ktf** [comment]
Can you update the AliceO2 documentation as well?

**Comment by sawenzel** [comment]
I will update the documentation ... once this in place.

**Comment by ktf** [comment]
Please, update it where it currently is: `Utilities/Tools/README.md`. If the place is not where we want it, we can clean it up later.

**Comment by sawenzel** [comment]
@dberzano : Any thoughts here? Can this go in?

**Comment by sawenzel** [comment]
@ktf, @dberzano : Any chance we can advance with this and put it into place?

**Comment by matthiasrichter** [comment]
+1 from me, would like to see this in the CI as soon as possible

**Pull request merged**
