### PR TITLE
Bump qualitycontrol to v1.1.4

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]

**Comment by knopers8** [comment]
The errors seems legit, but I completely don't understand why it went through our CI in QC, nor the error itself, as there is such file in O2:
```
/System/Volumes/Data/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/osx_x86-64/QualityControl/v1.1.4-1/include/QualityControl/DatabaseInterface.h:24:10: fatal error: 'Framework/ServiceRegistry.h' file not found
#include <Framework/ServiceRegistry.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Barthelemy** [comment]
Could it be a broken build environment ?

**Comment by knopers8** [comment]
Maybe, I can compile O2@dev with QC@v1.1.4 without problems on my machine.

**Comment by davidrohr** [comment]
have you tried inside the slc7-builder docker container? If needed, I can try it later, it should reproduce the build environment from the CI.

**Comment by Barthelemy** [comment]
@davidrohr I have not. I would be very much interested to learn how to do that. Would you mind writing down the steps you  go through ?  
I could then put it in our instructions: https://aliceo2group.github.io/advanced

**Comment by davidrohr** [comment]
```
docker pull alisw/slc7-builder # or you can also fetch another builder obviously, but slc7-builder is convenient since there are precompiled binaries so it is fast. It is the one used for build/O2/alidist
docker run -ti alisw/slc7-builder /bin/bash
pip install alibuild #No just the normal stuff to run aliBuild
aliBuild init
aliBuild --defaults o2 init QualityControl@whateveryoulike
ALIBUILD_O2_TESTS=1 aliBuild --defaults o2 build QualityControl --debug
```

**Comment by Barthelemy** [comment]
perfect, thanks

**Comment by Barthelemy** [comment]
I get an arrow error when building O2:
```
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0: -- Could NOT find arrow (missing: ARROW_INCLUDE_DIR) (found version "1.0.0")
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0: CMake Warning at dependencies/Findarrow.cmake:13 (find_package):
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:   Found package configuration file:
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0: 
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:     /root/sw/slc7_x86-64/arrow/v1.0.0-7/lib/cmake/arrow/arrow-config.cmake
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0: 
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:   but it set arrow_FOUND to FALSE so package "arrow" is considered to be NOT
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:   FOUND.
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0: Call Stack (most recent call first):
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:   dependencies/O2Dependencies.cmake:39 (find_package)
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:   dependencies/CMakeLists.txt:11 (include)
2020-09-17@08:58:35:DEBUG:QualityControl:O2:0:   CMakeLists.txt:45 (include)
```
This is unrelated to the issue at hand of course.

**Comment by Barthelemy** [comment]
My bad, I did not `init` O2. Now all passes fine in the docker container.

**Comment by Barthelemy** [comment]
https://alice.its.cern.ch/jira/browse/QC-408

**Pull request merged**
