### PR TITLE
add curl in monitoring/ppconsol requirements

### PR DESCRIPTION
**Pull request by AllaMaevskaya**

### CODE REVIEW

**Comment by awegrzyn** [comment]
`curl` is optional `Monitoring` dependency, do you need to have `http` backend enabled by default?

**Review by ktf — APPROVED** [review]

**Review by awegrzyn — CHANGES_REQUESTED** [review]
`ppconsul` indeed requires curl but `monitoring` does only for optional `http` backend. Could you explain why you need it enabled?

**Comment by AllaMaevskaya** [comment]
this was the only way to build monitoring, otherwise it crashed with the same complains as Roberto published

**Comment by sawenzel** [comment]
I confirm that the dependency in monitoring is also needed.

**Review by sawenzel — APPROVED** [review]

**Comment by awegrzyn** [comment]
@sawenzel Do you know why it is needed? The CMake of Monitoring does not make it required: `find_package(CURL MODULE)`

**Comment by sawenzel** [comment]
I am afraid I don't know. Just confirming that it solves the issue https://alice.its.cern.ch/jira/browse/O2-1723. Could it be that ppconsul is using curl in header files?

**Comment by awegrzyn** [comment]
Nope it does not, could you just paste me what CMake reports when compiles Monitoring?

**Review by awegrzyn — APPROVED** [review]
Not to block, we can investigate later on

**Review by awegrzyn — APPROVED** [review]

**Pull request merged**
