### PR TITLE
Fix Geant4 VMC location in defaults-o2-dev-fairroot.sh

### PR DESCRIPTION
**Pull request by rbx**

### CODE REVIEW

**Comment by sawenzel** [comment]
@rbx : Thanks a lot for spotting this. Sorry that this typo slipped in.

**Comment by sawenzel** [comment]
@brinick : This is a trivial yet urgent typo fix. Can this be merged asap?

**Comment by sawenzel** [comment]
Why is this branch out of date? Do we not have a rebase facility in alidist?

**Comment by rbx** [comment]
Sorry, forgot to rebase.

**Pull request merged**
