### PR TITLE
Revert obsolete workarounds for old CMake

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
@dennisklein : We have finally bumped CMake, and I am trying here to get rid of the boost workaround (removing the modern CMake files), but unfortunately that doesn't work.
In #1836 you said this should be fixed with CMake >= 3.15.
Bus asiofi is failing (and possible additional packages).
Could you have a look?

**Comment by dennisklein** [comment]
For asiofi and Boost 1.70, you need https://github.com/FairRootGroup/asiofi/commit/652ddb827eb4f8c27f188cccbe3f1719652322c4. I will have a look latest until Monday evening why alidist is still on asiofi v0.3.1. I don't remember of the top of my head if there was a good reason or if you could just bump to v0.4.3. Shout at me if I forget ;)

**Comment by davidrohr** [comment]
Shout @dennisklein

**Comment by dennisklein** [comment]
You should be fine to bump asiofi to `v0.4.3`.

Just updated my local alidist and started compilation to check, if there are other problems related to this PR. Will take a while though, it wants to compile a trillion packages including clang oO.

**Comment by dennisklein** [comment]
Can't build the current alidist on Fedora 31:

```
$ aliBuild build --defaults o2 O2

==> aliBuild can take the following packages from the system and will not build them:
      GCC-Toolchain, ZeroMQ, autotools, CMake, FreeType, zlib, libpng, lzma, flatbuffers, ofi, GLFW

==> The following packages cannot be taken from the system and will be built:
      GSL, libxml2, OpenSSL, yaml-cpp, lz4, boost

==> Packages will be built in the following order:
     - libxml2@v2.9.3
     - OpenSSL@OpenSSL_1_0_2o
     - Clang@llvmorg-9.0.0
     - pythia6@428-alice1
     - ms_gsl@b014508
     - libtirpc@libtirpc-1-1-4
     - Python-modules-list@1.0
     - FairLogger@v1.5.0
     - lhapdf@v6.2.1-alice2
     - UUID@alice/v2.27.1
     - fmt@6.1.2
     - googletest@release-1.8.0
     - GSL@release-1-16
     - Vc@1.4.1
     - DebugGUI@655f92e9c9d0bd89ecb62a15d98d4fd6ada54392
     - json-c@json-c-0.13.1-20180305
     - re2@2019-09-01
     - googlebenchmark@v1.3.0
     - protobuf@v3.7.1
     - Alice-GRID-Utils@0.0.6
     - RapidJSON@091de040edb3355dcf2f4a18c425aec51b906f08
     - hijing@v1.36
     - GEANT4@v10.4.2
     - double-conversion@v3.1.5
     - AliEn-CAs@4a5bccfccd2c32cc32eb53ae44e213d19b536d2d
     - lz4@v1.8.3
     - cub@v1.8.0
     - libwebsockets@v3.0.1
     - ApMon-CPP@v2.2.8-alice2
     - Python-modules@1.0
     - AliEn-Runtime@v2-19-le
     - boost@v1.70.0
     - XRootD@v4.11.1
     - libInfoLogger@v1.3.7
     - Monitoring@v2.6.4
     - arrow@apache-arrow-0.14.1
     - DDS@3.1
     - pythia@v8243
     - yaml-cpp@yaml-cpp-0.6.2
     - Common-O2@v1.4.6
     - Ppconsul@e32cf6f80b598760278c018eed546f88292f1735
     - asiofi@v0.4.3
     - xjalienfs@1.0.3
     - ROOT@v6-18-04-alice1
     - generators@v1.0
     - Configuration@v2.2.5
     - FairMQ@v1.4.12
     - GEANT3@v2-7
     - MCStepLogger@master
     - AEGIS@v1.0
     - HepMC3@d43693ce0e7731e9b787dbd6176cb6245fd770b3
     - JAliEn-ROOT@0.5.3
     - vgm@v4-4
     - GEANT4_VMC@v3-6-p3
     - simulation@v1.0
     - FairRoot@6af7e848585ce720e96a01d5565b1bd5e3884430
     - O2@v1.1.0
Using cached build for defaults-release
Using cached build for libxml2
Using cached build for OpenSSL
Using cached build for Clang
Using cached build for pythia6
Using cached build for ms_gsl
Using cached build for libtirpc
Using cached build for Python-modules-list
Using cached build for FairLogger
Using cached build for lhapdf
Using cached build for UUID
Using cached build for fmt
Using cached build for googletest
Using cached build for GSL
Using cached build for Vc
Using cached build for DebugGUI
Using cached build for json-c
Using cached build for re2
Using cached build for googlebenchmark
Using cached build for protobuf
Using cached build for Alice-GRID-Utils
Using cached build for RapidJSON
Using cached build for hijing
Using cached build for GEANT4
Using cached build for double-conversion
Using cached build for AliEn-CAs
Using cached build for lz4
Using cached build for cub
Using cached build for libwebsockets
Using cached build for ApMon-CPP
Using cached build for Python-modules
Using cached build for AliEn-Runtime
Using cached build for boost
Using cached build for XRootD
Using cached build for libInfoLogger

==> Building Monitoring@v2.6.4
==> Monitoring is being built (use --debug for full output): failed
ERROR: Error while executing /home/dklein/alice/sw/SPECS/fedora31_x86-64/Monitoring/v2.6.4-1/build.sh on `delta'.
ERROR: Log can be found in /home/dklein/alice/sw/BUILD/Monitoring-latest/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is /home/dklein/alice/sw/BUILD/Monitoring-latest/Monitoring.
```
```
$ tail -90 /home/dklein/alice/sw/BUILD/Monitoring-latest/log
++ case $ARCHITECTURE in
++ [[ -n '' ]]
++ cmake /home/dklein/alice/sw/SOURCES/Monitoring/v2.6.4/v2.6.4 -DCMAKE_INSTALL_PREFIX=/home/dklein/alice/sw/INSTALLROOT/06ba8a6b158583fa1dafb125fe1c875468355c2e/fedora31_x86-64/Monitoring/v2.6.4-1 -DBOOST_ROOT=/home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2 -DAPMON_ROOT=/home/dklein/alice/sw/fedora31_x86-64/ApMon-CPP/v2.2.8-alice2-1 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components: doxygen dot
-- Found Boost 1.70.0 at /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS unit_test_framework;program_options;system;filesystem
-- Found boost_headers 1.70.0 at /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/boost_headers-1.70.0
-- Found boost_unit_test_framework 1.70.0 at /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/boost_unit_test_framework-1.70.0
--   libboost_unit_test_framework.so.1.70.0
-- Adding boost_unit_test_framework dependencies: headers
-- Found boost_program_options 1.70.0 at /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/boost_program_options-1.70.0
--   libboost_program_options.so.1.70.0
-- Adding boost_program_options dependencies: headers
-- Found boost_system 1.70.0 at /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/boost_system-1.70.0
--   libboost_system.so.1.70.0
-- Adding boost_system dependencies: headers
-- Found boost_filesystem 1.70.0 at /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/boost_filesystem-1.70.0
--   libboost_filesystem.so.1.70.0
-- Adding boost_filesystem dependencies: headers
-- Found Boost: /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-2/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0") found components: unit_test_framework program_options system filesystem
-- Found ApMon: /home/dklein/alice/sw/fedora31_x86-64/ApMon-CPP/v2.2.8-alice2-1/lib/libapmoncpp.so
-- Could NOT find RdKafka (missing: RdKafka_DIR)
-- Backends
--   Compiling StdCout backend
--   Compiling Flume UDP/JSON backend
--   Compiling InfluxDB backend with Unix socket and UDP transport
--   Compiling ApMon backend
-- Detected Linux: Process monitor enabled
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_ROOT


-- Build files have been written to: /home/dklein/alice/sw/BUILD/06ba8a6b158583fa1dafb125fe1c875468355c2e/Monitoring
++ cp /home/dklein/alice/sw/BUILD/06ba8a6b158583fa1dafb125fe1c875468355c2e/Monitoring/compile_commands.json /home/dklein/alice/sw/INSTALLROOT/06ba8a6b158583fa1dafb125fe1c875468355c2e/fedora31_x86-64/Monitoring/v2.6.4-1
++ make -j 8 install
Scanning dependencies of target Monitoring
[  3%] Building CXX object CMakeFiles/Monitoring.dir/src/Monitoring.cxx.o
[  3%] Building CXX object CMakeFiles/Monitoring.dir/src/ComplexMetric.cxx.o
[  5%] Building CXX object CMakeFiles/Monitoring.dir/src/Metric.cxx.o
[  6%] Building CXX object CMakeFiles/Monitoring.dir/src/Backends/InfluxDB.cxx.o
[  8%] Building CXX object CMakeFiles/Monitoring.dir/src/Backends/StdOut.cxx.o
[ 10%] Building CXX object CMakeFiles/Monitoring.dir/src/Backends/Flume.cxx.o
[ 12%] Building CXX object CMakeFiles/Monitoring.dir/src/DerivedMetrics.cxx.o
[ 13%] Building CXX object CMakeFiles/Monitoring.dir/src/ProcessDetails.cxx.o
[ 15%] Building CXX object CMakeFiles/Monitoring.dir/src/ProcessMonitor.cxx.o
[ 17%] Building CXX object CMakeFiles/Monitoring.dir/src/MonitoringFactory.cxx.o
[ 18%] Building CXX object CMakeFiles/Monitoring.dir/src/Transports/UDP.cxx.o
[ 20%] Building CXX object CMakeFiles/Monitoring.dir/src/Transports/TCP.cxx.o
[ 22%] Building CXX object CMakeFiles/Monitoring.dir/src/Transports/Unix.cxx.o
[ 24%] Building CXX object CMakeFiles/Monitoring.dir/src/Exceptions/MonitoringException.cxx.o
[ 25%] Building CXX object CMakeFiles/Monitoring.dir/src/Backends/ApMonBackend.cxx.o
In file included from /home/dklein/alice/sw/SOURCES/Monitoring/v2.6.4/v2.6.4/src/Backends/ApMonBackend.h:20,
                 from /home/dklein/alice/sw/SOURCES/Monitoring/v2.6.4/v2.6.4/src/Backends/ApMonBackend.cxx:16:
/home/dklein/alice/sw/fedora31_x86-64/ApMon-CPP/v2.2.8-alice2-1/include/ApMon.h:111:10: fatal error: rpc/rpc.h: No such file or directory
  111 | #include <rpc/rpc.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Monitoring.dir/build.make:245: CMakeFiles/Monitoring.dir/src/Backends/ApMonBackend.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/dklein/alice/sw/SOURCES/Monitoring/v2.6.4/v2.6.4/src/Backends/ApMonBackend.h:20,
                 from /home/dklein/alice/sw/SOURCES/Monitoring/v2.6.4/v2.6.4/src/MonitoringFactory.cxx:30:
/home/dklein/alice/sw/fedora31_x86-64/ApMon-CPP/v2.2.8-alice2-1/include/ApMon.h:111:10: fatal error: rpc/rpc.h: No such file or directory
  111 | #include <rpc/rpc.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Monitoring.dir/build.make:180: CMakeFiles/Monitoring.dir/src/MonitoringFactory.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:408: CMakeFiles/Monitoring.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Any idea?

```
$ find sw/fedora31_x86-64 | grep rpc\/rpc.h
sw/fedora31_x86-64/libtirpc/libtirpc-1-1-4-1/include/tirpc/rpc/rpc.h
```

**Comment by davidrohr** [comment]
@dennisklein : I just tried as well, and control failed to build. But asiofi works now. I'll contact the maintainers of the other packages that fail to build. Thx for the help.

**Comment by davidrohr** [comment]
@teo @vascobarroso : As of boost 1.70, boost usually installs modern CMake config files. This was broken up until CMake 3.15, so we had to introduce a hack to get rid of this. Since we have bumped CMake now, we'd like to get rid of these workarounds.

This PR is testing the O2Suite build with newest  boost / CMake without the workaround, and currently it fails at at Control-OCPPlugint. The log is attached below.
[build.log.gz](https://github.com/alisw/alidist/files/4153629/build.log.gz)

To me, it seems that Control-OCPPlugin is not compatible to modern CMake with boost detected via a CMake Config file. Could you have a look whether this can be fixed?

**Comment by dennisklein** [comment]
@davidrohr Maybe it makes sense to also try to bump Boost beyond 1.70, most packages will run into https://github.com/boostorg/boost_install/issues/5 I am afraid.

**Comment by davidrohr** [comment]
Ok, but I'd do this independently?

Kind Regards
David Rohr

**Comment by davidrohr** [comment]
Ah, ok, I understand your point. I'll try to bump it as well.

Kind Regards
David Rohr

**Comment by davidrohr** [comment]
@dennisklein : I have tried locally with boost 1.72, and DDS fails. Would you advise to use boost 1.71 instead, or do we have to bump DDS as well? Anything else to bump?

**Comment by dennisklein** [comment]
Do you have the error for the DDS failure? I think I have installed DDS against 1.70 and 1.71 in the past, never tried 1.72. But I would want to repair it anyways.

**Comment by davidrohr** [comment]
DDS error log attached
[dds-error.log.gz](https://github.com/alisw/alidist/files/4154778/dds-error.log.gz)

**Comment by dennisklein** [comment]
Turns out the DDS build failure is due to a bug in Boost.Process in Boost 1.72. Upstream expects a fix to land only in Boost 1.73. You may want to consider patching your alidist Boost 1.72 like this: https://github.com/OpenMandrivaAssociation/boost/commit/167e6d8982319d16d846f8d337b93723b807de9a - I have not verified if this fix works, but it looks very reasonable.

**Comment by davidrohr** [comment]
Ok, but then I'd rather just try 1.71 for now.

Kind Regards
David Rohr

**Comment by davidrohr** [comment]
@teo @vascobarroso : The problem in Control-OCCPlugin is gone after bumping boost, so nothing to be done on your side.

**Comment by davidrohr** [comment]
@dennisklein : Now O2 builds on linux with boost 1.71, but asiofi fails on MacOS. Could you have a look again :(

**Comment by dennisklein** [comment]
Hm, when I click the Details link next to the `build/O2Suite/alidist_macOS` check, I see an empty page. Can you post the logs please?

**Comment by davidrohr** [comment]
Shit, the build log is gone.
@ktf @MichaelLettrich : Could you check what happened here? 10 minutes ago I could still access the log. Now it is empty.
I'll let the other finish, then force push to restart the CI, and this time save the log.

**Comment by dennisklein** [comment]
While it is interesting to see what is broken on macOS, in the end, we should probably just disable building libfabric, and asiofi, as well as setting `-DBUILD_OFI_TRANSPORT=OFF` on the fairmq recipe. There is no point in building this on macOS. Support for macOS is coincidental and there are no Infiniband  devices on macs anyways, are there?

**Comment by dennisklein** [comment]
Btw, DDS and FairMQ are affected by the Boost.Process bug in Boost 1.72: FairRootGroup/FairMQ#237, FairRootGroup/DDS#286.

The underlying change for the bug is actually in Boost.Asio. The author even comments in his commit message (https://github.com/chriskohlhoff/asio/commit/5b126e38458a706cce304b780de1943235354c94):
> The presence of `executor_type` and `get_executor()` should be treated
as optional, and consequently it may be preferable to access them via
the `associated_executor` trait and the `get_associated_executor()`
helper function.
But in the very same commit the mentioned type trait and helper function are not used ...

So far I have no good idea for a workaround other than patching our Boost installations as it appears to be also the chosen course of action of [OpenMandriva](https://github.com/OpenMandrivaAssociation/boost/commit/167e6d8982319d16d846f8d337b93723b807de9a). I will probably push this patch also forward with Spack unless I find a better solution in the next days.

**Comment by MichaelLettrich** [comment]
@davidrohr and @dennisklein : This log is back. Nevertheless, here you go:
[fullLog.txt](https://github.com/alisw/alidist/files/4160396/fullLog.txt)

**Comment by dennisklein** [comment]
@MichaelLettrich thx!
@davidrohr I will have a look into this issue (FairRootGroup/asiofi/issues/6) but I do not know how fast I can deliver a solution here. To not block the efforts of this PR, I recommend to move forward with what I said earlier (unless you or anyone else has a reason why it needs to be compiled on macOS)
> we should probably just disable building libfabric, and asiofi, as well as setting `-DBUILD_OFI_TRANSPORT=OFF` on the fairmq recipe (for macOS). There is no point in building this on macOS. Past support for macOS is coincidental and there are no Infiniband devices on macs anyways, aren't there?

**Comment by dennisklein** [comment]
@davidrohr I backported the CMake/Boost stuff to the asiofi `v0.3` branch - only the `v0.4` branch contains the folly dependency. So, if you want to keep compiling asiofi on macOS, pick version `v0.3.3` for now.

**Comment by dennisklein** [comment]
```
-- Found Boost 1.70.0 at /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.71.0-18/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS program_options;container;program_options;filesystem;date_time;regex;system;log;log_setup;thread
-- Found boost_headers 1.70.0 at /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.71.0-18/lib/cmake/boost_headers-1.70.0
-- Found boost_program_options 1.70.0 at /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.71.0-18/lib/cmake/boost_program_options-1.70.0
-- No suitable boost_program_options variant has been identified!
--   libboost_program_options.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
```

@davidrohr aliBuild thinks it is building Boost 1.71, but it is really building Boost 1.70. The reason is that https://github.com/alisw/boost does not contain 1.71.

**Comment by davidrohr** [comment]
@ktf : Can you clean the build directory for this PR?
I tried it locally in the alisw/slc7-builder, and it built successfully.
So I think something is messed up here with incremental builds.

**Comment by davidrohr** [comment]
@dennisklein : But this is a bug with incremental builds. I changed the repo to my fork of boost for this test. And actually boost was build correctly, the Control-OCPPlugin is confused. I'd like to retry with a fresh build directory.

**Comment by dennisklein** [comment]
ups, I see, nvm then

**Comment by davidrohr** [comment]
For reference, I tried locally until this build are thing is fixed, and now it dies during O2 compilation with
```
DEBUG:O2Suite:O2:0: /root/alice/sw/slc7_x86-64/boost/v1.71.0-1/lib/libboost_iostreams.so.1.71.0: undefined reference to `lzma_cputhreads@XZ_5.2.2'
DEBUG:O2Suite:O2:0: /root/alice/sw/slc7_x86-64/boost/v1.71.0-1/lib/libboost_iostreams.so.1.71.0: undefined reference to `lzma_stream_encoder_mt@XZ_5.1.2alpha'
```
Need to have a closer look when I find time.

**Comment by davidrohr** [comment]
Closing this, apparently the same change was done in #2161 in the meantime

**Pull request closed without merging**
