### PR TITLE
bump infologger

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by ktf** [comment]
It looks like a genuine issue with this PR.

**Comment by sy-c** [comment]
yes, there was something wrong in readoutcard cmake

**Comment by sy-c** [comment]
@alisw/dataflow-experts can someone please review ?

**Review by vascobarroso — APPROVED** [review]

**Comment by sy-c** [comment]
Hello @alisw/infrastructure-admins 
can you please check the build/O2/alidist-centos8 error ? it does not seem related to this PR.

**Comment by ktf** [comment]
fullCI and C8 issue unrelated. Merging.

**Pull request merged**
