### PR TITLE
lz4: fix library relocation

### PR DESCRIPTION
**Pull request by ktf**
Move to new cmake based builds, which should generate the
appropriate RPATH information.

### CODE REVIEW

**Review by pzhristov — APPROVED** [review]
Much cleaner version that fixes longstanding issues.

**Comment by ktf** [comment]
@Barthelemy I see:

```
In file included from /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.6.0/v1.6.0/Modules/TOF/include/TOF/TaskDigits.h:21:
/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.6.0/v1.6.0/Modules/TOF/include/Base/Counter.h:207:9: error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]
    if (labels && labels[i] && !labels[i][0]) { // Labels are defined and label is empty
        ^~~~~~ ~~
        false
--
--
                           ^
In file included from /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.6.0/v1.6.0/Modules/TOF/src/TaskDigits.cxx:35:
In file included from /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.6.0/v1.6.0/Modules/TOF/include/TOF/TaskDigits.h:21:
/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/SOURCES/QualityControl/v1.6.0/v1.6.0/Modules/TOF/include/Base/Counter.h:220:9: error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]
    if (labels) {
    ~~  ^~~~~~
        false
```

is this a known issue?

**Comment by ktf** [comment]
Merging as it seems to improve issues about relocation.

**Comment by Barthelemy** [comment]
@ktf I have to release a new version but it is fixed in master

**Pull request merged**
