### PR TITLE
Roll back ROOT to v6-10-08 for Run2

### PR DESCRIPTION
**Pull request by dberzano**
See #994

### CODE REVIEW

**Comment by dberzano** [comment]
Run2 software is currently broken with the latest version of ROOT6. Does not affect Run3 software.

**Comment by sawenzel** [comment]
I am afraid we can't easily. I am already using a couple of the new features.

**Comment by ktf** [comment]
Can we move forward, then? Hoping it fixes the problem?

**Comment by pzhristov** [comment]
Do we have any list of problems with Root v6-12-04?

**Pull request merged**
