### PR TITLE
update python patch version

### PR DESCRIPTION
**Pull request by adriansev**

### CODE REVIEW

**Review by TimoWilken — APPROVED** [review]
Fine by me in principle! I've started a [caching build for the CI](https://alijenkins.cern.ch/job/CacheO2Package/75/) to avoid slowdows when this PR is merged.

**Comment by adriansev** [comment]
@TimoWilken the failed test seems to be only some timeout in QC:
```
++ ctest --output-on-failure -LE '(CCDB)|(manual)'
Test project /sw/BUILD/a3592fe80ac0afdc0bbc6df97905b4b277b88fbb/QualityControl
      Start  1: testActivity
 1/41 Test  #1: testActivity ............................***Timeout  30.11 sec

      Start  3: testMonitorObject
 2/41 Test  #3: testMonitorObject .......................***Timeout  30.06 sec
 ```

**Comment by TimoWilken** [comment]
That seems to have solved itself; now two different unit tests fail, apparently due to the out-of-memory killer, so unrelated to this PR.

@ktf, any objection to merging this patch version bump?

**Comment by TimoWilken** [comment]
I haven't heard back about the quota increase or the bare-metal machines, unfortunately...

**Comment by awegrzyn** [comment]
@adriansev Could you just quickly comment why this bump is needed?

**Comment by adriansev** [comment]
@awegrzyn well, i started to see on my centos7 cluster with both local (--nosystem) and cvmfs software this behavior for alien.py:
```
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
```

this error i traced it (meaning found in multiple places on google) to a asyncio problem in the finishing/closing of tasks which seemingly was fixed. So, given that changing of python version is not possible i thought that most innocuous action with guaranteed no side effects would be to update the patch version and see if it happen again (but i did not had the chance to test it yet)

**Pull request merged**
