### PR TITLE
Update Rivet and YODA

### PR DESCRIPTION
**Pull request by dberzano**
* Rivet 2.4.3
* YODA 1.6.1

### CODE REVIEW

**Comment by dberzano** [comment]
Note that this pull request affects the production branch (but does not trigger any rebuild of AliPhysics and its dependencies).

Needs @alisw/pwgmm sign-off.

**Comment by qgp** [comment]
Signed-off-by: @qgp for @alisw/pwgmm 

for reference: this also fixes the issues with rivet-buildplugin

**Comment by dberzano** [comment]
Note that the check was cancelled as another test was performed and proved successful, see https://alijenkins.cern.ch/job/build-any-ib/6152/.

**Comment by dberzano** [comment]
The new Rivet will be published shortly (alisw/ali-bot#283).

**Pull request merged**
