### PR TITLE
add generators to meta package

### PR DESCRIPTION
**Pull request by qgp**

### CODE REVIEW

**Comment by ktf** [comment]
Notice the generators package is currently used only by AliceO2.

**Comment by qgp** [comment]
Hi @ktf, I added the generators required for ALICE here on explicit request by @dberzano. I leave it to you guys to figure out if this is useful for ALICE or not.

**Comment by qgp** [comment]
you can also add sherpa.sh

**Comment by dberzano** [comment]
Hello @qgp, thanks for this PR and sorry for having overlooked it.

I have two requests:

1. Could you, instead of changing the `generators` package (used by O2), create a new `AliGenerators` package?
2. This package should `require` the generators and `build_require` all the generator _tests_ we have.

**Comment by dberzano** [comment]
As for the deployment: as discussed with @qgp the idea is to have to rebuild only `AliGenerators`: aliBuild is smart enough to rebuild only the things that have changed. `AliGenerators` would be a meta package but not like `AliEn-Runtime`: the single generators will be kept separated but this meta package would ease deployment in aliPublish and ease the rebuild procedure too.

**Comment by dberzano** [comment]
As for versioning: the idea (again, as discussed with @qgp) is to use a date-based versioning for the `AliGenerators` package.

As we can see from [the documentation](http://alisw.github.io/alibuild/reference.html) this is already supported by aliBuild.

This allows for automatic versioning without manually changing the `version:` in the `aligenerators.sh` package.

Waiting for your refreshed PR :-)

**Comment by dberzano** [comment]
For the record, @qgp: I have recently added a `DYLD_LIBRARY_PATH` thingy to all recipes, could you do the same for the generators while you refresh this PR? Thanks!

**Comment by qgp** [comment]
@dberzano: here comes the udpated PR. There is still an issue with EPOS and the new gcc toolchain, I will look into this separately.

The DYLD_LIBRARY_PATH is already in place where relevant.

Let me know if you are fine with the PR now.

**Comment by dberzano** [comment]
OK many thanks! Merging now.

**Pull request merged**
