### PR TITLE
Bump qualitycontrol to v1.107.2

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by vascobarroso — APPROVED** [review]

**Comment by davidrohr** [comment]
> I guess that it won't build against the latest O2

I have seen that, but if we bump QC in alidist, we have to make sure it also builds with latest O2, otherwise we break the O2 CI, since it will pick up the new QC :(.
Can we fix this in QC, to be compatible with latest O2/dev as well? Do we need to do anything on O2 side?

**Comment by Barthelemy** [comment]
@davidrohr checking...

**Comment by Barthelemy** [comment]
@davidrohr it is probably missing https://github.com/AliceO2Group/QualityControl/commit/42981ae72d5392102253d54ca6c50061b2492bef
I can add it to v1.107 --> v1.107.3

**Comment by Barthelemy** [comment]
As Vasco just pointed out to me, we don't need this version in alidist, it is just to redo the RPMs for the FLPs in prod

**Pull request closed without merging**
