### PR TITLE
Bump qcg version and tag to 1.6.2

### PR DESCRIPTION
**Pull request by graduta**

### CODE REVIEW

**Comment by awegrzyn** [comment]
Not sure why macOS build failed as `100% tests passed, 0 tests failed out of 72`. @ktf

**Comment by ktf** [comment]
@MichaelLettrich could you check what is going on? I suspect it silently failed while testing QC. @awegrzyn do you have the correct tag?

**Comment by MichaelLettrich** [comment]
```
DEBUG:O2Suite:qcg:1853: + '[' Xv1 = X ']'
DEBUG:O2Suite:qcg:1853: + export PKG_NAME=qcg
DEBUG:O2Suite:qcg:1853: + PKG_NAME=qcg
DEBUG:O2Suite:qcg:1853: + export PKG_VERSION=v1.6.2
DEBUG:O2Suite:qcg:1853: + PKG_VERSION=v1.6.2
DEBUG:O2Suite:qcg:1853: + export PKG_BUILDNUM=1
DEBUG:O2Suite:qcg:1853: + PKG_BUILDNUM=1
DEBUG:O2Suite:qcg:1853: + export SOURCE0=https://github.com/AliceO2Group/WebUi.git
DEBUG:O2Suite:qcg:1853: + SOURCE0=https://github.com/AliceO2Group/WebUi.git
DEBUG:O2Suite:qcg:1853: + export PKGPATH=osx_x86-64/qcg/v1.6.2-1
DEBUG:O2Suite:qcg:1853: + PKGPATH=osx_x86-64/qcg/v1.6.2-1
DEBUG:O2Suite:qcg:1853: + mkdir -p /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/TARS /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SPECS /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT
DEBUG:O2Suite:qcg:1853: + export BUILDROOT=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b
DEBUG:O2Suite:qcg:1853: + BUILDROOT=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b
DEBUG:O2Suite:qcg:1853: + '[' h == / ']'
DEBUG:O2Suite:qcg:1853: + export INSTALLROOT=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/ce5dfcecd6056d357869a88ee432c415e280467b/osx_x86-64/qcg/v1.6.2-1
DEBUG:O2Suite:qcg:1853: + INSTALLROOT=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/ce5dfcecd6056d357869a88ee432c415e280467b/osx_x86-64/qcg/v1.6.2-1
DEBUG:O2Suite:qcg:1853: + export SOURCEDIR=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: + SOURCEDIR=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: + export BUILDDIR=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b/qcg
DEBUG:O2Suite:qcg:1853: + BUILDDIR=/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b/qcg
DEBUG:O2Suite:qcg:1853: + SHORT_TAG=@aliceo2/q
DEBUG:O2Suite:qcg:1853: ++ dirname /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: + mkdir -p /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2
DEBUG:O2Suite:qcg:1853: + [[ @aliceo2/qc@1.6.2 != @aliceo2/qc@1.6.2 ]]
DEBUG:O2Suite:qcg:1853: + rm -fr /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/ce5dfcecd6056d357869a88ee432c415e280467b
DEBUG:O2Suite:qcg:1853: + [[ 0 == 0 ]]
DEBUG:O2Suite:qcg:1853: + rm -rf /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b
DEBUG:O2Suite:qcg:1853: + mkdir -p /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/ce5dfcecd6056d357869a88ee432c415e280467b/osx_x86-64/qcg/v1.6.2-1 /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b/qcg /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/INSTALLROOT/ce5dfcecd6056d357869a88ee432c415e280467b/osx_x86-64/qcg/v1.6.2-1
DEBUG:O2Suite:qcg:1853: + cd /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/ce5dfcecd6056d357869a88ee432c415e280467b
DEBUG:O2Suite:qcg:1853: + ln -snf ce5dfcecd6056d357869a88ee432c415e280467b /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/qcg-latest
DEBUG:O2Suite:qcg:1853: + [[ -n '' ]]
DEBUG:O2Suite:qcg:1853: + export GIT_REFERENCE=/build/mirror/qcg
DEBUG:O2Suite:qcg:1853: + GIT_REFERENCE=/build/mirror/qcg
DEBUG:O2Suite:qcg:1853: + [[ ! https://github.com/AliceO2Group/WebUi.git == '' ]]
DEBUG:O2Suite:qcg:1853: + [[ h != \/ ]]
DEBUG:O2Suite:qcg:1853: + [[ ! -d /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2 ]]
DEBUG:O2Suite:qcg:1853: + rm -rf /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: + git clone --reference /build/mirror/qcg https://github.com/AliceO2Group/WebUi.git /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: Cloning into '/build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2'...
DEBUG:O2Suite:qcg:1853: + cd /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SOURCES/qcg/v1.6.2/@aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: + git remote set-url --push origin https://github.com/AliceO2Group/WebUi.git
DEBUG:O2Suite:qcg:1853: + git checkout @aliceo2/qc@1.6.2
DEBUG:O2Suite:qcg:1853: error: pathspec '@aliceo2/qc@1.6.2' did not match any file(s) known to git
DEBUG:O2Suite:qcg:1853: 
ERROR:O2Suite:qcg:1853: Error while executing /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/SPECS/osx_x86-64/qcg/v1.6.2-1/build.sh on `alibuildmac03.cern.ch'.
ERROR:O2Suite:qcg:1853: Log can be found in /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/qcg-latest/log.
ERROR:O2Suite:qcg:1853: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR:O2Suite:qcg:1853: Build directory is /build/ci_checks/alidist_checker_macos_o2_ci_0/sw/BUILD/qcg-latest/qcg.
```
Fails to build qc as stated by Giulio

**Comment by awegrzyn** [comment]
Thanks for the logs!
Indeed it is wrongly tagged (with a trailing character) `@aliceo2/qc@1.6.2U` instead of `@aliceo2/qc@1.6.2U`

**Comment by graduta** [comment]
Closed in favour of: #1855

**Pull request closed without merging**
