### PR TITLE
Delete byproducts of old PRs (O2-1150)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@alisw/o2-wp3 I **think** this is what is needed to avoid obvious crosstalk between pull-requests, there might be some more failure modes but I am afraid that we cannot do anything about it, at least not with ninja (not even trying it with make...).

**Comment by davidrohr** [comment]
What about installed include files?

**Comment by ktf** [comment]
AFAICT, there is no way to get them from ninja.

```
_ ninja -t targets all  | grep include |wc
       0       0       0
```

**Comment by ktf** [comment]
Closing this to wait for the next time the problem happens.

**Comment by aphecetche** [comment]
For the next time, note that there's a file API in CMake (https://cmake.org/cmake/help/v3.16/manual/cmake-file-api.7.html#id1) that gives a lot of information about targets. 
Just have to create an empty `.cmake/api/v1/query/codemodel-v2` file in the build tree and upon cmake running you'll get a reply directory with one json file per target. Not saying it's definitely the way to go but might be worthwhile to investigate at some point, as this would allow to have a solution independent from the underlying build system used (ninja or make).  Don't think it allows to get the list of installed include files (to be x-checked), but the installed libs and exe should be there.

**Comment by ktf** [comment]
Interesting.

**Comment by ktf** [comment]
We have the issue again, so this should fix it.

**Comment by davidrohr** [comment]
@ktf : I believe this breaks the build directory in certain cases.
I am not 100% sure yet, but I ended up with a non-working incremental O2 build twice today and wiping the build folder recovered it in both cases. What I believe is that if an incremental build fails very early, it has cleaned up the stuff in stage found by `find stage/{bin,lib,tests} -type f > old.txt` and if nothing new is created inside, the next find command fails making the recipe fail. Is that possible?
Perhaps we should add an "|| true" there?

**Comment by ktf** [comment]
#2233 fixes the issue.

**Comment by davidrohr** [comment]
I updated alidist and retried, but I still encounter the same problem. Relevant part of the log is below. Any idea?
```
2020-05-07@10:34:03:DEBUG:O2:O2:0: + cd /home/qon/alice/sw/BUILD/81593f0698f6316e5cf76ffdc6728bd7781b77c6
2020-05-07@10:34:03:DEBUG:O2:O2:0: + ln -snf 81593f0698f6316e5cf76ffdc6728bd7781b77c6 /home/qon/alice/sw/BUILD/O2-latest
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ -n dev ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + ln -snf 81593f0698f6316e5cf76ffdc6728bd7781b77c6 /home/qon/alice/sw/BUILD/O2-latest-dev
2020-05-07@10:34:03:DEBUG:O2:O2:0: + export GIT_REFERENCE=/home/qon/alice/sw/MIRROR/o2
2020-05-07@10:34:03:DEBUG:O2:O2:0: + GIT_REFERENCE=/home/qon/alice/sw/MIRROR/o2
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ ! /home/qon/alice/O2 == '' ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ / != \/ ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ ! /home/qon/alice/O2 == '' ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ / == \/ ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + ln -snf /home/qon/alice/O2 /home/qon/alice/sw/SOURCES/O2/v1.2.0/0
2020-05-07@10:34:03:DEBUG:O2:O2:0: + mkdir -p /home/qon/alice/sw/SOURCES/O2/v1.2.0/0
2020-05-07@10:34:03:DEBUG:O2:O2:0: + cd /home/qon/alice/sw/BUILD/81593f0698f6316e5cf76ffdc6728bd7781b77c6/O2
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ '' == '' ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ ! -f /home/qon/alice/sw/BUILD/81593f0698f6316e5cf76ffdc6728bd7781b77c6/log ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ '' == '' ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ 94e7ececef0c921506c6df8c60ca679678d181c4 != \0 ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ -f /home/qon/alice/sw/BUILD/81593f0698f6316e5cf76ffdc6728bd7781b77c6/O2/.build_succeeded ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + set -o pipefail
2020-05-07@10:34:03:DEBUG:O2:O2:0: + tee /home/qon/alice/sw/BUILD/81593f0698f6316e5cf76ffdc6728bd7781b77c6/log
2020-05-07@10:34:03:DEBUG:O2:O2:0: + unset DYLD_LIBRARY_PATH
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ ! -n '' ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ '' != 1 ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ '' != /home/qon/alice/sw/SOURCES/O2/v1.2.0/0 ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + NINJA_BIN=ninja-build
2020-05-07@10:34:03:DEBUG:O2:O2:0: + type ninja-build
2020-05-07@10:34:03:DEBUG:O2:O2:0: + NINJA_BIN=ninja
2020-05-07@10:34:03:DEBUG:O2:O2:0: + type ninja
2020-05-07@10:34:03:DEBUG:O2:O2:0: + [[ -n ninja ]]
2020-05-07@10:34:03:DEBUG:O2:O2:0: + CMAKE_GENERATOR=Ninja
2020-05-07@10:34:03:DEBUG:O2:O2:0: + unset NINJA_BIN
2020-05-07@10:34:03:DEBUG:O2:O2:0: + '[' XNinja = XNinja ']'
2020-05-07@10:34:03:DEBUG:O2:O2:0: + mkdir -p stage/bin stage/lib stage/tests
2020-05-07@10:34:03:DEBUG:O2:O2:0: + find stage/bin stage/lib stage/tests -type f
2020-05-07@10:34:03:DEBUG:O2:O2:0: + ninja -t targets all
2020-05-07@10:34:03:DEBUG:O2:O2:0: + grep stage
2020-05-07@10:34:03:DEBUG:O2:O2:0: + cut -f1 -d:
2020-05-07@10:34:03:DEBUG:O2:O2:0: + cat old.txt old.txt new.txt
2020-05-07@10:34:03:DEBUG:O2:O2:0: + sort
2020-05-07@10:34:03:DEBUG:O2:O2:0: + uniq -c
2020-05-07@10:34:03:DEBUG:O2:O2:0: + grep ' 2 '
2020-05-07@10:34:03:DEBUG:O2:O2:0: + sed '-es|[ ][ ]*2 ||'
2020-05-07@10:34:03:DEBUG:O2:O2:0: + xargs rm -f
2020-05-07@10:34:03:ERROR:O2:O2:0: Error while executing /home/qon/alice/sw/SPECS/gentoo2_x86-64/O2/v1.2.0-1/build.sh on `qon'.
2020-05-07@10:34:03:ERROR:O2:O2:0: Log can be found in /home/qon/alice/sw/BUILD/O2-latest/log
2020-05-07@10:34:03:ERROR:O2:O2:0: Please upload it to CERNBox/Dropbox if you intend to request support.
2020-05-07@10:34:03:ERROR:O2:O2:0: Build directory is /home/qon/alice/sw/BUILD/O2-latest/O2.
```

**Comment by ktf** [comment]
I do not understand rm -f should return 0 even when called without args, same for xargs. Can you try adding a || true after the rm -f?

**Comment by sawenzel** [comment]
@davidrohr : I am seeing the same and opened a  ticket here: https://alice.its.cern.ch/jira/browse/O2-1398

**Comment by ktf** [comment]
@sawenzel in principle #2233 fixed what you reported in O2-1398. If you apply it do you see the same problem as @davidrohr ?

**Comment by davidrohr** [comment]
Hm, well yesterday I had the same problem as in the ticket, but now the folder is there and it still fails. So the error is slightly different. I'll try the `|| true` later, for now I just commented out the whole block to have something working.

**Pull request merged**
