### PR TITLE
Allow for custom package lists by distributions

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by mconcas** [comment]
Hi, I tried it on my Ubuntu machine, seems not working yet.
Log is the same as before:
```
++ PIPOPTION=--user
++ '[' '!' X = X ']'
++ env PYTHONUSERBASE=/data/BUILDS/latest/sw/INSTALLROOT/04a3c469b7967b7ff8c4a4b6ec1b6c9aef5570c2/ubuntu2004_x86-64/xjalienfs/1.3.7-local1 ALIBUILD=1 python3 -m pip install --ignore-installed --user file:///data/BUILDS/latest/sw/SOURCES/xjalienfs/1.3.7/1.3.7
Processing /data/BUILDS/latest/sw/SOURCES/xjalienfs/1.3.7/1.3.7
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/BUILDS/latest/sw/SOURCES/xjalienfs/1.3.7/1.3.7/setup.py", line 33, in <module>
          setuptools.setup(
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/dist.py", line 458, in __init__
          _Distribution.__init__(
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/dist.py", line 850, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/dist.py", line 849, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/data/BUILDS/latest/sw/ubuntu2004_x86-64/Python-modules/1.0-local1/share/python-modules/lib/python/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mslupeck** [comment]
Hi, I'm getting the same log output for xjalienfs as @mconcas

The full aliBuild log with debug options on is here
[log.txt](https://github.com/alisw/alidist/files/8233056/log.txt)

**Comment by mconcas** [comment]
[log.txt](https://github.com/alisw/alidist/files/8239923/log.txt)

**Comment by mfaggin** [comment]
Hi,
just as a follow up: I am encountering the same issue reported by @mconcas in my machine (Ubuntu 20.04 LTS) and suggested me to try and revert back before the commit #3907, commit 8a2f3668c1c68dff55aff153062ce7f0e610548b and I tried to just change by hand those lines (see the screenshot from the `git diff`):

image

However doing like this I get errors at the level of Python-modules bulding, I attach here the log. Do you have any clue? Or shall I just wait for the merging of this PR to solve the issue? [Here](https://cernbox.cern.ch/index.php/s/hGRYhoZjRQT3a3r) the log.

Many thanks.

**Comment by mslupeck** [comment]
Hi, for those of you using Ubuntu 20.04.4 who are stuck but need a local work-around, I managed to get it to build yesterday evening. I'm using the alidist commit: `af90552d08b3a158b2e79748cf99f40d67741236` and then 
`git revert 4779ac9c10cdbfe5d85b9e23c6b6d7ad6ac27377`

**Comment by rpezzi** [comment]
> Hi, for those of you using Ubuntu 20.04.4 who are stuck but need a local work-around, I managed to get it to build yesterday evening. I'm using the alidist commit: `af90552d08b3a158b2e79748cf99f40d67741236` and then `git revert 4779ac9c10cdbfe5d85b9e23c6b6d7ad6ac27377`

For reference, after observing the same problem as reported by Matteo for xjalienfs on Ubuntu 20.04, @mslupeck tip is working here. Thanks.

**Comment by martenole** [comment]
Hi, I have encountered the same error on two ubuntu 20.04 machines. With alidist@master and reverting the above mentioned commit the compilation of xjalienfs still fails for me.
For now I went back to `bd0ae3c3e5860b794822564187dafef2a48ebfeb` which is one commit before `4779ac9c10cdbfe5d85b9e23c6b6d7ad6ac27377` and with that the compilation works. I also attach the log for xjalienfs here, but I am not sure if it helps
[xjalienfs_log.txt](https://github.com/alisw/alidist/files/8304854/xjalienfs_log.txt)

**Comment by mfaggin** [comment]
Just for book-keeping in case it can help somebody else, waiting for a final solution of this issue.
The `git revert` solutions proposed above did not work for me in my Ubuntu 20.04 LTS machine, I was still encountering Python Module issues as mentioned above. The workaround that finally worked in my case was to use `git switch -d bd0ae3c3e5860b794822564187dafef2a48ebfeb`, apparently the differences with respect `git revert` are important in this case (thanks @mconcas for the suggestion).

**Comment by lgraczykCern** [comment]
Hi all. I have just started a very fresh installation on a new machine, Ubuntu 20.04, and I encounter the same problem. Any news on that matter @ktf @mconcas  ?
git switch -d to the version provided by @mfaggin worked for me, but it would be nice to have the final solution.

**Comment by stefanopolitano** [comment]
Hi all, I was encountering the same issue with xjalienfs thus I followed the workaround proposed by @mconcas, but now I am getting a different error regarding XRootD. I attach here the log file in case any of you have any hint 

[log.txt](https://github.com/alisw/alidist/files/8379113/log.txt)

**Comment by mconcas** [comment]
> just to provide a data point of experience: on ubuntu 20.04.4 with alidist at [0beda65](https://github.com/alisw/alidist/commit/0beda6541caebcea22ae7bfee3c160ccad058cc8) (datadist v1.3.11 (#4044) Thu Apr 7 00:09:58 2022 +0200) i did a alibuild for xjalienfs package with o2 defaults and `--no-remote-store -j2` with fresh update of pip related tools (`python3 -m pip install --no-cache-dir --user --upgrade pip setuptools wheel`) and everything worked (both usage of alien.py and of xrootd subsystem) .. so maybe this is no longer relevant?

Hello, I tried to build O2 with your configuration, I'm getting the same error.
The only difference in the two approaches that comes to my mind is that `xjalienfs` is not in dev mode for alibuild, although I have no clue whether this makes any difference.

So I fear this is somehow still relevant.

**Comment by adriansev** [comment]
@mconcas Hi! I do not have the xjalienfs in dev mode on this ubuntu machine, this is a pure alibuild nothing changed with respect to upstream alidist. This was done on a clean account on an ubuntu machine (not mine as i'm not a ubuntu user) where the system dependencies where the exact ones from [ALICE documentation](https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html) (only that alibuild was pip installed in the user)..

I wonder what setuptools the system seems? i do have in this account:
```
[Saturday 09.04.22 15:48] adrian@ALICE2 : ~  $ 
python3 -m pip install --no-cache-dir --user --upgrade pip setuptools wheel
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: pip in ./.local/lib/python3.8/site-packages (22.0.4)
Requirement already satisfied: setuptools in ./.local/lib/python3.8/site-packages (62.0.0)
Requirement already satisfied: wheel in ./.local/lib/python3.8/site-packages (0.37.1)
```
also, while digging in some ubuntu xrootd problems i discovered that `SETUPTOOLS_USE_DISTUTILS=stdlib` could return to some old behaviour 
see https://github.com/xrootd/xrootd/issues/1668#issuecomment-1090328582
maybe you can try this?

Moreover, while it should not matter but who knows, could you try to build just xjalienfs package, and see how it goes?
Also, to note is that `--no-remote-store` is important as if the package is downloaded as already built (without `--no-remote-store` argument), the the python configuration of building machine might be/is different from your own, so there could be mismatches of what is installed within alibuild python infrastructure.
For the moment i have no other ideas, and is frustrating that i cannot reproduce this..
Thanks!

**Comment by mconcas** [comment]
> @mconcas Hi! I do not have the xjalienfs in dev mode on this ubuntu machine, this is a pure alibuild nothing changed with respect to upstream alidist. This was done on a clean account on an ubuntu machine (not mine as i'm not a ubuntu user) where the system dependencies where the exact ones from [ALICE documentation](https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html) (only that alibuild was pip installed in the user)..
> 
> I wonder what setuptools the system seems? i do have in this account:
> 
> ```
> [Saturday 09.04.22 15:48] adrian@ALICE2 : ~  $ 
> python3 -m pip install --no-cache-dir --user --upgrade pip setuptools wheel
> /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
>   from cryptography.utils import int_from_bytes
> /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
>   from cryptography.utils import int_from_bytes
> Requirement already satisfied: pip in ./.local/lib/python3.8/site-packages (22.0.4)
> Requirement already satisfied: setuptools in ./.local/lib/python3.8/site-packages (62.0.0)
> Requirement already satisfied: wheel in ./.local/lib/python3.8/site-packages (0.37.1)
> ```
> 
> also, while digging in some ubuntu xrootd problems i discovered that `SETUPTOOLS_USE_DISTUTILS=stdlib` could return to some old behaviour see [xrootd/xrootd#1668 (comment)](https://github.com/xrootd/xrootd/issues/1668#issuecomment-1090328582) maybe you can try this?
> 
> Moreover, while it should not matter but who knows, could you try to build just xjalienfs package, and see how it goes? Also, to note is that `--no-remote-store` is important as if the package is downloaded as already built (without `--no-remote-store` argument), the the python configuration of building machine might be/is different from your own, so there could be mismatches of what is installed within alibuild python infrastructure. For the moment i have no other ideas, and is frustrating that i cannot reproduce this.. Thanks!

Hi!
so this is my setuptools:
```bash
mconcas@ali47xl:~/alice/gpu$ python3 -m pip install --no-cache-dir --user --upgrade pip setuptools wheel
Requirement already satisfied: pip in /home/mconcas/.local/lib/python3.8/site-packages (22.0.4)
Requirement already satisfied: setuptools in /home/mconcas/.local/lib/python3.8/site-packages (62.0.0)
Requirement already satisfied: wheel in /home/mconcas/.local/lib/python3.8/site-packages (0.37.1)
```
After cleaning up the `sw` directory I tried to reinstall xjalienfs only with `--no-remote-store` and setting the `SETUPTOOLS_USE_DISTUTILS=stdlib`.

Unfortunately I still get the same error. Must be something else...

**Comment by adriansev** [comment]
Hi! @mconcas @lgraczykCern @mslupeck i made another try to have all proper tools in place with https://github.com/alisw/alidist/pull/4080 maybe you can give it a try to see how it goes? this was tested with xjalienfs package installation, on centos7, fedora35 and ubuntu 20.04.

**Comment by mslupeck** [comment]
Thanks for the update @adriansev but the error remains the same. The full, most recent log is attached. 
[log.txt](https://github.com/alisw/alidist/files/8510522/log.txt)

**Comment by adriansev** [comment]
> Thanks for the update @adriansev but the error remains the same. The full, most recent log is attached. [log.txt](https://github.com/alisw/alidist/files/8510522/log.txt)

@mslupeck  well, if you do not use the `--no-remote-store` the packages will not be rebuilt.. notice   
`2022-04-19@08:37:38:DEBUG:O2:Python-modules:0: Packages already built using this version`

so, the new recipe was not applied .. but did you checked out the PR?
like doing in alidist something like:
```
git fetch <origin|or the name of your upstream remote> pull/4080/head:test4080
git checkout test4080
```

**Comment by adriansev** [comment]
actually one need to delete the content of the tar directory from ALIBUILD_WORK_DIR to disable the local stores (and force rebuild). i'm doing this each time and missed this to mention.

**Comment by adriansev** [comment]
just for reference this is what i get on the same ubuntu 20.04:
```
2022-04-19@10:32:04:DEBUG:xjalienfs:xjalienfs:xjalienfs: Building wheels for collected packages: alienpy
2022-04-19@10:32:04:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Building wheel for alienpy (setup.py): started
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Building wheel for alienpy (setup.py): finished with status 'done'
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Created wheel for alienpy: filename=alienpy-1.3.7-py3-none-any.whl size=60794 sha256=e02a796f6e85253c55ae7b9bcbca6c95b37b2e19c3930a7f8d56a2c4bc1e810b
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Stored in directory: /home/adrian/alisw/xjalienfs/tmp/pip-ephem-wheel-cache-jh51jc_g/wheels/8a/66/2d/f205aac84c57b786ba714393bad949954dc57c545dbb5ee9e4
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs: Successfully built alienpy
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs: Installing collected packages: gnureadline, commonmark, websockets, typing-extensions, pygments, pycparser, async-stagger, rich, cffi, cryptography, pyOpenSSL, alienpy
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs:   WARNING: The script cmark is installed in '/home/adrian/alisw/sw/INSTALLROOT/08fa52ca443d615beb598b7a4a0e802dee1d6359/ubuntu2004_x86-64/xjalienfs/1.3.7-local1/bin' which is not on PATH.
2022-04-19@10:32:05:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs:   WARNING: The script pygmentize is installed in '/home/adrian/alisw/sw/INSTALLROOT/08fa52ca443d615beb598b7a4a0e802dee1d6359/ubuntu2004_x86-64/xjalienfs/1.3.7-local1/bin' which is not on PATH.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs:   WARNING: The scripts alien-cert-info, alien-token-destroy, alien-token-info, alien-token-init, alien.py, alien_cmd, alien_cp, alien_find, alien_guid2lfn, alien_lfn2guid, alien_ls, alien_mirror, alien_mkdir, alien_mv, alien_pfn, alien_ps, alien_rm, alien_rmdir, alien_stat, alien_submit and alien_whereis are installed in '/home/adrian/alisw/sw/INSTALLROOT/08fa52ca443d615beb598b7a4a0e802dee1d6359/ubuntu2004_x86-64/xjalienfs/1.3.7-local1/bin' which is not on PATH.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs: tensorflow 2.4.1 requires numpy~=1.19.2, but you have numpy 1.22.3 which is incompatible.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs: tensorflow 2.4.1 requires typing-extensions~=3.7.4, but you have typing-extensions 4.2.0 which is incompatible.
2022-04-19@10:32:06:DEBUG:xjalienfs:xjalienfs:xjalienfs: Successfully installed alienpy-1.3.7 async-stagger-0.3.1 cffi-1.15.0 commonmark-0.9.1 cryptography-36.0.2 gnureadline-8.0.0 pyOpenSSL-22.0.0 pycparser-2.21 pygments-2.11.2 rich-12.2.0 typing-extensions-4.2.0 websockets-10.3
```

**Comment by mslupeck** [comment]
Hi @adriansev ,
Thanks for all the trials and hints, but it still doesn't work for me. Details are below.

Your git commands didn't work for me.
> ```
> git fetch <origin|or the name of your upstream remote> pull/4080/head:test4080
> git checkout test4080
> ```
The second one failed with `error: pathspec 'test4080' did not match any file(s) known to git`

Instead, I downloaded your branch, that you used for that PR::
```
git remote add adriansev https://github.com/adriansev/alidist.git
git fetch adriansev python_base_packages
git checkout python_base_packages
```
I see the same sequence of commits in `git log` as in your branch on github, so I'm fairly sure I have the right version of alidist.

Since my previous message, I've done a completely clean install. I removed the whole `sw` directory, after which I ran:
`env ALIBUILD_O2_TESTS=1 aliBuild build O2 --defaults o2 --debug &> log.txt`
I suppose `--no-remote-store` is meaningless since I did a clean install.

The full log is quite big, so I had to upload it to the external place: 
https://drive.google.com/file/d/1uaIgz2pWeCwtF0zJfwsc0Cs1kDq2FrHq/view?usp=sharing

**Comment by martenole** [comment]
Hi @mslupeck 
for me there is now no workaround needed anymore. And before I also had the issue described above on my ubuntu 20 machine.
With aliBuild v1.11.1 and the latest alidist and O2 the compilation works again out of the box for me.
Maybe it works for you as well now?
Cheers,
Ole

**Comment by mslupeck** [comment]
> Hi @mslupeck for me there is now no workaround needed anymore. And before I also had the issue described above on my ubuntu 20 machine. With aliBuild v1.11.1 and the latest alidist and O2 the compilation works again out of the box for me. Maybe it works for you as well now? Cheers, Ole

@martenole Thanks for the hint about the aliBuild version. Now I got everything to build successfully (even without PR #4080)
The resolution (for the benefit of others) is:

- Don't follow the instructions (!) from 'Ubuntu prerequisites' page: https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html
  - In my case, it installed aliBuild v1.8.x, which is clearly very outdated.  
- You can get the latest v1.11.1 by following the 'I don't have root permissions' page: https://alice-doc.github.io/alice-analysis-tutorial/building/custom.html#i-dont-have-root-permissions

Then indeed everything works out of the box. Thanks again @adriansev and @martenole

**Comment by mconcas** [comment]
> i no longer have any idea on what to try to reproduce ..

Hi @adriansev, thanks a lot for following this up. I just updated `alidist` and the re-triggered build of `xjalienfs` went through smoothly.
I did not need any additional `--no-remote-store`, I'm using aliBuild `1.11.1`. Now it's building O2, so I think this is fixed 🤞🏼.

>  - Don't follow the instructions (!) from 'Ubuntu prerequisites' page: https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html
In my case, it installed aliBuild v1.8.x, which is clearly very outdated.

Hi @mslupeck, thanks for spotting this, I'll investigate and adjust the guide accordingly.

**Comment by mfaggin** [comment]
Hi @mconcas @mslupeck , if I understand correctly the last couple of messages from you, now there is a way to avoid any workaround mentioned above and the solution is just to `git pull` the `alidist` local repository and build the entire framework after updating `aliBuild`? If yes, is it enough to update it with the command `pip install alibuild --upgrade --user` or is it mandatory also to do the mentioned operations in `.bashrc` without root permissions?
Thanks again for the support.

**Comment by mconcas** [comment]
> Hi @mconcas @mslupeck , if I understand correctly the last couple of messages from you, now there is a way to avoid any workaround mentioned above and the solution is just to `git pull` the `alidist` local repository and build the entire framework after updating `aliBuild`? If yes, is it enough to update it with the command `pip install alibuild --upgrade --user` or is it mandatory also to do the mentioned operations in `.bashrc` without root permissions? Thanks again for the support.

Ciao Mattia, I just did a pull of `alidist` and upgraded `aliBuild` and it started working.

**Comment by ktf** [comment]
for the record, i uploaded a new ubuntu package for alibuild. you can get
it after doing apt update.

Ciao,
Giulio

**Comment by chiarazampolli** [comment]
Thanks!

**Review by pzhristov — APPROVED** [review]

**Pull request merged**
