### PR TITLE
Use system lhapdf if available

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @davidrohr, LHAPDF is a small package which does not take so much time for being built. Do you have a particular reason for preferring a system-installed one? If we merge this, we might get into weird issues with our users having LHAPDF "accidentally" installed system-wide. I'd prefer not to merge this, but I am open to listen to your use case :-)

**Comment by ktf** [comment]
I agree with @dberzano. My experience is that using system installations for "physics" packages leaves the door open to can of worms.

**Comment by davidrohr** [comment]
Hi, OK, I see, might make sense from your standpoint. I usually prefer system packages as general principle, but I can keep that patch locally.

**Comment by ktf** [comment]
Alternatively we could have some special default where we are much more aggressive with this.

**Comment by ktf** [comment]
Something like `--defaults full-system-dependencies-use-at-your-own-risk`

**Comment by davidrohr** [comment]
Hi,

that sounds like a good idea for me. Can you provide multiple defaults in a row?
Then, one could perhaps also use that for what I described here: https://github.com/alisw/alidist/issues/876.

**Comment by ktf** [comment]
No, you cannot, by design. We want to avoid people specifying multiple defaults on the command line, in order to avoid huge command lines, to avoid having to check if they are compatible with each other, and to avoid to have default order dependent builds.

What we discussed at some point was to allow defaults to inherit from each other, but unless I am mistaken (@dberzano correct me if not the case) no work went into it.

**Comment by dberzano** [comment]
@ktf you're correct, no work's been done so far.

**Pull request closed without merging**
