### PR TITLE
xjalienfs/alienpy 1.6.2

### PR DESCRIPTION
**Pull request by adriansev**
Mostly XRootD::Cp fixes and improvements:
* document `-parent`; rewrite logic to add `-rmprefix` (removing first N components from the absolute path of the source) when copy to destination
* fileIsValid :: update the access/mod time for present and valid files also when md5 check is not requested
* XRootD::cp allow (and fix) multiple usage of `-e` `-exclude` `-exclude_re`

Also a fix for args passed to InitConnection when no token is found

### CODE REVIEW

**Comment by adriansev** [comment]
so, so far, the errors are:
1. for AliGenerators/generators
```
## sw/BUILD/Rivet-latest/log
--
                 from /sw/slc7_x86-64/HepMC3/3.3.0-1/include/HepMC3/ReaderFactory_fwd.h:19,
                 from /sw/slc7_x86-64/HepMC3/3.3.0-1/include/HepMC3/ReaderFactory.h:15,
                 from RivetHepMC_3.cc:7:
/sw/slc7_x86-64/HepMC3/3.3.0-1/include/HepMC3/bxzstr/strict_fstream.hpp:57:7: error: redefinition of 'class strict_fstream::Exception'
   57 | class Exception
      |       ^~~~~~~~~
In file included from ../Core/zstr/zstr.hpp:16,
```

2. for O2/alidist-slc9-aarch64
```
## sw/BUILD/Python-modules-latest/log
--
Collecting Keras==2.7.0
  Downloading keras-2.7.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 81.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.1 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.7.1
```

**Review by costing — APPROVED** [review]

**Comment by adriansev** [comment]
@ktf Looking into full build log of O2/fullCI/alidist i do not really get what is the problem but certainly is not the alienpy :) .. could you review please these errors?
Thanks a lot!

**Comment by adriansev** [comment]
@ktf seems that test with error in the required alidist/O2Suite/o2/macOS-arm is the same:
```
Testing framework-run...framework error not found
```

Given that this is repeatable and have nothing to do with alien.py can this be merged?
Thank you!

**Comment by adriansev** [comment]
Good morning @ktf :) Can this be merged?

**Pull request merged**
