### PR TITLE
Migrate to GCC 13

### PR DESCRIPTION
**Pull request by ktf**
Migrate to GCC 13

- Move to GCC 13.2.0
- Move to GDB 14.2
- Do not use GCC 7.3.0 as default, since now AliRoot it's built
  with its own default.
- Add support for CCACHE. While disabled by default it can be enabled
  by passing CCACHE_DISABLE=false as environment variable.

### CODE REVIEW

**Comment by davidrohr** [comment]
I just checked locally that the Geant header problem we have with new GCC versions is fixed in new Geant versions, i.e. if we have a fix and go back to new Geant reverting https://github.com/alisw/alidist/pull/5567, the GCC bump should go through.
@sawenzel : do we any ETA when we can bump Geant again?

**Comment by sawenzel** [comment]
@davidrohr : https://github.com/alisw/alidist/pull/5574

**Comment by davidrohr** [comment]
Great, thx!

**Comment by davidrohr** [comment]
https://github.com/AliceO2Group/AliceO2/pull/13425  and https://github.com/AliceO2Group/AliceO2/pull/13426 should fix O2 compilation with this GCC

**Comment by ktf** [comment]
aarch issue unrelated and it was working before. Merging this to be in time for the PbPb datataking.

**Pull request merged**
