### PR TITLE
Bump FairMQ to v1.4.26

### PR DESCRIPTION
**Pull request by rbx**
Upon request from @AndreyLebedev, related to the ongoing DDS/ODC developments.

@Barthelemy this also includes the changes discussed in https://github.com/AliceO2Group/InfoLogger/pull/52.

### CODE REVIEW

**Comment by rbx** [comment]
```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/Readout/v1.4.7.2/v1.4.7.2/src/testTxFMQ.cxx:28:16: error: 'class FairMQChannel' has no member named 'ValidateChannel'; did you mean 'FairMQChannel'?
   if (!channel.ValidateChannel()) {
                ^~~~~~~~~~~~~~~
                FairMQChannel
```

The `ValidateChannel()` method has been deprecated since more than a year and has now been removed. Please use `Validate()`.

**Comment by Barthelemy** [comment]
@rbx thank you very much, as usual you are very fast !

**Comment by teo** [comment]
Since the blocking Readout bump was merged, can this merge go ahead?

**Review by teo — APPROVED** [review]

**Comment by ktf** [comment]
Yes, that's why I merged the other one, actually. Let's wait for the tests, though.

**Comment by rbx** [comment]
Closing in favor of #2635.

**Pull request closed without merging**
