### PR TITLE
Fix boost library name in ThePeg and Rivet

### PR DESCRIPTION
**Pull request by ktf**
ThePeg and Rivet recipes now account for the different names that
boost_thread and boost_system can have.

### CODE REVIEW

**Comment by dberzano** [comment]
@qgp, @ktf: can we merge this?

**Comment by dberzano** [comment]
@ktf ping

**Comment by ktf** [comment]
There is an issue in the Rivet recipe which prevented the tests from working. This should fix it. Waiting for the tests to run again.

**Comment by ktf** [comment]
Rivet tests now correctly pass. Not sure why the ROOT6 test fails, but it seems unrelated.

**Pull request merged**
