### PR TITLE
root: support for Big Sur

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by MichaelLettrich** [comment]
@Barthelemy can it be that some of the npm packages FLP uses can't find python or is incompatible with the used python version? We use `python 3.9` on the machine via brew, symlinked propperly and path verified, so things look OK from our side. Maybe some merges without macOS CI passing brought in the issue? 

```bash

gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/bin/node',
gyp verb cli   '/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--jobs',
gyp verb cli   'max'
gyp verb cli ]
gyp info using node-gyp@5.1.0
gyp info using node@14.12.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - "python" is not in PATH or produced an error
gyp verb find Python checking if "python2" can be used
gyp verb find Python - executing "python2" to get executable path
gyp verb find Python - "python2" is not in PATH or produced an error
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:438:11)
gyp ERR! stack     at Socket.emit (events.js:314:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:672:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/bin/node" "/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/BUILD/0c229dd4ad7b738c1a1c3c49e871274232f0bd16/qcg/node_modules/@aliceo2/qc
gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by Barthelemy** [comment]
@awegrzyn @graduta I think that you could be more of help than myself

**Comment by awegrzyn** [comment]
I managed to build yesterday on Catalina with XCode 12.2, how can I reproduce this?

**Comment by awegrzyn** [comment]
Could you check if there's on your system `/usr/bin/python` or `/usr/local/bin/python3`?
If not could you try adding `Python` to `build_requires`?

**Comment by MichaelLettrich** [comment]
```bash
alibuild@aido2osx3 ~ % cd /usr/local/bin/    
alibuild@aido2osx3 bin % ls -la | grep python
lrwxr-xr-x    1 alibuild  admin      37 10 Nov 10:04 2to3 -> ../Cellar/python@3.9/3.9.0_1/bin/2to3
lrwxr-xr-x    1 alibuild  admin      41 10 Nov 10:04 2to3-3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/2to3-3.9
lrwxr-xr-x    1 alibuild  admin      49 10 Nov 10:04 easy_install-3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/easy_install-3.9
lrwxr-xr-x    1 alibuild  admin      38 10 Nov 10:04 idle3 -> ../Cellar/python@3.9/3.9.0_1/bin/idle3
lrwxr-xr-x    1 alibuild  admin      40 10 Nov 10:04 idle3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/idle3.9
lrwxr-xr-x    1 alibuild  admin      37 10 Nov 10:04 pip3 -> ../Cellar/python@3.9/3.9.0_1/bin/pip3
lrwxr-xr-x    1 alibuild  admin      39 10 Nov 10:04 pip3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/pip3.9
lrwxr-xr-x    1 alibuild  admin      39 10 Nov 10:04 pydoc3 -> ../Cellar/python@3.9/3.9.0_1/bin/pydoc3
lrwxr-xr-x    1 alibuild  admin      41 10 Nov 10:04 pydoc3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/pydoc3.9
lrwxr-xr-x    1 alibuild  admin      22 26 Mär  2020 python -> /usr/local/bin/python3
lrwxr-xr-x    1 alibuild  admin      40 10 Nov 10:04 python3 -> ../Cellar/python@3.9/3.9.0_1/bin/python3
lrwxr-xr-x    1 alibuild  admin      47 10 Nov 10:04 python3-config -> ../Cellar/python@3.9/3.9.0_1/bin/python3-config
lrwxr-xr-x    1 alibuild  admin      42 10 Nov 10:04 python3.9 -> ../Cellar/python@3.9/3.9.0_1/bin/python3.9
lrwxr-xr-x    1 alibuild  admin      49 10 Nov 10:04 python3.9-config -> ../Cellar/python@3.9/3.9.0_1/bin/python3.9-config
lrwxr-xr-x    1 alibuild  admin      39 10 Nov 10:04 wheel3 -> ../Cellar/python@3.9/3.9.0_1/bin/wheel3
```

**Comment by MichaelLettrich** [comment]
```bash
alibuild@aido2osx3 ~ % ls -la /usr/bin | grep python 
lrwxr-xr-x     1 root   wheel        75  5 Dez  2019 python -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x     1 root   wheel        82  5 Dez  2019 python-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
lrwxr-xr-x     1 root   wheel        75  5 Dez  2019 python2 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x     1 root   wheel        75  5 Dez  2019 python2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x     1 root   wheel        82  5 Dez  2019 python2.7-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
-rwxr-xr-x     1 root   wheel     31488 22 Sep 02:29 python3
lrwxr-xr-x     1 root   wheel        76  5 Dez  2019 pythonw -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
lrwxr-xr-x     1 root   wheel        76  5 Dez  2019 pythonw2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
```

`PATH` looks fine as well.

```bash
alibuild@aido2osx3 bin % echo $PATH
/usr/local/opt/openjdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
```

**Review by pzhristov — DISMISSED** [review]
I tested it locally and it solves the issue with the wrong compilation options in ACLiC.

**Comment by awegrzyn** [comment]
@MichaelLettrich `node-gyp` requires any python to be available in `PATH`. Apparently there's none. I tried to fix it by adding `Python` to `build_required` (https://github.com/alisw/alidist/pull/2622) but no luck.

**Comment by MichaelLettrich** [comment]
@awegrzyn : as you can see, python should be available on `PATH`. I mean our buildscripts use bash and `python`, so does `alibuild`. Are you sure the packages is compatible with `python3.9` ?

**Comment by pzhristov** [comment]
I will merge this PR since the errors are not related to it.

**Comment by awegrzyn** [comment]
Indeed, official `node-gyp` page does not mention anything higher than `3.8` although I'd expect it to fail during compilation not python detection.

**Pull request merged**
