### PR TITLE
Bump FairMQ to 1.4.43

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by ktf** [comment]
@rbx does this already have the channel-config option for the Send timeout?

**Comment by davidrohr** [comment]
> @rbx does this already have the channel-config option for the Send timeout?

No, this is several days old. It supports querrying the number of peers. We couldn't merge it before since it deprecated some functions used by DD, which was bumped today to become compatible to the new FairMQ.

**Comment by davidrohr** [comment]
errors unrelated, merging

**Comment by rbx** [comment]
@ktf for the channel-config option I have a PR open already, shouldn't be too long until that is tagged.

**Pull request merged**
