### PR TITLE
QC v0.24.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@ktf @MichaelLettrich there seems to be a problem with the build/O2/alidist

**Comment by MichaelLettrich** [comment]
I will check. Without looking at it I can say though that last week I had a couple of timeouts when checking out CERN hosted repositories and had to try again multiple times till they were checked out properly. Seems CERN infrastructure is  not always able to take the load that the massive telework is putting on it.

**Comment by ktf** [comment]
Did you take my changes? Looks like it still fails...

**Comment by Barthelemy** [comment]
@ktf  yes : https://github.com/AliceO2Group/QualityControl/compare/v0.23.1...v0.24.0

**Comment by ktf** [comment]
Yeah, I missed one place, apparently... :-/ Will do a new PR.

**Comment by ktf** [comment]
I took the liberty to tag 0.24.1 with the fix. Sorry about that.

**Comment by Barthelemy** [comment]
There is another PR automatically generated when releasing QC.

**Pull request closed without merging**
