### PR TITLE
Specify ROOTSYS to current aliBuild ROOT version

### PR DESCRIPTION
**Pull request by mfasDa**
Needed in order to force compilation against ROOT from
alidist in case system ROOT versions are present.

### CODE REVIEW

**Comment by ktf** [comment]
I would use `$ROOT_ROOT`.

**Comment by mfasDa** [comment]
> I would use `$ROOT_ROOT`.

Not sure what you mean, but RooUnfold has its own CMake module for ROOT, and there it discovers ROOT according to the root-config executable which it finds like this: 

```
FIND_PROGRAM( ROOT_CONFIG_EXECUTABLE root-config PATHS ${ROOT_DIR}/bin NO_DEFAULT_PATH )
```

So in order to take the custom root I need to specify -DROOT_DIR, and I suspect the environment variable ROOT_ROOT won't help here too much.

**Comment by mfasDa** [comment]
@ktf I see now what you mean, but who exports $ROOT_ROOT? Our modulefile still export $ROOTSYS. Just checked with the ROOT module and the $ROOT_ROOT environment variable is not set

**Comment by ktf** [comment]
modulefiles are build time only. alibuild automatically defines `<uppercase-package-name>_ROOT`. IMHO this is better than using ROOTSYS, because this way the user environment is less likely to come into play during the build.

**Comment by mfasDa** [comment]
@ktf Thanks for clarification - I was not aware of this. Indeed then that approach is safer.

**Review by ktf — APPROVED** [review]

**Pull request merged**
