### PR TITLE
Bump qualitycontrol to v1.12.0

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by sy-c — APPROVED** [review]

**Comment by Barthelemy** [comment]
@ktf @TimoWilken Something seems to have gone wrong here...

**Comment by TimoWilken** [comment]
- alidist-dataflow is a known issue, to be fixed soon(tm) -- sorry!
- alidist-centos8 is something I've been trying to debug since yesterday, no news yet
- I'm looking into fullCI/alidist

**Comment by ktf** [comment]
the centos8 issue seems to be a CCDB one?

**Comment by ktf** [comment]
@Barthelemy / @costing is this expected?
```
→ curl http://ccdb-test.cern.ch:8080/Test/pid11174/Detector/1615360582377/Hello\=World/
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> No matching objects found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /></body></html>%                                                                                                                                          (alibuild_deps)
```

**Pull request merged**
