### PR TITLE
Move O2 to v10.2.0-alice2

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
Thx for this! It was overdue :)
Just one comment, before merging I would wait a bit for the CI to stabilize before we introduce more possibly breaking changes

**Comment by ktf** [comment]
No, I guess I will just merge it now for the fun of it breaking everything... ;-)

Yes, we should also do the merging in steps, first deploying the compiler from the PR branch, checking it can actually work on CVMFS (there is some blackmagic to get it to work there) and then rebuild everything.

**Comment by pzhristov** [comment]
@TimoWilken @ktf I think the check was misled by a warning where the variable "failed" was present and then it considered the build as failed. Concerning the documentation build, it seems we need to install with pip3 setuptools.

I have an issue with gcc 9.3 on Ubuntu: If I use it, the reconstruction of simulated data (AliRoot) crashes with segmentation violation in TOF, that looks like caused by wrong compilation.

**Comment by TimoWilken** [comment]
@pzhristov @ktf it seems the GCC build fails with a genuine error:
```
2021-01-08@07:17:56:DEBUG:O2Suite:GCC-Toolchain:build_O2_alidist: ++ pushd mpfr
2021-01-08@07:17:56:DEBUG:O2Suite:GCC-Toolchain:build_O2_alidist: /mnt/mesos/sandbox/sandbox/o2-alidist/sw/SPECS/slc7_x86-64/GCC-Toolchain/v9.3.0-alice1-1/GCC-Toolchain.sh: line 50: pushd: mpfr: No such file or directory
2021-01-08@07:17:56:ERROR:O2Suite:GCC-Toolchain:build_O2_alidist: Error while executing /mnt/mesos/sandbox/sandbox/o2-alidist/sw/SPECS/slc7_x86-64/GCC-Toolchain/v9.3.0-alice1-1/build.sh on `alientest02'.
2021-01-08@07:17:56:ERROR:O2Suite:GCC-Toolchain:build_O2_alidist: Log can be found in /mnt/mesos/sandbox/sandbox/o2-alidist/sw/BUILD/GCC-Toolchain-latest/log
2021-01-08@07:17:56:ERROR:O2Suite:GCC-Toolchain:build_O2_alidist: Please upload it to CERNBox/Dropbox if you intend to request support.
2021-01-08@07:17:56:ERROR:O2Suite:GCC-Toolchain:build_O2_alidist: Build directory is /mnt/mesos/sandbox/sandbox/o2-alidist/sw/BUILD/GCC-Toolchain-latest/GCC-Toolchain.
```

Perhaps the mpfr extension was removed in v9.3.0-alice1? The error is from [this line] with `EXT=mpfr`. I note that there is no mpfr directory in [gcc-toolchain].

[this line]: https://github.com/alisw/alidist/blob/0eba9068c8fa925e4ad629e584eb1da43352deb7/gcc-toolchain.sh#L66
[gcc-toolchain]: https://github.com/alisw/gcc-toolchain/tree/alice/v9/gcc-9.3.0

I'll send a PR to install setuptools in the documentation build in a minute.

**Comment by ktf** [comment]
I hopefully fixed it.

**Comment by davidrohr** [comment]
@TimoWilken (fyi @ktf) : the alidist-centos8 CI is failing due to
```
[ERROR] error while setting up workflow: boost::filesystem::status: Operation not permitted: "/tmp"
```
Could you have a look?

**Comment by davidrohr** [comment]
@ktf @TimoWilken : This should fix the build for CC7, an autoconf package is missing in the SLC7 container: alisw/docks#217

**Comment by davidrohr** [comment]
OK, my fix doesn't work since we are not using the system autoconf I guess.

**Comment by davidrohr** [comment]
For reference, just tried locally, fixing the autoconf-archive issue, compilation in SLC7 still fails in the CI container for building `gmq` with
```
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c: In function 'mpn_compute_powtab_mul':
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:142:3: error: 'for' loop initial declarations are only allowed in C99 mode
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (long pi = start_idx; pi >= 0; pi--)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:142:3: note: use option -std=c99 or -std=gnu99 to compile your code
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c: In function 'mpn_compute_powtab_div':
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:226:3: error: 'for' loop initial declarations are only allowed in C99 mode
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (long pi = n_pows - 1; pi >= 0; pi--)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:274:13: error: redefinition of 'pi'
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (long pi = n_pows; pi >= 0; pi--)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:              ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:226:13: note: previous definition of 'pi' was here
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (long pi = n_pows - 1; pi >= 0; pi--)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:              ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:274:3: error: 'for' loop initial declarations are only allowed in C99 mode
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (long pi = n_pows; pi >= 0; pi--)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c: In function 'powtab_decide':
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:296:3: error: 'for' loop initial declarations are only allowed in C99 mode
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (size_t pn = (un + 1) >> 1; pn != 1; pn = (pn + 1) >> 1)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../gcc/gmp/mpn -I.. -D__GMP_WITHIN_GMP -I../../../gcc/gmp -DOPERATION_hgcd2_jacobi -DNO_ASM -g -c hgcd2_jacobi.c -o hgcd2_jacobi.o
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:304:10: error: redefinition of 'pn'
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    size_t pn = un - 1;
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:           ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:296:15: note: previous definition of 'pn' was here
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (size_t pn = (un + 1) >> 1; pn != 1; pn = (pn + 1) >> 1)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:                ^
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a: compute_powtab.c:308:3: error: 'for' loop initial declarations are only allowed in C99 mode
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    for (long i = n_pows - 2; i >= 0; i--)
2021-03-08@15:42:55:DEBUG:GCC-Toolchain:GCC-Toolchain:v9.3.0-a:    ^
```

**Comment by ktf** [comment]
How come you have `v9.3.0`? Are you using a devel package? This worked find on my ubuntu box. I will check if there is a newer version of gmp.

**Comment by ktf** [comment]
@Barthelemy we also need https://github.com/AliceO2Group/QualityControl/pull/681 for this to go forward.

**Comment by Barthelemy** [comment]
@ktf QC v1.16.1 is released: https://github.com/alisw/alidist/pull/2982  it contains your changes. 

Will we enable c++20 ?

**Comment by davidrohr** [comment]
For reference, fix for the GMP issue is here: alisw/gcc-toolchain#3

**Comment by davidrohr** [comment]
> Will we enable c++20 ?

I am afraid the GPU part will not yet run with C++20. But at some point we can switch to 20 and just enforce that everything that will run on the GPU has to remain C++17 compatible. But has Gcc10 full C++20 support already?

**Comment by ktf** [comment]
@Barthelemy I would vote to enable c++20, however we cannot use it in headers which are exposed to ROOT (like it happens already in AliROOT for C++11, IIRC...). In particular I am looking forward for aggregate initialisers...

**Comment by ktf** [comment]
@davidrohr yes, I would say we need to treat GPU and dictionary code like you suggest... I do not think anyone has full C++20, yet, however we can simply restrict ourselves to the long available features which work everywhere.

**Comment by davidrohr** [comment]
@ktf : Unfortunately, the recipe doesn't work correctly. The prefer system check allows using a system GCC 7, even though we have moved the version to 10. The check should depend on the version we have actually set in the recipe.

**Comment by ktf** [comment]
Yes, I modified the check at some point, but then realised it would have killed the AliPhysics builds, which at least for now we should keep on GCC7. I will check how to introduce a version dependent check.

**Comment by davidrohr** [comment]
great, gcc and O2 compiled, but we have failing ctests...
Can try later to reproduce this locally...

**Comment by davidrohr** [comment]
OK, just tried locally. Failing tests for me are:
```
2021-04-23@18:07:04:DEBUG:O2:O2:0: The following tests FAILED:
2021-04-23@18:07:04:DEBUG:O2:O2:0:       93 - Detectors/Base/test/testMatBudLUT.cxx (Failed)
2021-04-23@18:07:04:DEBUG:O2:O2:0:      323 - o2sim_G3 (Failed)
2021-04-23@18:07:04:DEBUG:O2:O2:0:      325 - o2sim_hepmc (Failed)
```

So some similarities, but in the CI even more are failing:
```
	 53 - DataFormats/MemoryResources/test/testMemoryResources.cxx (Failed)
	 78 - Utilities/O2Device/test/test_O2Device.cxx (Failed)
	 93 - Detectors/Base/test/testMatBudLUT.cxx (Failed)
	323 - o2sim_G3 (Failed)
	325 - o2sim_hepmc (Failed)
```
The additional CI failures seem to come from, which I am not seen locally:
```
[ERROR] Failed to create/open shared memory segment (fmq_f8fb93a1_m_0): File exists
```

**Comment by ktf** [comment]
```
    Start 1: Detectors/Base/test/testMatBudLUT.cxx
1/2 Test #1: Detectors/Base/test/testMatBudLUT.cxx ...   Passed   28.48 sec
```

might be a timing regression which brings it above 30 seconds...

**Comment by ktf** [comment]
Nevermind, it looks like issues in the Fortran code... :-/ @sawenzel can you have a look?

**Comment by davidrohr** [comment]
@ktf : I have tried to improve the version check, but apparently that is not so easy.
It seems that during the prefer_system_check of the recipe, aliBuild does not expose the usual environment variables. I.e. $PKG_VERSION is not set. So I have no idea how to make this check dynamic.

**Comment by ktf** [comment]
@davidrohr see https://github.com/alisw/alibuild/pull/678. That said, do we really want to complicate it that way? Can't we simply switch everything to v10.2?

**Comment by davidrohr** [comment]
> @davidrohr see [alisw/alibuild#678](https://github.com/alisw/alibuild/pull/678). That said, do we really want to complicate it that way? Can't we simply switch everything to v10.2?

I think having that functionality makes sense anyway. I mean it has happened several times that something was bumped but the prefer_system_check was not bumped, and then something broke.

In general, as discussed yesterday, personally I'd also prefer to bump everything to 10.2 :)
We can just try it in this PR? Would make sense, then we see asap what breaks and what we have to fix.
Then we can still decide to leave AliRoot at 7.3 if it fails horribly :)

**Comment by awegrzyn** [comment]
> Can't we simply switch everything to v10.2?

Would that mean no more compiler from `devtoolset` on C7?

**Comment by davidrohr** [comment]
> Would that mean no more compiler from `devtoolset` on C7?

Yes, but actually, already when we move the o2 defaults to 10.2, we'll also have to bump o2-dataflow I guess.

**Comment by awegrzyn** [comment]
Ok, on FLP side we plan to migrate to CS8 soon (mid-June) so this should be all fine, although for CC7 we'd probably prefer stick with a compiler version that can come from system.

**Comment by ktf** [comment]
Ok, I've updated this to use the newly introduced REQUESTED_VERSION feature of aliBuild 1.8.2.

**Comment by davidrohr** [comment]
@TimoWilken : Disk seems to be running full in the full CI builder:
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -DNO_ASM -g   -o libmpn.la  fib_table.lo mp_bases.lo add.lo add_1.lo add_n.lo sub.lo sub_1.lo sub_n.lo cnd_add_n.lo cnd_sub_n.lo cnd_swap.lo neg.lo com.lo mul_1.lo addmul_1.lo submul_1.lo add_err1_n.lo add_err2_n.lo add_err3_n.lo sub_err1_n.lo sub_err2_n.lo sub_err3_n.lo lshift.lo rshift.lo dive_1.lo diveby3.lo divis.lo divrem.lo divrem_1.lo divrem_2.lo fib2_ui.lo fib2m.lo mod_1.lo mod_34lsub1.lo mode1o.lo pre_divrem_1.lo pre_mod_1.lo dump.lo mod_1_1.lo mod_1_2.lo mod_1_3.lo mod_1_4.lo lshiftc.lo mul.lo mul_fft.lo mul_n.lo sqr.lo mul_basecase.lo sqr_basecase.lo nussbaumer_mul.lo mulmid_basecase.lo toom42_mulmid.lo mulmid_n.lo mulmid.lo random.lo random2.lo pow_1.lo rootrem.lo sqrtrem.lo sizeinbase.lo get_str.lo set_str.lo compute_powtab.lo scan0.lo scan1.lo popcount.lo hamdist.lo cmp.lo zero_p.lo perfsqr.lo perfpow.lo strongfibo.lo gcd_11.lo gcd_22.lo gcd_1.lo gcd.lo gcdext_1.lo gcdext.lo gcd_subdiv_step.lo gcdext_lehmer.lo div_q.lo tdiv_qr.lo jacbase.lo jacobi_2.lo jacobi.lo get_d.lo matrix22_mul.lo matrix22_mul1_inverse_vector.lo hgcd_matrix.lo hgcd2.lo hgcd_step.lo hgcd_reduce.lo hgcd.lo hgcd_appr.lo hgcd2_jacobi.lo hgcd_jacobi.lo mullo_n.lo mullo_basecase.lo sqrlo.lo sqrlo_basecase.lo toom22_mul.lo toom32_mul.lo toom42_mul.lo toom52_mul.lo toom62_mul.lo toom33_mul.lo toom43_mul.lo toom53_mul.lo toom54_mul.lo toom63_mul.lo toom44_mul.lo toom6h_mul.lo toom6_sqr.lo toom8h_mul.lo toom8_sqr.lo toom_couple_handling.lo toom2_sqr.lo toom3_sqr.lo toom4_sqr.lo toom_eval_dgr3_pm1.lo toom_eval_dgr3_pm2.lo toom_eval_pm1.lo toom_eval_pm2.lo toom_eval_pm2exp.lo toom_eval_pm2rexp.lo toom_interpolate_5pts.lo toom_interpolate_6pts.lo toom_interpolate_7pts.lo toom_interpolate_8pts.lo toom_interpolate_12pts.lo toom_interpolate_16pts.lo invertappr.lo invert.lo binvert.lo mulmod_bnm1.lo sqrmod_bnm1.lo div_qr_1.lo div_qr_1n_pi1.lo div_qr_2.lo div_qr_2n_pi1.lo div_qr_2u_pi1.lo sbpi1_div_q.lo sbpi1_div_qr.lo sbpi1_divappr_q.lo dcpi1_div_q.lo dcpi1_div_qr.lo dcpi1_divappr_q.lo mu_div_qr.lo mu_divappr_q.lo mu_div_q.lo bdiv_q_1.lo sbpi1_bdiv_q.lo sbpi1_bdiv_qr.lo sbpi1_bdiv_r.lo dcpi1_bdiv_q.lo dcpi1_bdiv_qr.lo mu_bdiv_q.lo mu_bdiv_qr.lo bdiv_q.lo bdiv_qr.lo broot.lo brootinv.lo bsqrt.lo bsqrtinv.lo divexact.lo bdiv_dbm1c.lo redc_1.lo redc_2.lo redc_n.lo powm.lo powlo.lo sec_powm.lo sec_mul.lo sec_sqr.lo sec_div_qr.lo sec_div_r.lo sec_pi1_div_qr.lo sec_pi1_div_r.lo sec_add_1.lo sec_sub_1.lo sec_invert.lo trialdiv.lo remove.lo and_n.lo andn_n.lo nand_n.lo ior_n.lo iorn_n.lo nior_n.lo xor_n.lo xnor_n.lo copyi.lo copyd.lo zero.lo sec_tabselect.lo comb_tables.lo add_n_sub_n.lo 
libtool: link: ar rc .libs/libmpn.a  fib_table.o mp_bases.o add.o add_1.o add_n.o sub.o sub_1.o sub_n.o cnd_add_n.o cnd_sub_n.o cnd_swap.o neg.o com.o mul_1.o addmul_1.o submul_1.o add_err1_n.o add_err2_n.o add_err3_n.o sub_err1_n.o sub_err2_n.o sub_err3_n.o lshift.o rshift.o dive_1.o diveby3.o divis.o divrem.o divrem_1.o divrem_2.o fib2_ui.o fib2m.o mod_1.o mod_34lsub1.o mode1o.o pre_divrem_1.o pre_mod_1.o dump.o mod_1_1.o mod_1_2.o mod_1_3.o mod_1_4.o lshiftc.o mul.o mul_fft.o mul_n.o sqr.o mul_basecase.o sqr_basecase.o nussbaumer_mul.o mulmid_basecase.o toom42_mulmid.o mulmid_n.o mulmid.o random.o random2.o pow_1.o rootrem.o sqrtrem.o sizeinbase.o get_str.o set_str.o compute_powtab.o scan0.o scan1.o popcount.o hamdist.o cmp.o zero_p.o perfsqr.o perfpow.o strongfibo.o gcd_11.o gcd_22.o gcd_1.o gcd.o gcdext_1.o gcdext.o gcd_subdiv_step.o gcdext_lehmer.o div_q.o tdiv_qr.o jacbase.o jacobi_2.o jacobi.o get_d.o matrix22_mul.o matrix22_mul1_inverse_vector.o hgcd_matrix.o hgcd2.o hgcd_step.o hgcd_reduce.o hgcd.o hgcd_appr.o hgcd2_jacobi.o hgcd_jacobi.o mullo_n.o mullo_basecase.o sqrlo.o sqrlo_basecase.o toom22_mul.o toom32_mul.o toom42_mul.o toom52_mul.o toom62_mul.o toom33_mul.o toom43_mul.o toom53_mul.o toom54_mul.o toom63_mul.o toom44_mul.o toom6h_mul.o toom6_sqr.o toom8h_mul.o toom8_sqr.o toom_couple_handling.o toom2_sqr.o toom3_sqr.o toom4_sqr.o toom_eval_dgr3_pm1.o toom_eval_dgr3_pm2.o toom_eval_pm1.o toom_eval_pm2.o toom_eval_pm2exp.o toom_eval_pm2rexp.o toom_interpolate_5pts.o toom_interpolate_6pts.o toom_interpolate_7pts.o toom_interpolate_8pts.o toom_interpolate_12pts.o toom_interpolate_16pts.o invertappr.o invert.o binvert.o mulmod_bnm1.o sqrmod_bnm1.o div_qr_1.o div_qr_1n_pi1.o div_qr_2.o div_qr_2n_pi1.o div_qr_2u_pi1.o sbpi1_div_q.o sbpi1_div_qr.o sbpi1_divappr_q.o dcpi1_div_q.o dcpi1_div_qr.o dcpi1_divappr_q.o mu_div_qr.o mu_divappr_q.o mu_div_q.o bdiv_q_1.o sbpi1_bdiv_q.o sbpi1_bdiv_qr.o sbpi1_bdiv_r.o dcpi1_bdiv_q.o dcpi1_bdiv_qr.o mu_bdiv_q.o mu_bdiv_qr.o bdiv_q.o bdiv_qr.o broot.o brootinv.o bsqrt.o bsqrtinv.o divexact.o bdiv_dbm1c.o redc_1.o redc_2.o redc_n.o powm.o powlo.o sec_powm.o sec_mul.o sec_sqr.o sec_div_qr.o sec_div_r.o sec_pi1_div_qr.o sec_pi1_div_r.o sec_add_1.o sec_sub_1.o sec_invert.o trialdiv.o remove.o and_n.o andn_n.o nand_n.o ior_n.o iorn_n.o nior_n.o xor_n.o xnor_n.o copyi.o copyd.o zero.o sec_tabselect.o comb_tables.o add_n_sub_n.o
ar: .libs/libmpn.a: No space left on device
```

**Comment by TimoWilken** [comment]
@davidrohr thanks, I've restarted the builder.

**Comment by davidrohr** [comment]
@TimoWilken : For this failing centos8 container `build/O2/alidist-centos8`: could you perhaps also just restart these builders? I would like to see if the error persists then. If it is some kind of problem with the /tmp folder, perhaps it disappears?

**Comment by davidrohr** [comment]
@ktf: Thx for bumping also for CC8 :). Now we see another failure in the GPU CI. Seems to be some ABI issue. I am trying this locally.

**Comment by davidrohr** [comment]
OK, the problem seems to be that the AMD ROCm compiler tries to link to an old ABI for std::runtime_error.
I am wondering why I do not see this problem when compiling on my local system not inside the docker. Will investigate and try to find a patch.

**Comment by davidrohr** [comment]
Fix for the fullCI with gcc 10.2 in AliceO2Group/AliceO2#6017.

**Comment by davidrohr** [comment]
@TimoWilken : Could you restart the full CI for this PR?

**Comment by TimoWilken** [comment]
@davidrohr restarted

**Comment by davidrohr** [comment]
@ktf : CC8 and FullCI build with GCC 10 now.

@TimoWilken : the build/O2/alidist failed with
```
c++: fatal error: Killed signal terminated program cc1plus
```
Was this an out of memory error again?

**Comment by ktf** [comment]
Hopefully not GCC 10.2 being more memory hungry... :-/ @TimoWilken can you restart those two tests?

**Comment by TimoWilken** [comment]
I've restarted `build/O2/alidist` (though I also restarted it earlier when it was killed, so this is probably real). The error in `build/O2/alidist-centos8` is the same as usual, not related to this PR.

**Comment by davidrohr** [comment]
Failed again in the analysis part:
```
[ 93%] Linking CXX executable ../../../stage/bin/o2-analysis-hf-tree-creator-lc-topkpi
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake[2]: *** [Analysis/Tasks/PWGHF/CMakeFiles/O2exe-analysis-hf-task-jpsi.dir/taskJpsi.cxx.o] Error 1
gmake[1]: *** [Analysis/Tasks/PWGHF/CMakeFiles/O2exe-analysis-hf-task-jpsi.dir/all] Error 2
```
I would not exclude that new compilers might need more memory. They might also perform more optimizations, and computer memory usually increases, so compiler developers will over time assume they have more memory available.

**Comment by davidrohr** [comment]
For reference, I just did a test locally with GCC 10.2 on my gentoo, and memory consumption during analysis compilation was reduced to ~3 gb per file compared to 4.5 GB before.

**Comment by davidrohr** [comment]
For reference, it seems to fail continuously due to running out of memory.

But on top, it seems the cmake errors we have seen before are real. At the problems
```
	 93 - Detectors/Base/test/testMatBudLUT.cxx (Failed)
	323 - o2sim_G3 (Failed)
	325 - o2sim_hepmc (Failed)
```
I can reproduce consistently in the CI docker container.
To me it seems there is a general problem with Geant 3.
@sawenzel : Could you have a look?
I think the testMatBudLUT fails since it needs a geometry, and for that reasons calls o2sim.
And the other 2 o2sim tests with geant 3 fail as well.
The Geant 4 tests pass.
Interestingly enough, on my native system also with gcc 10.2 I can run o2sim with Geant3 without problems.

**Comment by ktf** [comment]
Could it be a problem with some common block which for some reason is allocated larger than before?

**Comment by pzhristov** [comment]
The common blocks did not change during the last few years, probably we have another issue there.

**Comment by ktf** [comment]
Common blocks behaviour is affected by linker / compiler behaviour, if I remember correctly.

**Comment by davidrohr** [comment]
OK, so I have now tested the simulation manually in the container (after compiling without ALIBUILD_O2_TESTS), and what I see is that 
```
o2-sim-serial -n 0 -e TGeant4 -g pythia8
```
runs through correctly, while
```
o2-sim-serial -n 0 -e TGeant3 -g pythia8
```
crashes either crashes with a segfault (log [crash.log.txt](https://github.com/alisw/alidist/files/6405217/crash.log.txt) ) or it terminates with failure (log like this [crash.log.2.txt](https://github.com/alisw/alidist/files/6405250/crash.log.2.txt) ).

I have tried to catch the segfault in gdb, but when I attach gdb I always see the 2nd type of error, and that is not a crash, but the application just exits.

Finally, I had a look with valgrind. And surprisingly, running inside valgrind, the simulations finishes successfully: 
[valgrind.log.txt](https://github.com/alisw/alidist/files/6405352/valgrind.log.txt)
Not sure how to proceed from here... Who is an expert for Fortran / Geant3?

**Comment by davidrohr** [comment]
OK, actually, comparing the working and failing version, I see this valgrind warning quite exactly where it fails with GCC 10:
```
==71611== Source and destination overlap in memcpy(0x431a1708, 0x431a1550, 42964)
==71611==    at 0x4C2E81D: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1035)
==71611==    by 0x41D87BB0: mzmove_ (mzmove.F:146)
==71611==    by 0x41D82F69: mzgar1_ (mzgar1.F:158)
==71611==    by 0x41D858CB: mzlift_ (mzlift.F:358)
==71611==    by 0x41D80599: mzbook_ (mzbook.F:63)
==71611==    by 0x41C03DBB: g3smate_ (gsmate.F:190)
==71611==    by 0x41DC7443: TGeant3::G3Material(int&, char const*, double, double, double, double, double, float*, int) (TGeant3.cxx:2834)
==71611==    by 0x41DCFEA2: TGeant3TGeo::Material(int&, char const*, double, double, double, double, double, float*, int) (TGeant3TGeo.cxx:823)
==71611==    by 0x795E096: o2::base::MaterialManager::Material(char const*, int, char const*, float, float, float, float, float, float*, int) (MaterialManager.cxx:71)
==71611==    by 0x50F184B: o2::passive::Shil::createMaterials() (Shil.cxx:1436)
==71611==    by 0x50F3015: o2::passive::Shil::ConstructGeometry() (Shil.cxx:98)
==71611==    by 0xCD920B0: FairMCApplication::ConstructGeometry() (FairMCApplication.cxx:936)
```
Perhaps the memcpy implementation has changed, and is non-linear now. That could explain it.

**Comment by ktf** [comment]
The stacktrack seems to point to https://github.com/alisw/geant3/blob/master/gbase/gzebra.F#L39 maybe NZEBRA < 30? Does -fsanitize=address say anything else?

**Comment by davidrohr** [comment]
I haven't tried with sanitizers.

So, from the valgrind warning, I am really confused. Looking at the code, `mzmove_ (mzmove.F:146)` calls UCOPY2, which is some memory copy routing that actually does overlap checking: https://gitlab.physics.ox.ac.uk/metodiev/genfit_atrap/-/blob/fe22beb36f03d5c633ddf9edf77c742ea2a82c5a/geant3/minicern/ucopy2.F
Why is it calling memcpy, which requires non overlapping regions?

**Comment by ktf** [comment]
There is also an UCOPY in `mzmove.F:122`, can you change that to UCOPY2?

**Comment by davidrohr** [comment]
> There is also an UCOPY in `mzmove.F:122`, can you change that to UCOPY2?
ok, can try, recompiling now that GEANT3 is a development package...

**Comment by davidrohr** [comment]
OK, I have a fix, PR is coming...

**Comment by davidrohr** [comment]
@TimoWilken : Could you restart the CC7 CI (O2/alidist) here?
(Fix is in #3003)

**Comment by davidrohr** [comment]
@TimoWilken :  I think it died with some random network error:
```
curl: (18) transfer closed with 443938 bytes remaining to read
## End sw/BUILD/FreeType-latest/log
```
Could you restart it once more?

**Comment by ktf** [comment]
Ok, the tests are green apart from the usual issues in CC8. I am merging this so that we get at least one build with 10.2 so that the dependencies are cached and we can try it on the grid. We can revert if it causes problems.

**Comment by davidrohr** [comment]
Nice, finally. So next we should try to move the AliRoot defaults to gcc 10 :)
In case of problems, sure we can revert but first lets try to fix them!

**Comment by pzhristov** [comment]
@davidrohr AliRoot/AliPhysics have no issues with gcc 10.2. I already run full set of tests.

**Comment by davidrohr** [comment]
I have done the same using the O2 defaults, looks also good to me.

So what shall we do as next test?
Move it generally to 10.2, but keep it at 7.3 for the release defaults for now?

**Comment by ktf** [comment]
The only problem I see is building GCC 10.2 on slc6, since that's what we are still using for the AliRoot releases (or finally iron out the various quirks when moving GRID to slc7). We should also bump the protobuf version in the o2 defaults, so that we can move to arrow 3.0.

**Comment by davidrohr** [comment]
Agreed on protobuf / arrow.
I have opened #3006 to test bumping gcc generally, except in release defaults.

**Pull request merged**
