### PR TITLE
Change standard to build boost from 14 to 17

### PR DESCRIPTION
**Pull request by Barthelemy**
Given that brew updated boost to 1.69, most people will have to rebuild boost (we force version 1.68). However, boost 1.68 does not build on Mac, it gives an error : 
```
./boost/asio/ip/basic_resolver_entry.hpp:54:7: error: no type named 'string_view' in namespace 'boost::asio'; did you mean 'std::string_view'?
      BOOST_ASIO_STRING_VIEW_PARAM host, BOOST_ASIO_STRING_VIEW_PARAM service)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      std::string_view
```

### CODE REVIEW

**Comment by Barthelemy** [comment]
It breaks ReadoutCard on CC7

**Comment by Barthelemy** [comment]
https://github.com/AliceO2Group/ReadoutCard/pull/101 fixes the problem

**Comment by Barthelemy** [comment]
@dberzano could you approve again  ?

**Comment by ktf** [comment]
I will merge this after 16:00.

**Comment by mpuccio** [comment]
Actually I tested this on top of alidist master locally with XCode 10.2.1 and the compilation of boost failed with the following error:
```    
"g++"   -std=c++17 -fPIC -m64 -O3 -Wall -pedantic -dynamic -gdwarf-2 -fexceptions -Wno-long-long -Wno-inline  -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_DYN_LINK=1 -DNDEBUG  -I"." -c -o "build-boost/boost/bin.v2/libs/system/build/darwin-4.2.1/release/cxxstd-17-iso/threading-multi/error_code.o" "libs/system/src/error_code.cpp"

In file included from libs/system/src/error_code.cpp:19:
./boost/system/detail/error_code.ipp:53:58: error: redefinition of 'message'
  BOOST_SYSTEM_DECL_ std::string generic_error_category::message( int ev ) const
                                                         ^
/usr/local/include/boost/system/error_code.hpp:891:67: note: previous definition is here
inline std::string boost::system::detail::generic_error_category::message( int ev ) const
                                                                  ^
In file included from libs/system/src/error_code.cpp:19:
./boost/system/detail/error_code.ipp:146:61: error: redefinition of 'default_error_condition'
  BOOST_SYSTEM_DECL_ error_condition system_error_category::default_error_condition( int ev ) const
                                                            ^
/usr/local/include/boost/system/error_code.hpp:926:85: note: previous definition is here
inline boost::system::error_condition boost::system::detail::system_error_category::default_error_condition( int ev ) const BOOST_NOEXCEPT
                                                                                    ^
In file included from libs/system/src/error_code.cpp:19:
./boost/system/detail/error_code.ipp:351:57: error: redefinition of 'message'
  BOOST_SYSTEM_DECL_ std::string system_error_category::message( int ev ) const
                                                        ^
/usr/local/include/boost/system/error_code.hpp:931:66: note: previous definition is here
inline std::string boost::system::detail::system_error_category::message( int ev ) const
                                                                 ^
3 errors generated.
```
I noticed that the Mac testing is running with the previous version of clang, maybe it is green because of that?

**Comment by Barthelemy** [comment]
@mpuccio I have the same version of XCode. What version of boost do you have on your mac ?

**Comment by mpuccio** [comment]
boost 1.69, do you think that there is a kind of cross talk between my system boost and the one that is getting installed by aliBuild?

**Comment by Barthelemy** [comment]
I am not sure. I have boost 1.69 installed by brew and the latest XCode. The little change in this PR was enough to get the boost 1.68 from alidist to compile. What command did you run that provoked this error ? did you run alienv before or not ?

**Comment by mpuccio** [comment]
No, I always check that I am not inside alienv. These are the options I am using: `aliBuild O2 -j9 -z --defaults o2 -d`

**Comment by mpuccio** [comment]
Hi @Barthelemy , removing boost from brew solved the issue...

**Comment by Barthelemy** [comment]
@mpuccio Not sure if it is good or not though :) It should work for people who already have 1.69 installed with brew.

**Comment by mpuccio** [comment]
Eh, this is indeed a good point. But it might just be an issue with my local config (it is actually quite clean, but one never knows).

**Pull request merged**
