### PR TITLE
Bump AEGIS to v1.4

### PR DESCRIPTION
**Pull request by preghenella**

### CODE REVIEW

**Comment by preghenella** [comment]
not sure I understand the failures in some of the checks.
They seem to me not correlated with this PR.
@ktf  can this be merged in case?

**Comment by ktf** [comment]
@TimoWilken @MichaelLettrich is aidoosx full again?

**Comment by TimoWilken** [comment]
@ktf @MichaelLettrich it seems that the Python build is missing libssl:
```
2020-12-09@17:24:54:DEBUG:QualityControl:Python:553: building '_hashlib' extension
2020-12-09@17:24:54:DEBUG:QualityControl:Python:553: gcc -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openssl@1.1/include/openssl -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openssl@1.1/include/openssl -I/System/Volumes/Data
2020-12-09@17:24:54:DEBUG:QualityControl:Python:553: gcc -bundle -undefined dynamic_lookup -L/System/Volumes/Data/build/ci_checks/alice_ci_0/qualitycontrol-o2/sw/osx_x86-64/libffi/v3.2.1-1/lib -L/System/Volumes/Data/build/ci_checks/alice_ci_0/qualitycontrol-o2/sw/osx_x86-6
2020-12-09@17:24:54:DEBUG:QualityControl:Python:553: ld: library not found for -lssl
2020-12-09@17:24:54:DEBUG:QualityControl:Python:553: clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I don't know if that's causing the later error (`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: fatal error: the __LINKEDIT segment does not cover the end of the file (can't be processed) in: osx_x86-64/Python/v3.6.10-1/bin/python3.6`).

**Comment by TimoWilken** [comment]
@ktf The AliGenerators error is interesting:
```
ERROR: Error on 'git ls-remote --heads https://github.com/live-clones/hdf5.git': fatal: could not read Username for 'https://github.com': No such device or address
```
It seems that repo has been deleted (or maybe made private). I'll make a fork under the alisw org and change the entry in alidist.

**Comment by ktf** [comment]
No, I think I understand what is going on. I will add you to the ticket I have opened with CERN IT.

**Pull request merged**
