### PR TITLE
xrootd v5.4.3

### PR DESCRIPTION
**Pull request by adriansev**
for reference:
[diff commit list](https://github.com/xrootd/xrootd/compare/v5.4.2...v5.4.3)
[Release notes](https://github.com/xrootd/xrootd/blob/v5.4.3/docs/ReleaseNotes.txt)

### CODE REVIEW

**Comment by adriansev** [comment]
@TimoWilken @ktf Hi guys! is there a way to start the tests even if this is a draft?

**Comment by adriansev** [comment]
@ktf Hi Giulio! it seems that something is really wrong with O2/fullCI/alidist (with the actual test i mean) as i see in the full log:
```
[64788:TOFClusterer]: [15:17:07][INFO] tof::Geo: Initialization of TOF rotation parameters
[64788:TOFClusterer]: [15:17:07][INFO]  no TGeo! Loading it
[64788:TOFClusterer]: [15:17:07][INFO] Loading geometry from /sw/BUILD/262b9d243304143ea244358a4c2aa490c5338bf9/O2-full-system-test/full-system-test-sim/o2sim_geometry-aligned.root
[64821:qc-task-MID-QcTaskMIDDigits]: [15:17:07][STATE] Exiting FairMQ state machine
[64821:qc-task-MID-QcTaskMIDDigits]: [15:17:07][FATAL] Unhandled o2::framework::runtime_error reached the top of main of o2-qc, device shutting down.
[64821:qc-task-MID-QcTaskMIDDigits]:  Reason: Unknown argument requested digitrofs - no matching route found for digitrofs
[64821:qc-task-MID-QcTaskMIDDigits]:  Backtrace follow: 
```
from the huge log i cannot tell for certain, but given the above FATAL, maybe is not the xrootd problem?

**Comment by dstocco** [comment]
Indeed, the problem is that I modified the QC and the .json used by it in O2DPG. Unfortunately, the CI is not using the QC master. So I had to revert the O2DPG commit, until the QC is bumped.
This is done here: https://github.com/AliceO2Group/O2DPG/commit/b00cbbf75c616316071b21dcd9041fd80e7a258d
So in principle if the fullCI is rerun, it should work now...

**Comment by adriansev** [comment]
@ktf Hi Giulio! seems that the tests are ok now.. can we move forward with this?

**Pull request merged**
