### PR TITLE
adding recipe for FFTW3

### PR DESCRIPTION
**Pull request by matthias-kleiner**
Adding a recipe for FFTW3 to be able to use fast fourier transform in O2 which will be used in https://github.com/AliceO2Group/AliceO2/pull/5947

### CODE REVIEW

**Review by ktf — DISMISSED** [review]

**Comment by ktf** [comment]
@TimoWilken this is not getting picked up....

**Comment by matthias-kleiner** [comment]
Do I have to force push to restart the checks or will they start automatically or is there something wrong with the "Build Documentation / build" check which has to be fixed first?

**Comment by davidrohr** [comment]
it rechecks periodically

**Review by ktf — APPROVED** [review]

**Comment by ktf** [comment]
"Pending — Started Fri 10:14 CET @ mesosci/ci_alisw_slc7-builder_latest/3"

**Comment by ktf** [comment]
@TimoWilken "Pending — Started Fri 10:14 CET @ mesosci/ci_alisw_slc7-builder_latest/3"

**Comment by wiechula** [comment]
@ktf , can this be merged? Or is there something that should / can be done about the failing test?

**Comment by ktf** [comment]
I am not sure about the cc8 error... Let me check...

**Comment by wiechula** [comment]
@ktf, did you manage to have a look?

**Comment by ktf** [comment]
Now it's green. Merging.

**Pull request merged**
