### PR TITLE
Use libInfoLogger instead of InfoLogger in QC

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by Barthelemy** [comment]
ok qc has been bumped

**Comment by awegrzyn** [comment]
Well not really, you bumped QC to `v0.9.4` and the build is still using `v0.9.3`

**Comment by ktf** [comment]
Did you really bump qc? i see `v0.9.3` in `qualitycontrol.sh`.

**Comment by Barthelemy** [comment]
Indeed, it seems I did not ? let me check and redo it if needed.

**Pull request merged**
