### PR TITLE
Temporarily masking FairMQ unit test FairMQ.Poller

### PR DESCRIPTION
**Pull request by matthiasrichter**
The FairMQ unit tests are not completely ready for continuous integration because
they use hardcoded ports which might be taken already on the testing machine.

Some of the tests are already masked, excluding now FairMQ.Poller, which creates
problems in the macos CI and results in O2 not even being compiled.

Unit tests should be re-activated once a generic solution is implemented in FairMQ
Related feature request:
https://github.com/FairRootGroup/FairRoot/issues/857

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@dennisklein there is a problem in the `FairMQ.Device` unit test in the testing of exceptions
```
[EXCEPTION IN Run][08:58:27][INFO] DEVICE: Running...
[EXCEPTION IN Run][08:58:27][STATE] Entering ERROR state
[EXCEPTION IN Run][08:58:27][DEBUG] Shutting down Plugin Manager
[EXCEPTION IN Run][08:58:27][DEBUG] Unloaded plugin: 'control', version '1.3.7', maintainer 'FairRootGroup <fairroot@gsi.de>', homepage 'https://github.com/FairRootGroup/FairRoot'
[EXCEPTION IN Run][08:58:27][DEBUG] Shutting down Plugin Services
[EXCEPTION IN Run][08:58:27][DEBUG] Destructing device exceptions_Run_
[EXCEPTION IN Run][08:58:27][STATE] Exiting FairMQ state machine
/mnt/mesos/sandbox/sandbox/sw/SOURCES/FairMQ/v1.3.7/v1.3.7/test/device/_exceptions.cxx:62: Failure
Death test: RunExceptionIn("Run")
    Result: failed to die.
 Error msg:
[  DEATH   ] 
[  FAILED  ] Exceptions.InRun________static (120 ms)
```

**Comment by dberzano** [comment]
@matthiasrichter I have just discussed with @dennisklein an option that would fit our workflow, and his.

We are going to _not_ exclude any test, but to put the whole `ctest` call in an `if` clause (they will be disabled . I am updating your PR directly if you don't mind.

**Comment by dberzano** [comment]
It's funny that I have the power to amend some person's PR, and then approve it as well, lol...

**Comment by matthiasrichter** [comment]
ah good, fine with me. Yes and you got the power.

I still would call this a temporary solution and re-activate once the proper solution is in place.

**Pull request merged**
