### PR TITLE
DDS: update to 2.2

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Looks like the new FairMQ requires this...

**Comment by ktf** [comment]
or boost...

**Comment by ktf** [comment]
or FairMQ itself.

**Comment by ktf** [comment]
@dennisklein @rbx do you plan to support DDS 2.2 in the 1.3.X branch?

**Comment by rbx** [comment]
It is supported and required in FairMQ 1.3.7 (released just now).

**Comment by ktf** [comment]
@dberzano @brinick any idea why the O2 tests are stuck?

**Comment by ktf** [comment]
@Barthelemy can you take a look at the QC error?

**Comment by Barthelemy** [comment]
Hi, Sure, I am in the ML workshop though thus my time is very limited today.

**Comment by dberzano** [comment]
I am aware... I am checking it since it's blocking everything, not just this PR.

**Comment by Barthelemy** [comment]
By the way, I am trying to build this PR on Mac and CC7. With defaults "o2-dataflow" I get a different errors : 
```
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: warning: libarrow.so.10, needed by /home/local/alice/sw/slc7_x86-64/ROOT/v6-14-04-3/lib/libROOTDataFrame.so.6.14, not found (try using -rpath or -rpath-link)
(...)
/home/local/alice/sw/slc7_x86-64/ROOT/v6-14-04-3/lib/libROOTDataFrame.so.6.14 : référence indéfinie vers « arrow::ArrayVisitor::Visit(arrow::NumericArray<arrow::UInt16Type> const&) »
```

**Comment by ktf** [comment]
Do you have the ROOT dependency on arrow in `dataflow`?

**Comment by Barthelemy** [comment]
As a matter of fact, we do.

**Comment by Barthelemy** [comment]
but it is not built

**Comment by ktf** [comment]
You mean you pick it up from the system?

**Comment by Barthelemy** [comment]
sorry, no, I see in the defaults file that arrow is listed as dependency of ROOT but then it does not build arrow.

**Comment by dberzano** [comment]
Very good! For the record, the O2 alidist PR checker kept failing and restarting over and over, this fixed it: https://github.com/alisw/ali-bot/pull/625

**Pull request merged**
