### PR TITLE
Bump CMake to 3.19.1 and c-ares to v1.17.1

### PR DESCRIPTION
**Pull request by teo**
This includes https://github.com/alisw/alidist/pull/2643

### CODE REVIEW

**Comment by ktf** [comment]
Looks like GEANT4 mirror had troubles. @TimoWilken can you restart the tests again?

**Comment by TimoWilken** [comment]
@ktf done, tests are yellow again!

**Comment by ktf** [comment]
It looks like we cannot compile AliRoot with the new CMake...

**Comment by pzhristov** [comment]
I will have a look today, please do not merge!

**Review by ktf — CHANGES_REQUESTED** [review]
Breaks AliRoot.

**Comment by davidrohr** [comment]
Closing in favor of #2643

**Pull request closed without merging**
