### PR TITLE
Add FullCI.sh recipe with complete continuous integration setup

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
new recipe for full ci, not yet tested anyway, merging

**Comment by ihrivnac** [comment]
@davidrohr ,
I find the "FullCI" name misleading, could we add O2 to make clear that this relates O2 suite etc.? 
What do you think?

**Comment by davidrohr** [comment]
@ihrivnac : Done

**Comment by ihrivnac** [comment]
Great, thanks !

**Pull request merged**
