### PR TITLE
O2 checker: check only modified files in a PR

### PR DESCRIPTION
**Pull request by sawenzel**

### CODE REVIEW

**Comment by dberzano** [comment]
OK I am testing it and will come back on it tomorrow.

**Comment by dberzano** [comment]
Still needed: use the list for the copyright notice check. Coming soon.

**Comment by dberzano** [comment]
Hi @sawenzel, as discussed privately, if I run the recipe with `time` without exporting commit variables I get a running time of 48 seconds on my computer. If I export, for instance:

```
export O2CHECKCODE_BASECOMMIT=244f0e545e19c56d933b8d39e23fbc8a333b7b8f
export O2CHECKCODE_HEADCOMMIT=d70f5678ee586f8a74e8df4d54aa6f9c6c25b8f7
```

it runs for 48 minutes straight. Time is essentially spent in `ThinCompilationsDatabase.py`. I will still add the option to use the list for copyright check and we can merge this anyway afterwards, but until this issue is fixed we cannot export those variables in the pull request checker.

**Comment by dberzano** [comment]
Hi, so I am satisfied with those changes (we need to squash the commits of course), apart from the time problem. Actually, some _initial_ time is spent in `ThinCompilationsDatabase.py`, but it's negligible. The code checker itself (`O2codecheck`) seems to be extremely time-consuming.

**Comment by dberzano** [comment]
As discussed, I have tested the last iteration (with the limit set to 50 files) in three different scenarios: without the `COMMIT` variables exported, with a `BASE` having less than 50 files, and with a `BASE` having more than 50 files. It seemed to work and to give a reasonable speedup with the average PR size. I would say, if you are happy, we can squash-merge it.

**Comment by sawenzel** [comment]
Fine for me.

**Comment by dberzano** [comment]
Tomorrow I'll take care of exporting the variables in the PR check.

**Pull request merged**
