### PR TITLE
Annotate FLP builds with special env variable

### PR DESCRIPTION
**Pull request by sawenzel**
This is in order to be able to know when we are
buiding for FLP and to take build decisions based
in this flag

See for instance https://alice.its.cern.ch/jira/browse/O2-2975

### CODE REVIEW

**Comment by sawenzel** [comment]
@davidrohr

**Comment by sawenzel** [comment]
@ktf : I think once alibuild provides this internally, we can again get rid of this annotation. (If you tag and release new alibuild to the FLP build machines also fine with me.)

**Comment by ktf** [comment]
I would do it only for the O2-customization package, so that we do not rebuild the whole stack.

**Comment by sawenzel** [comment]
I am not familiar with the O2-customization package. Would the builds for FLP pick this up?

**Comment by ktf** [comment]
Yes, it should, the idea is to be able to customize O2 only, without having to rebuild every single package because of the choice.

**Comment by sawenzel** [comment]
Fine for me

**Pull request merged**
