### PR TITLE
Integrate JAliEn

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@Atlantic777 I am creating a new set of defaults in order to make it possible to merge it upstream without affecting production.

**Comment by dberzano** [comment]
For the record once the tests are all green, this can be merged without any fear of breaking production.

**Comment by ktf** [comment]
Is this still ongoing?

**Comment by dberzano** [comment]
@Atlantic777 should know - but I am more comfortable with not changing anything on Fridays 😄

**Comment by ktf** [comment]
I was actually hoping to close this, not to merge it.. ;-)

**Comment by dberzano** [comment]
From my understanding this should be merged instead 😄 But again, let's wait for @Atlantic777's feedback

**Comment by Atlantic777** [comment]
My contribution in this pull request is very small and I am still not completely sure how everything fits together so it's better to check with the rest of the team. However, I also understood that this functionality is appreciated and it should eventually be merged into alidist/alisw master.

**Comment by ktf** [comment]
I discussed with @Atlantic777 and he said this is ready to be merged. Given the only critical change is a rather safe one in AliRoot, I propose we go forward and fix whatever needs to be fixed later.

**Comment by dberzano** [comment]
I am syncing the ROOT 6 version first, then I agree we can move forward.

**Comment by dberzano** [comment]
Done, I have synced ROOT, AliRoot and AliPhysics. Actual tests will not use `defaults-jalien-root6.sh` and since `aliroot.sh` did not change wrt/the last test, I am merging this.

**Pull request merged**
