### PR TITLE
Bump qualitycontrol to v1.68.1

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by kostorr — APPROVED** [review]

**Comment by Barthelemy** [comment]
@TimoWilken @ktf There seems to be a problem in cs8 build

**Comment by awegrzyn** [comment]
https://github.com/alisw/alidist/pull/4445

**Comment by Barthelemy** [comment]
@awegrzyn I am not sure whether we should close this one. We won't install v1.69.0 immediately at P2, it is to be included in the next FLP Suite. V1.68.1 is to be installed at P2 tomorrow. 

I am not against installing QC v1.69 at P2 tomorrow (outside FLP Suite) but I don't know what @pippohub think

**Comment by Barthelemy** [comment]
ignore my previous message, thank you

**Pull request closed without merging**
