### PR TITLE
[WIP] Fix boost git url

### PR DESCRIPTION
**Pull request by davidrohr**
@sawenzel : Does this fix the issue (of #1776).
Not sure if we can trust the CI in this respect, should be investigated independently.

### CODE REVIEW

**Comment by ktf** [comment]
Do not use the official one.

--
Ciao,
Giulio

**Comment by davidrohr** [comment]
OK, I see, the problem with building from upstream is anyway that it uses git submodules and alibuild does not fetch the full build tree. I'll close this one, and try locally with a full build tree, and open a PR to our boost fork.

**Comment by ktf** [comment]
Yes, submodules are one of the problems (which could be solved, but would require everyone move to a new version of aliBuild).

The other is that when we have huge git history we decided to either download the tarballs (like for CGAL, which has other "peculiarities") or to import the tarballs in our own github repository. 

This is not of so easy solution, because alibuild uses git history to facilitate development with features like development packages and incremental builds. We could use the GitHub API, but that complicates things (because users would need to get their own access token) and slow them down (because using a local git repo is 1000x faster (if not more) than using the REST API for most of the repositories).

**Comment by ktf** [comment]
BTW, the instructions are here:

https://github.com/alisw/alidist#guidelines-for-handling-externals-sources

**Pull request closed without merging**
