### PR TITLE
Install node-gyp locally

### PR DESCRIPTION
**Pull request by pzhristov**

### CODE REVIEW

**Comment by awegrzyn** [comment]
I've tested `master` @ `aido2osx2` with Python 3.9 and the qcg compiles fine. So I guess we should find out what's the configuration difference between these 2 machines with @MichaelLettrich

Regarding this change I'm not sure this will help as `node-gyp` is picked up from `npm` dependencies (`lib/node_modules/npm/node_modules/node-gyp`). To update it to the newest version the following code can be used:
```
(PATH=$PATH:$INSTALLROOT/bin; cd $INSTALLROOT/lib/node_modules/npm/node_modules; npm install --save node-gyp@latest)
```
Unfortunately in such case Node tries to protect itself from using unsupported version of `node-gyp` and picks up older version from `npm-lifecycle` packages (`lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/`).

**Review by awegrzyn — APPROVED** [review]
If it solves the problem

**Comment by pzhristov** [comment]
On Ubuntu 18.04 the -g option forces the installation of node-gyp in /usr/lib even if the help says 
 npm install (in package directory, no arguments):
           Install the dependencies in the local node_modules folder.
           In global mode (ie, with -g or --global appended to the command),
           it installs the current package context (ie, the current working
           directory) as a global package.
           By default, npm install will install all modules listed as dependencies
Without it indeed we got the lib/node_modules folder and the O2Suit compilation was OK.

**Comment by MichaelLettrich** [comment]
@awegrzyn : 

hmm this seems to be causing the error

```bash
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build', '--jobs', 12 ]
  cc '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/include/node -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/src -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/deps/openssl/config -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/deps/openssl/openssl/include -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/deps/uv/include -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/deps/zlib -I/Users/alibuild/Library/Caches/node-gyp/14.12.0/deps/v8/include  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/nothing/../../node-addon-api/src/nothing.o.d.raw  -fPIC -O2 -c -o Release/obj.target/nothing/../../node-addon-api/src/nothing.o ../../../node-addon-api/src/nothing.c
  rm -f Release/nothing.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/nothing.a Release/obj.target/nothing/../../node-addon-api/src/nothing.o
Usage: /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/autotools/v1.6.3-1/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/bin/node" "/System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/osx_x86-64/node/v14.12.0-1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--jobs" "max"
gyp ERR! cwd /System/Volumes/Data/build/ci_checks/alice_ci_0/alidist-o2/sw/BUILD/d95ad41bd1496ac825d4e476f36cef392f5c18cf/qcg/node_modules/@aliceo2/qc
gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

**Comment by pzhristov** [comment]
@MichaelLettrich Is this on Mac? The errors I see from the CI are not related to this PR?

**Comment by MichaelLettrich** [comment]
@pzhristov I was refering to @awegrzyn, sorry for the confusion.

**Pull request merged**
