### PR TITLE
Bump clang to 13.0.0

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr I would leave this open until we see the fullCI results and then we merge  #3506.

**Comment by ktf** [comment]
In the meanwhile I will check on hyperloop as well.

**Comment by ktf** [comment]
This seems to break Gandiva...

**Comment by pzhristov** [comment]
> This seems to break Gandiva...

Gandiva was quite Ok with clang 13 on Mac M1. Where do you see the issue?

**Comment by ktf** [comment]
In hyperloop (ubuntu)

**Comment by ktf** [comment]
I am testing again and will report the actual error I see...

**Comment by ktf** [comment]
It looks like hyperloop has unrelated problems right now...

**Comment by ktf** [comment]
Ok, the issue I was having was unrelated. We can probably merge #3506, but we should first create the caches for it. @TimoWilken can you take care?

**Comment by davidrohr** [comment]
For merging #3506, we have to fix the O2CodeChecker issue first. But probably we can close this one. If we bump, we should use #3506.

**Pull request closed without merging**
